/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 3e629e58-243c-4f64-be72-cd52aa2ea65f

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of the coefficient of the finite free convolution (boxplus) of two polynomials.
-/
open Polynomial BigOperators Finset Classical

def boxplus_coeff (n : ℕ) (p q : ℝ[X]) (k : ℕ) : ℝ :=
  ∑ i ∈ range (k + 1),
    let j := k - i
    (Nat.factorial (n - i) * Nat.factorial (n - j) : ℝ) / (Nat.factorial n * Nat.factorial (n - k) : ℝ) *
    (p.coeff (n - i)) * (q.coeff (n - j))

/-
Definition of the finite free convolution (boxplus) of two polynomials.
-/
def boxplus (n : ℕ) (p q : ℝ[X]) : ℝ[X] :=
  Finset.sum (range (n + 1)) (fun k => C (boxplus_coeff n p q k) * X ^ (n - k))

/-
Definition of the Phi functional and its inverse.
-/
def Phi (p : ℝ[X]) : ℝ :=
  let roots := p.roots.toFinset
  ∑ r_i ∈ roots, (∑ r_j ∈ roots.erase r_i, 1 / (r_i - r_j))^2

def invPhi (p : ℝ[X]) : ℝ :=
  if p.roots.Nodup ∧ p.roots.card > 1 then
    1 / Phi p
  else 0

/-
Definition of a centered polynomial of degree n.
-/
def is_centered (n : ℕ) (p : ℝ[X]) : Prop :=
  p.Monic ∧ p.natDegree = n ∧ p.coeff (n - 1) = 0

/-
A polynomial is centered of degree 2 if and only if it is of the form X^2 + c.
-/
lemma is_centered_two_iff (p : ℝ[X]) :
    is_centered 2 p ↔ ∃ c : ℝ, p = X^2 + C c := by
      unfold is_centered;
      constructor;
      · intro hp
        obtain ⟨h_monic, h_deg, h_coeff⟩ := hp;
        use p.coeff 0; rw [ Polynomial.as_sum_range_C_mul_X_pow p ] ; norm_num [ h_deg, Finset.sum_range_succ', h_coeff ] ;
        rw [ ← h_deg, h_monic.coeff_natDegree, Polynomial.C_1 ];
      · rintro ⟨ c, rfl ⟩ ; erw [ Polynomial.Monic, Polynomial.leadingCoeff_X_pow_add_C ] <;> norm_num [ Polynomial.natDegree_add_eq_left_of_natDegree_lt ] ;

/-
Calculation of invPhi for the polynomial X^2 + c.
-/
lemma invPhi_X_sq_add_C (c : ℝ) :
    invPhi (X^2 + C c) = if c < 0 then -2 * c else 0 := by
      unfold invPhi;
      split_ifs <;> simp_all +decide [ sub_eq_iff_eq_add ];
      · -- The roots of $X^2 + c$ are $\pm \sqrt{-c}$.
        have h_roots : (Polynomial.X ^ 2 + Polynomial.C c).roots = {Real.sqrt (-c), -Real.sqrt (-c)} := by
          rw [ show ( Polynomial.X ^ 2 + Polynomial.C c : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C ( Real.sqrt ( -c ) ) ) * ( Polynomial.X - Polynomial.C ( -Real.sqrt ( -c ) ) ) by exact Polynomial.funext fun x => by norm_num; linarith [ Real.mul_self_sqrt ( show 0 ≤ -c by linarith ) ] ] ; rw [ Polynomial.roots_mul <| by exact mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ] ; rw [ Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] ; norm_num;
        -- Substitute the roots into the definition of Phi.
        simp [h_roots, Phi];
        rw [ Finset.sum_pair ] <;> norm_num [ Finset.sum_erase ] <;> ring <;> norm_num [ ne_of_gt, Real.sqrt_pos, ‹c < 0› ];
        grind;
      · refine' Finset.sum_eq_zero fun x hx => _;
        rw [ Finset.sum_eq_zero ] ; aesop;
        norm_num +zetaDelta at *;
        exact fun y hy₁ hy₂ hy₃ => by nlinarith [ mul_self_pos.2 ( sub_ne_zero.2 hy₁ ) ] ;
      · rename_i h₁ h₂;
        contrapose! h₁;
        erw [ show ( Polynomial.X ^ 2 + Polynomial.C c : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C ( Real.sqrt ( -c ) ) ) * ( Polynomial.X - Polynomial.C ( -Real.sqrt ( -c ) ) ) by exact Polynomial.funext fun x => by norm_num; linarith [ Real.mul_self_sqrt ( show 0 ≤ -c by linarith ) ] ];
        rw [ Polynomial.roots_mul <| mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ), Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] ; norm_num;
        linarith [ Real.sqrt_pos.2 ( neg_pos.2 h₂ ) ]

/-
Calculation of boxplus for two polynomials of the form X^2 + c and X^2 + d.
-/
lemma boxplus_two_X_sq_add_C (c d : ℝ) :
    boxplus 2 (X^2 + C c) (X^2 + C d) = X^2 + C (c + d) := by
      unfold boxplus;
      unfold boxplus_coeff; norm_num [ Finset.sum_range_succ', Polynomial.coeff_X ] ; ring;

/-
The finite free Stam inequality holds for n=2, assuming p and q have distinct real roots.
-/
lemma finite_free_stam_inequality_n2 (p q : ℝ[X])
    (hp : is_centered 2 p)
    (hq : is_centered 2 q)
    (hp_roots : p.roots.Nodup ∧ p.roots.card = 2)
    (hq_roots : q.roots.Nodup ∧ q.roots.card = 2) :
    invPhi (boxplus 2 p q) ≥ invPhi p + invPhi q := by
      obtain ⟨c₁, rfl⟩ := is_centered_two_iff p |>.1 hp
      obtain ⟨c₂, rfl⟩ := is_centered_two_iff q |>.1 hq;
      -- Since $c₁$ and $c₂$ are negative, we have $invPhi (X^2 + C c₁) = -2c₁$ and $invPhi (X^2 + C c₂) = -2c₂$.
      have h_invPhi_neg : invPhi (X^2 + C c₁) = -2 * c₁ ∧ invPhi (X^2 + C c₂) = -2 * c₂ := by
        constructor <;> rw [ invPhi_X_sq_add_C ];
        · contrapose! hp_roots;
          intro h; rw [ Multiset.card_eq_zero.mpr ] <;> norm_num;
          exact Multiset.eq_zero_of_forall_notMem fun x hx => hp_roots <| by norm_num at hx; split_ifs <;> nlinarith;
        · obtain ⟨ x, hx ⟩ := Multiset.card_pos_iff_exists_mem.mp ( by linarith ) ; norm_num at hx ; split_ifs <;> nlinarith;
      rw [ boxplus_two_X_sq_add_C ] ; rw [ h_invPhi_neg.1, h_invPhi_neg.2 ] ; rw [ invPhi_X_sq_add_C ] ; split_ifs <;> linarith;

/-
For n=3, the finite free convolution of X^3+bX+c and X^3+BX+C is X^3+(b+B)X+(c+C).
-/
lemma boxplus_three_add_coeffs (b c B CC : ℝ) :
    boxplus 3 (X^3 + C b * X + C c) (X^3 + C B * X + C CC) = X^3 + C (b + B) * X + C (c + CC) := by
      unfold boxplus;
      norm_num [ Finset.sum_range_succ, boxplus_coeff ];
      norm_num [ Polynomial.coeff_X ] ; ring

/-
The value of the Phi functional for a centered cubic polynomial X^3 + bX + c is 18b^2 / (-4b^3 - 27c^2).
-/
lemma Phi_cubic_eq (b c : ℝ) (p : ℝ[X])
    (hp : p = X^3 + C b * X + C c)
    (h_roots : p.roots.Nodup ∧ p.roots.card = 3) :
    Phi p = 18 * b^2 / (-4 * b^3 - 27 * c^2) := by
      -- By Vieta's formulas, we know that for the roots $r_1, r_2, r_3$ of $p$, we have $r_1 + r_2 + r_3 = 0$, $r_1r_2 + r_2r_3 + r_3r_1 = b$, and $r_1r_2r_3 = -c$.
      obtain ⟨r₁, r₂, r₃, hr₁, hr₂, hr₃⟩ : ∃ r₁ r₂ r₃ : ℝ, r₁ + r₂ + r₃ = 0 ∧ r₁ * r₂ + r₂ * r₃ + r₃ * r₁ = b ∧ r₁ * r₂ * r₃ = -c ∧ p = Polynomial.C 1 * (Polynomial.X - Polynomial.C r₁) * (Polynomial.X - Polynomial.C r₂) * (Polynomial.X - Polynomial.C r₃) := by
        obtain ⟨r₁, r₂, r₃, hr⟩ : ∃ r₁ r₂ r₃ : ℝ, p = Polynomial.C 1 * (Polynomial.X - Polynomial.C r₁) * (Polynomial.X - Polynomial.C r₂) * (Polynomial.X - Polynomial.C r₃) := by
          rw [ ← Polynomial.prod_multiset_X_sub_C_of_monic_of_roots_card_eq ( show Polynomial.Monic p from ?_ ) ];
          · rw [ Multiset.card_eq_three ] at h_roots;
            rcases h_roots.2 with ⟨ x, y, z, h ⟩ ; exact ⟨ x, y, z, by simpa [ h, mul_assoc ] ⟩ ;
          · rw [ h_roots.2, hp, Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases hb : b = 0 <;> simp +decide [ hb ];
          · rw [ hp, Polynomial.Monic, Polynomial.leadingCoeff, Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases hb : b = 0 <;> simp +decide [ hb ];
        exact ⟨ r₁, r₂, r₃, by have h₁ := congr_arg ( Polynomial.eval 0 ) hr; have h₂ := congr_arg ( Polynomial.eval 1 ) hr; have h₃ := congr_arg ( Polynomial.eval ( -1 ) ) hr; norm_num [ hp ] at h₁ h₂ h₃; linarith, by have h₁ := congr_arg ( Polynomial.eval 0 ) hr; have h₂ := congr_arg ( Polynomial.eval 1 ) hr; have h₃ := congr_arg ( Polynomial.eval ( -1 ) ) hr; norm_num [ hp ] at h₁ h₂ h₃; linarith, by have h₁ := congr_arg ( Polynomial.eval 0 ) hr; have h₂ := congr_arg ( Polynomial.eval 1 ) hr; have h₃ := congr_arg ( Polynomial.eval ( -1 ) ) hr; norm_num [ hp ] at h₁ h₂ h₃; linarith, hr ⟩;
      -- By definition of Phi, we have
      have h_Phi_def : Phi p = (∑ i ∈ ({r₁, r₂, r₃} : Finset ℝ), (∑ j ∈ ({r₁, r₂, r₃} \ {i}), (1 / (i - j))) ^ 2) := by
        -- By definition of $p$, we know that its roots are exactly $r_1$, $r_2$, and $r_3$.
        have h_roots_eq : p.roots.toFinset = {r₁, r₂, r₃} := by
          ext; simp [hr₃];
          exact ⟨ fun h => by simpa [ sub_eq_iff_eq_add, or_assoc ] using h.2, fun h => ⟨ ⟨ ⟨ Polynomial.X_sub_C_ne_zero _, Polynomial.X_sub_C_ne_zero _ ⟩, Polynomial.X_sub_C_ne_zero _ ⟩, by simpa [ sub_eq_iff_eq_add, or_assoc ] using h ⟩ ⟩;
        unfold Phi; aesop;
      by_cases h₁ : r₁ = r₂ <;> by_cases h₂ : r₁ = r₃ <;> by_cases h₃ : r₂ = r₃ <;> simp_all +decide [ Finset.sdiff_singleton_eq_erase ];
      · grind;
      · replace hp := congr_arg ( Polynomial.roots ) hp ; norm_num [ Polynomial.roots_mul, Polynomial.X_sub_C_ne_zero ] at hp;
        replace hp := congr_arg Multiset.Nodup hp ; aesop;
      · replace hp := congr_arg ( Polynomial.roots ) hp ; norm_num [ Polynomial.roots_mul, Polynomial.X_ne_zero ] at hp;
        rw [ Polynomial.roots_mul, Polynomial.roots_mul ] at hp <;> norm_num at *;
        · replace hp := congr_arg Multiset.Nodup hp ; simp_all +decide [ Multiset.nodup_cons ];
        · exact ⟨ Polynomial.X_sub_C_ne_zero _, by exact ne_of_apply_ne Polynomial.derivative <| by norm_num ⟩;
        · exact ⟨ ⟨ Polynomial.X_sub_C_ne_zero _, by exact ne_of_apply_ne Polynomial.derivative <| by norm_num ⟩, Polynomial.X_sub_C_ne_zero _ ⟩;
      · replace hp := congr_arg ( Polynomial.roots ) hp ; simp_all +decide [ Polynomial.roots_mul, Polynomial.X_sub_C_ne_zero ];
        replace hp := congr_arg Multiset.Nodup hp ; simp_all +decide [ Multiset.nodup_cons ];
      · rw [ eq_div_iff ];
        · field_simp;
          rw [ div_add_div, div_add_div, div_add_div ] <;> try nlinarith [ mul_self_pos.2 ( sub_ne_zero.2 h₁ ), mul_self_pos.2 ( sub_ne_zero.2 h₂ ), mul_self_pos.2 ( sub_ne_zero.2 h₃ ) ];
          rw [ div_pow, div_pow, div_pow ];
          rw [ div_add_div, div_add_div ] <;> try nlinarith [ mul_self_pos.2 ( sub_ne_zero.2 h₁ ), mul_self_pos.2 ( sub_ne_zero.2 h₂ ), mul_self_pos.2 ( sub_ne_zero.2 h₃ ) ];
          · rw [ div_mul_eq_mul_div, div_eq_iff ];
            · rw [ ← eq_sub_iff_add_eq' ] at hr₁ ; subst_vars ; ring;
              grind +ring;
            · exact mul_ne_zero ( pow_ne_zero 2 ( mul_ne_zero ( sub_ne_zero_of_ne h₁ ) ( sub_ne_zero_of_ne h₂ ) ) ) ( mul_ne_zero ( pow_ne_zero 2 ( mul_ne_zero ( sub_ne_zero_of_ne ( Ne.symm h₁ ) ) ( sub_ne_zero_of_ne h₃ ) ) ) ( pow_ne_zero 2 ( mul_ne_zero ( sub_ne_zero_of_ne ( Ne.symm h₂ ) ) ( sub_ne_zero_of_ne ( Ne.symm h₃ ) ) ) ) );
          · exact mul_ne_zero ( pow_ne_zero 2 ( mul_ne_zero ( sub_ne_zero_of_ne <| by tauto ) ( sub_ne_zero_of_ne <| by tauto ) ) ) ( pow_ne_zero 2 ( mul_ne_zero ( sub_ne_zero_of_ne <| by tauto ) ( sub_ne_zero_of_ne <| by tauto ) ) );
        · grind

/-
The finite free Stam inequality holds for n=3, assuming p and q have distinct real roots.
-/
lemma finite_free_stam_inequality_n3 (p q : ℝ[X])
    (hp : is_centered 3 p)
    (hq : is_centered 3 q)
    (hp_roots : p.roots.Nodup ∧ p.roots.card = 3)
    (hq_roots : q.roots.Nodup ∧ q.roots.card = 3) :
    invPhi (boxplus 3 p q) ≥ invPhi p + invPhi q := by
      obtain ⟨c₁, c₂, b₁, b₂, hp_eq, hq_eq⟩ : ∃ c₁ c₂ b₁ b₂ : ℝ, p = X^3 + C b₁ * X + C c₁ ∧ q = X^3 + C b₂ * X + C c₂ := by
        obtain ⟨c₁, b₁, hp_eq⟩ : ∃ c₁ b₁ : ℝ, p = X^3 + C b₁ * X + C c₁ := by
          obtain ⟨ hp₁, hp₂ ⟩ := hp;
          rw [ p.as_sum_range_C_mul_X_pow ] ; norm_num [ Finset.sum_range_succ', Polynomial.natDegree_eq_of_degree_eq_some, hp₂ ];
          have := hp₁.coeff_natDegree; aesop;
        obtain ⟨c₂, b₂, hq_eq⟩ : ∃ c₂ b₂ : ℝ, q = X^3 + C b₂ * X + C c₂ := by
          rcases hq with ⟨ hq₁, hq₂, hq₃ ⟩;
          rw [ Polynomial.as_sum_range_C_mul_X_pow q ];
          norm_num [ Finset.sum_range_succ', hq₂ ];
          have := hq₁.coeff_natDegree; aesop;
        use c₁, c₂, b₁, b₂;
      by_cases h₁ : b₁ < 0 <;> by_cases h₂ : b₂ < 0 <;> simp_all +decide [ invPhi ];
      · -- Apply the lemma that states the finite free Stam inequality holds for n=3.
        have h_ineq : invPhi (X^3 + C (b₁ + b₂) * X + C (c₁ + c₂)) ≥ invPhi (X^3 + C b₁ * X + C c₁) + invPhi (X^3 + C b₂ * X + C c₂) := by
          by_cases h₃ : -4 * (b₁ + b₂) ^ 3 - 27 * (c₁ + c₂) ^ 2 > 0 <;> simp_all +decide [ invPhi ];
          · have h_ineq : (18 * b₁ ^ 2 / (-4 * b₁ ^ 3 - 27 * c₁ ^ 2))⁻¹ + (18 * b₂ ^ 2 / (-4 * b₂ ^ 3 - 27 * c₂ ^ 2))⁻¹ ≤ (18 * (b₁ + b₂) ^ 2 / (-4 * (b₁ + b₂) ^ 3 - 27 * (c₁ + c₂) ^ 2))⁻¹ := by
              field_simp;
              rw [ div_add_div, div_le_div_iff₀ ] <;> try nlinarith;
              · have h_ineq : (c₁ + c₂) ^ 2 / (b₁ + b₂) ^ 2 ≤ c₁ ^ 2 / b₁ ^ 2 + c₂ ^ 2 / b₂ ^ 2 := by
                  rw [ div_add_div, div_le_div_iff₀ ] <;> try nlinarith;
                  · nlinarith [ sq_nonneg ( c₁ * b₂ ^ 2 - c₂ * b₁ ^ 2 ), sq_nonneg ( c₁ * b₂ * ( b₁ + b₂ ) - c₂ * b₁ * ( b₁ + b₂ ) ), sq_nonneg ( c₁ * b₂ * ( b₁ + b₂ ) + c₂ * b₁ * ( b₁ + b₂ ) ), mul_pos ( neg_pos.mpr h₁ ) ( neg_pos.mpr h₂ ) ];
                  · exact mul_pos ( sq_pos_of_neg h₁ ) ( sq_pos_of_neg h₂ );
                rw [ div_add_div, div_le_div_iff₀ ] at h_ineq <;> try nlinarith;
                exact mul_pos ( sq_pos_of_neg h₁ ) ( sq_pos_of_neg h₂ );
              · exact mul_pos ( sq_pos_of_neg h₁ ) ( sq_pos_of_neg h₂ );
            convert h_ineq using 1;
            · rw [ Phi_cubic_eq _ _ _ rfl hp_roots, Phi_cubic_eq _ _ _ rfl hq_roots ];
            · rw [ if_pos ];
              · rw [ show ( Polynomial.X ^ 3 + ( Polynomial.C b₁ + Polynomial.C b₂ ) * Polynomial.X + ( Polynomial.C c₁ + Polynomial.C c₂ ) ) = ( Polynomial.X ^ 3 + Polynomial.C ( b₁ + b₂ ) * Polynomial.X + Polynomial.C ( c₁ + c₂ ) ) by simp, Phi_cubic_eq ] ; aesop;
                -- Since the discriminant is positive, the polynomial has three distinct real roots.
                have h_distinct_roots : ∃ r₁ r₂ r₃ : ℝ, r₁ ≠ r₂ ∧ r₂ ≠ r₃ ∧ r₃ ≠ r₁ ∧ r₁ + r₂ + r₃ = 0 ∧ r₁ * r₂ + r₂ * r₃ + r₃ * r₁ = b₁ + b₂ ∧ r₁ * r₂ * r₃ = -(c₁ + c₂) := by
                  obtain ⟨r₁, r₂, r₃, hr⟩ : ∃ r₁ r₂ r₃ : ℝ, r₁ + r₂ + r₃ = 0 ∧ r₁ * r₂ + r₂ * r₃ + r₃ * r₁ = b₁ + b₂ ∧ r₁ * r₂ * r₃ = -(c₁ + c₂) := by
                    -- By the properties of the cubic function, since its discriminant is positive, it must have three distinct real roots.
                    obtain ⟨r₁, hr₁⟩ : ∃ r₁ : ℝ, r₁ ^ 3 + (b₁ + b₂) * r₁ + (c₁ + c₂) = 0 := by
                      -- By the Intermediate Value Theorem, since the polynomial $X^3 + (b₁ + b₂)X + (c₁ + c₂)$ is continuous and changes sign, it must have at least one real root.
                      have h_ivt : ∃ r₁ ∈ Set.Icc (-|c₁ + c₂| - |b₁ + b₂| - 1) (|c₁ + c₂| + |b₁ + b₂| + 1), r₁ ^ 3 + (b₁ + b₂) * r₁ + (c₁ + c₂) = 0 := by
                        apply_rules [ intermediate_value_Icc ] <;> norm_num;
                        · linarith [ abs_nonneg ( c₁ + c₂ ), abs_nonneg ( b₁ + b₂ ) ];
                        · fun_prop;
                        · constructor <;> cases abs_cases ( c₁ + c₂ ) <;> cases abs_cases ( b₁ + b₂ ) <;> nlinarith [ sq_abs ( c₁ + c₂ ), sq_abs ( b₁ + b₂ ) ];
                      grind;
                    use r₁;
                    use (-r₁ + Real.sqrt (r₁^2 - 4 * (b₁ + b₂ + r₁^2))) / 2, (-r₁ - Real.sqrt (r₁^2 - 4 * (b₁ + b₂ + r₁^2))) / 2;
                    ring_nf at *;
                    rw [ Real.sq_sqrt ] <;> norm_num;
                    · constructor <;> linarith;
                    · contrapose! h₃;
                      rw [ show c₁ = -r₁ * b₁ - r₁ * b₂ - r₁ ^ 3 - c₂ by linarith ] ; ring_nf;
                      nlinarith [ sq_nonneg ( r₁ ^ 2 - ( -b₁ - b₂ ) / 3 ), mul_pos ( neg_pos.mpr h₁ ) ( neg_pos.mpr h₂ ), mul_pos ( neg_pos.mpr h₁ ) ( sub_pos.mpr h₃ ), mul_pos ( neg_pos.mpr h₂ ) ( sub_pos.mpr h₃ ) ];
                  use r₁, r₂, r₃;
                  grind;
                obtain ⟨ r₁, r₂, r₃, h₁, h₂, h₃, h₄, h₅, h₆ ⟩ := h_distinct_roots; rw [ show ( Polynomial.X ^ 3 + Polynomial.C ( b₁ + b₂ ) * Polynomial.X + Polynomial.C ( c₁ + c₂ ) ) = ( Polynomial.X - Polynomial.C r₁ ) * ( Polynomial.X - Polynomial.C r₂ ) * ( Polynomial.X - Polynomial.C r₃ ) by exact Polynomial.funext fun x => by norm_num; linear_combination h₄ * x^2 - h₅ * x + h₆ ] ; rw [ Polynomial.roots_mul <| by exact mul_ne_zero ( mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ) ( Polynomial.X_sub_C_ne_zero _ ), Polynomial.roots_mul <| by exact mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ] ; aesop;
              · have h_card : Multiset.card (Polynomial.roots (Polynomial.X ^ 3 + (Polynomial.C (b₁ + b₂)) * Polynomial.X + (Polynomial.C (c₁ + c₂)))) = 3 := by
                  have h_card : ∃ r₁ r₂ r₃ : ℝ, r₁ + r₂ + r₃ = 0 ∧ r₁ * r₂ + r₂ * r₃ + r₃ * r₁ = b₁ + b₂ ∧ r₁ * r₂ * r₃ = -(c₁ + c₂) := by
                    -- By the properties of the cubic function, since its discriminant is positive, it must have three distinct real roots.
                    obtain ⟨r₁, hr₁⟩ : ∃ r₁ : ℝ, r₁ ^ 3 + (b₁ + b₂) * r₁ + (c₁ + c₂) = 0 := by
                      -- By the Intermediate Value Theorem, since the polynomial $X^3 + (b₁ + b₂)X + (c₁ + c₂)$ is continuous and changes sign, it must have at least one real root.
                      have h_ivt : ∃ r₁ ∈ Set.Icc (-|c₁ + c₂| - |b₁ + b₂| - 1) (|c₁ + c₂| + |b₁ + b₂| + 1), r₁ ^ 3 + (b₁ + b₂) * r₁ + (c₁ + c₂) = 0 := by
                        apply_rules [ intermediate_value_Icc ] <;> norm_num;
                        · linarith [ abs_nonneg ( c₁ + c₂ ), abs_nonneg ( b₁ + b₂ ) ];
                        · fun_prop;
                        · constructor <;> cases abs_cases ( c₁ + c₂ ) <;> cases abs_cases ( b₁ + b₂ ) <;> nlinarith [ sq_abs ( c₁ + c₂ ), sq_abs ( b₁ + b₂ ) ];
                      grind;
                    use r₁;
                    use (-r₁ + Real.sqrt (r₁^2 - 4 * (b₁ + b₂ + r₁^2))) / 2, (-r₁ - Real.sqrt (r₁^2 - 4 * (b₁ + b₂ + r₁^2))) / 2;
                    ring_nf at *;
                    rw [ Real.sq_sqrt ] <;> norm_num;
                    · constructor <;> linarith;
                    · contrapose! h₃;
                      rw [ show c₁ = -r₁ * b₁ - r₁ * b₂ - r₁ ^ 3 - c₂ by linarith ] ; ring_nf;
                      nlinarith [ sq_nonneg ( r₁ ^ 2 - ( -b₁ - b₂ ) / 3 ), mul_pos ( neg_pos.mpr h₁ ) ( neg_pos.mpr h₂ ), mul_pos ( neg_pos.mpr h₁ ) ( sub_pos.mpr h₃ ), mul_pos ( neg_pos.mpr h₂ ) ( sub_pos.mpr h₃ ) ];
                  obtain ⟨ r₁, r₂, r₃, h₁, h₂, h₃ ⟩ := h_card; rw [ show ( Polynomial.X ^ 3 + Polynomial.C ( b₁ + b₂ ) * Polynomial.X + Polynomial.C ( c₁ + c₂ ) ) = ( Polynomial.X - Polynomial.C r₁ ) * ( Polynomial.X - Polynomial.C r₂ ) * ( Polynomial.X - Polynomial.C r₃ ) by exact Polynomial.funext fun x => by norm_num; linear_combination h₁ * x^2 - h₂ * x + h₃ ] ; rw [ Polynomial.roots_mul, Polynomial.roots_mul ] ; aesop;
                  · exact mul_ne_zero ( Polynomial.X_sub_C_ne_zero r₁ ) ( Polynomial.X_sub_C_ne_zero r₂ );
                  · exact mul_ne_zero ( mul_ne_zero ( Polynomial.X_sub_C_ne_zero r₁ ) ( Polynomial.X_sub_C_ne_zero r₂ ) ) ( Polynomial.X_sub_C_ne_zero r₃ );
                have h_distinct : Multiset.Nodup (Polynomial.roots (Polynomial.X ^ 3 + (Polynomial.C (b₁ + b₂)) * Polynomial.X + (Polynomial.C (c₁ + c₂)))) := by
                  by_contra h_dup;
                  -- If the roots are not distinct, then the polynomial must have a repeated root.
                  obtain ⟨r, hr⟩ : ∃ r : ℝ, Polynomial.eval r (Polynomial.X ^ 3 + (Polynomial.C (b₁ + b₂)) * Polynomial.X + (Polynomial.C (c₁ + c₂))) = 0 ∧ Polynomial.eval r (Polynomial.derivative (Polynomial.X ^ 3 + (Polynomial.C (b₁ + b₂)) * Polynomial.X + (Polynomial.C (c₁ + c₂)))) = 0 := by
                    rw [ Multiset.nodup_iff_count_le_one ] at h_dup;
                    simp +zetaDelta at *;
                    obtain ⟨ r, hr ⟩ := h_dup;
                    have h_root : Polynomial.eval r (Polynomial.X ^ 3 + (Polynomial.C (b₁ + b₂)) * Polynomial.X + (Polynomial.C (c₁ + c₂))) = 0 ∧ Polynomial.eval r (Polynomial.derivative (Polynomial.X ^ 3 + (Polynomial.C (b₁ + b₂)) * Polynomial.X + (Polynomial.C (c₁ + c₂)))) = 0 := by
                      exact ⟨ by simpa using Polynomial.rootMultiplicity_pos ( show Polynomial.X ^ 3 + ( Polynomial.C b₁ + Polynomial.C b₂ ) * Polynomial.X + ( Polynomial.C c₁ + Polynomial.C c₂ ) ≠ 0 from by exact ne_of_apply_ne ( fun p => p.coeff 3 ) <| by norm_num [ Polynomial.coeff_X, Polynomial.coeff_C ] ) |>.1 <| pos_of_gt hr, by simpa using Polynomial.isRoot_iterate_derivative_of_lt_rootMultiplicity hr ⟩;
                    exact ⟨ r, by simpa using h_root.1, by norm_num at h_root; linarith ⟩;
                  norm_num at hr;
                  grind;
                aesop;
          · have h_discriminant : -4 * b₁^3 - 27 * c₁^2 > 0 ∧ -4 * b₂^3 - 27 * c₂^2 > 0 := by
              have h_discriminant : ∀ (b c : ℝ), b < 0 → (Polynomial.X ^ 3 + Polynomial.C b * Polynomial.X + Polynomial.C c).roots.Nodup ∧ (Polynomial.X ^ 3 + Polynomial.C b * Polynomial.X + Polynomial.C c).roots.card = 3 → -4 * b^3 - 27 * c^2 > 0 := by
                intros b c hb h_roots
                obtain ⟨r₁, r₂, r₃, hr⟩ : ∃ r₁ r₂ r₃ : ℝ, r₁ ≠ r₂ ∧ r₂ ≠ r₃ ∧ r₁ ≠ r₃ ∧ r₁ + r₂ + r₃ = 0 ∧ r₁ * r₂ + r₂ * r₃ + r₃ * r₁ = b ∧ r₁ * r₂ * r₃ = -c := by
                  obtain ⟨r₁, r₂, r₃, hr⟩ : ∃ r₁ r₂ r₃ : ℝ, r₁ ∈ Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C b * Polynomial.X + Polynomial.C c) ∧ r₂ ∈ Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C b * Polynomial.X + Polynomial.C c) ∧ r₃ ∈ Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C b * Polynomial.X + Polynomial.C c) ∧ r₁ ≠ r₂ ∧ r₂ ≠ r₃ ∧ r₁ ≠ r₃ := by
                    rcases Multiset.card_eq_three.mp h_roots.2 with ⟨ r₁, r₂, r₃, hr ⟩ ; use r₁, r₂, r₃ ; aesop;
                  use r₁, r₂, r₃;
                  norm_num at hr;
                  grind;
                -- Substitute the expressions for $b$ and $c$ into the discriminant formula.
                have h_discriminant_subst : -4 * b^3 - 27 * c^2 = (r₁ - r₂)^2 * (r₂ - r₃)^2 * (r₃ - r₁)^2 := by
                  grind;
                exact h_discriminant_subst.symm ▸ mul_pos ( mul_pos ( sq_pos_of_ne_zero ( sub_ne_zero.mpr hr.1 ) ) ( sq_pos_of_ne_zero ( sub_ne_zero.mpr hr.2.1 ) ) ) ( sq_pos_of_ne_zero ( sub_ne_zero.mpr hr.2.2.1.symm ) );
              exact ⟨ h_discriminant b₁ c₁ h₁ hp_roots, h_discriminant b₂ c₂ h₂ hq_roots ⟩;
            nlinarith [ mul_pos ( neg_pos.mpr h₁ ) ( neg_pos.mpr h₂ ), mul_pos ( neg_pos.mpr h₁ ) ( sq_pos_of_neg h₂ ), mul_pos ( neg_pos.mpr h₂ ) ( sq_pos_of_neg h₁ ), pow_pos ( neg_pos.mpr h₁ ) 3, pow_pos ( neg_pos.mpr h₂ ) 3 ];
        convert h_ineq.le using 1;
        · unfold invPhi; aesop;
        · rw [ boxplus_three_add_coeffs ];
          unfold invPhi; aesop;
      · contrapose! hq_roots;
        intro h; intro H; have := Multiset.card_eq_three.mp H; obtain ⟨ x, y, z, h ⟩ := this; simp_all +decide [ Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_X, Polynomial.eval_C ] ;
        -- By Vieta's formulas, we know that $x + y + z = 0$ and $xy + xz + yz = b₂$.
        have h_vieta_sum : x + y + z = 0 := by
          have r₁ := h.symm ▸ Multiset.mem_cons_self _ _; have r₂ := h.symm ▸ Multiset.mem_cons_of_mem ( Multiset.mem_cons_self _ _ ) ; have r₃ := h.symm ▸ Multiset.mem_cons_of_mem ( Multiset.mem_cons_of_mem ( Multiset.mem_cons_self _ _ ) ) ; norm_num at r₁ r₂ r₃; exact mul_left_cancel₀ ( sub_ne_zero_of_ne ( by tauto : x ≠ y ) ) <| mul_left_cancel₀ ( sub_ne_zero_of_ne ( by tauto : x ≠ z ) ) <| mul_left_cancel₀ ( sub_ne_zero_of_ne ( by tauto : y ≠ z ) ) <| by cases le_total x 0 <;> cases le_total y 0 <;> cases le_total z 0 <;> nlinarith;
        have h_vieta_prod_sum : x * y + x * z + y * z = b₂ := by
          have r₁ := h.symm ▸ Multiset.mem_cons_self _ _; have r₂ := h.symm ▸ Multiset.mem_cons_of_mem ( Multiset.mem_cons_self _ _ ) ; have r₃ := h.symm ▸ Multiset.mem_cons_of_mem ( Multiset.mem_cons_of_mem ( Multiset.mem_cons_self _ _ ) ) ; norm_num at r₁ r₂ r₃; exact mul_left_cancel₀ ( sub_ne_zero_of_ne <| by tauto : ( x - y ) ≠ 0 ) <| by ring_nf at *; nlinarith;
        nlinarith [ mul_self_pos.2 ( sub_ne_zero.2 ( by tauto : x ≠ y ) ), mul_self_pos.2 ( sub_ne_zero.2 ( by tauto : x ≠ z ) ), mul_self_pos.2 ( sub_ne_zero.2 ( by tauto : y ≠ z ) ) ];
      · have h_contra : ∀ x : ℝ, x^3 + b₁ * x + c₁ ≠ 0 ∨ x^3 + b₁ * x + c₁ = 0 ∧ ∀ y : ℝ, y^3 + b₁ * y + c₁ = 0 → y = x := by
          intro x; by_cases hx : x^3 + b₁ * x + c₁ = 0 <;> simp_all +decide ;
          intro y hy; by_contra hxy; exact hxy <| by nlinarith [ sq_nonneg ( y - x ), sq_nonneg ( y + x ), mul_self_pos.mpr ( sub_ne_zero.mpr hxy ) ] ;
        obtain ⟨x₁, x₂, x₃, hx⟩ : ∃ x₁ x₂ x₃ : ℝ, x₁ ≠ x₂ ∧ x₁ ≠ x₃ ∧ x₂ ≠ x₃ ∧ x₁^3 + b₁ * x₁ + c₁ = 0 ∧ x₂^3 + b₁ * x₂ + c₁ = 0 ∧ x₃^3 + b₁ * x₃ + c₁ = 0 := by
          obtain ⟨x₁, x₂, x₃, hx⟩ : ∃ x₁ x₂ x₃ : ℝ, x₁ ∈ Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C b₁ * Polynomial.X + Polynomial.C c₁) ∧ x₂ ∈ Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C b₁ * Polynomial.X + Polynomial.C c₁) ∧ x₃ ∈ Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C b₁ * Polynomial.X + Polynomial.C c₁) ∧ x₁ ≠ x₂ ∧ x₁ ≠ x₃ ∧ x₂ ≠ x₃ := by
            rcases Multiset.card_eq_three.mp hp_roots.2 with ⟨ x₁, x₂, x₃, h ⟩ ; use x₁, x₂, x₃ ; aesop;
          exact ⟨ x₁, x₂, x₃, hx.2.2.2.1, hx.2.2.2.2.1, hx.2.2.2.2.2, by norm_num at hx; linarith, by norm_num at hx; linarith, by norm_num at hx; linarith ⟩;
        grind;
      · -- Since $b₁ \geq 0$ and $b₂ \geq 0$, the polynomials $p$ and $q$ have at most one real root each.
        have h_real_roots : ∀ r : ℝ, r ∈ (Polynomial.X ^ 3 + Polynomial.C b₁ * Polynomial.X + Polynomial.C c₁).roots.toFinset → r ^ 3 + b₁ * r + c₁ = 0 → ∀ s : ℝ, s ∈ (Polynomial.X ^ 3 + Polynomial.C b₁ * Polynomial.X + Polynomial.C c₁).roots.toFinset → s ^ 3 + b₁ * s + c₁ = 0 → r = s := by
          intros r hr hr' s hs hs';
          by_contra h_neq;
          exact h_neq <| by nlinarith [ sq_nonneg ( r - s ), sq_nonneg ( r + s ), mul_self_pos.2 ( sub_ne_zero.2 h_neq ) ] ;
        have h_card_roots : Finset.card (Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C b₁ * Polynomial.X + Polynomial.C c₁)).toFinset ≤ 1 := by
          contrapose! h_real_roots;
          obtain ⟨ r, hr, s, hs, hrs ⟩ := Finset.one_lt_card.mp h_real_roots; use r, by aesop, by aesop, s, by aesop, by aesop;
        exact absurd h_card_roots ( by rw [ Multiset.toFinset_card_of_nodup hp_roots.1 ] ; linarith )