/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4cc2c239-8983-487f-9215-8ce8aa708a5a

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

/-
Context file for Aristotle Query 4: Finite Free Stam Inequality — General n Case

This file collects all results proven by Aristotle (Queries 1-3) that are relevant
to proving the general n case. The key structural result is that finite free cumulants
are additive under ⊞_n (finite free additive convolution).

The missing piece: express 1/Φ_n in terms of finite free cumulants and prove
that the resulting function is superadditive (or concave).

Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators Real Nat Classical Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Polynomial BigOperators Finset Classical

/-! ## Core Definitions -/

/-- Coefficient formula for finite free additive convolution (⊞_n). -/
def boxplus_coeff (n : ℕ) (p q : ℝ[X]) (k : ℕ) : ℝ :=
  ∑ i ∈ range (k + 1),
    let j := k - i
    (Nat.factorial (n - i) * Nat.factorial (n - j) : ℝ) / (Nat.factorial n * Nat.factorial (n - k) : ℝ) *
    (p.coeff (n - i)) * (q.coeff (n - j))

/-- Finite free additive convolution p ⊞_n q. -/
def boxplus (n : ℕ) (p q : ℝ[X]) : ℝ[X] :=
  Finset.sum (range (n + 1)) (fun k => C (boxplus_coeff n p q k) * X ^ (n - k))

/-- Φ_n(p) = Σ_i (Σ_{j≠i} 1/(r_i - r_j))² for roots r_1,...,r_n of p. -/
def Phi (p : ℝ[X]) : ℝ :=
  let roots := p.roots.toFinset
  ∑ r_i ∈ roots, (∑ r_j ∈ roots.erase r_i, 1 / (r_i - r_j))^2

/-- 1/Φ_n(p), defined as 0 when roots are not distinct or polynomial has degree ≤ 1. -/
def invPhi (p : ℝ[X]) : ℝ :=
  if p.roots.Nodup ∧ p.roots.card > 1 then
    1 / Phi p
  else 0

/-- Φ_n using Fin n → ℝ representation. -/
def phi (n : ℕ) (roots : Fin n → ℝ) : ℝ :=
  ∑ i, (∑ j ∈ univ.erase i, 1 / (roots i - roots j)) ^ 2

/-- Formal statement of the finite free additive convolution. -/
def freeAddConv (n : ℕ) (p q : ℝ[X]) : ℝ[X] :=
  ∑ k ∈ range (n + 1), C
    (∑ i ∈ range (k + 1),
      (((n - i).factorial : ℝ) * ((n - (k - i)).factorial : ℝ)) /
      (((n.factorial : ℝ) * ((n - k).factorial : ℝ))) *
      p.coeff (n - i) * q.coeff (n - (k - i))) * X ^ (n - k)

/-! ## Hat Polynomial Transform -/

/-- Hat transform: hat_p(X) = Σ_{i=0}^n coeff(p, n-i) · (n-i)! · X^i -/
def hat_poly (n : ℕ) (p : ℝ[X]) : ℝ[X] :=
  ∑ i ∈ range (n + 1), C (p.coeff (n - i) * (n - i).factorial) * X ^ i

/-- Normalized hat polynomial: hat_p / hat_p(0), so constant term = 1. -/
noncomputable def normalized_hat_poly (n : ℕ) (p : ℝ[X]) : ℝ[X] :=
  (hat_poly n p) * C (1 / (hat_poly n p).coeff 0)

/-! ## Truncated Polynomial Operations -/

/-- Truncated polynomial inverse: Σ_{i=0}^n (1-p)^i, satisfying p · poly_inv ≡ 1 (mod X^{n+1}). -/
noncomputable def poly_inv (n : ℕ) (p : ℝ[X]) : ℝ[X] :=
  let q := 1 - p
  ∑ i ∈ range (n + 1), q ^ i

/-- Truncated polynomial logarithm: Σ_{i=0}^n (-1)^i/(i+1) · (p-1)^{i+1}. -/
noncomputable def poly_log (n : ℕ) (p : ℝ[X]) : ℝ[X] :=
  let q := p - 1
  ∑ i ∈ range (n + 1), C ((-1 : ℝ) ^ i / (i + 1 : ℝ)) * q ^ (i + 1)

/-! ## Finite Free Cumulants -/

/-- k-th finite free cumulant of p: coefficient of X^k in poly_log(normalized_hat_poly(p)). -/
noncomputable def finite_free_cumulant (n : ℕ) (p : ℝ[X]) (k : ℕ) : ℝ :=
  (poly_log n (normalized_hat_poly n p)).coeff k

/-! ## Centered Polynomial Predicate -/

/-- A polynomial is centered if it is monic, has degree n, and zero trace (coeff of x^{n-1} = 0). -/
def is_centered (n : ℕ) (p : ℝ[X]) : Prop :=
  p.Monic ∧ p.natDegree = n ∧ p.coeff (n - 1) = 0

/-! ## PROVEN RESULTS (General n) -/

/-- Φ_n = 2 Σ_{i<j} 1/(λ_i - λ_j)² (cross terms cancel). PROVEN for all n. -/
theorem phi_eq_sum_sq_diff (n : ℕ) (roots : Fin n → ℝ) (h_distinct : Function.Injective roots) :
    phi n roots = 2 * ∑ i, ∑ j ∈ univ.filter (fun j => i < j), 1 / (roots i - roots j) ^ 2 := by
  sorry -- Proven by Aristotle (Query 3), ~60 line proof

/-- Φ_n is translation invariant. PROVEN for all n. -/
theorem phi_translation_invariant (n : ℕ) (roots : Fin n → ℝ) (c : ℝ) :
    phi n (fun i => roots i + c) = phi n roots := by
  sorry -- Proven by Aristotle (Query 3)

/-- Φ_n scales by 1/c² when roots are scaled by c. PROVEN for all n. -/
theorem phi_scaling (n : ℕ) (roots : Fin n → ℝ) (c : ℝ) (hc : c ≠ 0) :
    phi n (fun i => c * roots i) = (1 / c ^ 2) * phi n roots := by
  sorry -- Proven by Aristotle (Query 3)

/-- Phi from polynomial roots equals phi from Fin n roots. PROVEN for all n. -/
theorem Phi_eq_phi (n : ℕ) (roots : Fin n → ℝ) (h_distinct : Function.Injective roots) :
    Phi (∏ i, (X - C (roots i))) = phi n roots := by
  sorry -- Proven by Aristotle (Query 3)

/-- The (n-1)-th coefficient of ⊞_n is additive. PROVEN for all n > 0. -/
theorem boxplus_coeff_n_minus_1 (n : ℕ) (hn : 0 < n) (p q : ℝ[X])
    (hp : p.natDegree = n) (hq : q.natDegree = n)
    (hp_monic : p.Monic) (hq_monic : q.Monic) :
    (boxplus n p q).coeff (n - 1) = p.coeff (n - 1) + q.coeff (n - 1) := by
  sorry -- Proven by Aristotle (Query 3)

/-- For centered polynomials, the (n-2)-th coefficient of ⊞_n is additive. PROVEN for all n ≥ 2. -/
theorem boxplus_coeff_n_minus_2_of_centered (n : ℕ) (hn : 2 ≤ n) (p q : ℝ[X])
    (hp : p.natDegree = n) (hq : q.natDegree = n)
    (hp_monic : p.Monic) (hq_monic : q.Monic)
    (hp_centered : p.coeff (n - 1) = 0) (hq_centered : q.coeff (n - 1) = 0) :
    (boxplus n p q).coeff (n - 2) = p.coeff (n - 2) + q.coeff (n - 2) := by
  sorry -- Proven by Aristotle (Query 3)

/-- Centered polynomials are closed under ⊞_n. PROVEN for all n. -/
theorem boxplus_centered_is_centered (n : ℕ) (p q : ℝ[X])
    (hp : is_centered n p) (hq : is_centered n q) :
    is_centered n (boxplus n p q) := by
  sorry -- Proven by Aristotle (Query 2)

/-- Hat transform key identity: hat(p ⊞_n q) ≡ (1/n!) · hat(p) · hat(q) (mod X^{n+1}). PROVEN. -/
theorem hat_poly_boxplus_coeff (n : ℕ) (p q : ℝ[X]) (k : ℕ) (hk : k ≤ n) :
    (hat_poly n (boxplus n p q)).coeff k =
    (1 / (n.factorial : ℝ)) * ((hat_poly n p) * (hat_poly n q)).coeff k := by
  sorry -- Proven by Aristotle (Query 3)

/-- Truncated polynomial inverse works: p · poly_inv(p) ≡ 1 (mod X^{n+1}). PROVEN. -/
theorem poly_inv_mul_mod (n : ℕ) (p : ℝ[X]) (hp : p.coeff 0 = 1) :
    (p * poly_inv n p) % (X ^ (n + 1)) = 1 := by
  sorry -- Proven by Aristotle (Query 3)

/-- Truncated inverse is unique. PROVEN. -/
theorem poly_inv_unique (n : ℕ) (p q : ℝ[X]) (hp : p.coeff 0 = 1)
    (h : (p * q) % (X ^ (n + 1)) = 1) :
    q % (X ^ (n + 1)) = (poly_inv n p) % (X ^ (n + 1)) := by
  sorry -- Proven by Aristotle (Query 3)

/-- Truncated log derivative is the logarithmic derivative. PROVEN. -/
theorem poly_log_derivative (n : ℕ) (p : ℝ[X]) (hp : p.coeff 0 = 1) :
    (Polynomial.derivative (poly_log n p)) % (X ^ n) =
    ((Polynomial.derivative p) * (poly_inv n p)) % (X ^ n) := by
  sorry -- Proven by Aristotle (Query 3)

/-- Truncated log of a product is additive modulo X^n. PROVEN. -/
theorem poly_log_derivative_mul_mod (n : ℕ) (p q : ℝ[X])
    (hp : p.coeff 0 = 1) (hq : q.coeff 0 = 1) :
    (Polynomial.derivative (poly_log n (p * q))) % (X ^ n) =
    ((Polynomial.derivative (poly_log n p)) + (Polynomial.derivative (poly_log n q))) % (X ^ n) := by
  sorry -- Proven by Aristotle (Query 3)

/-- The normalized hat polynomial has constant term 1. PROVEN. -/
theorem normalized_hat_poly_coeff_zero (n : ℕ) (p : ℝ[X])
    (hp : p.natDegree = n) (hp_monic : p.Monic) :
    (normalized_hat_poly n p).coeff 0 = 1 := by
  sorry -- Proven by Aristotle (Query 3)

/-- ⭐ KEY RESULT: Finite free cumulants are additive under ⊞_n. PROVEN for all n. -/
theorem finite_free_cumulant_additive (n : ℕ) (p q : ℝ[X]) (k : ℕ)
    (hk : k ≤ n) (hk0 : 0 < k)
    (hp : p.natDegree = n) (hq : q.natDegree = n)
    (hp_monic : p.Monic) (hq_monic : q.Monic) :
    finite_free_cumulant n (boxplus n p q) k =
    finite_free_cumulant n p k + finite_free_cumulant n q k := by
  sorry -- Proven by Aristotle (Query 3)

/-! ## PROVEN RESULTS (Small cases) -/

/-- n=2: 1/Φ_2 is additive under ⊞_2 (EQUALITY). PROVEN. -/
theorem conjecture_n_2 (p q : ℝ[X])
    (hp_monic : p.Monic) (hq_monic : q.Monic)
    (hp_deg : p.natDegree = 2) (hq_deg : q.natDegree = 2)
    (hp_real : p.Splits (RingHom.id ℝ)) (hq_real : q.Splits (RingHom.id ℝ)) :
    invPhi (boxplus 2 p q) = invPhi p + invPhi q := by
  sorry -- Proven by Aristotle (Query 1-2)

/-- n=3: Finite free Stam inequality holds for reduced cubics. PROVEN. -/
theorem conjecture_n_3_reduced (a1 b1 a2 b2 : ℝ)
    (h_real1 : (X^3 + C a1 * X + C b1).Splits (RingHom.id ℝ))
    (h_nodup1 : (X^3 + C a1 * X + C b1).roots.Nodup)
    (h_real2 : (X^3 + C a2 * X + C b2).Splits (RingHom.id ℝ))
    (h_nodup2 : (X^3 + C a2 * X + C b2).roots.Nodup)
    (h_real3 : (X^3 + C (a1+a2) * X + C (b1+b2)).Splits (RingHom.id ℝ))
    (h_nodup3 : (X^3 + C (a1+a2) * X + C (b1+b2)).roots.Nodup) :
    invPhi (X^3 + C (a1+a2) * X + C (b1+b2)) ≥
    invPhi (X^3 + C a1 * X + C b1) + invPhi (X^3 + C a2 * X + C b2) := by
  sorry -- Proven by Aristotle (Query 2-3), via Cauchy-Schwarz

/-- n=3: Auxiliary Cauchy-Schwarz inequality. PROVEN. -/
theorem n3_inequality (b1 b2 u1 u2 : ℝ) (hu1 : u1 > 0) (hu2 : u2 > 0) :
    (b1 + b2)^2 / (u1 + u2)^2 ≤ b1^2 / u1^2 + b2^2 / u2^2 := by
  sorry -- Proven by Aristotle (Query 2)

/-- n=3: Superadditivity of 1/Φ_3 formula in coefficients. PROVEN. -/
theorem invPhi_deg3_superadditive (a1 b1 a2 b2 : ℝ) (ha1 : a1 < 0) (ha2 : a2 < 0) :
    let f := fun a b => (-4 * a^3 - 27 * b^2) / (18 * a^2)
    f (a1 + a2) (b1 + b2) ≥ f a1 b1 + f a2 b2 := by
  sorry -- Proven by Aristotle (Query 3)

/-! ## FORMAL PROBLEM STATEMENT -/

/-- The Finite Free Stam Inequality: 1/Φ_n(p ⊞_n q) ≥ 1/Φ_n(p) + 1/Φ_n(q). -/
theorem first_proof_problem4 (n : ℕ) (hn : 0 < n)
    (rp rq rpq : Fin n → ℝ)
    (hp : Function.Injective rp) (hq : Function.Injective rq) (hpq : Function.Injective rpq)
    (hconv : (∏ i : Fin n, (X - C (rpq i))) =
             freeAddConv n (∏ i : Fin n, (X - C (rp i))) (∏ i : Fin n, (X - C (rq i))))
    : 1 / phi n rpq ≥ 1 / phi n rp + 1 / phi n rq := by
  sorry


/-
The (2k)-th coefficient of the hat polynomial of the scaled Hermite polynomial is given by a specific formula involving factorials and powers of t.
-/
def scaled_hermite (n : ℕ) (t : ℝ) : ℝ[X] :=
  ∑ k ∈ range (n / 2 + 1), C ((-1 : ℝ) ^ k * (n.factorial : ℝ) / ((k.factorial : ℝ) * ((n - 2 * k).factorial : ℝ) * (2 : ℝ) ^ k) * t ^ k) * X ^ (n - 2 * k)

theorem coeff_hat_poly_scaled_hermite (n : ℕ) (t : ℝ) (k : ℕ) (hk : k ≤ n / 2) :
    (hat_poly n (scaled_hermite n t)).coeff (2 * k) =
    (-1 : ℝ) ^ k * (n.factorial : ℝ) / ((k.factorial : ℝ) * (2 : ℝ) ^ k) * t ^ k := by
  -- The coefficient of $X^{2k}$ in the hat polynomial is given by the coefficient of $X^{n-2k}$ in the original polynomial multiplied by $(n-2k)!$.
  have h_coeff : (hat_poly n (scaled_hermite n t)).coeff (2 * k) = ((Polynomial.coeff (scaled_hermite n t) (n - 2 * k)) * (n - 2 * k).factorial) := by
    unfold hat_poly;
    norm_num [ mul_assoc, Polynomial.coeff_C_mul_X_pow ];
    intros; omega;
  rw [ h_coeff, scaled_hermite ];
  norm_num [ Polynomial.coeff_sum, div_mul_eq_mul_div ];
  rw [ Finset.sum_eq_single_of_mem k ];
  · norm_num [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Nat.factorial_ne_zero ];
  · exact Finset.mem_range.mpr ( Nat.lt_succ_of_le hk );
  · grind

/-
The normalized hat polynomial of the scaled Hermite polynomial is a truncated Gaussian (exponential of X^2).
-/
def truncated_gaussian (n : ℕ) (c : ℝ) : ℝ[X] :=
  ∑ k ∈ range (n / 2 + 1), C (c ^ k / k.factorial) * X ^ (2 * k)

theorem normalized_hat_poly_scaled_hermite (n : ℕ) (t : ℝ) :
    normalized_hat_poly n (scaled_hermite n t) = truncated_gaussian n (-t / 2) := by
  -- By definition of hat polynomial, we know that its coefficients match those of the truncated Gaussian.
  have h_hat_poly_coeff : ∀ k ∈ Finset.range (n + 1), (hat_poly n (scaled_hermite n t)).coeff k = if k % 2 = 0 then ((-t / 2 : ℝ) ^ (k / 2) / (k / 2).factorial) * (n.factorial : ℝ) else 0 := by
    intro k hk
    by_cases hk_even : k % 2 = 0;
    · have h_coeff_even : (hat_poly n (scaled_hermite n t)).coeff k = (-1 : ℝ) ^ (k / 2) * (n.factorial : ℝ) / ((k / 2).factorial * (2 : ℝ) ^ (k / 2)) * t ^ (k / 2) := by
        convert coeff_hat_poly_scaled_hermite n t ( k / 2 ) ( Nat.div_le_div_right ( Finset.mem_range_succ_iff.mp hk ) ) using 1 ; ring;
        rw [ Nat.div_mul_cancel ( Nat.dvd_of_mod_eq_zero hk_even ) ];
      rw [ h_coeff_even, if_pos hk_even ] ; ring;
      norm_num only [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, ← mul_pow ];
    · -- Since $k$ is odd, the coefficient of $X^k$ in the scaled Hermite polynomial is zero.
      have h_odd_coeff : ∀ k ∈ Finset.range (n + 1), k % 2 = 1 → (scaled_hermite n t).coeff (n - k) = 0 := by
        intros k hk hk_odd
        have h_coeff_zero : ∀ i ∈ Finset.range (n / 2 + 1), (n - k) ≠ (n - 2 * i) := by
          intros i hi; intro H; rw [ tsub_right_inj ] at H <;> try linarith [ Finset.mem_range.mp hk, Finset.mem_range.mp hi, Nat.div_mul_le_self n 2 ] ; ; omega;
        rw [ scaled_hermite ];
        field_simp;
        rw [ Polynomial.finset_sum_coeff, Finset.sum_eq_zero ] ; aesop;
      simp_all +decide [ hat_poly ];
      rw [ Finset.sum_eq_single k ] <;> simp_all +decide [ Polynomial.coeff_C, Polynomial.coeff_X_pow ];
      intro b hb hb'; by_cases hb_even : b % 2 = 0 <;> simp_all +decide [ Polynomial.coeff_C, Polynomial.coeff_X_pow, mul_assoc ] ;
      aesop;
  -- By definition of normalized_hat_poly, we know that its coefficients match those of the truncated Gaussian.
  have h_normalized_hat_poly_coeff : ∀ k ∈ Finset.range (n + 1), (normalized_hat_poly n (scaled_hermite n t)).coeff k = if k % 2 = 0 then ((-t / 2 : ℝ) ^ (k / 2) / (k / 2).factorial) else 0 := by
    -- By definition of normalized_hat_poly, we know that its coefficients are the same as those of the hat_poly divided by the constant term.
    intros k hk
    simp [normalized_hat_poly, h_hat_poly_coeff k hk];
    rw [ h_hat_poly_coeff 0 ( by norm_num ) ] ; norm_num [ Nat.factorial_ne_zero ];
  ext k; by_cases hk : k ≤ n <;> simp_all +decide [ Polynomial.ext_iff ] ;
  · rw [ h_normalized_hat_poly_coeff k ( Nat.lt_succ_of_le hk ), truncated_gaussian ];
    rcases Nat.even_or_odd' k with ⟨ k, rfl | rfl ⟩ <;> norm_num [ Polynomial.coeff_C, Polynomial.coeff_X_pow ];
    · exact fun h => absurd h ( by omega );
    · exact Eq.symm ( Finset.sum_eq_zero fun x hx => if_neg ( by omega ) );
  · rw [ Polynomial.coeff_eq_zero_of_natDegree_lt, Polynomial.coeff_eq_zero_of_natDegree_lt ] <;> norm_num [ truncated_gaussian ];
    · refine' lt_of_le_of_lt ( Polynomial.natDegree_sum_le _ _ ) _;
      refine' lt_of_le_of_lt ( Finset.sup_le _ ) _ <;> norm_num;
      exacts [ n, fun b hb => le_trans ( Polynomial.natDegree_C_mul_X_pow_le _ _ ) ( by linarith [ Nat.div_mul_le_self n 2 ] ), by linarith [ Nat.div_mul_le_self n 2 ] ];
    · refine' lt_of_le_of_lt ( Polynomial.natDegree_le_of_degree_le _ ) hk;
      refine' le_trans ( Polynomial.degree_mul_le _ _ ) _ ; norm_num [ Polynomial.degree_le_iff_coeff_zero ];
      refine' le_trans ( add_le_add ( Polynomial.degree_le_of_natDegree_le <| Polynomial.natDegree_le_of_degree_le <| Polynomial.degree_sum_le _ _ |> le_trans <| Finset.sup_le _ ) ( Polynomial.degree_C_le ) ) _;
      exacts [ n, fun i hi => le_trans ( Polynomial.degree_C_mul_X_pow_le _ _ ) ( by norm_num; linarith [ Finset.mem_range.mp hi ] ), by norm_num ]

/-
The truncated Gaussian is congruent to the truncated exponential of cX^2 modulo X^(n+1).
-/
def poly_exp (n : ℕ) (p : ℝ[X]) : ℝ[X] :=
  ∑ i ∈ range (n + 1), C (1 / (i.factorial : ℝ)) * p ^ i

theorem truncated_gaussian_eq_poly_exp_mod (n : ℕ) (c : ℝ) :
    (truncated_gaussian n c) % (X ^ (n + 1)) = (poly_exp n (C c * X ^ 2)) % (X ^ (n + 1)) := by
  -- By definition of polynomial congruence, we need to show that the polynomials differ by a multiple of $X^{n+1}$.
  suffices h_diff : ∃ Q : ℝ[X], poly_exp n (C c * X ^ 2) = (truncated_gaussian n c) + X ^ (n + 1) * Q by
    cases' h_diff with Q hQ; norm_num [ hQ, Polynomial.mod_def ] ;
    rw [ Polynomial.add_modByMonic ] ; norm_num;
  -- The terms for $k > n / 2$ in the sum for `poly_exp n (C c * X ^ 2)` are all divisible by $X^{n+1}$.
  have h_div : ∀ k > n / 2, X ^ (n + 1) ∣ C (c ^ k / k.factorial) * X ^ (2 * k) := by
    exact fun k hk => dvd_mul_of_dvd_right ( pow_dvd_pow _ ( by omega ) ) _;
  -- We can split the sum into two parts: one for $k \leq n / 2$ and one for $k > n / 2$.
  have h_split : poly_exp n (C c * X ^ 2) = (∑ k ∈ Finset.range (n / 2 + 1), C (c ^ k / k.factorial) * X ^ (2 * k)) + (∑ k ∈ Finset.Ico (n / 2 + 1) (n + 1), C (c ^ k / k.factorial) * X ^ (2 * k)) := by
    rw [ Finset.sum_range_add_sum_Ico _ ( by linarith [ Nat.div_mul_le_self n 2 ] ) ];
    exact Finset.sum_congr rfl fun i hi => by rw [ show C c * X ^ 2 = ( C c * X ^ 2 ) by rfl ] ; rw [ show ( C c * X ^ 2 ) ^ i = ( C c ^ i * X ^ ( 2 * i ) ) by ring ] ; simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, pow_mul', Nat.factorial_ne_zero ] ;
  -- The second sum is divisible by $X^{n+1}$.
  have h_second_sum_div : X ^ (n + 1) ∣ ∑ k ∈ Finset.Ico (n / 2 + 1) (n + 1), C (c ^ k / k.factorial) * X ^ (2 * k) := by
    exact Finset.dvd_sum fun k hk => h_div k <| Finset.mem_Ico.mp hk |>.1;
  exact h_split.symm ▸ by obtain ⟨ Q, hQ ⟩ := h_second_sum_div; exact ⟨ Q, by rw [ hQ ] ; rfl ⟩ ;

/-
The derivative of the truncated Gaussian is 2cX times the truncated Gaussian of degree n-2, for n >= 2.
-/
theorem derivative_truncated_gaussian (n : ℕ) (c : ℝ) (hn : 2 ≤ n) :
    (truncated_gaussian n c).derivative = 2 * C c * X * (truncated_gaussian (n - 2) c) := by
  rcases Nat.even_or_odd' n with ⟨ k, rfl | rfl ⟩ <;> simp_all +decide [ truncated_gaussian, Polynomial.derivative_pow ];
  · rcases k with ( _ | k ) <;> simp_all +decide [ Nat.mul_succ, Finset.sum_range_succ' ];
    norm_num [ Finset.mul_sum _ _ _, mul_assoc, mul_left_comm, mul_add, add_mul, pow_succ, Nat.factorial_succ ] ; ring;
    refine' congrArg₂ ( · + · ) _ ( Finset.sum_congr rfl fun x hx => _ ) <;> norm_num ; ring;
    · exact Polynomial.funext fun x => by norm_num; ring;
    · refine' Polynomial.funext fun x => _ ; norm_num ; ring;
      -- Combine and simplify the terms in the equation.
      field_simp
      ring;
  · rcases k with ( _ | k ) <;> simp_all +decide [ Nat.add_div, Nat.mul_succ, Finset.sum_range_succ' ];
    norm_num [ Finset.mul_sum _ _ _, mul_assoc, mul_left_comm, mul_add, add_mul, pow_succ, Nat.factorial_succ ] ; ring;
    refine' congrArg₂ ( · + · ) _ ( Finset.sum_congr rfl fun x hx => _ ) <;> norm_num ; ring;
    · exact Polynomial.funext fun x => by norm_num; ring;
    · refine' Polynomial.funext fun x => _ ; norm_num ; ring;
      -- Combine and simplify the terms in the equation.
      field_simp
      ring

/-
The formula for 1/Phi of a symmetric quartic in terms of cumulants is correct.
-/
def invPhi4_sym_formula (k2 k4 : ℝ) : ℝ :=
  (2 / 3) * (-k2) - (4 / 3) * k4 ^ 2 / (-k2 * (k2 ^ 2 + k4))

theorem invPhi_eq_formula_n4_sym (a b : ℝ)
    (ha : a < 0) (hb : 0 < b) (hdiscr : a ^ 2 > 4 * b) :
    let p := X ^ 4 + C a * X ^ 2 + C b
    let k2 := finite_free_cumulant 4 p 2
    let k4 := finite_free_cumulant 4 p 4
    invPhi p = invPhi4_sym_formula k2 k4 := by
  have h_invPhi : let p := X ^ 4 + C a * X ^ 2 + C b;
    let k2 := finite_free_cumulant 4 p 2;
    let k4 := finite_free_cumulant 4 p 4;
    invPhi p = -2 * b * (a^2 - 4 * b) / (a * (a^2 + 12 * b)) := by
      -- By definition of $p$, we know that its roots are $\pm \sqrt{y_1}$ and $\pm \sqrt{y_2}$, where $y_1$ and $y_2$ are the roots of $y^2 + ay + b = 0$.
      obtain ⟨y1, y2, hy1, hy2, hy_distinct⟩ : ∃ y1 y2 : ℝ, y1 ≠ y2 ∧ y1 + y2 = -a ∧ y1 * y2 = b ∧ y1 > 0 ∧ y2 > 0 := by
        exact ⟨ ( -a + Real.sqrt ( a^2 - 4 * b ) ) / 2, ( -a - Real.sqrt ( a^2 - 4 * b ) ) / 2, by nlinarith [ Real.mul_self_sqrt ( show 0 ≤ a^2 - 4 * b by linarith ) ], by ring, by linarith [ Real.mul_self_sqrt ( show 0 ≤ a^2 - 4 * b by linarith ) ], by nlinarith [ Real.sqrt_nonneg ( a^2 - 4 * b ), Real.mul_self_sqrt ( show 0 ≤ a^2 - 4 * b by linarith ) ], by nlinarith [ Real.sqrt_nonneg ( a^2 - 4 * b ), Real.mul_self_sqrt ( show 0 ≤ a^2 - 4 * b by linarith ) ] ⟩;
      -- The roots of $p$ are $\pm \sqrt{y_1}$ and $\pm \sqrt{y_2}$.
      have h_roots : Polynomial.roots (Polynomial.X ^ 4 + Polynomial.C a * Polynomial.X ^ 2 + Polynomial.C b) = {Real.sqrt y1, -Real.sqrt y1, Real.sqrt y2, -Real.sqrt y2} := by
        rw [ show ( Polynomial.X ^ 4 + Polynomial.C a * Polynomial.X ^ 2 + Polynomial.C b : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C ( Real.sqrt y1 ) ) * ( Polynomial.X - Polynomial.C ( -Real.sqrt y1 ) ) * ( Polynomial.X - Polynomial.C ( Real.sqrt y2 ) ) * ( Polynomial.X - Polynomial.C ( -Real.sqrt y2 ) ) from _ ];
        · rw [ Polynomial.roots_mul, Polynomial.roots_mul, Polynomial.roots_mul, Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ];
          · rfl;
          · exact mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ );
          · exact mul_ne_zero ( mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ) ( Polynomial.X_sub_C_ne_zero _ );
          · apply_rules [ mul_ne_zero, Polynomial.X_sub_C_ne_zero ];
        · refine' Polynomial.funext fun x => _ ; norm_num ; ring;
          grind;
      -- Calculate the value of $\Phi$ for the polynomial $p$.
      have h_phi : Phi (Polynomial.X ^ 4 + Polynomial.C a * Polynomial.X ^ 2 + Polynomial.C b) = -a * (a ^ 2 + 12 * b) / (2 * b * (a ^ 2 - 4 * b)) := by
        have h_phi : Phi (Polynomial.X ^ 4 + Polynomial.C a * Polynomial.X ^ 2 + Polynomial.C b) = 2 * (1 / (Real.sqrt y1 - (-Real.sqrt y1)) ^ 2 + 1 / (Real.sqrt y1 - Real.sqrt y2) ^ 2 + 1 / (Real.sqrt y1 - (-Real.sqrt y2)) ^ 2 + 1 / ((-Real.sqrt y1) - Real.sqrt y2) ^ 2 + 1 / ((-Real.sqrt y1) - (-Real.sqrt y2)) ^ 2 + 1 / (Real.sqrt y2 - (-Real.sqrt y2)) ^ 2) := by
          convert phi_eq_sum_sq_diff 4 ( fun i => if i = 0 then Real.sqrt y1 else if i = 1 then -Real.sqrt y1 else if i = 2 then Real.sqrt y2 else -Real.sqrt y2 ) _ using 1;
          · convert Phi_eq_phi 4 _ _ using 2;
            · refine' Polynomial.eq_of_degree_sub_lt_of_eval_finset_eq _ _ _;
              exact { Real.sqrt y1, -Real.sqrt y1, Real.sqrt y2, -Real.sqrt y2 };
              · refine' lt_of_lt_of_le ( Polynomial.degree_sub_lt _ _ _ ) _;
                · norm_num [ Polynomial.degree_prod, Polynomial.degree_X_pow_sub_C ];
                  rw [ Polynomial.degree_add_C ] <;> rw [ Polynomial.degree_add_eq_left_of_degree_lt ] <;> norm_num [ ha.ne, hb.ne' ];
                · exact ne_of_apply_ne ( fun p => p.coeff 4 ) ( by norm_num [ Polynomial.coeff_eq_zero_of_natDegree_lt ] );
                · norm_num [ Polynomial.leadingCoeff_prod ];
                  rw [ Polynomial.leadingCoeff, Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> norm_num [ Polynomial.natDegree_X_pow, Polynomial.natDegree_C, ha.ne, hb.ne' ];
                · rw [ Finset.card_insert_of_notMem, Finset.card_insert_of_notMem, Finset.card_insert_of_notMem, Finset.card_singleton ] <;> norm_num [ Real.sqrt_ne_zero'.mpr hy_distinct.2.1, Real.sqrt_ne_zero'.mpr hy_distinct.2.2, hy1 ];
                  · rw [ Polynomial.degree_add_C ] <;> rw [ Polynomial.degree_add_eq_left_of_degree_lt ] <;> by_cases ha : a = 0 <;> simp +decide [ ha ];
                  · linarith [ Real.sqrt_pos.2 hy_distinct.2.2 ];
                  · exact ⟨ by linarith [ Real.sqrt_pos.2 hy_distinct.2.1, Real.sqrt_pos.2 hy_distinct.2.2 ], by rw [ Real.sqrt_inj ] <;> cases lt_or_gt_of_ne hy1 <;> nlinarith ⟩;
                  · grind;
              · simp +decide [ Fin.prod_univ_four ];
                grind;
            · simp +decide [ Function.Injective, Fin.forall_fin_succ ];
              norm_num [ Real.sqrt_eq_cases, hy_distinct.2.1.le, hy_distinct.2.2.le ];
              exact ⟨ ⟨ hy_distinct.2.1, Ne.symm hy1, fun h => by linarith ⟩, ⟨ by linarith [ Real.sqrt_pos.2 hy_distinct.2.1 ], by linarith [ Real.sqrt_pos.2 hy_distinct.2.1, Real.sqrt_pos.2 hy_distinct.2.2 ], Ne.symm hy1 ⟩, ⟨ hy1, fun h => by linarith, hy_distinct.2.2 ⟩, by linarith [ Real.sqrt_pos.2 hy_distinct.2.1, Real.sqrt_pos.2 hy_distinct.2.2 ], hy1, by linarith [ Real.sqrt_pos.2 hy_distinct.2.1, Real.sqrt_pos.2 hy_distinct.2.2 ] ⟩;
          · simp +decide [ Fin.sum_univ_four, Finset.sum_filter ] ; ring;
          · simp +decide [ Function.Injective, Fin.forall_fin_succ ];
            norm_num [ Real.sqrt_eq_cases, hy_distinct.2.1.le, hy_distinct.2.2.le ];
            exact ⟨ ⟨ hy_distinct.2.1, Ne.symm hy1, fun h => by linarith ⟩, ⟨ by linarith [ Real.sqrt_pos.2 hy_distinct.2.1 ], by linarith [ Real.sqrt_pos.2 hy_distinct.2.1, Real.sqrt_pos.2 hy_distinct.2.2 ], Ne.symm hy1 ⟩, ⟨ hy1, fun h => by linarith, hy_distinct.2.2 ⟩, by linarith [ Real.sqrt_pos.2 hy_distinct.2.1, Real.sqrt_pos.2 hy_distinct.2.2 ], hy1, by linarith [ Real.sqrt_pos.2 hy_distinct.2.1, Real.sqrt_pos.2 hy_distinct.2.2 ] ⟩;
        rw [ h_phi ];
        rw [ ← hy2, ← hy_distinct.1 ] ; ring;
        rw [ show a = -y1 - y2 by linarith ] ; ring;
        field_simp;
        rw [ div_add_div, div_add_div, div_add_div, div_eq_div_iff ] <;> try nlinarith [ Real.mul_self_sqrt hy_distinct.2.1.le, Real.mul_self_sqrt hy_distinct.2.2.le ];
        · rw [ Real.sq_sqrt hy_distinct.2.1.le, Real.sq_sqrt hy_distinct.2.2.le ] ; ring;
          rw [ show Real.sqrt y1 ^ 4 = ( Real.sqrt y1 ^ 2 ) ^ 2 by ring, show Real.sqrt y2 ^ 2 = y2 by rw [ Real.sq_sqrt ( by linarith ) ] ] ; ring;
          rw [ show Real.sqrt y1 ^ 4 = ( Real.sqrt y1 ^ 2 ) ^ 2 by ring, Real.sq_sqrt ( by linarith ) ] ; ring;
        · simp_all +decide [ ne_of_gt, le_of_lt ];
          constructor <;> nlinarith only [ Real.mul_self_sqrt hy_distinct.2.1.le, Real.mul_self_sqrt hy_distinct.2.2.le, Real.sqrt_pos.2 hy_distinct.2.1, Real.sqrt_pos.2 hy_distinct.2.2, mul_self_pos.2 ( sub_ne_zero_of_ne hy1 ) ];
        · grind;
        · grind;
        · grind;
      convert congr_arg ( fun x => 1 / x ) h_phi using 1;
      · unfold invPhi;
        rw [ h_roots ] ; norm_num [ hy1, hy2, hy_distinct ];
        exact fun h => False.elim <| h ( by linarith [ Real.sqrt_pos.2 hy_distinct.2.1 ] ) ( by rw [ Real.sqrt_inj ] <;> cases lt_or_gt_of_ne hy1 <;> nlinarith ) ( by linarith [ Real.sqrt_pos.2 hy_distinct.2.1, Real.sqrt_pos.2 hy_distinct.2.2 ] ) ( by linarith [ Real.sqrt_pos.2 hy_distinct.2.1, Real.sqrt_pos.2 hy_distinct.2.2 ] ) ( by rw [ Real.sqrt_inj ] <;> cases lt_or_gt_of_ne hy1 <;> nlinarith ) |> fun h => by linarith [ Real.sqrt_pos.2 hy_distinct.2.1, Real.sqrt_pos.2 hy_distinct.2.2 ] ;
      · grind;
  -- By definition of $k2$ and $k4$, we know that $k2 = a / 12$ and $k4 = b / 24 - a^2 / 288$.
  have h_k2_k4 : finite_free_cumulant 4 (X ^ 4 + C a * X ^ 2 + C b) 2 = a / 12 ∧ finite_free_cumulant 4 (X ^ 4 + C a * X ^ 2 + C b) 4 = b / 24 - a^2 / 288 := by
    unfold finite_free_cumulant;
    unfold normalized_hat_poly poly_log;
    norm_num [ Finset.sum_range_succ', Polynomial.coeff_one, Polynomial.coeff_X, Polynomial.coeff_C, hat_poly ];
    norm_num [ Polynomial.coeff_one, Polynomial.coeff_X, pow_succ, mul_assoc, add_mul, sub_mul ] ; ring_nf ; norm_num;
  unfold invPhi4_sym_formula; norm_num [ h_invPhi, h_k2_k4 ] ; ring;
  rw [ show b * a * 12 + a ^ 3 = ( b * a * ( -1 / 288 ) + a ^ 3 * ( -1 / 3456 ) ) * ( -12 * 288 ) by ring ] ; norm_num ; ring;
  nlinarith [ inv_mul_cancel_left₀ ( show b * a * ( -1 / 288 ) + a ^ 3 * ( -1 / 3456 ) ≠ 0 by nlinarith [ pow_pos ( neg_pos.mpr ha ) 3 ] ) ( b * a ^ 2 ), inv_mul_cancel_left₀ ( show b * a * ( -1 / 288 ) + a ^ 3 * ( -1 / 3456 ) ≠ 0 by nlinarith [ pow_pos ( neg_pos.mpr ha ) 3 ] ) a ]

/-
The function f(x, y) = 2/3 x - 4/3 y^2/(x(x^2+y)) is superadditive on the domain x>0, -x^2/2 < y < x^2.
-/
theorem invPhi4_sym_superadditive (x1 y1 x2 y2 : ℝ)
    (hx1 : x1 > 0) (hy1_lower : y1 > -x1 ^ 2 / 2) (hy1_upper : y1 < x1 ^ 2)
    (hx2 : x2 > 0) (hy2_lower : y2 > -x2 ^ 2 / 2) (hy2_upper : y2 < x2 ^ 2) :
    let f := fun x y => (2 / 3) * x - (4 / 3) * y ^ 2 / (x * (x ^ 2 + y))
    f (x1 + x2) (y1 + y2) ≥ f x1 y1 + f x2 y2 := by
  -- Let's simplify the expression by cancelling out common terms.
  suffices h_simp : (y1 ^ 2 / (x1 * (x1 ^ 2 + y1))) + (y2 ^ 2 / (x2 * (x2 ^ 2 + y2))) ≥ ((y1 + y2) ^ 2 / ((x1 + x2) * ((x1 + x2) ^ 2 + (y1 + y2)))) by
    ring_nf at *; linarith;
  -- By Cauchy-Schwarz inequality, we have $\frac{y_1^2}{x_1(x_1^2 + y_1)} + \frac{y_2^2}{x_2(x_2^2 + y_2)} \geq \frac{(y_1 + y_2)^2}{x_1(x_1^2 + y_1) + x_2(x_2^2 + y_2)}$.
  have h_cauchy_schwarz : (y1^2 / (x1 * (x1^2 + y1))) + (y2^2 / (x2 * (x2^2 + y2))) ≥ (y1 + y2)^2 / (x1 * (x1^2 + y1) + x2 * (x2^2 + y2)) := by
    rw [ ge_iff_le, div_add_div, div_le_div_iff₀ ] <;> try nlinarith;
    · nlinarith [ sq_nonneg ( y1 * ( x2 * ( x2 ^ 2 + y2 ) ) - y2 * ( x1 * ( x1 ^ 2 + y1 ) ) ) ];
    · exact mul_pos ( mul_pos hx1 ( by nlinarith ) ) ( mul_pos hx2 ( by nlinarith ) );
  exact le_trans ( by exact div_le_div_of_nonneg_left ( by positivity ) ( by nlinarith ) ( by nlinarith [ sq_nonneg ( x1 - x2 ), mul_pos hx1 hx2 ] ) ) h_cauchy_schwarz

/-
The finite free additive convolution of two symmetric quartics is a symmetric quartic.
-/
def is_symmetric_quartic (p : ℝ[X]) : Prop :=
  p.Monic ∧ p.natDegree = 4 ∧ p.coeff 3 = 0 ∧ p.coeff 1 = 0

theorem boxplus_symmetric_quartic (p q : ℝ[X])
    (hp : is_symmetric_quartic p) (hq : is_symmetric_quartic q) :
    is_symmetric_quartic (boxplus 4 p q) := by
  -- By definition of $is_symmetric_quartic$, we know that $p$ and $q$ are of the form $X^4 + aX^2 + b$.
  obtain ⟨a1, b1, hp_def⟩ := hp
  obtain ⟨a2, b2, hq_def⟩ := hq;
  -- By definition of $boxplus$, we know that $p ⊞_4 q$ is also a polynomial of degree 4.
  have h_deg : (boxplus 4 p q).natDegree = 4 := by
    refine' Polynomial.natDegree_eq_of_degree_eq_some _;
    refine' Polynomial.degree_eq_of_le_of_coeff_ne_zero _ _;
    · refine' le_trans ( Polynomial.degree_sum_le _ _ ) _;
      norm_num [ Finset.sup_le_iff ];
      exact fun k hk => le_trans ( add_le_add ( Polynomial.degree_C_le ) le_rfl ) ( by interval_cases k <;> norm_num );
    · unfold boxplus; norm_num [ Finset.sum_range_succ', Polynomial.coeff_one, Polynomial.coeff_X, Polynomial.coeff_C, b1, b2, hp_def, hq_def ] ;
      unfold boxplus_coeff; norm_num [ Polynomial.coeff_eq_zero_of_natDegree_lt, b1, b2, hp_def, hq_def ] ;
      exact ⟨ by rw [ ← b1, a1.coeff_natDegree ] ; aesop, by rw [ ← b2, a2.coeff_natDegree ] ; aesop ⟩;
  -- By definition of $boxplus$, we know that $p ⊞_4 q$ is also a polynomial of degree 4 with coefficients zero for $X^3$ and $X^1$.
  have h_coeff : (boxplus 4 p q).coeff 3 = 0 ∧ (boxplus 4 p q).coeff 1 = 0 := by
    unfold boxplus; simp_all +decide [ Polynomial.coeff_eq_zero_of_natDegree_lt ] ;
    norm_num [ Finset.sum_range_succ, boxplus_coeff ] ; aesop;
  -- By definition of $boxplus$, we know that $p ⊞_4 q$ is also a polynomial of degree 4 with coefficients zero for $X^3$ and $X^1$, and leading coefficient 1.
  have h_monic : (boxplus 4 p q).Monic := by
    convert boxplus_centered_is_centered 4 p q _ _ |> And.left;
    · exact ⟨ a1, b1, by aesop ⟩;
    · exact ⟨ a2, b2, by aesop ⟩;
  unfold is_symmetric_quartic; aesop;

/-
Explicit formulas for the 2nd and 4th cumulants of a symmetric quartic.
-/
theorem symmetric_quartic_cumulants_explicit (a b : ℝ) :
    let p := X ^ 4 + C a * X ^ 2 + C b
    finite_free_cumulant 4 p 2 = a / 12 ∧ finite_free_cumulant 4 p 4 = b / 24 - a ^ 2 / 288 := by
  -- Let's compute the normalized hat polynomial of $p$.
  have h_normalized_hat : normalized_hat_poly 4 (X ^ 4 + C a * X ^ 2 + C b) = 1 + C (a / 12) * X ^ 2 + C (b / 24) * X ^ 4 := by
    unfold normalized_hat_poly hat_poly; norm_num [ Polynomial.coeff_one, Polynomial.coeff_X, Finset.sum_range_succ' ] ; ring;
    exact Polynomial.funext fun x => by norm_num; ring;
  unfold finite_free_cumulant;
  norm_num [ h_normalized_hat, poly_log ];
  norm_num [ Finset.sum_range_succ', Polynomial.coeff_one, Polynomial.coeff_X, pow_succ, mul_assoc, add_mul, sub_mul ] ; ring

/-
The finite free Stam inequality holds for symmetric quartics (using boxplus).
-/
theorem stam_inequality_n4_symmetric_boxplus (a1 b1 a2 b2 : ℝ)
    (ha1 : a1 < 0) (hb1 : 0 < b1) (hdiscr1 : a1 ^ 2 > 4 * b1)
    (ha2 : a2 < 0) (hb2 : 0 < b2) (hdiscr2 : a2 ^ 2 > 4 * b2) :
    let p1 := X ^ 4 + C a1 * X ^ 2 + C b1
    let p2 := X ^ 4 + C a2 * X ^ 2 + C b2
    let p3 := boxplus 4 p1 p2
    invPhi p3 ≥ invPhi p1 + invPhi p2 := by
  convert invPhi4_sym_superadditive ( - ( a1 / 12 ) ) ( b1 / 24 - a1 ^ 2 / 288 ) ( - ( a2 / 12 ) ) ( b2 / 24 - a2 ^ 2 / 288 ) _ _ _ _ _ _ using 1 <;> try nlinarith;
  constructor <;> intro h;
  · convert invPhi4_sym_superadditive ( - ( a1 / 12 ) ) ( b1 / 24 - a1 ^ 2 / 288 ) ( - ( a2 / 12 ) ) ( b2 / 24 - a2 ^ 2 / 288 ) _ _ _ _ _ _ using 1 <;> nlinarith;
  · have h_poly3 : ∃ a3 b3 : ℝ, boxplus 4 (X ^ 4 + C a1 * X ^ 2 + C b1) (X ^ 4 + C a2 * X ^ 2 + C b2) = X ^ 4 + C a3 * X ^ 2 + C b3 := by
      unfold boxplus;
      unfold boxplus_coeff; norm_num [ Finset.sum_range_succ', Polynomial.coeff_one, Polynomial.coeff_X, Polynomial.coeff_C ] ; ring_nf ;
      exact ⟨ a1 + a2, b1 + b2 + a1 * a2 / 6, by exact Polynomial.funext fun x => by norm_num; ring ⟩;
    obtain ⟨ a3, b3, h ⟩ := h_poly3; simp_all +decide [ invPhi4_sym_formula ] ;
    convert ‹- ( 2 / 3 * ( a1 / 12 ) ) - 4 / 3 * ( b1 / 24 - a1 ^ 2 / 288 ) ^ 2 / - ( a1 / 12 * ( ( a1 / 12 ) ^ 2 + ( b1 / 24 - a1 ^ 2 / 288 ) ) ) + ( - ( 2 / 3 * ( a2 / 12 ) ) - 4 / 3 * ( b2 / 24 - a2 ^ 2 / 288 ) ^ 2 / - ( a2 / 12 * ( ( a2 / 12 ) ^ 2 + ( b2 / 24 - a2 ^ 2 / 288 ) ) ) ) ≤ 2 / 3 * ( - ( a1 / 12 ) + - ( a2 / 12 ) ) - 4 / 3 * ( b1 / 24 - a1 ^ 2 / 288 + ( b2 / 24 - a2 ^ 2 / 288 ) ) ^ 2 / ( ( - ( a1 / 12 ) + - ( a2 / 12 ) ) * ( ( - ( a1 / 12 ) + - ( a2 / 12 ) ) ^ 2 + ( b1 / 24 - a1 ^ 2 / 288 + ( b2 / 24 - a2 ^ 2 / 288 ) ) ) ) › using 1;
    · convert congr_arg₂ ( · + · ) ( invPhi_eq_formula_n4_sym a1 b1 ha1 hb1 hdiscr1 ) ( invPhi_eq_formula_n4_sym a2 b2 ha2 hb2 hdiscr2 ) using 1;
      rw [ symmetric_quartic_cumulants_explicit a1 b1 |>.1, symmetric_quartic_cumulants_explicit a1 b1 |>.2, symmetric_quartic_cumulants_explicit a2 b2 |>.1, symmetric_quartic_cumulants_explicit a2 b2 |>.2 ] ; unfold invPhi4_sym_formula ; ring;
    · convert invPhi_eq_formula_n4_sym a3 b3 _ _ _ using 1;
      · rw [ ← h ];
        rw [ finite_free_cumulant_additive, finite_free_cumulant_additive ] <;> norm_num [ symmetric_quartic_cumulants_explicit ];
        any_goals erw [ Polynomial.Monic, Polynomial.leadingCoeff, Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> norm_num [ Polynomial.coeff_eq_zero_of_natDegree_lt ];
        any_goals rw [ Polynomial.natDegree_C_mul_X_pow ] <;> norm_num ; linarith;
        · unfold invPhi4_sym_formula; ring;
        · rw [ Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> norm_num [ ha1.ne ];
        · rw [ Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> norm_num [ Polynomial.natDegree_C_mul_X_pow, ha2.ne ];
        · rw [ Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> norm_num [ ha1.ne ];
        · rw [ Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> norm_num [ Polynomial.natDegree_C_mul_X_pow, ha2.ne ];
      · unfold boxplus at h; norm_num [ Finset.sum_range_succ', Polynomial.coeff_X, Polynomial.coeff_C ] at h;
        unfold boxplus_coeff at h; norm_num [ Finset.sum_range_succ', Polynomial.coeff_X, Polynomial.coeff_C ] at h;
        have := congr_arg ( Polynomial.eval 0 ) h; norm_num at this; ( have := congr_arg ( Polynomial.eval 1 ) h; norm_num at this; ( have := congr_arg ( Polynomial.eval ( -1 ) ) h; norm_num at this; nlinarith; ) );
      · unfold boxplus at h;
        norm_num [ Finset.sum_range_succ', boxplus_coeff ] at h;
        have := congr_arg ( Polynomial.eval 0 ) h; norm_num at this; ( have := congr_arg ( Polynomial.eval 1 ) h; norm_num at this; ( have := congr_arg ( Polynomial.eval ( -1 ) ) h; norm_num at this; nlinarith; ) );
      · unfold boxplus at h;
        norm_num [ Finset.sum_range_succ', boxplus_coeff ] at h;
        have h₁ := congr_arg ( Polynomial.eval 0 ) h; have h₂ := congr_arg ( Polynomial.eval 1 ) h; have h₃ := congr_arg ( Polynomial.eval ( -1 ) ) h; have h₄ := congr_arg ( Polynomial.eval ( -2 ) ) h; norm_num at h₁ h₂ h₃ h₄; nlinarith;

/-
Explicit formulas for the cumulants of a general centered quartic.
-/
theorem quartic_cumulants_general (a b c : ℝ) :
    let p := X ^ 4 + C a * X ^ 2 + C b * X + C c
    finite_free_cumulant 4 p 2 = a / 12 ∧
    finite_free_cumulant 4 p 3 = b / 24 ∧
    finite_free_cumulant 4 p 4 = c / 24 - a ^ 2 / 288 := by
  unfold finite_free_cumulant;
  unfold poly_log normalized_hat_poly hat_poly;
  norm_num [ Finset.sum_range_succ', Polynomial.coeff_one, Polynomial.coeff_X, Polynomial.coeff_C ];
  norm_num [ Polynomial.coeff_one, Polynomial.coeff_X, pow_succ, mul_assoc, sub_mul, add_mul ] ; ring_nf ; norm_num

/-
The condition for a symmetric quartic to have real distinct roots is equivalent to its cumulants lying in a specific domain.
-/
def cumulant_x (p : ℝ[X]) : ℝ := - finite_free_cumulant 4 p 2
def cumulant_y (p : ℝ[X]) : ℝ := finite_free_cumulant 4 p 4

theorem symmetric_quartic_roots_iff_cumulants_domain (a b : ℝ) :
    let p := X ^ 4 + C a * X ^ 2 + C b
    let x := cumulant_x p
    let y := cumulant_y p
    (a < 0 ∧ 0 < b ∧ a ^ 2 > 4 * b) ↔ (x > 0 ∧ y > -x ^ 2 / 2 ∧ y < x ^ 2) := by
  have h_x : cumulant_x ( X ^ 4 + C a * X ^ 2 + C b ) = -a / 12 := by
    convert congr_arg Neg.neg ( symmetric_quartic_cumulants_explicit a b |> And.left ) using 1 ; ring!;
  have h_y : cumulant_y ( X ^ 4 + C a * X ^ 2 + C b ) = b / 24 - a ^ 2 / 288 := by
    convert symmetric_quartic_cumulants_explicit a b |> And.right using 1
  simp [h_x, h_y];
  exact fun _ => ⟨ fun h => ⟨ by linarith, by linarith ⟩, fun h => ⟨ by linarith, by linarith ⟩ ⟩

/-
Generate data points for n=4.
-/
def get_quart_data (r1 r2 r3 r4 : ℚ) : (ℚ × ℚ × ℚ × ℚ) :=
  let s := (r1 + r2 + r3 + r4) / 4
  let x1 := r1 - s
  let x2 := r2 - s
  let x3 := r3 - s
  let x4 := r4 - s
  -- Coefficients of centered poly: X^4 + aX^2 + bX + c
  -- sum x_i = 0
  -- a = sum_{i<j} x_i x_j
  let a := x1*x2 + x1*x3 + x1*x4 + x2*x3 + x2*x4 + x3*x4
  -- b = - sum_{i<j<k} x_i x_j x_k
  let b := - (x1*x2*x3 + x1*x2*x4 + x1*x3*x4 + x2*x3*x4)
  -- c = x1 x2 x3 x4
  let c := x1*x2*x3*x4
  -- Cumulants
  let k2 := a / 12
  let k3 := b / 24
  let k4 := c / 24 - a^2 / 288
  -- Phi
  let phi := 2 * (1/(x1-x2)^2 + 1/(x1-x3)^2 + 1/(x1-x4)^2 + 1/(x2-x3)^2 + 1/(x2-x4)^2 + 1/(x3-x4)^2)
  (k2, k3, k4, 1/phi)

#eval get_quart_data 0 1 (-1) 0
#eval get_quart_data 1 (-1) 2 (-2)
#eval get_quart_data 1 2 3 (-6)
#eval get_quart_data 1 1 (-1) (-1)
#eval get_quart_data 1 2 4 (-7)

/-
Compute exact values.
-/
def compute_exact_values : ℚ × ℚ × ℚ × ℚ :=
  let roots : List ℚ := [-2, -1, 0, 3]
  let s := (roots.sum) / 4
  let centered := roots.map (fun r => r - s)
  let x1 := centered.get! 0
  let x2 := centered.get! 1
  let x3 := centered.get! 2
  let x4 := centered.get! 3
  let a := x1*x2 + x1*x3 + x1*x4 + x2*x3 + x2*x4 + x3*x4
  let b := - (x1*x2*x3 + x1*x2*x4 + x1*x3*x4 + x2*x3*x4)
  let c := x1*x2*x3*x4
  let k2 := a / 12
  let k3 := b / 24
  let k4 := c / 24 - a^2 / 288
  let phi := 2 * (1/(x1-x2)^2 + 1/(x1-x3)^2 + 1/(x1-x4)^2 + 1/(x2-x3)^2 + 1/(x2-x4)^2 + 1/(x3-x4)^2)
  (k2, k3, k4, 1/phi)

#eval compute_exact_values

/-
Gather data points.
-/
#eval get_quart_data (-2) (-1) 0 3
#eval get_quart_data (-3) (-2) 2 3
#eval get_quart_data (-5) 1 2 2
#eval get_quart_data (-1) 0 0 1
#eval get_quart_data (-2) 0 0 2

/-
The finite free Stam inequality holds for symmetric quartics.
-/
theorem stam_inequality_n4_symmetric_boxplus_v2 (a1 b1 a2 b2 : ℝ)
    (ha1 : a1 < 0) (hb1 : 0 < b1) (hdiscr1 : a1 ^ 2 > 4 * b1)
    (ha2 : a2 < 0) (hb2 : 0 < b2) (hdiscr2 : a2 ^ 2 > 4 * b2) :
    let p1 := X ^ 4 + C a1 * X ^ 2 + C b1
    let p2 := X ^ 4 + C a2 * X ^ 2 + C b2
    let p3 := boxplus 4 p1 p2
    invPhi p3 ≥ invPhi p1 + invPhi p2 := by
      convert stam_inequality_n4_symmetric_boxplus a1 b1 a2 b2 ha1 hb1 hdiscr1 ha2 hb2 hdiscr2 using 1