/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 123dc4b4-be55-480d-9994-5aff3dc81216

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of f_aux and poly_diff from the context.
-/
def f_aux (k : ℝ) : ℝ := (2 * k * (1 - 4 * k)) / (12 * k + 1)

def poly_diff (t x y : ℝ) : ℝ :=
  let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
  (2 * Z * (1 - 4 * Z)) * (1 + 12 * x) * (1 + 12 * y) -
  (t * (2 * x * (1 - 4 * x)) * (1 + 12 * Z) * (1 + 12 * y) +
   (1 - t) * (2 * y * (1 - 4 * y)) * (1 + 12 * Z) * (1 + 12 * x))

/-
poly_diff is symmetric under the transformation t -> 1-t, x <-> y.
-/
lemma poly_diff_symmetry (t x y : ℝ) :
    poly_diff t x y = poly_diff (1 - t) y x := by
  unfold poly_diff
  have hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 = (1 - t)^2 * y + (1 - (1 - t))^2 * x + (1 - t) * (1 - (1 - t)) / 6 := by
    ring
  rw [hZ]
  ring

/-
Relate poly_diff to the difference of f_aux values.
-/
def Z_val (t x y : ℝ) : ℝ := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6

lemma poly_diff_eq_numerator (t x y : ℝ)
    (hZ : 12 * Z_val t x y + 1 ≠ 0)
    (hx : 12 * x + 1 ≠ 0)
    (hy : 12 * y + 1 ≠ 0) :
    poly_diff t x y = (12 * Z_val t x y + 1) * (12 * x + 1) * (12 * y + 1) *
      (f_aux (Z_val t x y) - (t * f_aux x + (1 - t) * f_aux y)) := by
        unfold f_aux;
        field_simp;
        unfold poly_diff Z_val; ring;

/-
f_aux is increasing on (0, 1/12] and concave on (0, infinity).
-/
lemma f_aux_increasing (x y : ℝ) (hx : 0 < x) (hy : y ≤ 1/12) (hxy : x ≤ y) :
    f_aux x ≤ f_aux y := by
      unfold f_aux; rw [ div_le_div_iff₀ ] <;> nlinarith [ mul_le_mul_of_nonneg_left hxy hx.le ] ;

lemma f_aux_concave : ConcaveOn ℝ (Set.Ioi 0) f_aux := by
  apply_rules [ concaveOn_of_deriv2_nonpos, convex_Ioi ];
  · exact ContinuousOn.div ( Continuous.continuousOn ( by continuity ) ) ( Continuous.continuousOn ( by continuity ) ) fun x hx => by linarith [ hx.out ] ;
  · exact DifferentiableOn.div ( DifferentiableOn.mul ( differentiableOn_const _ |> DifferentiableOn.mul <| differentiableOn_id ) <| differentiableOn_const _ |> DifferentiableOn.sub <| differentiableOn_id.const_mul _ ) ( differentiableOn_id.const_mul _ |> DifferentiableOn.add <| differentiableOn_const _ ) ( by intro x hx; linarith [ Set.mem_Ioi.mp <| interior_subset hx ] );
  · unfold f_aux;
    refine' DifferentiableOn.congr _ _;
    exacts [ fun k => ( 2 * ( 1 - 4 * k ) + 2 * k * -4 ) * ( 12 * k + 1 ) / ( 12 * k + 1 ) ^ 2 - 2 * k * ( 1 - 4 * k ) * 12 / ( 12 * k + 1 ) ^ 2, DifferentiableOn.sub ( DifferentiableOn.div ( DifferentiableOn.mul ( DifferentiableOn.add ( DifferentiableOn.mul ( differentiableOn_const _ ) ( differentiableOn_const _ |> DifferentiableOn.sub <| differentiableOn_id.const_mul _ ) ) <| DifferentiableOn.mul ( differentiableOn_id.const_mul _ ) <| differentiableOn_const _ ) <| DifferentiableOn.add ( differentiableOn_id.const_mul _ ) <| differentiableOn_const _ ) ( DifferentiableOn.pow ( DifferentiableOn.add ( differentiableOn_id.const_mul _ ) <| differentiableOn_const _ ) _ ) <| by intro x hx; exact ne_of_gt <| sq_pos_of_pos <| by linarith [ Set.mem_Ioi.mp <| interior_subset hx ] ) ( DifferentiableOn.div ( DifferentiableOn.mul ( DifferentiableOn.mul ( differentiableOn_id.const_mul _ ) <| differentiableOn_const _ |> DifferentiableOn.sub <| differentiableOn_id.const_mul _ ) <| differentiableOn_const _ ) ( DifferentiableOn.pow ( DifferentiableOn.add ( differentiableOn_id.const_mul _ ) <| differentiableOn_const _ ) _ ) <| by intro x hx; exact ne_of_gt <| sq_pos_of_pos <| by linarith [ Set.mem_Ioi.mp <| interior_subset hx ] ), fun x hx => by norm_num [ mul_assoc, mul_comm, mul_left_comm, show x * 12 + 1 ≠ 0 from by linarith [ Set.mem_Ioi.mp <| interior_subset hx ] ] ; ring ];
  · unfold f_aux;
    norm_num [ fderiv_deriv, mul_comm ];
    -- Let's simplify the expression for the second derivative.
    intro x hx
    have h_deriv2_simplified : deriv (deriv fun k : ℝ => k * 2 * (1 - k * 4) / (k * 12 + 1)) x = deriv (fun k : ℝ => (2 * (1 - k * 4) - k * 2 * 4) / (k * 12 + 1) - k * 2 * (1 - k * 4) * 12 / (k * 12 + 1)^2) x := by
      field_simp;
      exact Filter.EventuallyEq.deriv_eq ( by filter_upwards [ lt_mem_nhds hx ] with k hk using by norm_num [ show k * 12 + 1 ≠ 0 by linarith ] ; ring );
    norm_num [ h_deriv2_simplified, show x * 12 + 1 ≠ 0 by positivity ];
    rw [ div_le_div_iff₀ ] <;> nlinarith [ pow_pos hx 3 ]

/-
f_aux is decreasing on [1/12, 1/4).
-/
lemma f_aux_decreasing (x y : ℝ) (hx : 1/12 ≤ x) (hy : y < 1/4) (hxy : x ≤ y) :
    f_aux y ≤ f_aux x := by
  unfold f_aux; rw [ div_le_div_iff₀ ] <;> try nlinarith;
  nlinarith [ mul_le_mul_of_nonneg_left hxy ( sub_nonneg_of_le hx ) ]

/-
Inequality holds when x+y <= 1/6 and Z <= 1/12.
-/
lemma f_aux_ineq_easy_case (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y ≤ 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 ≤ 1/12) :
    f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ t * f_aux x + (1 - t) * f_aux y := by
      -- Since $f_aux$ is concave on $(0, \infty)$, we can apply Jensen's inequality.
      have h_concave : ConcaveOn ℝ (Set.Ioi 0) f_aux := by
        exact?;
      -- Apply Jensen's inequality for the concave function $f_aux$ with weights $t$ and $1-t$.
      have h_jensen : f_aux (t * x + (1 - t) * y) ≥ t * f_aux x + (1 - t) * f_aux y := by
        exact h_concave.2 hx hy ( by linarith ) ( by linarith ) ( by linarith );
      refine le_trans h_jensen ?_;
      apply_rules [ f_aux_increasing ];
      · nlinarith;
      · nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ]

/-
Inequality holds when x+y > 1/6 and Z >= 1/12.
-/
lemma f_aux_ineq_case2_easy (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y > 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 ≥ 1/12) :
    f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ t * f_aux x + (1 - t) * f_aux y := by
      -- By definition of $f_aux$, we know that $f_aux$ is concave on $(0, \infty)$.
      have h_concave : ConcaveOn ℝ (Set.Ioi 0) f_aux := by
        apply_rules [ f_aux_concave ];
      have h_concave_ineq : f_aux (t * x + (1 - t) * y) ≥ t * f_aux x + (1 - t) * f_aux y := by
        exact h_concave.2 hx hy ( by linarith ) ( by linarith ) ( by linarith );
      refine le_trans h_concave_ineq ?_;
      apply_rules [ f_aux_decreasing ] <;> try nlinarith only [ ht, ht1, hx, hx1, hy, hy1, hsum, hZ ] ;
      nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ), mul_pos hx ( sub_pos.mpr ht1 ), mul_pos hy ( sub_pos.mpr ht1 ) ]

/-
Define W_val and prove the difference between Z and W.
-/
def W_val (t x y : ℝ) : ℝ := t * x + (1 - t) * y

lemma Z_sub_W (t x y : ℝ) : Z_val t x y - W_val t x y = t * (1 - t) * (1/6 - (x + y)) := by
  unfold Z_val W_val
  ring

/-
Define substitution variables and prove equivalence.
-/
def Z_subst (s x y : ℝ) : ℝ := (1/2 - s)^2 * x + (1/2 + s)^2 * y + (1/4 - s^2) / 6

def poly_diff_subst (s x y : ℝ) : ℝ :=
  let t := 1/2 - s
  poly_diff t x y

lemma poly_diff_eq_subst (t x y : ℝ) : poly_diff t x y = poly_diff_subst (1/2 - t) x y := by
  unfold poly_diff_subst
  simp

lemma Z_eq_Z_subst (t x y : ℝ) : Z_val t x y = Z_subst (1/2 - t) x y := by
  unfold Z_val Z_subst
  ring

/-
Definitions of boxplus, Phi, invPhi, and is_centered from context.
-/
open scoped BigOperators Real Nat Classical Pointwise
open Polynomial BigOperators Finset Classical

def boxplus_coeff (n : ℕ) (p q : ℝ[X]) (k : ℕ) : ℝ :=
  ∑ i ∈ range (k + 1),
    let j := k - i
    (Nat.factorial (n - i) * Nat.factorial (n - j) : ℝ) / (Nat.factorial n * Nat.factorial (n - k) : ℝ) *
    (p.coeff (n - i)) * (q.coeff (n - j))

def boxplus (n : ℕ) (p q : ℝ[X]) : ℝ[X] :=
  Finset.sum (range (n + 1)) (fun k => C (boxplus_coeff n p q k) * X ^ (n - k))

def Phi (p : ℝ[X]) : ℝ :=
  let roots := p.roots.toFinset
  ∑ r_i ∈ roots, (∑ r_j ∈ roots.erase r_i, 1 / (r_i - r_j))^2

def invPhi (p : ℝ[X]) : ℝ :=
  if p.roots.Nodup ∧ p.roots.card > 1 then
    1 / Phi p
  else 0

def is_centered (n : ℕ) (p : ℝ[X]) : Prop :=
  p.Monic ∧ p.natDegree = n ∧ p.coeff (n - 1) = 0

/-
Prove poly_diff is non-negative at t=1/2.
-/
lemma poly_diff_half_nonneg (x y : ℝ)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4) :
    poly_diff (1/2) x y ≥ 0 := by
      unfold poly_diff;
      nlinarith [ mul_nonneg hx.le hy.le, mul_nonneg hx.le ( sq_nonneg ( y - x ) ), mul_nonneg hy.le ( sq_nonneg ( x - y ) ), mul_nonneg hx.le ( sq_nonneg ( x - 1 / 12 ) ), mul_nonneg hy.le ( sq_nonneg ( y - 1 / 12 ) ) ]

/-
Assume the n=2 case of the inequality holds.
-/
theorem finite_free_stam_inequality_n2 (p q : ℝ[X])
    (hp : p.Splits (RingHom.id ℝ)) (hp_nodup : p.roots.Nodup)
    (hp_monic : p.Monic) (hp_deg : p.natDegree = 2)
    (hq : q.Splits (RingHom.id ℝ)) (hq_nodup : q.roots.Nodup)
    (hq_monic : q.Monic) (hq_deg : q.natDegree = 2)
    (hpq : (boxplus 2 p q).Splits (RingHom.id ℝ))
    (hpq_nodup : (boxplus 2 p q).roots.Nodup) :
    invPhi (boxplus 2 p q) ≥ invPhi p + invPhi q := by
      -- Let $x = \frac{1}{a_1 - \frac{1}{2}(a_1 + a_2)}$ and $y = \frac{1}{b_1 - \frac{1}{2}(b_1 + b_2)}$.
      obtain ⟨a1, a2, ha⟩ : ∃ a1 a2 : ℝ, p = Polynomial.C 1 * (Polynomial.X - Polynomial.C a1) * (Polynomial.X - Polynomial.C a2) := by
        rw [ Polynomial.splits_iff_card_roots ] at hp;
        obtain ⟨a1, a2, ha⟩ : ∃ a1 a2 : ℝ, p.roots = {a1, a2} := by
          exact Multiset.card_eq_two.mp ( hp.trans hp_deg );
        rw [ ← Polynomial.prod_multiset_X_sub_C_of_monic_of_roots_card_eq hp_monic ] <;> aesop
      obtain ⟨b1, b2, hb⟩ : ∃ b1 b2 : ℝ, q = Polynomial.C 1 * (Polynomial.X - Polynomial.C b1) * (Polynomial.X - Polynomial.C b2) := by
        norm_num [ Polynomial.splits_iff_card_roots ] at *;
        obtain ⟨ b1, b2, h ⟩ := Multiset.card_eq_two.mp ( by linarith : Multiset.card q.roots = 2 ) ; use b1, b2; rw [ ← Polynomial.prod_multiset_X_sub_C_of_monic_of_roots_card_eq hq_monic ] <;> aesop;
      by_cases ha1 : a1 = a2 <;> by_cases hb1 : b1 = b2 <;> simp_all +decide [ Polynomial.Monic.def, Polynomial.leadingCoeff_mul ];
      · simp_all +decide [ Polynomial.roots_mul, Polynomial.X_sub_C_ne_zero ];
      · erw [ Polynomial.roots_mul ( by exact mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ) ] at hp_nodup ; aesop;
      · rw [ Polynomial.roots_mul ] at hq_nodup <;> aesop;
      · unfold boxplus;
        unfold boxplus_coeff; norm_num [ Finset.sum_range_succ', Polynomial.coeff_one, Polynomial.coeff_X, mul_assoc, sub_mul ] ;
        unfold invPhi; norm_num [ Polynomial.natDegree_add_eq_right_of_natDegree_lt, Polynomial.natDegree_sub_eq_right_of_natDegree_lt ] ;
        unfold Phi; norm_num [ Polynomial.natDegree_add_eq_right_of_natDegree_lt, Polynomial.natDegree_sub_eq_right_of_natDegree_lt ] ;
        rw [ show ( Polynomial.C a1 * Polynomial.C a2 + Polynomial.C ( 1 / 2 ) * ( - ( Polynomial.C a2 * ( - ( Polynomial.C b2 ) - Polynomial.C b1 ) ) - Polynomial.C a1 * ( - ( Polynomial.C b2 ) - Polynomial.C b1 ) ) + Polynomial.C b1 * Polynomial.C b2 + ( - ( Polynomial.C a2 ) - Polynomial.C a1 + ( - ( Polynomial.C b2 ) - Polynomial.C b1 ) ) * Polynomial.X + Polynomial.X ^ 2 : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C ( ( a1 + a2 + b1 + b2 ) / 2 - Real.sqrt ( ( a1 - a2 ) ^ 2 + ( b1 - b2 ) ^ 2 ) / 2 ) ) * ( Polynomial.X - Polynomial.C ( ( a1 + a2 + b1 + b2 ) / 2 + Real.sqrt ( ( a1 - a2 ) ^ 2 + ( b1 - b2 ) ^ 2 ) / 2 ) ) by exact Polynomial.funext fun x => by norm_num; linarith [ Real.mul_self_sqrt ( show 0 ≤ ( a1 - a2 ) ^ 2 + ( b1 - b2 ) ^ 2 by positivity ) ] ];
        rw [ Polynomial.roots_mul <| mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ] ; norm_num [ Polynomial.roots_X_sub_C ];
        rw [ show ( Polynomial.X * ( Polynomial.X - Polynomial.C a2 ) - Polynomial.C a1 * ( Polynomial.X - Polynomial.C a2 ) : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C a1 ) * ( Polynomial.X - Polynomial.C a2 ) by ring, show ( Polynomial.X * ( Polynomial.X - Polynomial.C b2 ) - Polynomial.C b1 * ( Polynomial.X - Polynomial.C b2 ) : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C b1 ) * ( Polynomial.X - Polynomial.C b2 ) by ring ] at * ; simp_all +decide [ Polynomial.roots_mul, Polynomial.X_sub_C_ne_zero ];
        rw [ show ( Polynomial.X - ( Polynomial.C ( ( a1 + a2 + b1 + b2 ) / 2 ) - Polynomial.C ( Real.sqrt ( ( a1 - a2 ) ^ 2 + ( b1 - b2 ) ^ 2 ) / 2 ) ) ) = ( Polynomial.X - Polynomial.C ( ( a1 + a2 + b1 + b2 ) / 2 - Real.sqrt ( ( a1 - a2 ) ^ 2 + ( b1 - b2 ) ^ 2 ) / 2 ) ) by norm_num, show ( Polynomial.X - ( Polynomial.C ( ( a1 + a2 + b1 + b2 ) / 2 ) + Polynomial.C ( Real.sqrt ( ( a1 - a2 ) ^ 2 + ( b1 - b2 ) ^ 2 ) / 2 ) ) ) = ( Polynomial.X - Polynomial.C ( ( a1 + a2 + b1 + b2 ) / 2 + Real.sqrt ( ( a1 - a2 ) ^ 2 + ( b1 - b2 ) ^ 2 ) / 2 ) ) by norm_num ] ; erw [ Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] ; norm_num;
        rw [ Finset.sum_pair, Finset.sum_pair ] <;> norm_num;
        · rw [ Finset.sum_pair ] <;> norm_num;
          · rw [ if_neg ( by linarith [ Real.sqrt_pos.mpr ( show 0 < ( a1 - a2 ) ^ 2 + ( b1 - b2 ) ^ 2 by nlinarith [ mul_self_pos.mpr ( sub_ne_zero.mpr ha1 ), mul_self_pos.mpr ( sub_ne_zero.mpr hb1 ) ] ) ] ) ] ; ring_nf ; norm_num;
            rw [ Real.sq_sqrt ] <;> nlinarith [ sq_nonneg ( a1 - a2 ), sq_nonneg ( b1 - b2 ) ];
          · linarith [ Real.sqrt_pos.mpr ( show 0 < ( a1 - a2 ) ^ 2 + ( b1 - b2 ) ^ 2 by nlinarith only [ mul_self_pos.mpr ( sub_ne_zero.mpr ha1 ), mul_self_pos.mpr ( sub_ne_zero.mpr hb1 ) ] ) ];
        · linarith [ Real.sqrt_pos.mpr ( show 0 < ( a1 - a2 ) ^ 2 + ( b1 - b2 ) ^ 2 by nlinarith only [ mul_self_pos.mpr ( sub_ne_zero.mpr ha1 ), mul_self_pos.mpr ( sub_ne_zero.mpr hb1 ) ] ) ];
        · linarith [ Real.sqrt_pos.mpr ( show 0 < ( a1 - a2 ) ^ 2 + ( b1 - b2 ) ^ 2 by nlinarith only [ mul_self_pos.mpr ( sub_ne_zero.mpr ha1 ), mul_self_pos.mpr ( sub_ne_zero.mpr hb1 ) ] ) ]

/-
Add boxplus_comp_add_C_left and boxplus_comm with proofs.
-/
lemma boxplus_comp_add_C_left (n : ℕ) (p q : ℝ[X]) (c : ℝ)
    (hp : p.natDegree = n) (hq : q.natDegree = n) :
    boxplus n (p.comp (X + C c)) q = (boxplus n p q).comp (X + C c) := by
      refine' Polynomial.funext _;
      intro r;
      -- We'll use the fact that $p(x+c)$ has coefficients given by the binomial theorem.
      have h_coeff : ∀ i ≤ n, (p.comp (.X + (.C c))).coeff (n - i) = ∑ j ∈ Finset.range (i + 1), Nat.choose (n - j) (n - i) * c ^ (i - j) * p.coeff (n - j) := by
        intro i hi
        have h_coeff : (p.comp (.X + (.C c))).coeff (n - i) = ∑ j ∈ Finset.range (n + 1), p.coeff j * Nat.choose j (n - i) * c ^ (j - (n - i)) := by
          rw [ Polynomial.comp, Polynomial.eval₂_eq_sum_range ];
          norm_num [ Polynomial.coeff_X_add_C_pow ];
          simp +decide [ mul_assoc, mul_comm, mul_left_comm, hp ];
        rw [ h_coeff, ← Finset.sum_flip ];
        rw [ ← Finset.sum_subset ( Finset.range_mono ( Nat.succ_le_succ hi ) ) ];
        · refine' Finset.sum_congr rfl fun x hx => _;
          grind;
        · simp +zetaDelta at *;
          exact fun x hx₁ hx₂ => Or.inl <| Or.inr <| Nat.choose_eq_zero_of_lt <| by omega;
      -- Substitute the expression for the coefficients of $p(x+c)$ into the definition of $boxplus$.
      have h_boxplus_subst : ∀ k ≤ n, boxplus_coeff n (p.comp (.X + (.C c))) q k = ∑ j ∈ Finset.range (k + 1), boxplus_coeff n p q j * Nat.choose (n - j) (n - k) * c^(k - j) := by
        unfold boxplus_coeff;
        intro k hk; rw [ Finset.sum_congr rfl fun i hi => by rw [ h_coeff i ( by linarith [ Finset.mem_range.mp hi ] ) ] ] ; simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Finset.sum_mul ] ;
        rw [ Finset.sum_sigma', Finset.sum_sigma' ];
        refine' Finset.sum_bij ( fun x hx => ⟨ k - x.1 + x.2, x.2 ⟩ ) _ _ _ _ <;> simp_all +decide [ Nat.choose_succ_succ, add_comm ];
        · exact fun a ha₁ ha₂ => ⟨ by omega, by omega ⟩;
        · grind;
        · exact fun b hb₁ hb₂ => ⟨ k - ( b.fst - b.snd ), b.snd, ⟨ by omega, by omega ⟩, by ext <;> norm_num ; omega ⟩;
        · intro a ha₁ ha₂; rw [ show a.fst - a.snd = k - ( a.snd + ( k - a.fst ) ) by omega ] ; ring;
          rw [ Nat.cast_choose, Nat.cast_choose ] <;> try omega;
          field_simp;
          rw [ show n - ( a.snd + ( k - a.fst ) ) - ( n - k ) = n - a.snd - ( n - a.fst ) by omega ] ; ring;
      -- By Fubini's theorem, we can interchange the order of summation.
      have h_fubini : ∑ k ∈ Finset.range (n + 1), (∑ j ∈ Finset.range (k + 1), boxplus_coeff n p q j * Nat.choose (n - j) (n - k) * c^(k - j)) * (r^(n - k)) = ∑ j ∈ Finset.range (n + 1), boxplus_coeff n p q j * (∑ k ∈ Finset.Ico j (n + 1), Nat.choose (n - j) (n - k) * c^(k - j) * r^(n - k)) := by
        simp +decide only [mul_assoc, sum_mul, Finset.mul_sum _ _ _];
        rw [ Finset.range_eq_Ico, Finset.sum_Ico_Ico_comm ];
      -- Let's simplify the inner sum $\sum_{k=j}^{n} \binom{n-j}{n-k} c^{k-j} r^{n-k}$.
      have h_inner_sum : ∀ j ≤ n, ∑ k ∈ Finset.Ico j (n + 1), Nat.choose (n - j) (n - k) * c^(k - j) * r^(n - k) = (r + c)^(n - j) := by
        intro j hj; rw [ add_pow ] ; simp +decide [ mul_assoc, mul_comm, mul_left_comm, Finset.sum_Ico_eq_sum_range ] ;
        rw [ ← Finset.sum_flip ];
        simp +decide [ Nat.sub_sub, add_comm, tsub_tsub_cancel_of_le hj ];
        rw [ Nat.sub_add_comm hj ];
        refine' Finset.sum_congr rfl fun x hx => _ ; rw [ show n - ( j + ( n - ( j + x ) ) ) = x by rw [ tsub_eq_of_eq_add ] ; linarith [ Nat.sub_add_cancel ( show j + x ≤ n from by linarith [ Finset.mem_range.mp hx, Nat.sub_add_cancel hj ] ) ] ] ; ring;
      unfold boxplus; simp_all +decide [ Polynomial.eval_finset_sum ] ;
      exact Eq.trans ( Finset.sum_congr rfl fun x hx => by rw [ h_boxplus_subst x ( Finset.mem_range_succ_iff.mp hx ) ] ) ( h_fubini.trans ( Finset.sum_congr rfl fun x hx => by rw [ h_inner_sum x ( Finset.mem_range_succ_iff.mp hx ) ] ) )

lemma boxplus_comm (n : ℕ) (p q : ℝ[X]) :
    boxplus n p q = boxplus n q p := by
      -- By definition of `boxplus`, we know that it is symmetric.
      have h_symm : ∀ k, boxplus_coeff n p q k = boxplus_coeff n q p k := by
        intro k
        unfold boxplus_coeff
        simp [mul_comm, mul_assoc, mul_left_comm];
        rw [ ← Finset.sum_flip ];
        exact Finset.sum_congr rfl fun x hx => by rw [ tsub_tsub_cancel_of_le ( Finset.mem_range_succ_iff.mp hx ) ] ; ring;
      unfold boxplus; aesop;

/-
boxplus commutes with translation.
-/
theorem boxplus_comp_add_C (n : ℕ) (p q : ℝ[X]) (c d : ℝ)
    (hp : p.natDegree = n) (hq : q.natDegree = n) :
    boxplus n (p.comp (X + C c)) (q.comp (X + C d)) = (boxplus n p q).comp (X + C (c + d)) := by
      -- By definition of boxplus, we can rewrite the left-hand side.
      have h_lhs : boxplus n (p.comp (X + C c)) (q.comp (X + C d)) = (boxplus n (p.comp (X + C c)) q).comp (X + C d) := by
        rw [ boxplus_comm ];
        rw [ boxplus_comp_add_C_left ];
        · rw [ boxplus_comm ];
        · exact hq;
        · rw [ Polynomial.natDegree_comp, Polynomial.natDegree_X_add_C, hp, mul_one ];
      rw [ h_lhs ];
      rw [ boxplus_comp_add_C_left ];
      · norm_num [ Polynomial.comp_assoc ];
        ring;
      · exact hp;
      · exact hq

/-
Add n3_inequality and Phi_deg3_reduced_eq.
-/
lemma n3_inequality (b1 b2 u1 u2 : ℝ) (hu1 : u1 > 0) (hu2 : u2 > 0) :
  (b1 + b2)^2 / (u1 + u2)^2 ≤ b1^2 / u1^2 + b2^2 / u2^2 := by
  rw [ div_add_div, div_le_div_iff₀ ] <;> try positivity;
  have h_am_gm : (b1 * u2)^2 + (b2 * u1)^2 ≥ 2 * b1 * b2 * u1 * u2 := by
    linarith [ sq_nonneg ( b1 * u2 - b2 * u1 ) ];
  nlinarith [ sq_nonneg ( u1 - u2 ), mul_pos hu1 hu2, mul_le_mul_of_nonneg_left h_am_gm ( sq_nonneg u1 ), mul_le_mul_of_nonneg_left h_am_gm ( sq_nonneg u2 ) ]

lemma Phi_deg3_reduced_eq (a b : ℝ)
  (h_real : (X^3 + C a * X + C b).Splits (RingHom.id ℝ))
  (h_nodup : (X^3 + C a * X + C b).roots.Nodup) :
  Phi (X^3 + C a * X + C b) = 18 * a^2 / (-4 * a^3 - 27 * b^2) := by
    -- Let $r_1, r_2, r_3$ be the roots of $p(x) = x^3 + ax + b$.
    obtain ⟨r1, r2, r3, hr⟩ : ∃ r1 r2 r3 : ℝ, r1 + r2 + r3 = 0 ∧ r1 * r2 + r2 * r3 + r3 * r1 = a ∧ r1 * r2 * r3 = -b := by
      -- By Vieta's formulas, the roots of the polynomial $X^3 + aX + b$ satisfy $r_1 + r_2 + r_3 = 0$, $r_1r_2 + r_2r_3 + r_3r_1 = a$, and $r_1r_2r_3 = -b$.
      obtain ⟨r1, r2, r3, hr⟩ : ∃ r1 r2 r3 : ℝ, Polynomial.X^3 + Polynomial.C a * Polynomial.X + Polynomial.C b = Polynomial.C 1 * (Polynomial.X - Polynomial.C r1) * (Polynomial.X - Polynomial.C r2) * (Polynomial.X - Polynomial.C r3) := by
        rw [ Polynomial.splits_iff_card_roots ] at h_real;
        rw [ ← Polynomial.prod_multiset_X_sub_C_of_monic_of_roots_card_eq ( show Polynomial.Monic ( Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b ) from ?_ ) ];
        · -- Since the polynomial is cubic and has real roots, its roots form a multiset of cardinality 3.
          have h_card : Multiset.card (Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b)) = 3 := by
            rw [ h_real, Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases ha : a = 0 <;> simp +decide [ ha ];
          rw [ Multiset.card_eq_three ] at h_card; obtain ⟨ r1, r2, r3, hr ⟩ := h_card; use r1, r2, r3; simp +decide [ hr, mul_assoc ] ;
        · exact h_real;
        · rw [ Polynomial.Monic, Polynomial.leadingCoeff, Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases ha : a = 0 <;> simp +decide [ ha ];
      have h₁ := congr_arg ( Polynomial.eval 0 ) hr; have h₂ := congr_arg ( Polynomial.eval 1 ) hr; have h₃ := congr_arg ( Polynomial.eval ( -1 ) ) hr; norm_num at h₁ h₂ h₃; exact ⟨ r1, r2, r3, by linarith, by linarith, by linarith ⟩ ;
    have h_roots : Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b) = {r1, r2, r3} := by
      rw [ show ( Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C r1 ) * ( Polynomial.X - Polynomial.C r2 ) * ( Polynomial.X - Polynomial.C r3 ) by exact Polynomial.funext fun x => by norm_num; linear_combination hr.1 * x^2 - hr.2.1 * x + hr.2.2 ];
      rw [ Polynomial.roots_mul ( by exact mul_ne_zero ( mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ) ( Polynomial.X_sub_C_ne_zero _ ) ), Polynomial.roots_mul ( by exact mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ), Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] ; tauto;
    unfold Phi;
    by_cases h : r1 = r2 <;> by_cases h' : r1 = r3 <;> by_cases h'' : r2 = r3 <;> simp_all +decide [ Finset.sum ];
    rw [ inv_add_inv, inv_add_inv, inv_add_inv ] <;> try cases lt_or_gt_of_ne h <;> cases lt_or_gt_of_ne h' <;> cases lt_or_gt_of_ne h'' <;> nlinarith;
    rw [ show a = r1 * r2 + r2 * r3 + r3 * r1 by linarith, show b = -r1 * r2 * r3 by linarith ] ; ring;
    rw [ show r3 = -r1 - r2 by linarith ] ; ring;
    field_simp;
    rw [ div_add_div, div_add_div ];
    · rw [ mul_div, div_add_div, div_add_div ];
      · rw [ div_eq_div_iff ];
        · grind;
        · grind;
        · grind;
      · grind;
      · exact pow_ne_zero 2 ( by cases lt_or_gt_of_ne h <;> cases lt_or_gt_of_ne h' <;> cases lt_or_gt_of_ne h'' <;> nlinarith );
      · grind;
      · exact pow_ne_zero 2 ( by cases lt_or_gt_of_ne h <;> cases lt_or_gt_of_ne h' <;> cases lt_or_gt_of_ne h'' <;> nlinarith );
    · simp_all +decide [ sub_eq_iff_eq_add ];
      constructor <;> cases lt_or_gt_of_ne h <;> cases lt_or_gt_of_ne h' <;> cases lt_or_gt_of_ne h'' <;> nlinarith;
    · exact pow_ne_zero 2 ( by cases lt_or_gt_of_ne h <;> cases lt_or_gt_of_ne h' <;> cases lt_or_gt_of_ne h'' <;> nlinarith );
    · exact pow_ne_zero 2 ( by cases lt_or_gt_of_ne h <;> cases lt_or_gt_of_ne h' <;> cases lt_or_gt_of_ne h'' <;> nlinarith );
    · exact pow_ne_zero 2 ( by cases lt_or_gt_of_ne h <;> cases lt_or_gt_of_ne h' <;> cases lt_or_gt_of_ne h'' <;> nlinarith )

/-
Define shift_to_center_amount and shifted_to_center.
-/
def shift_to_center_amount (n : ℕ) (p : ℝ[X]) : ℝ :=
  - p.coeff (n - 1) / n

def shifted_to_center (n : ℕ) (p : ℝ[X]) : ℝ[X] :=
  p.comp (X + C (shift_to_center_amount n p))

/-
shifted_to_center produces a centered polynomial.
-/
lemma shifted_to_center_is_centered (n : ℕ) (p : ℝ[X])
    (hn : n ≠ 0) (hp_monic : p.Monic) (hp_deg : p.natDegree = n) :
    is_centered n (shifted_to_center n p) := by
      refine' ⟨ _, _, _ ⟩ <;> simp_all +decide [ Polynomial.Monic.def, Polynomial.leadingCoeff_comp, Polynomial.natDegree_comp ];
      · erw [ Polynomial.leadingCoeff_comp, Polynomial.leadingCoeff_X_add_C ] <;> aesop;
      · erw [ Polynomial.natDegree_comp, Polynomial.natDegree_X_add_C ] ; aesop;
      · unfold shifted_to_center;
        rw [ Polynomial.comp, Polynomial.eval₂_eq_sum_range ];
        norm_num [ Polynomial.coeff_X_add_C_pow, Finset.sum_range_succ, hp_deg ];
        rw [ Finset.sum_eq_single ( n - 1 ) ] <;> norm_num;
        · rcases n with ( _ | _ | n ) <;> simp_all +decide [ Nat.succ_eq_add_one, Polynomial.leadingCoeff, Polynomial.natDegree_eq_of_degree_eq_some ];
          · unfold shift_to_center_amount; aesop;
          · unfold shift_to_center_amount; norm_num [ hp_monic ] ; ring;
            nlinarith [ inv_mul_cancel_left₀ ( by linarith : ( 2 : ℝ ) + n ≠ 0 ) ( p.coeff ( 1 + n ) ) ];
        · exact fun k hk₁ hk₂ => Or.inr <| Or.inr <| Nat.choose_eq_zero_of_lt <| lt_of_le_of_ne ( Nat.le_sub_one_of_lt hk₁ ) hk₂;
        · aesop

/-
Properties of shifted_to_center: preserves splits and nodup.
-/
lemma shifted_to_center_properties (n : ℕ) (p : ℝ[X])
    (hp_splits : p.Splits (RingHom.id ℝ)) (hp_nodup : p.roots.Nodup) :
    (shifted_to_center n p).Splits (RingHom.id ℝ) ∧ (shifted_to_center n p).roots.Nodup := by
      constructor;
      · unfold shifted_to_center;
        exact?;
      · -- The roots of the shifted polynomial are the roots of p shifted by -shift_to_center_amount n p.
        have h_roots_shifted : (p.comp (X + C (shift_to_center_amount n p))).roots = Multiset.map (fun r => r - shift_to_center_amount n p) p.roots := by
          ext r;
          rw [ Multiset.count_map, eq_comm ];
          rw [ show ( Multiset.filter ( fun a => r = a - shift_to_center_amount n p ) p.roots ) = Multiset.filter ( fun a => a = r + shift_to_center_amount n p ) p.roots by congr; ext; constructor <;> intro <;> linarith ] ;
          simp +decide [ Multiset.filter_eq', Polynomial.rootMultiplicity_eq_zero ];
          rw [ Polynomial.rootMultiplicity_eq_natTrailingDegree, Polynomial.rootMultiplicity_eq_natTrailingDegree ];
          norm_num [ Polynomial.comp_assoc ];
          rw [ add_assoc ];
        exact h_roots_shifted.symm ▸ Multiset.Nodup.map ( fun x => by aesop ) hp_nodup