/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 77c4d757-db33-4da8-9744-3f320343261b

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of boxplus convolution, Phi functional, and inverse Phi functional.
-/
open Polynomial BigOperators Finset Classical
open scoped BigOperators

def boxplus_coeff (n : ℕ) (p q : ℝ[X]) (k : ℕ) : ℝ :=
  ∑ i ∈ range (k + 1),
    let j := k - i
    (Nat.factorial (n - i) * Nat.factorial (n - j) : ℝ) / (Nat.factorial n * Nat.factorial (n - k) : ℝ) *
    (p.coeff (n - i)) * (q.coeff (n - j))

def boxplus (n : ℕ) (p q : ℝ[X]) : ℝ[X] :=
  Finset.sum (range (n + 1)) (fun k => C (boxplus_coeff n p q k) * X ^ (n - k))

def Phi (p : ℝ[X]) : ℝ :=
  let roots := p.roots.toFinset
  ∑ r_i ∈ roots, (∑ r_j ∈ roots.erase r_i, 1 / (r_i - r_j))^2

def invPhi (p : ℝ[X]) : ℝ :=
  if p.roots.Nodup ∧ p.roots.card > 1 then
    1 / Phi p
  else 0

/-
The w-th derivative of the boxplus convolution at 0 is related to the derivatives of the input polynomials at 0 by a convolution-like formula involving factorials.
-/
open Polynomial BigOperators Finset Classical
open scoped BigOperators

lemma boxplus_deriv_at_zero (n : ℕ) (p q : ℝ[X]) (w : ℕ)
  (hp_deg : p.natDegree ≤ n) (hq_deg : q.natDegree ≤ n) :
  (Polynomial.derivative^[w] (boxplus n p q)).eval 0 =
  (1 / Nat.factorial n) * ∑ u ∈ range (n + w + 1),
    let v := n + w - u
    (Polynomial.derivative^[u] p).eval 0 * (Polynomial.derivative^[v] q).eval 0 := by
      by_cases hw : n < w;
      · rw [ Polynomial.iterate_derivative_eq_zero ];
        · rw [ Finset.sum_eq_zero ] ; aesop;
          intro x hx; by_cases hx' : x ≤ n <;> simp_all +decide [ Polynomial.iterate_derivative_eq_zero ] ;
          · exact Or.inr ( by rw [ Polynomial.iterate_derivative_eq_zero ( by omega ) ] ; norm_num );
          · exact Or.inl ( by rw [ Polynomial.iterate_derivative_eq_zero ( by linarith ) ] ; norm_num );
        · refine' lt_of_le_of_lt ( Polynomial.natDegree_sum_le _ _ ) _;
          refine' lt_of_le_of_lt ( Finset.sup_le _ ) _;
          exacts [ n, fun k hk => le_trans ( Polynomial.natDegree_C_mul_X_pow_le _ _ ) ( Nat.sub_le _ _ ), by linarith ];
      · -- By definition of boxplus, we can write its w-th derivative at 0.
        have h_deriv : (Polynomial.derivative^[w] (boxplus n p q)).eval 0 =
          (Nat.factorial w) * (boxplus_coeff n p q (n - w)) := by
            -- By definition of $boxplus$, we know that its $w$-th derivative at $0$ is given by the sum of the $w$-th derivatives of its terms.
            have h_deriv_term : ∀ k ∈ Finset.range (n + 1), Polynomial.eval 0 ((Polynomial.derivative^[w] (Polynomial.C (boxplus_coeff n p q k) * Polynomial.X ^ (n - k)))) = if k = n - w then (Nat.factorial w) * (boxplus_coeff n p q (n - w)) else 0 := by
              intro k hk; split_ifs <;> simp_all +decide [ Polynomial.coeff_iterate_derivative ] ;
              · rw [ Nat.sub_sub_self hw ] ; norm_num [ Polynomial.eval, Polynomial.coeff_iterate_derivative ] ; ring;
                rw [ Nat.descFactorial_self ];
              · by_cases h : n - k < w <;> simp_all +decide [ Polynomial.eval, Polynomial.coeff_iterate_derivative ];
                · exact Or.inr ( ne_of_gt h );
                · omega;
            rw [ show boxplus n p q = ∑ k ∈ Finset.range ( n + 1 ), Polynomial.C ( boxplus_coeff n p q k ) * Polynomial.X ^ ( n - k ) from ?_ ];
            · convert Finset.sum_congr rfl h_deriv_term using 1;
              · induction' ( Finset.range ( n + 1 ) ) using Finset.induction <;> aesop;
              · simp +zetaDelta at *;
                exact fun h => absurd h ( by omega );
            · exact?;
        -- By definition of $boxplus_coeff$, we can rewrite the sum.
        have h_sum : ∑ u ∈ Finset.range (n + w + 1), (Polynomial.eval 0 ((Polynomial.derivative^[u] p))) * (Polynomial.eval 0 ((Polynomial.derivative^[n + w - u] q))) =
          ∑ i ∈ Finset.range (n - w + 1), (Nat.factorial (n - i) * Nat.factorial (w + i) : ℝ) *
            (p.coeff (n - i)) * (q.coeff (w + i)) := by
              have h_sum : ∑ u ∈ Finset.range (n + w + 1), (Polynomial.eval 0 ((Polynomial.derivative^[u] p))) * (Polynomial.eval 0 ((Polynomial.derivative^[n + w - u] q))) =
                ∑ u ∈ Finset.range (n + 1), (Nat.factorial u * Nat.factorial (n + w - u) : ℝ) * (p.coeff u) * (q.coeff (n + w - u)) := by
                  have h_sum : ∀ u ∈ Finset.range (n + w + 1), (Polynomial.eval 0 ((Polynomial.derivative^[u] p))) * (Polynomial.eval 0 ((Polynomial.derivative^[n + w - u] q))) =
                    (if u ≤ n then (Nat.factorial u * Nat.factorial (n + w - u) : ℝ) * (p.coeff u) * (q.coeff (n + w - u)) else 0) := by
                      intro u hu; split_ifs <;> simp_all +decide [ Polynomial.eval, Polynomial.coeff_iterate_derivative ] ;
                      · simp +decide [ Nat.descFactorial_self, mul_assoc, mul_comm, mul_left_comm ];
                      · exact Or.inl <| Polynomial.coeff_eq_zero_of_natDegree_lt <| by linarith;
                  rw [ Finset.sum_congr rfl h_sum, Finset.sum_ite ];
                  norm_num [ Finset.sum_filter ];
                  rw [ ← Finset.sum_range_add_sum_Ico _ ( by linarith : n + 1 ≤ n + w + 1 ) ];
                  rw [ Finset.sum_congr rfl fun x hx => if_pos <| by linarith [ Finset.mem_range.mp hx ], Finset.sum_congr rfl fun x hx => if_neg <| by linarith [ Finset.mem_Ico.mp hx ] ] ; norm_num;
              rw [ h_sum, ← Finset.sum_flip ];
              rw [ ← Finset.sum_subset ( Finset.range_mono ( Nat.succ_le_succ ( Nat.sub_le n w ) ) ) ];
              · refine' Finset.sum_congr rfl fun x hx => _;
                rw [ show n + w - ( n - x ) = w + x by rw [ tsub_eq_of_eq_add ] ; linarith [ Nat.sub_add_cancel ( show x ≤ n from by linarith [ Finset.mem_range.mp hx, Nat.sub_le n w ] ) ] ];
              · norm_num +zetaDelta at *;
                exact fun x hx₁ hx₂ => Or.inr <| Polynomial.coeff_eq_zero_of_natDegree_lt <| by omega;
        simp_all +decide [ boxplus_coeff ];
        rw [ Finset.mul_sum _ _ _ ] ; rw [ Finset.mul_sum _ _ _ ] ; refine' Finset.sum_congr rfl fun i hi => _ ; rw [ Nat.sub_sub_self ( by linarith [ Finset.mem_range.mp hi, Nat.sub_add_cancel hw ] ) ] ; ring;
        rw [ show n - ( n - w - i ) = w + i by exact Nat.sub_eq_of_eq_add <| by linarith [ Nat.sub_add_cancel <| show w ≤ n from hw, Nat.sub_add_cancel <| show i ≤ n - w from Finset.mem_range_succ_iff.mp hi ] ] ; norm_num [ Nat.factorial_ne_zero, mul_assoc, mul_comm, mul_left_comm ]

/-
The boxplus convolution of two monomials X^u and X^v is a monomial X^(u+v-n) scaled by a factor involving factorials, provided u+v >= n. Otherwise it is zero.
-/
open Polynomial BigOperators Finset Classical
open scoped BigOperators

lemma boxplus_monomials (n u v : ℕ) (hu : u ≤ n) (hv : v ≤ n) :
  boxplus n (X^u) (X^v) =
  if u + v < n then 0
  else C ((Nat.factorial u * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial (u + v - n))) * X^(u + v - n) := by
    -- Assume $n+1 \leq u+v$. In this case $n-k \leq k \implies k \geq \frac{n-1}{2}$.
    by_cases huv : u + v < n
    -- Case 1
    -- If $u+v < n$, then for any $k$, either $u > n-i$ or $v > n-j$, making the term zero.
    have h_zero : ∀ k ∈ Finset.range (n + 1), boxplus_coeff n (.X ^ u) (.X ^ v) k = 0 := by
      intro k hk
      simp [boxplus_coeff, huv];
      simp_all +decide [ Finset.sum_ite ];
      exact Or.inl fun x hx₁ hx₂ hx₃ => by omega;
    exact if_pos huv ▸ Finset.sum_eq_zero fun k hk => by aesop;
    -- Case 2
    -- In this case, the boxplus convolution of $X^u$ and $X^v$ is a monomial $X^{u+v-n}$ scaled by a factor involving factorials.
    have h_monomial : ∀ k, k ∈ Finset.range (n + 1) → (boxplus_coeff n (Polynomial.X ^ u) (Polynomial.X ^ v) k) = if k = 2 * n - u - v then (u.factorial * v.factorial : ℝ) / (n.factorial * (u + v - n).factorial) else 0 := by
      intro k hk
      simp [boxplus_coeff];
      split_ifs <;> simp_all +decide [ Finset.sum_ite ];
      · rw [ show n - ( 2 * n - u - v ) = u + v - n by omega ];
        rw [ Finset.card_eq_one.mpr ] ; aesop;
        use n - u;
        grind;
      · contrapose! huv; omega;
    simp_all +decide [ boxplus ];
    rw [ Finset.sum_eq_single ( 2 * n - u - v ) ];
    · rw [ h_monomial ];
      · rw [ show n - ( 2 * n - u - v ) = u + v - n by omega ] ; aesop;
      · omega;
    · aesop;
    · exact fun h => False.elim <| h <| Finset.mem_range.mpr <| by omega;

/-
Translation covariance holds for monomials: boxplus of (X+c)^u and X^v is the shifted boxplus of X^u and X^v.
-/
open Polynomial BigOperators Finset Classical
open scoped BigOperators

lemma boxplus_comp_add_C_left_monomials (n u v : ℕ) (c : ℝ)
  (hu : u ≤ n) (hv : v ≤ n) :
  boxplus n ((X + C c)^u) (X^v) = (boxplus n (X^u) (X^v)).comp (X + C c) := by
    -- By linearity of boxplus, we can expand both sides.
    have h_expand : boxplus n ((Polynomial.X + (Polynomial.C c)) ^ u) (Polynomial.X ^ v) = Finset.sum (Finset.range (u + 1)) (fun k => Polynomial.C ((Nat.choose u k : ℝ) * c ^ (u - k)) * boxplus n (Polynomial.X ^ k) (Polynomial.X ^ v)) := by
      -- Apply the linearity of boxplus to split the polynomial into a sum of monomials.
      have h_linear : ∀ p q : Polynomial ℝ, boxplus n (p + q) (Polynomial.X ^ v) = boxplus n p (Polynomial.X ^ v) + boxplus n q (Polynomial.X ^ v) := by
        unfold boxplus;
        unfold boxplus_coeff; norm_num [ Finset.sum_add_distrib ] ;
        intro p q; rw [ ← Finset.sum_add_distrib ] ; congr; ext; simp +decide [ Finset.sum_add_distrib, mul_add ] ;
        simp +decide [ Finset.sum_ite, Finset.filter_congr, Finset.filter_eq', Finset.filter_ne', Polynomial.coeff_mul ];
        rw [ ← Finset.sum_add_distrib ] ; congr ; ext ; rw [ ← Finset.sum_add_distrib ] ; congr ; ext ; aesop;
      have h_expand : ∀ (p : Polynomial ℝ), boxplus n p (Polynomial.X ^ v) = ∑ k ∈ Finset.range (p.natDegree + 1), Polynomial.C (p.coeff k) * boxplus n (Polynomial.X ^ k) (Polynomial.X ^ v) := by
        intro p
        have h_sum : boxplus n p (Polynomial.X ^ v) = ∑ k ∈ Finset.range (p.natDegree + 1), boxplus n (Polynomial.C (p.coeff k) * Polynomial.X ^ k) (Polynomial.X ^ v) := by
          -- By definition of polynomial multiplication and the linearity of boxplus, we can expand both sides.
          have h_expand : p = ∑ k ∈ Finset.range (p.natDegree + 1), Polynomial.C (p.coeff k) * Polynomial.X ^ k := by
            conv_lhs => rw [ p.as_sum_range_C_mul_X_pow ] ;
          conv_lhs => rw [ h_expand ];
          induction' ( Finset.range ( p.natDegree + 1 ) ) using Finset.induction <;> norm_num at *;
          · specialize h_linear 0 ( Polynomial.X ^ v ) ; norm_num at h_linear ; linear_combination' h_linear;
          · grind;
        -- By definition of boxplus, we can factor out the constant coefficient.
        have h_factor : ∀ k : ℕ, boxplus n (Polynomial.C (p.coeff k) * Polynomial.X ^ k) (Polynomial.X ^ v) = Polynomial.C (p.coeff k) * boxplus n (Polynomial.X ^ k) (Polynomial.X ^ v) := by
          intro k
          simp [boxplus];
          simp +decide [ boxplus_coeff, Finset.mul_sum _ _ _ ];
          simp +decide [ Finset.mul_sum _ _ _, mul_assoc, mul_left_comm, Finset.sum_mul ];
          exact Finset.sum_congr rfl fun _ _ => Finset.sum_congr rfl fun _ _ => by split_ifs <;> simp +decide [ *, mul_assoc, mul_left_comm ] ;
        aesop;
      rw [ h_expand ];
      norm_num [ Polynomial.natDegree_add_eq_left_of_natDegree_lt, Polynomial.coeff_X_add_C_pow ];
      ac_rfl;
    -- By definition of boxplus, we know that boxplus n (Polynomial.X ^ k) (Polynomial.X ^ v) is zero unless k + v ≥ n.
    have h_boxplus_nonzero : ∀ k ∈ Finset.range (u + 1), boxplus n (Polynomial.X ^ k) (Polynomial.X ^ v) = if k + v < n then 0 else Polynomial.C ((Nat.factorial k * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial (k + v - n))) * Polynomial.X ^ (k + v - n) := by
      exact fun k hk => boxplus_monomials n k v ( by linarith [ Finset.mem_range.mp hk ] ) ( by linarith [ Finset.mem_range.mp hk ] );
    by_cases h : u + v < n <;> simp_all +decide [ Polynomial.eval_finset_sum ];
    · exact Finset.sum_eq_zero fun x hx => if_pos <| by linarith [ Finset.mem_range.mp hx ] ;
    · -- By simplifying, we can see that both sides are equal.
      have h_simp : ∀ j ∈ Finset.range (u + v - n + 1), ∑ k ∈ Finset.Icc (n - v) u, (Nat.choose u k : ℝ) * c ^ (u - k) * (Nat.factorial k * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial (k + v - n)) * (if k + v - n = j then 1 else 0) = (Nat.factorial u * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial (u + v - n)) * (Nat.choose (u + v - n) j : ℝ) * c ^ (u + v - n - j) := by
        intro j hj
        have h_simp : ∑ k ∈ Finset.Icc (n - v) u, (Nat.choose u k : ℝ) * c ^ (u - k) * (Nat.factorial k * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial (k + v - n)) * (if k + v - n = j then 1 else 0) = (Nat.choose u (n - v + j) : ℝ) * c ^ (u - (n - v + j)) * (Nat.factorial (n - v + j) * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial j) := by
          rw [ Finset.sum_eq_single ( n - v + j ) ] <;> norm_num;
          · grind;
          · intros; omega;
          · exact fun h₁ h₂ => Or.inl <| Or.inl <| Or.inl <| Nat.choose_eq_zero_of_lt h₁;
        rw [ h_simp, Nat.cast_choose, Nat.cast_choose ];
        · field_simp;
          rw [ show u + v - n - j = u - ( n - v + j ) by omega ] ; ring;
        · linarith [ Finset.mem_range.mp hj ];
        · linarith [ Finset.mem_range.mp hj, Nat.sub_add_cancel hv, Nat.sub_add_cancel h ];
      refine' Polynomial.funext fun x => _;
      simp_all +decide [ Polynomial.eval_finset_sum ];
      convert Finset.sum_congr rfl fun j hj => congr_arg ( fun y => y * x ^ j ) ( h_simp j <| Finset.mem_range.mp hj ) using 1;
      · simp +decide [ Finset.sum_ite, Finset.sum_mul _ _ _ ];
        rw [ ← Finset.sum_subset ( show Finset.Icc ( n - v ) u ⊆ Finset.range ( u + 1 ) from fun x hx => Finset.mem_range.mpr ( by linarith [ Finset.mem_Icc.mp hx ] ) ) ];
        · rw [ Finset.sum_sigma' ];
          refine' Finset.sum_bij ( fun x hx => ⟨ x + v - n, x ⟩ ) _ _ _ _ <;> simp +decide;
          · exact fun a ha₁ ha₂ => ⟨ by omega, ha₁, ha₂ ⟩;
          · exact fun b hb₁ hb₂ hb₃ hb₄ => ⟨ b.snd, ⟨ hb₂, hb₃ ⟩, by aesop ⟩;
          · intro a ha₁ ha₂; rw [ if_neg ( by linarith ) ] ; norm_num ; ring;
        · intro k hk₁ hk₂; split_ifs <;> simp_all +decide [ Nat.choose_eq_zero_of_lt ] ;
      · rw [ if_neg ( by linarith ) ] ; simp +decide [ Polynomial.eval_finset_sum ] ; ring;
        rw [ add_comm, add_pow ] ; ring;
        simp +decide only [mul_assoc, Finset.mul_sum _ _ _]

/-
The boxplus convolution commutes with translation of the first argument for any polynomials of degree at most n.
-/
open Polynomial BigOperators Finset Classical
open scoped BigOperators

lemma boxplus_comp_add_C_left (n : ℕ) (p q : ℝ[X]) (c : ℝ)
  (hp : p.natDegree ≤ n) (hq : q.natDegree ≤ n) :
  boxplus n (p.comp (X + C c)) q = (boxplus n p q).comp (X + C c) := by
    -- By linearity of `boxplus`, we can expand both sides as sums of `boxplus` operations on monomials.
    have h_expand : ∀ (p q : ℝ[X]) (c : ℝ), p.natDegree ≤ n → q.natDegree ≤ n → (boxplus n (p.comp (Polynomial.X + Polynomial.C c)) q) = ∑ u ∈ Finset.range (n + 1), (p.coeff u) • ∑ v ∈ Finset.range (n + 1), (q.coeff v) • (boxplus n ((Polynomial.X + Polynomial.C c)^u) (Polynomial.X^v)) := by
      intros p q c hp hq
      have h_expand : boxplus n (p.comp (Polynomial.X + Polynomial.C c)) q = ∑ u ∈ Finset.range (n + 1), (p.coeff u) • boxplus n ((Polynomial.X + Polynomial.C c)^u) q := by
        rw [ show p.comp ( Polynomial.X + Polynomial.C c ) = ∑ u ∈ Finset.range ( n + 1 ), p.coeff u • ( Polynomial.X + Polynomial.C c ) ^ u from ?_ ];
        · unfold boxplus;
          simp +decide [ boxplus_coeff, Finset.mul_sum _ _ _, Finset.sum_mul, mul_assoc, mul_left_comm, Finset.sum_add_distrib ];
          simp +decide [ Finset.smul_sum, mul_assoc, mul_left_comm, Finset.mul_sum _ _ _, Polynomial.smul_eq_C_mul ];
          rw [ Finset.sum_comm ];
          exact Finset.sum_congr rfl fun _ _ => Finset.sum_comm;
        · rw [ Polynomial.comp, Polynomial.eval₂_eq_sum_range' ];
          exacts [ Finset.sum_congr rfl fun _ _ => by rw [ Polynomial.smul_eq_C_mul ], Nat.lt_succ_of_le hp ];
      have h_expand_q : ∀ (p q : ℝ[X]) (c : ℝ), p.natDegree ≤ n → q.natDegree ≤ n → boxplus n p q = ∑ v ∈ Finset.range (n + 1), (q.coeff v) • boxplus n p (Polynomial.X^v) := by
        intros p q c hp hq
        have h_expand_q : q = ∑ v ∈ Finset.range (n + 1), (q.coeff v) • Polynomial.X^v := by
          conv_lhs => rw [ Polynomial.as_sum_range' q ( n + 1 ) ( by linarith ) ];
          norm_num [ Polynomial.smul_eq_C_mul, ← Polynomial.C_mul_X_pow_eq_monomial ];
        conv_lhs => rw [ h_expand_q ];
        unfold boxplus;
        simp +decide [ boxplus_coeff, Finset.mul_sum _ _ _, Finset.sum_mul ];
        simp +decide [ Finset.smul_sum, Finset.sum_smul, Polynomial.smul_eq_C_mul ];
        rw [ Finset.sum_comm ];
        refine' Finset.sum_congr rfl fun x hx => _;
        rw [ Finset.sum_comm, Finset.sum_congr rfl ] ; simp +contextual [ Finset.sum_ite ];
        intro y hy; rw [ Finset.sum_eq_single ( n - ( x - y ) ) ] <;> simp +contextual [ Nat.sub_sub_self ( show x - y ≤ n from Nat.sub_le_of_le_add <| by linarith [ Finset.mem_range.mp hx ] ) ] ;
        · rw [ if_pos ( Nat.lt_succ_of_le ( Nat.sub_le _ _ ) ) ] ; norm_num ; ring;
        · exact fun b hb hb' => Or.inr fun h => False.elim <| hb' <| h.symm ▸ rfl;
        · exact fun h => absurd h ( by omega );
      convert h_expand using 2;
      rw [ h_expand_q _ _ c ( by exact le_trans ( Polynomial.natDegree_pow_le ) ( by simpa using by linarith [ Finset.mem_range.mp ‹_› ] ) ) hq ];
    have h_expand_rhs : ∀ (p q : ℝ[X]) (c : ℝ), p.natDegree ≤ n → q.natDegree ≤ n → (boxplus n p q).comp (Polynomial.X + Polynomial.C c) = ∑ u ∈ Finset.range (n + 1), (p.coeff u) • ∑ v ∈ Finset.range (n + 1), (q.coeff v) • (boxplus n (Polynomial.X^u) (Polynomial.X^v)).comp (Polynomial.X + Polynomial.C c) := by
      intros p q c hp hq
      have h_expand_rhs : (boxplus n p q) = ∑ u ∈ Finset.range (n + 1), (p.coeff u) • ∑ v ∈ Finset.range (n + 1), (q.coeff v) • (boxplus n (Polynomial.X^u) (Polynomial.X^v)) := by
        convert h_expand p q 0 hp hq using 1 ; norm_num [ Polynomial.smul_eq_C_mul ];
        norm_num [ Polynomial.smul_eq_C_mul ];
      simp +decide [ h_expand_rhs, Polynomial.smul_eq_C_mul ];
    rw [ h_expand p q c hp hq, h_expand_rhs p q c hp hq ];
    refine' Finset.sum_congr rfl fun u hu => congr_arg _ ( Finset.sum_congr rfl fun v hv => congr_arg _ <| _ );
    convert boxplus_comp_add_C_left_monomials n u v c ( Finset.mem_range_succ_iff.mp hu ) ( Finset.mem_range_succ_iff.mp hv ) using 1

/-
The boxplus convolution is commutative: boxplus n p q = boxplus n q p.
-/
open Polynomial BigOperators Finset Classical
open scoped BigOperators

lemma boxplus_comm (n : ℕ) (p q : ℝ[X]) :
  boxplus n p q = boxplus n q p := by
    ext k
    simp [boxplus];
    -- By definition of boxplus_coeff, we have:
    simp [boxplus_coeff];
    refine' Finset.sum_congr rfl fun x hx => _;
    rw [ ← Finset.sum_flip ];
    exact if_congr Iff.rfl ( Finset.sum_congr rfl fun i hi => by rw [ tsub_tsub_cancel_of_le ( Finset.mem_range_succ_iff.mp hi ) ] ; ring ) rfl

/-
The boxplus convolution is fully translation covariant.
-/
open Polynomial BigOperators Finset Classical
open scoped BigOperators

lemma boxplus_comp_add_C (n : ℕ) (p q : ℝ[X]) (c d : ℝ)
  (hp : p.natDegree ≤ n) (hq : q.natDegree ≤ n) :
  boxplus n (p.comp (X + C c)) (q.comp (X + C d)) = (boxplus n p q).comp (X + C (c + d)) := by
    -- By commutativity and left-translation covariance, we can rewrite the left-hand side.
    have h_lhs : (boxplus n (p.comp (.X + (.C c))) (q.comp (.X + (.C d)))) = (boxplus n (q.comp (.X + (.C d))) (p.comp (.X + (.C c)))) := by
      apply boxplus_comm;
    -- By left-translation covariance, we can rewrite the right-hand side.
    have h_rhs : (boxplus n (q.comp (.X + (.C d))) (p.comp (.X + (.C c)))) = ((boxplus n q (p.comp (.X + (.C c)))).comp (.X + (.C d))) := by
      apply_rules [ boxplus_comp_add_C_left ];
      rw [ Polynomial.natDegree_comp, Polynomial.natDegree_X_add_C ] ; linarith;
    -- By left-translation covariance, we can rewrite the right-hand side further.
    have h_rhs'' : (boxplus n (p.comp (.X + (.C c)))) q = ((boxplus n p q).comp (.X + (.C c))) := by
      exact?;
    rw [ h_lhs, h_rhs, ← boxplus_comm ];
    rw [ h_rhs'', Polynomial.comp_assoc ];
    norm_num [ Polynomial.comp_assoc ];
    exact congr_arg _ ( by ring )

/-
The Finite Free Stam Inequality holds with equality for n=2.
-/
open Polynomial BigOperators Finset Classical
open scoped BigOperators

lemma finite_free_stam_inequality_n2 (p q : ℝ[X])
    (hp : p.Splits (RingHom.id ℝ)) (hp_nodup : p.roots.Nodup)
    (hp_monic : p.Monic) (hp_deg : p.natDegree = 2)
    (hq : q.Splits (RingHom.id ℝ)) (hq_nodup : q.roots.Nodup)
    (hq_monic : q.Monic) (hq_deg : q.natDegree = 2)
    (hpq : (boxplus 2 p q).Splits (RingHom.id ℝ))
    (hpq_nodup : (boxplus 2 p q).roots.Nodup) :
    invPhi (boxplus 2 p q) ≥ invPhi p + invPhi q := by
      -- By definition of $p$ and $q$, we know that their roots are distinct and real.
      obtain ⟨r1, r2, hr⟩ : ∃ r1 r2 : ℝ, r1 ≠ r2 ∧ p.roots = {r1, r2} := by
        simp_all +decide [ Polynomial.splits_iff_card_roots ];
        rw [ Multiset.card_eq_two ] at hp ; aesop
      obtain ⟨s1, s2, hs⟩ : ∃ s1 s2 : ℝ, s1 ≠ s2 ∧ q.roots = {s1, s2} := by
        -- Since $q$ is a monic polynomial of degree 2 with distinct real roots, its roots must be exactly two distinct real numbers.
        have hq_roots : q.roots.card = 2 := by
          rw [ Polynomial.splits_iff_card_roots ] at hq ; aesop;
        rw [ Multiset.card_eq_two ] at hq_roots; aesop;
      obtain ⟨t1, t2, ht⟩ : ∃ t1 t2 : ℝ, t1 ≠ t2 ∧ (boxplus 2 p q).roots = {t1, t2} := by
        have h_deg : (boxplus 2 p q).natDegree = 2 := by
          refine' Polynomial.natDegree_eq_of_degree_eq_some _;
          refine' Polynomial.degree_eq_of_le_of_coeff_ne_zero _ _ <;> norm_num [ boxplus ];
          · exact le_trans ( Polynomial.degree_sum_le _ _ ) ( Finset.sup_le fun i hi => Polynomial.degree_C_mul_X_pow_le _ _ |> le_trans <| WithBot.coe_le_coe.mpr <| Nat.sub_le _ _ );
          · norm_num [ Finset.sum_range_succ', boxplus_coeff ];
            exact ⟨ by rw [ ← hp_deg, Polynomial.coeff_natDegree ] ; aesop_cat, by rw [ ← hq_deg, Polynomial.coeff_natDegree ] ; aesop_cat ⟩;
        have h_card : Multiset.card (boxplus 2 p q).roots = 2 := by
          rw [ Polynomial.splits_iff_card_roots ] at hpq ; aesop;
        rw [ Multiset.card_eq_two ] at h_card; aesop;
      -- By definition of $p$ and $q$, we know that their roots are distinct and real, so we can write them as $p(x) = (x - r1)(x - r2)$ and $q(x) = (x - s1)(x - s2)$.
      have hp_eq : p = (Polynomial.X - Polynomial.C r1) * (Polynomial.X - Polynomial.C r2) := by
        rw [ ← Polynomial.prod_multiset_X_sub_C_of_monic_of_roots_card_eq hp_monic ] <;> aesop
      have hq_eq : q = (Polynomial.X - Polynomial.C s1) * (Polynomial.X - Polynomial.C s2) := by
        rw [ ← Polynomial.prod_multiset_X_sub_C_of_monic_of_roots_card_eq hq_monic ] <;> aesop
      have hbox_eq : boxplus 2 p q = (Polynomial.X - Polynomial.C t1) * (Polynomial.X - Polynomial.C t2) := by
        convert Polynomial.eq_prod_roots_of_monic_of_splits_id _ _ using 1;
        · norm_num [ ht ];
        · unfold boxplus;
          unfold boxplus_coeff; norm_num [ Finset.sum_range_succ', hp_deg, hq_deg ] ;
          rw [ Polynomial.Monic, Polynomial.leadingCoeff_add_of_degree_lt ] <;> norm_num [ hp_deg, hq_deg, hp_eq, hq_eq ];
          · norm_num [ mul_sub, Polynomial.coeff_X, Polynomial.coeff_C ];
          · norm_num [ mul_sub, Polynomial.coeff_X, Polynomial.coeff_C ];
            erw [ Polynomial.degree_lt_iff_coeff_zero ] ; norm_num;
            rintro ( _ | _ | m ) <;> simp +decide [ Polynomial.coeff_eq_zero_of_natDegree_lt ];
        · assumption;
      -- By definition of $Phi$, we know that $invPhi(p) = \frac{(r1 - r2)^2}{2}$ and $invPhi(q) = \frac{(s1 - s2)^2}{2}$.
      have h_invPhi_p : invPhi p = (r1 - r2)^2 / 2 := by
        unfold invPhi;
        unfold Phi; norm_num [ hr, hs, hp_deg, hq_deg ] ; ring;
        rw [ inv_inv ] ; ring
      have h_invPhi_q : invPhi q = (s1 - s2)^2 / 2 := by
        unfold invPhi;
        unfold Phi; norm_num [ hs, hq_eq ] ; ring;
        rw [ show ( - ( Polynomial.X * Polynomial.C s1 ) - Polynomial.X * Polynomial.C s2 + Polynomial.X ^ 2 + Polynomial.C s1 * Polynomial.C s2 : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C s1 ) * ( Polynomial.X - Polynomial.C s2 ) by ring, Polynomial.roots_mul ] <;> norm_num [ hs ];
        · grind;
        · exact ⟨ Polynomial.X_sub_C_ne_zero _, Polynomial.X_sub_C_ne_zero _ ⟩
      have h_invPhi_box : invPhi (boxplus 2 p q) = (t1 - t2)^2 / 2 := by
        unfold invPhi;
        unfold Phi; norm_num [ ht ] ; ring;
        rw [ inv_inv ] ; ring;
      -- By definition of $boxplus$, we know that $t1 + t2 = r1 + r2 + s1 + s2$ and $t1 * t2 = r1 * r2 + s1 * s2 + (r1 + r2) * (s1 + s2) / 2$.
      have h_sum : t1 + t2 = r1 + r2 + s1 + s2 := by
        unfold boxplus at *; simp_all +decide [ Polynomial.coeff_X, Polynomial.coeff_C, mul_sub ] ;
        unfold boxplus_coeff at hbox_eq; norm_num [ Finset.sum_range_succ', Polynomial.coeff_X, Polynomial.coeff_C ] at hbox_eq; have := congr_arg ( Polynomial.eval 0 ) hbox_eq; norm_num at this; have := congr_arg ( Polynomial.eval 1 ) hbox_eq; norm_num at this; have := congr_arg ( Polynomial.eval ( -1 ) ) hbox_eq; norm_num at this; linarith;
      have h_prod : t1 * t2 = r1 * r2 + s1 * s2 + (r1 + r2) * (s1 + s2) / 2 := by
        unfold boxplus at hbox_eq; norm_num [ hp_eq, hq_eq ] at hbox_eq;
        norm_num [ Finset.sum_range_succ, boxplus_coeff ] at hbox_eq;
        norm_num [ mul_sub, Polynomial.coeff_X, Polynomial.coeff_C ] at hbox_eq; have := congr_arg ( Polynomial.eval 0 ) hbox_eq; norm_num at this; have := congr_arg ( Polynomial.eval 1 ) hbox_eq; norm_num at this; linarith;
      rw [ ← eq_sub_iff_add_eq' ] at h_sum ; subst_vars ; nlinarith [ sq_nonneg ( r1 - r2 - ( s1 - s2 ) ), sq_nonneg ( r1 - r2 + ( s1 - s2 ) ) ] ;

/-
The invPhi of the boxplus convolution is invariant under shifting the input polynomials.
-/
open Polynomial BigOperators Finset Classical
open scoped BigOperators

lemma invPhi_boxplus_shift_invariance (n : ℕ) (p q : ℝ[X]) (c d : ℝ)
  (hp : p.natDegree ≤ n) (hq : q.natDegree ≤ n) :
  invPhi (boxplus n p q) = invPhi (boxplus n (p.comp (X + C c)) (q.comp (X + C d))) := by
    rw [ boxplus_comp_add_C n p q c d hp hq ];
    -- By definition of invPhi, we have:
    unfold invPhi
    simp [Polynomial.comp_assoc];
    -- By definition of polynomial composition, the roots of $(boxplus n p q).comp (X + (C c + C d))$ are the roots of $boxplus n p q$ shifted by $-(c + d)$.
    have h_roots_comp : (boxplus n p q).comp (Polynomial.X + (Polynomial.C c + Polynomial.C d)) = Polynomial.comp (boxplus n p q) (Polynomial.X + Polynomial.C (c + d)) := by
      norm_num [ Polynomial.C_add ];
    rw [ h_roots_comp, show ( Polynomial.roots ( ( boxplus n p q |> Polynomial.comp ) ( Polynomial.X + Polynomial.C ( c + d ) ) ) ) = ( Polynomial.roots ( boxplus n p q ) |> Multiset.map fun x => x - ( c + d ) ) from ?_, Multiset.card_map ];
    · unfold Phi;
      split_ifs <;> simp_all +decide [ Multiset.nodup_map_iff_inj_on ];
      · -- By definition of polynomial composition, the roots of $(boxplus n p q).comp (X + (C c + C d))$ are the roots of $boxplus n p q$ shifted by $-(c + d)$. Hence, we can rewrite the sums.
        have h_roots_comp : ((boxplus n p q).comp (Polynomial.X + (Polynomial.C c + Polynomial.C d))).roots.toFinset = Finset.image (fun x => x - (c + d)) ((boxplus n p q).roots.toFinset) := by
          ext; simp [Finset.mem_image];
          rw [ Polynomial.comp_eq_zero_iff ] ; aesop;
        rw [ h_roots_comp, Finset.sum_image ];
        · refine' Finset.sum_congr rfl fun x hx => _;
          rw [ Finset.sum_image ] <;> aesop;
        · exact fun x hx y hy hxy => by simpa using hxy;
      · rw [ Multiset.nodup_iff_count_le_one ] at *;
        simp +zetaDelta at *;
        obtain ⟨ x, hx ⟩ := ‹∃ x, 1 < Polynomial.rootMultiplicity x ( boxplus n p q ) ›; specialize ‹ ( ∀ a : ℝ, Multiset.count a ( Multiset.map ( fun x => x - ( c + d ) ) ( boxplus n p q |> Polynomial.roots ) ) ≤ 1 ) ∧ 1 < ( boxplus n p q |> Polynomial.roots |> Multiset.card ) ›; have := ‹ ( ∀ a : ℝ, Multiset.count a ( Multiset.map ( fun x => x - ( c + d ) ) ( boxplus n p q |> Polynomial.roots ) ) ≤ 1 ) ∧ 1 < ( boxplus n p q |> Polynomial.roots |> Multiset.card ) ›.1 ( x - ( c + d ) ) ; simp_all +decide [ Multiset.count_map ] ;
        simp_all +decide [ Multiset.filter_eq, Polynomial.rootMultiplicity_eq_zero ];
        linarith;
    · ext x;
      have h_root_multiplicity : Polynomial.rootMultiplicity x ((boxplus n p q).comp (Polynomial.X + Polynomial.C (c + d))) = Polynomial.rootMultiplicity (x + (c + d)) (boxplus n p q) := by
        rw [ Polynomial.rootMultiplicity_eq_natTrailingDegree, Polynomial.rootMultiplicity_eq_natTrailingDegree ];
        norm_num [ add_assoc, Polynomial.comp_assoc ];
      rw [ Multiset.count_map ];
      rw [ show ( Multiset.filter ( fun a => x = a - ( c + d ) ) ( boxplus n p q |> Polynomial.roots ) ) = Multiset.filter ( fun a => a = x + ( c + d ) ) ( boxplus n p q |> Polynomial.roots ) by congr; ext; constructor <;> intro <;> linarith ] ; rw [ Multiset.filter_eq' ] ; aesop

/-
Any monic polynomial of positive degree can be shifted to have zero trace (second highest coefficient).
-/
open Polynomial BigOperators Finset Classical
open scoped BigOperators

lemma exists_shift_centered (n : ℕ) (p : ℝ[X]) (hn : n > 0)
  (hp_monic : p.Monic) (hp_deg : p.natDegree = n) :
  ∃ c : ℝ, (p.comp (X + C c)).coeff (n - 1) = 0 := by
    -- The coefficient of $X^{n-1}$ in $p(X+c)$ is given by the Taylor expansion formula or binomial expansion.
    have h_coeff : ∀ c : ℝ, p.comp (Polynomial.X + Polynomial.C c) = Finset.sum (Finset.range (n + 1)) (fun k => Polynomial.C (p.coeff k) * (Polynomial.X + Polynomial.C c)^k) := by
      intro c; nth_rw 1 [ p.as_sum_range_C_mul_X_pow ] ; simp +decide [ ← Polynomial.C_mul_X_pow_eq_monomial, hp_deg ] ;
    -- By comparing coefficients, we can see that the coefficient of $X^{n-1}$ in $p(X+c)$ is given by $n c + a_{n-1}$.
    have h_coeff_n_minus_1 : ∀ c : ℝ, (p.comp (Polynomial.X + Polynomial.C c)).coeff (n - 1) = n * c + p.coeff (n - 1) := by
      intro c; rw [ h_coeff c ] ; simp +decide [ Polynomial.coeff_X_add_C_pow ] ;
      rw [ Finset.sum_eq_add ( n - 1 ) n ] <;> norm_num [ Nat.choose_succ_succ, hn ];
      · rcases n with ( _ | _ | n ) <;> simp_all +decide [ Nat.choose_succ_succ, add_comm ];
        · rw [ ← hp_deg, hp_monic.coeff_natDegree ] ; ring;
        · simp_all +decide [ add_comm 1, Nat.choose_succ_succ, Polynomial.Monic.def, Polynomial.leadingCoeff, Polynomial.natDegree_eq_of_degree_eq_some ] ; ring;
      · omega;
      · intro k hk₁ hk₂ hk₃; rcases n with ( _ | _ | n ) <;> simp_all +decide [ Nat.choose_eq_zero_of_lt ] ;
        · interval_cases k <;> contradiction;
        · exact Or.inr <| Or.inr <| Nat.choose_eq_zero_of_lt <| lt_of_le_of_ne ( by omega ) hk₂;
      · exact fun h => absurd h ( by omega );
    exact ⟨ -p.coeff ( n - 1 ) / n, by rw [ h_coeff_n_minus_1, mul_div_cancel₀ _ ( by positivity ) ] ; ring ⟩