/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 3789cf67-3fe8-409f-9581-8aeccf8f7aea

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of power sums and proof of additivity for non-zero polynomials.
-/
open Polynomial

def power_sum (p : Polynomial ℝ) (k : ℕ) : ℝ :=
  (p.roots.map (fun r => r ^ k)).sum

lemma power_sum_add (p q : Polynomial ℝ) (k : ℕ) (hp : p ≠ 0) (hq : q ≠ 0) :
    power_sum (p * q) k = power_sum p k + power_sum q k := by
  simp [power_sum]
  rw [Polynomial.roots_mul]
  · simp only [Multiset.map_add, Multiset.sum_add]
  · exact mul_ne_zero hp hq

/-
Definitions of boxplus, Phi, invPhi, and is_centered from the context file.
-/
open scoped BigOperators Real Nat Classical Pointwise
open Polynomial BigOperators Finset Classical

def boxplus_coeff (n : ℕ) (p q : ℝ[X]) (k : ℕ) : ℝ :=
  ∑ i ∈ range (k + 1),
    let j := k - i
    (Nat.factorial (n - i) * Nat.factorial (n - j) : ℝ) / (Nat.factorial n * Nat.factorial (n - k) : ℝ) *
    (p.coeff (n - i)) * (q.coeff (n - j))

def boxplus (n : ℕ) (p q : ℝ[X]) : ℝ[X] :=
  Finset.sum (range (n + 1)) (fun k => C (boxplus_coeff n p q k) * X ^ (n - k))

def Phi (p : ℝ[X]) : ℝ :=
  let roots := p.roots.toFinset
  ∑ r_i ∈ roots, (∑ r_j ∈ roots.erase r_i, 1 / (r_i - r_j))^2

def invPhi (p : ℝ[X]) : ℝ :=
  if p.roots.Nodup ∧ p.roots.card > 1 then
    1 / Phi p
  else 0

def is_centered (n : ℕ) (p : ℝ[X]) : Prop :=
  p.Monic ∧ p.natDegree = n ∧ p.coeff (n - 1) = 0

/-
The sum of P(r)/Q'(r) over the roots r of Q is zero if deg(P) + 2 <= deg(Q).
-/
lemma sum_residues_eq_zero_of_deg_le (P Q : Polynomial ℝ)
    (h_deg : P.natDegree + 2 ≤ Q.natDegree)
    (h_splits : Q.Splits (RingHom.id ℝ))
    (h_nodup : Q.roots.Nodup) :
    (Q.roots.map (fun r => P.eval r / Q.derivative.eval r)).sum = 0 := by
  -- By the properties of the derivative and roots, we can express $P(x)$ as a sum of its partial fractions at the roots of $Q(x)$.
  have h_partial_fractions : ∀ x, x ∉ Q.roots → P.eval x / Q.eval x = ∑ r ∈ Q.roots.toFinset, (P.eval r) / (Q.derivative.eval r) * (1 / (x - r)) := by
    -- Since $Q$ splits into linear factors over the reals and has distinct roots, we can write it as $Q(x) = c \prod_{r \in Q.roots} (x - r)$ for some constant $c$.
    obtain ⟨c, hc⟩ : ∃ c : ℝ, Q = Polynomial.C c * Finset.prod Q.roots.toFinset (fun r => Polynomial.X - Polynomial.C r) := by
      use Q.leadingCoeff;
      convert Polynomial.eq_prod_roots_of_splits_id h_splits using 1;
      rw [ ← Multiset.toFinset_eq ] ; aesop;
    -- By the properties of the derivative and roots, we can express $P(x)$ as a sum of its partial fractions at the roots of $Q(x)$ using the fact that $Q(x)$ splits into linear factors over the reals.
    have h_partial_fractions : ∀ x, x ∉ Q.roots → P.eval x / Q.eval x = ∑ r ∈ Q.roots.toFinset, (P.eval r) / (Q.derivative.eval r) * (1 / (x - r)) := by
      intro x hx
      have h_eval : P.eval x = ∑ r ∈ Q.roots.toFinset, (P.eval r) * (∏ s ∈ Q.roots.toFinset \ {r}, (x - s)) / (∏ s ∈ Q.roots.toFinset \ {r}, (r - s)) := by
        have h_eval : P = Finset.sum Q.roots.toFinset (fun r => Polynomial.C (P.eval r / (∏ s ∈ Q.roots.toFinset \ {r}, (r - s))) * (∏ s ∈ Q.roots.toFinset \ {r}, (Polynomial.X - Polynomial.C s))) := by
          refine' Polynomial.eq_of_degree_sub_lt_of_eval_finset_eq _ _ _;
          exact Q.roots.toFinset;
          · refine' lt_of_le_of_lt ( Polynomial.degree_sub_le _ _ ) ( max_lt _ _ );
            · refine' lt_of_le_of_lt ( Polynomial.degree_le_natDegree ) _;
              rw [ hc, Polynomial.natDegree_C_mul ] at h_deg <;> norm_num at *;
              · linarith;
              · rintro rfl; norm_num at *;
            · refine' lt_of_le_of_lt ( Polynomial.degree_sum_le _ _ ) ( Finset.sup_lt_iff _ |>.2 _ );
              · exact WithBot.bot_lt_coe _;
              · intro r hr; rw [ Polynomial.degree_mul, Polynomial.degree_prod, Finset.sum_congr rfl fun s hs => Polynomial.degree_X_sub_C _ ] ; norm_num [ Finset.card_sdiff, hr ] ;
                exact lt_of_le_of_lt ( add_le_add ( Polynomial.degree_C_le ) le_rfl ) ( by norm_cast; linarith [ Finset.card_pos.mpr ⟨ r, hr ⟩, Nat.sub_add_cancel ( Finset.card_pos.mpr ⟨ r, hr ⟩ ) ] );
          · intro r hr; rw [ Polynomial.eval_finset_sum, Finset.sum_eq_single r ] <;> norm_num [ hr ];
            · simp +decide [ Polynomial.eval_prod, Finset.prod_eq_zero_iff, sub_eq_zero ];
            · intro b hb hb' hb''; rw [ Polynomial.eval_prod ] ; simp +decide [ Finset.prod_eq_zero_iff, sub_eq_zero, hb'' ] ;
              exact Or.inr ⟨ ⟨ hb, by simpa using Polynomial.isRoot_of_mem_roots ( Multiset.mem_toFinset.mp hr ) ⟩, Ne.symm hb'' ⟩;
        conv_lhs => rw [ h_eval ];
        simp +decide [ Polynomial.eval_finset_sum, Polynomial.eval_mul, Polynomial.eval_prod, Polynomial.eval_sub, Polynomial.eval_X, Polynomial.eval_C, div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.prod_mul_distrib ]
      -- By the properties of the derivative and roots, we can express $Q'(x)$ as a sum of its partial fractions at the roots of $Q(x)$.
      have h_deriv : ∀ r ∈ Q.roots.toFinset, Q.derivative.eval r = c * (∏ s ∈ Q.roots.toFinset \ {r}, (r - s)) := by
        intro r hr
        have h_deriv : Q.derivative.eval r = Polynomial.eval r (Polynomial.derivative (Polynomial.C c * Finset.prod Q.roots.toFinset (fun s => Polynomial.X - Polynomial.C s))) := by
          rw [ ← hc ];
        rw [ h_deriv, Finset.prod_eq_prod_diff_singleton_mul hr ] ; norm_num [ Polynomial.derivative_prod ] ; ring;
        norm_num [ Polynomial.eval_prod ];
      -- By the properties of the derivative and roots, we can express $Q(x)$ as a product of its roots.
      have h_prod : Q.eval x = c * (∏ r ∈ Q.roots.toFinset, (x - r)) := by
        simpa [ Polynomial.eval_prod ] using congr_arg ( Polynomial.eval x ) hc;
      rw [ h_eval, h_prod, Finset.sum_div _ _ _ ];
      refine Finset.sum_congr rfl fun r hr => ?_;
      rw [ h_deriv r hr, Finset.prod_eq_prod_diff_singleton_mul hr ] ; ring;
      field_simp;
      convert mul_div_mul_right _ _ ( show ( ∏ s ∈ Q.roots.toFinset \ { r }, ( x - s ) ) ≠ 0 from Finset.prod_ne_zero_iff.mpr fun s hs => sub_ne_zero_of_ne <| by rintro rfl; exact hx <| by simpa using Finset.mem_sdiff.mp hs |>.1 ) using 1 ; ring;
    assumption;
  -- Consider the limit of the partial fraction decomposition as $x$ goes to infinity.
  have h_limit : Filter.Tendsto (fun x : ℝ => (∑ r ∈ Q.roots.toFinset, (P.eval r) / (Q.derivative.eval r) * (1 / (x - r))) * x) Filter.atTop (nhds (∑ r ∈ Q.roots.toFinset, (P.eval r) / (Q.derivative.eval r))) := by
    -- Each term in the sum $\sum_{r \in Q.roots.toFinset} \frac{P(r)}{Q'(r)} \cdot \frac{x}{x - r}$ tends to $\frac{P(r)}{Q'(r)}$ as $x$ goes to infinity.
    have h_term_limit : ∀ r ∈ Q.roots.toFinset, Filter.Tendsto (fun x : ℝ => (P.eval r) / (Q.derivative.eval r) * (x / (x - r))) Filter.atTop (nhds ((P.eval r) / (Q.derivative.eval r))) := by
      intro r hr
      have : Filter.Tendsto (fun x : ℝ => x / (x - r)) Filter.atTop (nhds 1) := by
        erw [ Metric.tendsto_nhds ];
        exact fun ε ε_pos => Filter.eventually_atTop.mpr ⟨ ⌈ε⁻¹ * ( |r| + 1 ) ⌉₊ + |r| + 1, fun x hx => abs_lt.mpr ⟨ by cases abs_cases r <;> nlinarith [ Nat.le_ceil ( ε⁻¹ * ( |r| + 1 ) ), mul_inv_cancel₀ ( ne_of_gt ε_pos ), div_mul_cancel₀ x ( by linarith : ( x - r ) ≠ 0 ) ], by cases abs_cases r <;> nlinarith [ Nat.le_ceil ( ε⁻¹ * ( |r| + 1 ) ), mul_inv_cancel₀ ( ne_of_gt ε_pos ), div_mul_cancel₀ x ( by linarith : ( x - r ) ≠ 0 ) ] ⟩ ⟩;
      simpa using this.const_mul _;
    simpa [ mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _ ] using tendsto_finset_sum _ h_term_limit |> Filter.Tendsto.congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with x hx; simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, hx.ne' ] );
  -- Since $P(x)/Q(x)$ tends to zero as $x$ goes to infinity, the limit of the partial fraction decomposition must also be zero.
  have h_zero_limit : Filter.Tendsto (fun x : ℝ => P.eval x / Q.eval x * x) Filter.atTop (nhds 0) := by
    field_simp;
    have := Polynomial.div_tendsto_zero_of_degree_lt ( P * Polynomial.X ) Q;
    by_cases hP : P = 0 <;> by_cases hQ : Q = 0 <;> simp_all +decide [ Polynomial.degree_eq_natDegree ];
    exact this ( mod_cast by linarith );
  convert tendsto_nhds_unique h_limit ( h_zero_limit.congr' _ ) using 1;
  · rw [ ← Multiset.toFinset_eq ] ; aesop;
  · filter_upwards [ Filter.eventually_gt_atTop ( ∑ r ∈ Q.roots.toFinset, |r| ) ] with x hx;
    rw [ h_partial_fractions x ];
    intro hx';
    exact hx.not_le ( Finset.single_le_sum ( fun r _ => abs_nonneg r ) ( by aesop ) |> le_trans ( le_abs_self _ ) )

/-
Checking the definition of IsRoot and the existence of the derivative divisibility lemma.
-/
#check Polynomial.IsRoot
#check Polynomial.pow_sub_one_dvd_derivative_of_pow_dvd

/-
Checking the existence of Polynomial.mem_roots and Polynomial.roots_mul.
-/
#check Polynomial.mem_roots
#check Polynomial.roots_mul

/-
Checking the definition of Polynomial.IsRoot.
-/
#print Polynomial.IsRoot

/-
If p(a) = 0 and p'(a) = 0, then (x-a)^2 divides p(x).
-/
lemma dvd_pow_two_of_isRoot_of_isRoot_derivative {R : Type*} [CommRing R] [IsDomain R] [CharZero R]
    (p : Polynomial R) (a : R) (h1 : p.IsRoot a) (h2 : p.derivative.IsRoot a) :
    (Polynomial.X - Polynomial.C a)^2 ∣ p := by
  obtain ⟨ q, rfl ⟩ := Polynomial.dvd_iff_isRoot.mpr h1; simp_all +decide [ sq, Polynomial.derivative_mul ] ;
  exact mul_dvd_mul_left _ ( Polynomial.dvd_iff_isRoot.mpr h2 )

/-
If p has distinct roots and p' has distinct roots, then p * p' has distinct roots.
-/
lemma roots_mul_deriv_nodup (p : ℝ[X])
    (h_splits : p.Splits (RingHom.id ℝ))
    (h_nodup : p.roots.Nodup)
    (h_deriv_nodup : p.derivative.roots.Nodup) :
    (p * p.derivative).roots.Nodup := by
      by_cases h : Polynomial.derivative p = 0 <;> simp_all +decide [ Polynomial.splits_iff_card_roots ];
      rw [ Polynomial.roots_mul ];
      · -- Since $p$ and $p'$ have no common roots, their roots are disjoint.
        have h_disjoint : Disjoint (p.roots.toFinset) ((Polynomial.derivative p).roots.toFinset) := by
          rw [ Finset.disjoint_left ] ; intro x hx hx' ; simp_all +decide [ Polynomial.IsRoot ];
          have := Polynomial.dvd_iff_isRoot.mpr hx.2; obtain ⟨ q, rfl ⟩ := this; simp_all +decide [ Polynomial.derivative_mul ] ;
          rw [ Polynomial.roots_mul ] at h_nodup <;> aesop;
        rw [ Multiset.nodup_add ] ; aesop;
      · aesop

/-
Checking the types of Polynomial.splits_of_splits_of_dvd and Polynomial.splits_mul.
-/
#check Polynomial.splits_of_splits_of_dvd
#check Polynomial.splits_mul

/-
Checking the type of Polynomial.splits_mul.
-/
#check Polynomial.splits_mul

/-
Checking the types of Polynomial.splits_of_splits_of_dvd and Polynomial.splits_mul.
-/
#check Polynomial.splits_of_splits_of_dvd
#check Polynomial.splits_mul

/-
The degree of the derivative is deg(p) - 1 for real polynomials with deg(p) > 0.
-/
lemma natDegree_derivative_eq_natDegree_sub_one (p : ℝ[X]) (hp : p.natDegree > 0) :
    p.derivative.natDegree = p.natDegree - 1 := by
      rw [ Polynomial.natDegree_eq_of_degree_eq_some ] ; aesop;

/-
If a real polynomial splits, its derivative also splits.
-/
lemma splits_derivative (p : ℝ[X]) (h_splits : p.Splits (RingHom.id ℝ)) :
    p.derivative.Splits (RingHom.id ℝ) := by
  by_cases h : p.natDegree = 0 <;> simp_all +decide [ Polynomial.splits_iff_card_roots ];
  · rw [ Polynomial.eq_C_of_natDegree_eq_zero h ] ; aesop;
  · -- Since $p$ is a polynomial with real coefficients and $p$ splits into linear factors over the reals, by Rolle's theorem, between any two consecutive roots of $p$, there is at least one root of $p'$.
    have h_rolle : Multiset.card (Polynomial.derivative p).roots ≥ Multiset.card p.roots - 1 := by
      norm_num +zetaDelta at *;
      exact?;
    refine' le_antisymm _ _;
    · exact Polynomial.card_roots' _;
    · refine' le_trans _ ( h_rolle.trans' ( Nat.sub_le_sub_right h_splits.ge _ ) );
      exact Polynomial.natDegree_derivative_le _

/-
Adding Phi_derivative_form and roots_card_eq_natDegree to the workspace.
-/
lemma roots_card_eq_natDegree (p : ℝ[X])
    (h_splits : p.Splits (RingHom.id ℝ)) (h_monic : p.Monic) :
    p.roots.card = p.natDegree := by
  rw [Polynomial.splits_iff_card_roots] at h_splits
  exact h_splits

lemma Phi_derivative_form (p : ℝ[X])
    (h_splits : p.Splits (RingHom.id ℝ))
    (h_nodup : p.roots.Nodup) :
    Phi p = ∑ r ∈ p.roots.toFinset, (p.derivative.derivative.eval r / (2 * p.derivative.eval r))^2 := by
      refine' Finset.sum_congr rfl fun r hr => _;
      -- Let $q(x) = \frac{p(x)}{x - r}$.
      obtain ⟨q, hq⟩ : ∃ q : Polynomial ℝ, p = (Polynomial.X - Polynomial.C r) * q ∧ q.eval r ≠ 0 := by
        obtain ⟨q, hq⟩ : ∃ q : Polynomial ℝ, p = (Polynomial.X - Polynomial.C r) * q := by
          exact Polynomial.dvd_iff_isRoot.mpr ( by aesop );
        by_cases h : q.eval r = 0 <;> simp_all +decide [ Polynomial.splits_mul, Polynomial.splits_X_sub_C ];
        rw [ Polynomial.roots_mul ] at h_nodup <;> aesop;
      -- Since $q(x)$ is a polynomial with roots $r_j$ for $j \neq r$, we can write $q(x) = c \prod_{j \neq r} (x - r_j)$ for some constant $c$.
      obtain ⟨c, hc⟩ : ∃ c : ℝ, q = Polynomial.C c * ∏ r_j ∈ p.roots.toFinset.erase r, (Polynomial.X - Polynomial.C r_j) := by
        -- Since $q$ is a polynomial with roots $r_j$ for $j \neq i$, we can write $q$ as a product of linear factors corresponding to these roots.
        have hq_factor : q = Polynomial.C (q.leadingCoeff) * ∏ r_j ∈ q.roots.toFinset, (Polynomial.X - Polynomial.C r_j) := by
          convert Polynomial.eq_prod_roots_of_splits_id _;
          · rw [ ← Multiset.toFinset_eq ];
            rfl;
            rw [ hq.1, Polynomial.roots_mul ] at h_nodup <;> aesop;
          · simp_all +decide [ Polynomial.splits_mul_iff ];
        -- Since $q$ is a polynomial with roots $r_j$ for $j \neq i$, we have $q.roots.toFinset = p.roots.toFinset.erase r$.
        have hq_roots : q.roots.toFinset = p.roots.toFinset.erase r := by
          rw [ hq.1, Polynomial.roots_mul ] <;> norm_num [ hq.2 ];
          exact ⟨ Polynomial.X_sub_C_ne_zero _, by rintro rfl; simp +decide at hq ⟩;
        exact ⟨ q.leadingCoeff, hq_roots ▸ hq_factor ⟩;
      -- By definition of $q$, we know that $q'(r) = c \sum_{j \neq r} \prod_{k \neq r, j} (r - r_k)$.
      have hq'_eval : Polynomial.eval r (Polynomial.derivative q) = c * ∑ r_j ∈ p.roots.toFinset.erase r, (∏ r_k ∈ p.roots.toFinset.erase r \ {r_j}, (r - r_k)) := by
        rw [ hc, Polynomial.derivative_mul, Polynomial.derivative_C ] ; norm_num;
        erw [ Polynomial.derivative_prod ];
        erw [ Polynomial.eval_finset_sum ] ; norm_num [ Polynomial.eval_prod ];
        simp +decide [ Finset.sdiff_singleton_eq_erase, Polynomial.eval_multiset_prod ];
        exact Or.inl rfl;
      -- By definition of $q$, we know that $q(r) = c \prod_{j \neq r} (r - r_j)$.
      have hq_eval : Polynomial.eval r q = c * ∏ r_j ∈ p.roots.toFinset.erase r, (r - r_j) := by
        simp +decide [ hc, Polynomial.eval_prod ];
      -- By definition of $q$, we know that $\sum_{j \neq r} \frac{1}{r - r_j} = \frac{q'(r)}{q(r)}$.
      have h_sum_inv : ∑ r_j ∈ p.roots.toFinset.erase r, (1 / (r - r_j)) = Polynomial.eval r (Polynomial.derivative q) / Polynomial.eval r q := by
        rw [ hq'_eval, hq_eval, eq_div_iff ];
        · simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Finset.sum_mul ];
          refine' Finset.sum_congr rfl fun x hx => _;
          field_simp;
          rw [ Finset.prod_eq_prod_diff_singleton_mul hx, mul_div_assoc ] ; norm_num [ sub_ne_zero.mpr ( show r ≠ x from by rintro rfl; exact Finset.notMem_erase _ _ hx ) ];
        · exact hq_eval ▸ hq.2;
      rw [ h_sum_inv, hq.1 ] ; norm_num [ Polynomial.derivative_mul, Polynomial.derivative_prod ] ; ring;

/-
Helper lemma for degree inequality.
-/
lemma deg_P_plus_two_le_deg_Q (p : ℝ[X]) (hp : p.natDegree ≥ 2) :
    (p.derivative.derivative ^ 2).natDegree + 2 ≤ (p * p.derivative).natDegree := by
  have h_deg_p_pos : p.natDegree > 0 := by omega
  have h_deg_deriv : p.derivative.natDegree = p.natDegree - 1 :=
    natDegree_derivative_eq_natDegree_sub_one p h_deg_p_pos
  have h_deg_deriv_pos : p.derivative.natDegree > 0 := by
    rw [h_deg_deriv]
    omega
  have h_deg_deriv2 : p.derivative.derivative.natDegree = p.natDegree - 2 := by
    rw [natDegree_derivative_eq_natDegree_sub_one p.derivative h_deg_deriv_pos]
    rw [h_deg_deriv]
    omega
  have h_deg_P : (p.derivative.derivative ^ 2).natDegree = 2 * (p.natDegree - 2) := by
    rw [Polynomial.natDegree_pow, h_deg_deriv2]
  have h_deg_Q : (p * p.derivative).natDegree = 2 * p.natDegree - 1 := by
    rw [Polynomial.natDegree_mul]
    · rw [h_deg_deriv]
      omega
    · exact Polynomial.ne_zero_of_natDegree_gt h_deg_p_pos
    · exact Polynomial.ne_zero_of_natDegree_gt h_deg_deriv_pos
  rw [h_deg_P, h_deg_Q]
  omega

/-
Proof of the alternative formula for Phi using residues.
-/
lemma Phi_eq_sum_roots_deriv (p : ℝ[X])
    (h_splits : p.Splits (RingHom.id ℝ))
    (h_nodup : p.roots.Nodup)
    (h_deg : p.natDegree ≥ 2)
    (h_deriv_nodup : p.derivative.roots.Nodup) :
    Phi p = -1/4 * (p.derivative.roots.map (fun μ => p.derivative.derivative.eval μ / p.eval μ)).sum := by
      have := @Phi_derivative_form p h_splits h_nodup;
      have := @sum_residues_eq_zero_of_deg_le ( Polynomial.derivative ( Polynomial.derivative p ) ^ 2 ) ( p * Polynomial.derivative p ) ?_ ?_ ?_ <;> norm_num at *;
      · rw [ Polynomial.roots_mul ] at this;
        · simp_all +decide [ Finset.sum_add_distrib, Multiset.sum_map_mul_right, div_eq_mul_inv ];
          rw [ show ( Multiset.map ( fun x => Polynomial.eval x ( Polynomial.derivative ( Polynomial.derivative p ) ) ^ 2 * ( Polynomial.eval x ( Polynomial.derivative p ) * Polynomial.eval x ( Polynomial.derivative p ) + Polynomial.eval x p * Polynomial.eval x ( Polynomial.derivative ( Polynomial.derivative p ) ) ) ⁻¹ ) p.roots ).sum = ( Multiset.map ( fun x => Polynomial.eval x ( Polynomial.derivative ( Polynomial.derivative p ) ) ^ 2 * ( Polynomial.eval x ( Polynomial.derivative p ) * Polynomial.eval x ( Polynomial.derivative p ) ) ⁻¹ ) p.roots ).sum from ?_ ] at this;
          · rw [ show ( Multiset.map ( fun x => Polynomial.eval x ( Polynomial.derivative ( Polynomial.derivative p ) ) ^ 2 * ( Polynomial.eval x ( Polynomial.derivative p ) * Polynomial.eval x ( Polynomial.derivative p ) ) ⁻¹ ) p.roots ).sum = ( ∑ x ∈ p.roots.toFinset, ( Polynomial.eval x ( Polynomial.derivative ( Polynomial.derivative p ) ) ^ 2 * ( Polynomial.eval x ( Polynomial.derivative p ) * Polynomial.eval x ( Polynomial.derivative p ) ) ⁻¹ ) ) from ?_ ] at this;
            · rw [ show ( Multiset.map ( fun x => Polynomial.eval x ( Polynomial.derivative ( Polynomial.derivative p ) ) ^ 2 * ( Polynomial.eval x ( Polynomial.derivative p ) * Polynomial.eval x ( Polynomial.derivative p ) + Polynomial.eval x p * Polynomial.eval x ( Polynomial.derivative ( Polynomial.derivative p ) ) ) ⁻¹ ) ( Polynomial.derivative p |> Polynomial.roots ) ).sum = ( Multiset.map ( fun x => Polynomial.eval x ( Polynomial.derivative ( Polynomial.derivative p ) ) ^ 2 * ( Polynomial.eval x p * Polynomial.eval x ( Polynomial.derivative ( Polynomial.derivative p ) ) ) ⁻¹ ) ( Polynomial.derivative p |> Polynomial.roots ) ).sum from ?_ ] at this;
              · convert congr_arg ( fun x : ℝ => x / 4 ) ( eq_neg_of_add_eq_zero_left this ) using 1 <;> ring;
                · rw [ Finset.sum_mul _ _ _ ];
                · field_simp;
              · refine' congr_arg _ ( Multiset.map_congr rfl fun x hx => _ );
                aesop;
            · rw [ ← Multiset.toFinset_eq ];
              exact?;
              assumption;
          · refine' congr_arg _ ( Multiset.map_congr rfl fun x hx => _ );
            aesop;
        · norm_num +zetaDelta at *;
          exact ⟨ by aesop_cat, by exact fun h => by rw [ Polynomial.eq_C_of_derivative_eq_zero h ] at h_deg h_splits h_nodup; aesop_cat ⟩;
      · have := @deg_P_plus_two_le_deg_Q p h_deg;
        aesop;
      · exact Polynomial.splits_mul _ h_splits ( splits_derivative _ h_splits );
      · convert roots_mul_deriv_nodup p h_splits h_nodup h_deriv_nodup using 1

/-
Proof of the alternative formula for Phi using residues (v2).
-/
lemma Phi_eq_sum_roots_deriv_v2 (p : ℝ[X])
    (h_splits : p.Splits (RingHom.id ℝ))
    (h_nodup : p.roots.Nodup)
    (h_deg : p.natDegree ≥ 2)
    (h_deriv_nodup : p.derivative.roots.Nodup) :
    Phi p = -1/4 * (p.derivative.roots.map (fun μ => p.derivative.derivative.eval μ / p.eval μ)).sum := by
      convert Phi_eq_sum_roots_deriv p h_splits h_nodup h_deg h_deriv_nodup using 1

/-
Finite Free Stam Inequality for n=2.
-/
lemma finite_free_stam_inequality_n2 (p q : ℝ[X])
    (hp : p.Splits (RingHom.id ℝ)) (hp_nodup : p.roots.Nodup)
    (hp_monic : p.Monic) (hp_deg : p.natDegree = 2)
    (hq : q.Splits (RingHom.id ℝ)) (hq_nodup : q.roots.Nodup)
    (hq_monic : q.Monic) (hq_deg : q.natDegree = 2)
    (hpq : (boxplus 2 p q).Splits (RingHom.id ℝ))
    (hpq_nodup : (boxplus 2 p q).roots.Nodup) :
    invPhi (boxplus 2 p q) ≥ invPhi p + invPhi q := by
      -- Let's unfold the definitions of `invPhi` and `Phi`.
      simp [invPhi, Phi];
      by_cases h : 1 < Multiset.card ( Polynomial.roots p ) <;> by_cases h' : 1 < Multiset.card ( Polynomial.roots q ) <;> simp_all +decide [ Polynomial.natDegree_eq_of_degree_eq_some ];
      · -- Since $p$ and $q$ are monic polynomials of degree 2 with distinct roots, we can write them as $p(x) = (x - a)(x - b)$ and $q(x) = (x - c)(x - d)$.
        obtain ⟨a, b, ha, hb, hab⟩ : ∃ a b : ℝ, a ≠ b ∧ p = Polynomial.C 1 * (Polynomial.X - Polynomial.C a) * (Polynomial.X - Polynomial.C b) := by
          -- Since $p$ is a monic polynomial of degree 2 with distinct roots, it can be factored as $p(x) = (x - a)(x - b)$ where $a$ and $b$ are the roots.
          obtain ⟨a, b, hab⟩ : ∃ a b : ℝ, a ≠ b ∧ p = Polynomial.C 1 * (Polynomial.X - Polynomial.C a) * (Polynomial.X - Polynomial.C b) := by
            have h_roots : ∃ a b : ℝ, p.roots = {a, b} := by
              exact Multiset.card_eq_two.mp ( by linarith [ Polynomial.splits_iff_card_roots.mp hp ] )
            obtain ⟨ a, b, h ⟩ := h_roots; use a, b; rw [ ← Polynomial.prod_multiset_X_sub_C_of_monic_of_roots_card_eq hp_monic ] <;> aesop;
          use a, b
        obtain ⟨c, d, hc, hd, hcd⟩ : ∃ c d : ℝ, c ≠ d ∧ q = Polynomial.C 1 * (Polynomial.X - Polynomial.C c) * (Polynomial.X - Polynomial.C d) := by
          have h_roots : q.roots.card = 2 := by
            exact le_antisymm ( le_trans ( Polynomial.card_roots' q ) ( by norm_num [ hq_deg ] ) ) h';
          obtain ⟨ c, d, hcd ⟩ := Multiset.card_eq_two.mp h_roots;
          rw [ ← Polynomial.prod_multiset_X_sub_C_of_monic_of_roots_card_eq hq_monic ] <;> aesop;
        unfold boxplus; norm_num [ Polynomial.eval_finset_sum, Polynomial.eval_mul, Polynomial.eval_sub, Polynomial.eval_X, Polynomial.eval_C ] ;
        rw [ Polynomial.roots_mul, Polynomial.roots_mul ] <;> norm_num [ ha, hc ];
        · unfold boxplus_coeff; norm_num [ Finset.sum_range_succ' ] ; ring_nf;
          norm_num [ Polynomial.coeff_one, Polynomial.coeff_X, Polynomial.coeff_C, mul_assoc, sub_mul, add_mul ] ; ring_nf ; norm_num;
          rw [ show ( Polynomial.C a * Polynomial.C b - Polynomial.C a * Polynomial.X + Polynomial.C a * Polynomial.C c * Polynomial.C ( 1 / 2 ) + ( Polynomial.C a * Polynomial.C d * Polynomial.C ( 1 / 2 ) - Polynomial.C b * Polynomial.X ) + Polynomial.C b * Polynomial.C c * Polynomial.C ( 1 / 2 ) + Polynomial.C b * Polynomial.C d * Polynomial.C ( 1 / 2 ) + ( - ( Polynomial.C c * Polynomial.X ) - Polynomial.C d * Polynomial.X ) + Polynomial.X ^ 2 + Polynomial.C c * Polynomial.C d ) = ( Polynomial.X - Polynomial.C ( ( a + b + c + d ) / 2 ) ) ^ 2 - Polynomial.C ( ( a - b ) ^ 2 / 4 + ( c - d ) ^ 2 / 4 ) by exact Polynomial.funext fun x => by norm_num; ring ];
          rw [ show ( Polynomial.X - Polynomial.C ( ( a + b + c + d ) / 2 ) ) ^ 2 - Polynomial.C ( ( a - b ) ^ 2 / 4 + ( c - d ) ^ 2 / 4 ) = ( Polynomial.X - Polynomial.C ( ( a + b + c + d ) / 2 + Real.sqrt ( ( a - b ) ^ 2 / 4 + ( c - d ) ^ 2 / 4 ) ) ) * ( Polynomial.X - Polynomial.C ( ( a + b + c + d ) / 2 - Real.sqrt ( ( a - b ) ^ 2 / 4 + ( c - d ) ^ 2 / 4 ) ) ) by exact Polynomial.funext fun x => by norm_num; linarith [ Real.mul_self_sqrt ( show 0 ≤ ( a - b ) ^ 2 / 4 + ( c - d ) ^ 2 / 4 by positivity ) ] ];
          rw [ Polynomial.roots_mul <| by exact mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ), Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] ; norm_num ; ring_nf ; norm_num;
          rw [ Finset.sum_pair ] <;> norm_num;
          · rw [ Finset.sum_pair ] <;> norm_num ; ring_nf ; norm_num;
            · rw [ Real.sq_sqrt ] <;> nlinarith [ sq_nonneg ( a - b ), sq_nonneg ( c - d ) ];
            · nlinarith [ mul_self_pos.2 ( sub_ne_zero.2 ha ), mul_self_pos.2 ( sub_ne_zero.2 hc ), Real.sqrt_pos.2 ( show 0 < - ( a * b * ( 1 / 2 ) ) + a ^ 2 * ( 1 / 4 ) + b ^ 2 * ( 1 / 4 ) + - ( c * d * ( 1 / 2 ) ) + c ^ 2 * ( 1 / 4 ) + d ^ 2 * ( 1 / 4 ) by nlinarith [ mul_self_pos.2 ( sub_ne_zero.2 ha ), mul_self_pos.2 ( sub_ne_zero.2 hc ) ] ) ];
          · nlinarith [ mul_self_pos.2 ( sub_ne_zero.2 ha ), mul_self_pos.2 ( sub_ne_zero.2 hc ), Real.sqrt_pos.2 ( show 0 < - ( a * b * ( 1 / 2 ) ) + a ^ 2 * ( 1 / 4 ) + b ^ 2 * ( 1 / 4 ) + - ( c * d * ( 1 / 2 ) ) + c ^ 2 * ( 1 / 4 ) + d ^ 2 * ( 1 / 4 ) by nlinarith [ mul_self_pos.2 ( sub_ne_zero.2 ha ), mul_self_pos.2 ( sub_ne_zero.2 hc ) ] ) ];
        · exact ⟨ Polynomial.X_sub_C_ne_zero _, Polynomial.X_sub_C_ne_zero _ ⟩;
        · exact ⟨ Polynomial.X_sub_C_ne_zero a, Polynomial.X_sub_C_ne_zero b ⟩;
      · rw [ Polynomial.splits_iff_card_roots ] at * ; aesop;
      · rw [ Polynomial.splits_iff_card_roots ] at * ; aesop;
      · rw [ Polynomial.splits_iff_card_roots ] at * ; aesop