/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 3fa7f60c-b216-4518-a554-74058622e9f9

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Redefining the core definitions from the context file to ensure they are available in the workspace.
-/
open scoped BigOperators Real Nat Classical Pointwise
open Polynomial BigOperators Finset Classical

def boxplus_coeff (n : ℕ) (p q : ℝ[X]) (k : ℕ) : ℝ :=
  ∑ i ∈ range (k + 1),
    let j := k - i
    (Nat.factorial (n - i) * Nat.factorial (n - j) : ℝ) / (Nat.factorial n * Nat.factorial (n - k) : ℝ) *
    (p.coeff (n - i)) * (q.coeff (n - j))

def boxplus (n : ℕ) (p q : ℝ[X]) : ℝ[X] :=
  Finset.sum (range (n + 1)) (fun k => C (boxplus_coeff n p q k) * X ^ (n - k))

def Phi (p : ℝ[X]) : ℝ :=
  let roots := p.roots.toFinset
  ∑ r_i ∈ roots, (∑ r_j ∈ roots.erase r_i, 1 / (r_i - r_j))^2

def invPhi (p : ℝ[X]) : ℝ :=
  if p.roots.Nodup ∧ p.roots.card > 1 then
    1 / Phi p
  else 0

def is_centered (n : ℕ) (p : ℝ[X]) : Prop :=
  p.Monic ∧ p.natDegree = n ∧ p.coeff (n - 1) = 0

def kappa_4 (n : ℕ) (p : ℝ[X]) : ℝ :=
  p.coeff (n - 4) - (n - 2) * (n - 3) / (2 * n * (n - 1)) * (p.coeff (n - 2))^2

/-
The Phi functional for a symmetric quartic polynomial $X^4 + aX^2 + c$ is given by the formula $\frac{-a(12c + a^2)}{2c(a^2 - 4c)}$.
-/
open Polynomial

def Phi_symmetric_quartic_formula (a c : ℝ) : ℝ :=
  -a * (12 * c + a^2) / (2 * c * (a^2 - 4 * c))

theorem Phi_eq_Phi_symmetric_quartic_formula (a c : ℝ)
    (h_discr : a^2 - 4 * c > 0) (h_c : c > 0) (h_a : a < 0) :
    let p := X^4 + C a * X^2 + C c
    p.roots.Nodup → p.Splits (RingHom.id ℝ) →
    Phi p = Phi_symmetric_quartic_formula a c := by
      unfold Phi;
      field_simp;
      -- Let $y_1, y_2$ be the roots of $y^2 + ay + c = 0$.
      obtain ⟨y1, y2, hy1, hy2⟩ : ∃ y1 y2 : ℝ, y1 + y2 = -a ∧ y1 * y2 = c ∧ y1 > 0 ∧ y2 > 0 ∧ y1 ≠ y2 := by
        exact ⟨ ( -a + Real.sqrt ( a^2 - 4 * c ) ) / 2, ( -a - Real.sqrt ( a^2 - 4 * c ) ) / 2, by ring, by linarith [ Real.mul_self_sqrt h_discr.le ], by nlinarith [ Real.sqrt_nonneg ( a^2 - 4 * c ), Real.mul_self_sqrt h_discr.le ], by nlinarith [ Real.sqrt_nonneg ( a^2 - 4 * c ), Real.mul_self_sqrt h_discr.le ], by nlinarith [ Real.sqrt_nonneg ( a^2 - 4 * c ), Real.mul_self_sqrt h_discr.le ] ⟩;
      -- The roots of $p$ are $\pm \sqrt{y_1}, \pm \sqrt{y_2}$.
      have h_roots : (Polynomial.X ^ 4 + Polynomial.C a * Polynomial.X ^ 2 + Polynomial.C c).roots.toFinset = {Real.sqrt y1, -Real.sqrt y1, Real.sqrt y2, -Real.sqrt y2} := by
        ext;
        constructor <;> intro h <;> simp_all +decide [ Finset.mem_insert, Finset.mem_singleton ];
        · -- By definition of $y1$ and $y2$, we know that $x^2 = y1$ or $x^2 = y2$.
          have h_sq : (‹ℝ› ^ 2 = y1) ∨ (‹ℝ› ^ 2 = y2) := by
            grind;
          rcases h_sq with ( h_sq | h_sq ) <;> [ exact Or.imp id ( Or.inl ) ( eq_or_eq_neg_of_sq_eq_sq _ _ <| by rw [ h_sq, Real.sq_sqrt <| by linarith ] ) ; exact Or.inr <| Or.inr <| eq_or_eq_neg_of_sq_eq_sq _ _ <| by rw [ h_sq, Real.sq_sqrt <| by linarith ] ];
        · rcases h with ( rfl | rfl | rfl | rfl ) <;> exact ⟨ ne_of_apply_ne ( fun p => p.coeff 4 ) <| by norm_num [ Polynomial.coeff_X, Polynomial.coeff_C ], by nlinarith [ Real.mul_self_sqrt hy2.2.1.le, Real.mul_self_sqrt hy2.2.2.1.le ] ⟩;
      rw [ h_roots, Finset.sum_insert, Finset.sum_insert, Finset.sum_insert, Finset.sum_singleton ] <;> norm_num;
      · rw [ Finset.sum_insert, Finset.sum_insert, Finset.sum_insert, Finset.sum_singleton ] <;> norm_num;
        · rw [ Finset.sum_insert, Finset.sum_insert, Finset.sum_insert, Finset.sum_singleton ] <;> norm_num;
          · rw [ Finset.sum_insert, Finset.sum_insert, Finset.sum_insert, Finset.sum_singleton ] <;> norm_num;
            · rw [ Finset.erase_insert_of_ne, Finset.erase_insert_of_ne ] <;> norm_num;
              · rw [ Finset.sum_insert, Finset.sum_insert ] <;> norm_num;
                · rw [ Finset.erase_eq_of_notMem ] <;> norm_num;
                  · rw [ show a = - ( y1 + y2 ) by linarith, show c = y1 * y2 by linarith ] ; ring;
                    unfold Phi_symmetric_quartic_formula;
                    rw [ show ( -Real.sqrt y1 - Real.sqrt y2 ) = - ( Real.sqrt y1 + Real.sqrt y2 ) by ring, show ( -Real.sqrt y1 + Real.sqrt y2 ) = - ( Real.sqrt y1 - Real.sqrt y2 ) by ring, inv_neg, inv_neg ] ; ring;
                    rw [ show ( Real.sqrt y1 - Real.sqrt y2 ) = ( y1 - y2 ) / ( Real.sqrt y1 + Real.sqrt y2 ) by rw [ eq_div_iff <| by nlinarith [ Real.sqrt_pos.2 hy2.2.1, Real.sqrt_pos.2 hy2.2.2.1 ] ] ; linarith [ Real.mul_self_sqrt hy2.2.1.le, Real.mul_self_sqrt hy2.2.2.1.le ] ] ; norm_num ; ring;
                    rw [ show ( Real.sqrt y1 + Real.sqrt y2 ) ⁻¹ = ( Real.sqrt y1 - Real.sqrt y2 ) / ( y1 - y2 ) by rw [ inv_eq_one_div, div_eq_div_iff ] <;> cases lt_or_gt_of_ne hy2.2.2.2 <;> nlinarith [ Real.mul_self_sqrt hy2.2.1.le, Real.mul_self_sqrt hy2.2.2.1.le, Real.sqrt_nonneg y1, Real.sqrt_nonneg y2 ] ] ; ring;
                    norm_num [ ne_of_gt ( Real.sqrt_pos.mpr hy2.2.1 ), ne_of_gt ( Real.sqrt_pos.mpr hy2.2.2.1 ) ] ; ring;
                    field_simp;
                    rw [ div_add_div, div_add_div, div_add_div, div_eq_div_iff ] <;> try nlinarith [ Real.mul_self_sqrt hy2.2.1.le, Real.mul_self_sqrt hy2.2.2.1.le ];
                    · grind;
                    · simp_all +decide [ ne_of_gt, le_of_lt ];
                      exact ⟨ by cases lt_or_gt_of_ne hy2.2.2.2 <;> nlinarith, by nlinarith [ Real.sqrt_pos.2 hy2.2.1, Real.sqrt_pos.2 hy2.2.2.1 ] ⟩;
                    · exact mul_ne_zero ( mul_ne_zero ( by linarith ) ( by linarith ) ) ( by nlinarith [ mul_self_pos.mpr ( sub_ne_zero.mpr hy2.2.2.2 ) ] );
                    · exact mul_ne_zero ( mul_ne_zero ( by cases lt_or_gt_of_ne hy2.2.2.2 <;> nlinarith ) ( pow_ne_zero 2 ( Real.sqrt_ne_zero'.mpr hy2.2.1 ) ) ) ( pow_ne_zero 2 ( Real.sqrt_ne_zero'.mpr hy2.2.2.1 ) );
                    · grind;
                  · linarith [ Real.sqrt_pos.2 hy2.2.1, Real.sqrt_pos.2 hy2.2.2.1 ];
                · exact fun _ => by linarith [ Real.sqrt_pos.2 hy2.2.1, Real.sqrt_pos.2 hy2.2.2.1 ] ;
                · exact ⟨ by linarith [ Real.sqrt_pos.2 hy2.2.1, Real.sqrt_pos.2 hy2.2.2.1 ], fun _ => by rw [ Real.sqrt_inj ] <;> cases lt_or_gt_of_ne hy2.2.2.2 <;> linarith ⟩;
              · rw [ Real.sqrt_inj ] <;> cases lt_or_gt_of_ne hy2.2.2.2 <;> linarith;
              · linarith [ Real.sqrt_pos.2 hy2.2.1 ];
            · linarith [ Real.sqrt_pos.2 hy2.2.2.1 ];
            · exact ⟨ by linarith [ Real.sqrt_pos.2 hy2.2.1, Real.sqrt_pos.2 hy2.2.2.1 ], by rw [ Real.sqrt_inj ] <;> cases lt_or_gt_of_ne hy2.2.2.2 <;> linarith ⟩;
            · grind;
          · linarith [ Real.sqrt_pos.2 hy2.2.2.1 ];
          · exact ⟨ by linarith [ Real.sqrt_pos.2 hy2.2.1, Real.sqrt_pos.2 hy2.2.2.1 ], by rw [ Real.sqrt_inj ] <;> cases lt_or_gt_of_ne hy2.2.2.2 <;> linarith ⟩;
          · grind;
        · linarith [ Real.sqrt_pos.2 hy2.2.2.1 ];
        · exact ⟨ by linarith [ Real.sqrt_pos.2 hy2.2.1, Real.sqrt_pos.2 hy2.2.2.1 ], by rw [ Real.sqrt_inj ] <;> cases lt_or_gt_of_ne hy2.2.2.2 <;> linarith ⟩;
        · grind;
      · linarith [ Real.sqrt_pos.2 hy2.2.2.1 ];
      · exact ⟨ by linarith [ Real.sqrt_pos.2 hy2.2.1, Real.sqrt_pos.2 hy2.2.2.1 ], by rw [ Real.sqrt_inj ] <;> cases lt_or_gt_of_ne hy2.2.2.2 <;> linarith ⟩;
      · grind

/-
The inverse Phi functional for a symmetric quartic polynomial matches the explicit formula.
-/
def invPhi_symmetric_quartic_formula (a c : ℝ) : ℝ :=
  if a < 0 ∧ c > 0 ∧ a^2 > 4 * c then
    (2 * c * (a^2 - 4 * c)) / (-a * (12 * c + a^2))
  else 0

theorem invPhi_eq_invPhi_symmetric_quartic_formula (a c : ℝ)
    (h_discr : a^2 - 4 * c > 0) (h_c : c > 0) (h_a : a < 0) :
    let p := X^4 + C a * X^2 + C c
    p.roots.Nodup → p.Splits (RingHom.id ℝ) →
    invPhi p = invPhi_symmetric_quartic_formula a c := by
      intro p hp hp';
      convert congr_arg _ (Phi_eq_Phi_symmetric_quartic_formula a c h_discr h_c h_a hp hp') using 1;
      all_goals norm_num [ invPhi ];
      rotate_right;
      use fun x => if x = 0 then 0 else 1 / x;
      · have h_card : p.natDegree = 4 := by
          rw [ Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases ha : a = 0 <;> simp +decide [ ha ];
        rw [ Polynomial.splits_iff_card_roots ] at hp' ; aesop;
      · unfold Phi_symmetric_quartic_formula invPhi_symmetric_quartic_formula; aesop;

/-
Defining the auxiliary function $f(k) = \frac{2k(1-4k)}{12k+1}$.
-/
def f_aux (k : ℝ) : ℝ := (2 * k * (1 - 4 * k)) / (12 * k + 1)

/-
The second derivative of the auxiliary function $f(k)$ is $\frac{-64}{(12k+1)^3}$.
-/
lemma f_aux_second_deriv (k : ℝ) (hk : k > -1/12) :
    deriv (deriv f_aux) k = -64 / (12 * k + 1)^3 := by
      -- First, we need to find the first derivative of $f(k)$.
      have h_deriv : ∀ k > -1 / 12, deriv f_aux k = (deriv (fun k => (2 * k - 8 * k^2) / (12 * k + 1))) k := by
        exact fun k hk => by congr; ext; unfold f_aux; ring;
      -- Now, we need to find the second derivative of $f(k)$.
      have h_second_deriv : deriv (deriv f_aux) k = deriv (fun k => (2 - 16 * k) * (12 * k + 1) / (12 * k + 1)^2 - (2 * k - 8 * k^2) * 12 / (12 * k + 1)^2) k := by
        refine' Filter.EventuallyEq.deriv_eq _;
        filter_upwards [ lt_mem_nhds hk ] with x hx using by rw [ h_deriv x hx ] ; norm_num [ mul_comm, show x * 12 + 1 ≠ 0 from by linarith ] ; ring;
      norm_num [ h_second_deriv, mul_comm ];
      norm_num [ show k * 12 + 1 ≠ 0 by linarith ] ; ring;
      grind

/-
The auxiliary function $f(k)$ is concave on the interval $(0, 1/4)$.
-/
lemma f_aux_concave : ConcaveOn ℝ (Set.Ioo 0 (1/4)) f_aux := by
  apply_rules [ concaveOn_of_deriv2_nonpos, convex_Ioo ];
  · exact ContinuousOn.div ( continuousOn_const.mul continuousOn_id |> ContinuousOn.mul <| continuousOn_const.sub ( continuousOn_const.mul continuousOn_id ) ) ( continuousOn_const.mul continuousOn_id |> ContinuousOn.add <| continuousOn_const ) fun x hx => by linarith [ hx.1 ] ;
  · exact DifferentiableOn.div ( DifferentiableOn.mul ( differentiableOn_const _ |> DifferentiableOn.mul <| differentiableOn_id ) <| differentiableOn_const _ |> DifferentiableOn.sub <| differentiableOn_id.const_mul _ ) ( DifferentiableOn.add ( differentiableOn_const _ |> DifferentiableOn.mul <| differentiableOn_id ) <| differentiableOn_const _ ) fun x hx => by norm_num at hx; linarith;
  · refine' DifferentiableOn.congr _ _;
    refine' fun x => ( 2 * ( 1 - 4 * x ) - 8 * x ) / ( 12 * x + 1 ) - ( 2 * x * ( 1 - 4 * x ) ) * 12 / ( 12 * x + 1 ) ^ 2;
    · exact DifferentiableOn.sub ( DifferentiableOn.div ( DifferentiableOn.sub ( DifferentiableOn.mul ( differentiableOn_const _ ) ( DifferentiableOn.sub ( differentiableOn_const _ ) ( differentiableOn_id.const_mul _ ) ) ) ( differentiableOn_id.const_mul _ ) ) ( DifferentiableOn.add ( differentiableOn_id.const_mul _ ) ( differentiableOn_const _ ) ) ( by intro x hx; norm_num at hx; linarith ) ) ( DifferentiableOn.div ( DifferentiableOn.mul ( DifferentiableOn.mul ( differentiableOn_id.const_mul _ ) ( DifferentiableOn.sub ( differentiableOn_const _ ) ( differentiableOn_id.const_mul _ ) ) ) ( differentiableOn_const _ ) ) ( DifferentiableOn.pow ( DifferentiableOn.add ( differentiableOn_id.const_mul _ ) ( differentiableOn_const _ ) ) _ ) ( by intro x hx; norm_num at hx; nlinarith ) );
    · intro x hx; rw [ show f_aux = fun x => ( 2 * x * ( 1 - 4 * x ) ) / ( 12 * x + 1 ) by ext; rfl ] ; norm_num [ mul_assoc, mul_comm, mul_left_comm, show x * 12 + 1 ≠ 0 from by linarith [ Set.mem_Ioo.mp ( interior_subset hx ) ] ] ; ring;
      grind;
  · norm_num +zetaDelta at *;
    exact fun x hx₁ hx₂ => by rw [ f_aux_second_deriv x ( by linarith ) ] ; exact div_nonpos_of_nonpos_of_nonneg ( by norm_num ) ( pow_nonneg ( by linarith ) _ ) ;

/-
The auxiliary function $f(k)$ is increasing on the interval $(0, 1/12]$.
-/
lemma f_aux_increasing (x y : ℝ) (hx : 0 < x) (hy : y ≤ 1/12) (hxy : x ≤ y) :
    f_aux x ≤ f_aux y := by
      unfold f_aux; rw [ div_le_div_iff₀ ] <;> nlinarith [ mul_self_nonneg ( y - x ), mul_nonneg hx.le ( sub_nonneg_of_le hxy ) ] ;

/-
The auxiliary function $f(k)$ is decreasing on the interval $[1/12, 1/4)$.
-/
lemma f_aux_decreasing (x y : ℝ) (hx : 1/12 ≤ x) (hy : y < 1/4) (hxy : x ≤ y) :
    f_aux y ≤ f_aux x := by
      unfold f_aux; rw [ div_le_div_iff₀ ] <;> try nlinarith;
      nlinarith [ mul_le_mul_of_nonneg_left hxy ( sub_nonneg_of_le hx ) ]

/-
Defining the inverse Phi functional for symmetric quartics in terms of parameters $A$ and $c$.
-/
def invPhi_sym_param (A c : ℝ) : ℝ :=
  (2 * c * (A^2 - 4 * c)) / (A * (12 * c + A^2))

/-
The inverse Phi functional can be expressed as $A \cdot f(c/A^2)$.
-/
lemma invPhi_sym_param_eq (A c : ℝ) (hA : A ≠ 0) :
    invPhi_sym_param A c = A * f_aux (c / A^2) := by
      unfold invPhi_sym_param f_aux; ring_nf; simp +decide [ hA, pow_three, mul_assoc, mul_left_comm, div_eq_mul_inv ] ; ring;
      grind

/-
The difference between the combined argument $K$ and the weighted average $k_{avg}$ is proportional to $1/6 - (k+k')$.
-/
lemma invPhi_sym_param_arg_diff (A A' c c' : ℝ) (hA : A > 0) (hA' : A' > 0) :
    let k := c / A^2
    let k' := c' / A'^2
    let K := (c + c' + A * A' / 6) / (A + A')^2
    let k_avg := (A * k + A' * k') / (A + A')
    K - k_avg = (A * A' / (A + A')^2) * (1/6 - (k + k')) := by
      -- Combine and simplify the fractions in the expression.
      field_simp
      ring