/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: da8f6c1f-62d5-4dd3-a243-0db687f737ad

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Auxiliary function f_aux(x) = 2x(1-4x)/(12x+1).
-/
def f_aux (x : ℝ) : ℝ := 2 * x * (1 - 4 * x) / (12 * x + 1)

/-
Definition of the polynomial difference representing the numerator of the Jensen gap inequality.
-/
def poly_diff (t x y : ℝ) : ℝ :=
  let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
  (2 * Z * (1 - 4 * Z)) * (1 + 12 * x) * (1 + 12 * y) -
  (t * (2 * x * (1 - 4 * x)) * (1 + 12 * Z) * (1 + 12 * y) +
   (1 - t) * (2 * y * (1 - 4 * y)) * (1 + 12 * Z) * (1 + 12 * x))

/-
The polynomial P_poly(t, x, y) representing the numerator of the difference f_aux(Z) - (t f_aux(x) + (1-t) f_aux(y)), without the factor of 2 in poly_diff.
-/
def P_poly (t x y : ℝ) : ℝ :=
  let Z := t^2 * x + (1-t)^2 * y + t*(1-t)/6
  Z * (1 - 4 * Z) * (12 * x + 1) * (12 * y + 1) -
  (t * x * (1 - 4 * x) * (12 * Z + 1) * (12 * y + 1) +
   (1 - t) * y * (1 - 4 * y) * (12 * Z + 1) * (12 * x + 1))

/-
Expansion of P_poly_d(t, x, d) as a cubic polynomial in d, with coefficients depending on t and x.
-/
def P_poly_d (t x d : ℝ) : ℝ := P_poly t x (x + d)

def P_poly_d_coeff_0 (t x : ℝ) : ℝ := P_poly t x x

def P_poly_d_coeff_1 (t x : ℝ) : ℝ :=
  let u := (1-t)^2
  let Z0 := t^2 * x + u * x + t*(1-t)/6
  (u * (1 - 4 * Z0) + Z0 * (-4 * u)) * (12 * x + 1)^2 + Z0 * (1 - 4 * Z0) * 12 * (12 * x + 1) -
  (t * x * (1 - 4 * x) * (12 * u * (12 * x + 1) + (12 * Z0 + 1) * 12)) -
  ((1 - t) * (12 * x + 1) * ((1 - 8 * x) * (12 * Z0 + 1) + x * (1 - 4 * x) * 12 * u))

def P_poly_d_coeff_2 (t x : ℝ) : ℝ :=
  let u := (1-t)^2
  let Z0 := t^2 * x + u * x + t*(1-t)/6
  (-4 * u^2) * (12 * x + 1)^2 + u * (1 - 8 * Z0) * 12 * (12 * x + 1) -
  (t * x * (1 - 4 * x) * 144 * u) -
  ((1 - t) * (12 * x + 1) * (-4 * (12 * Z0 + 1) + (1 - 8 * x) * 12 * u))

def P_poly_d_coeff_3 (t x : ℝ) : ℝ :=
  let u := (1-t)^2
  (-4 * u^2) * 12 * (12 * x + 1) -
  0 -
  ((1 - t) * (12 * x + 1) * (-4 * 12 * u))

lemma P_poly_d_expansion (t x d : ℝ) :
    P_poly_d t x d =
    P_poly_d_coeff_0 t x +
    P_poly_d_coeff_1 t x * d +
    P_poly_d_coeff_2 t x * d^2 +
    P_poly_d_coeff_3 t x * d^3 := by
      unfold P_poly_d P_poly_d_coeff_0 P_poly_d_coeff_1 P_poly_d_coeff_2 P_poly_d_coeff_3;
      unfold P_poly; ring;

/-
The coefficient of d^3 in the expansion of P_poly_d is positive for t in (0, 1) and x > 0.
-/
lemma P_poly_d_coeff_3_pos (t x : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) :
    P_poly_d_coeff_3 t x > 0 := by
      unfold P_poly_d_coeff_3;
      nlinarith [ mul_pos ( sub_pos.2 ht1 ) ( mul_pos ( sub_pos.2 ht1 ) ( sub_pos.2 ht ) ), mul_pos ( sub_pos.2 ht1 ) hx, mul_pos ( sub_pos.2 ht ) hx, pow_pos ( sub_pos.2 ht1 ) 3 ] ;

/-
The coefficient of d^2 in the expansion of P_poly_d is positive for t in (0, 1) and x > 0.
-/
lemma P_poly_d_coeff_2_pos (t x : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) :
    P_poly_d_coeff_2 t x > 0 := by
  unfold P_poly_d_coeff_2
  let u := (1-t)^2
  let Z0 := t^2 * x + u * x + t*(1-t)/6
  have hu : u = (1-t)^2 := rfl
  have hZ0 : Z0 = (t^2 + u) * x + t*(1-t)/6 := by
    dsimp [Z0]
    ring
  -- We want to show the expression is positive.
  -- The expression is:
  -- (-4 * u^2) * (12 * x + 1)^2 + u * (1 - 8 * Z0) * 12 * (12 * x + 1) -
  -- (t * x * (1 - 4 * x) * 144 * u) -
  -- ((1 - t) * (12 * x + 1) * (-4 * (12 * Z0 + 1) + (1 - 8 * x) * 12 * u))
  -- This looks complicated. Let's try nlinarith directly first.
  have := mul_pos ht hx;
  nlinarith [ mul_pos this hx, mul_pos this ( sq_pos_of_pos hx ), mul_pos this ( sq_pos_of_pos ( sub_pos.mpr ht1 ) ), mul_pos hx ( sq_pos_of_pos ( sub_pos.mpr ht1 ) ), mul_pos hx ( sq_pos_of_pos ( sub_pos.mpr ht ) ), mul_pos ( sq_pos_of_pos ( sub_pos.mpr ht1 ) ) ( sq_pos_of_pos ( sub_pos.mpr ht ) ) ]

/-
poly_diff is exactly 2 times P_poly.
-/
lemma poly_diff_eq_two_mul_P_poly (t x y : ℝ) :
    poly_diff t x y = 2 * P_poly t x y := by
  unfold poly_diff P_poly
  ring

/-
P_poly(t, x, x) is non-negative for x in (0, 1/4).
-/
lemma P_poly_eq_y_proven (t x : ℝ)
    (ht0 : 0 < t) (ht1 : t < 1)
    (hx0 : 0 < x) (hx1 : x < 1/4) :
    P_poly t x x ≥ 0 := by
      have h_poly_factor : P_poly t x x = (12 * x + 1) * (t * (1 - t) * (1 / 6 - 2 * x)) * ((1 - 12 * x) * ((1 + 4 * x) - (2 * (t * (1 - t)) / 3) * (1 + 12 * x))) := by
        unfold P_poly;
        ring_nf;
      by_cases h_case : x ≤ 1 / 12;
      · exact h_poly_factor.symm ▸ mul_nonneg ( mul_nonneg ( by linarith ) ( by nlinarith [ mul_pos ht0 ( sub_pos.mpr ht1 ) ] ) ) ( mul_nonneg ( by linarith ) ( by nlinarith [ mul_pos ht0 ( sub_pos.mpr ht1 ), sq_nonneg ( t - 1 / 2 ) ] ) );
      · exact h_poly_factor.symm ▸ mul_nonneg_of_nonpos_of_nonpos ( mul_nonpos_of_nonneg_of_nonpos ( by linarith ) ( mul_nonpos_of_nonneg_of_nonpos ( by nlinarith ) ( by linarith ) ) ) ( mul_nonpos_of_nonpos_of_nonneg ( by linarith ) ( by nlinarith [ mul_self_nonneg ( t - 1 / 2 ) ] ) )

/-
poly_diff is non-negative under the substitution x = 1/12 + u, y = 1/12 - v, with u > v and t^2 u < (1-t)^2 v.
-/
lemma poly_diff_case4_subst (t u v : ℝ)
    (ht : 0 < t) (ht_half : t < 1/2)
    (hu : 0 < u) (hu_bound : u < 1/6) -- x < 1/4 => u < 1/6
    (hv : 0 < v) (hv_bound : v < 1/12) -- y > 0 => v < 1/12
    (h_uv : v < u) -- x+y > 1/6
    (h_Z : t^2 * u < (1-t)^2 * v) -- Z < 1/12
    : poly_diff t (1/12 + u) (1/12 - v) ≥ 0 := by
  unfold poly_diff;
  have := mul_pos ht ( sub_pos.mpr h_uv );
  have := mul_pos this ( sub_pos.mpr h_Z );
  nlinarith [ mul_pos ht ( mul_pos hu hv ), mul_pos ht ( mul_pos hu ( sub_pos.mpr h_uv ) ), mul_pos ht ( mul_pos hv ( sub_pos.mpr h_uv ) ), mul_pos hu ( mul_pos hv ( sub_pos.mpr h_uv ) ), mul_pos ht ( mul_pos hu ( sub_pos.mpr h_Z ) ), mul_pos ht ( mul_pos hv ( sub_pos.mpr h_Z ) ), mul_pos hu ( mul_pos hv ( sub_pos.mpr h_Z ) ), mul_pos ht ( mul_pos hu ( sub_pos.mpr ht_half ) ), mul_pos ht ( mul_pos hv ( sub_pos.mpr ht_half ) ), mul_pos hu ( mul_pos hv ( sub_pos.mpr ht_half ) ) ]

/-
Case 4 of the f_aux inequality: x+y > 1/6 and Z < 1/12 implies poly_diff >= 0.
-/
lemma poly_diff_nonneg_case4 (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y > 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 < 1/12) :
    poly_diff t x y ≥ 0 := by
      by_cases hy_le : y ≤ 1 / 12;
      · convert poly_diff_case4_subst t ( x - 1 / 12 ) ( 1 / 12 - y ) ht _ _ _ _ _ _ using 1 <;> try linarith;
        · norm_num;
          exact Or.inl ( by nlinarith );
        · nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ];
        · nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ];
      · -- Since $t > 1/2$, we can apply the symmetry of the problem to swap $x$ and $y$, and $t$ and $1-t$.
        have h_symm : poly_diff t x y = poly_diff (1 - t) y x := by
          unfold poly_diff; ring;
        rw [h_symm];
        convert poly_diff_case4_subst ( 1 - t ) ( y - 1 / 12 ) ( 1 / 12 - x ) _ _ _ _ _ _ using 1 <;> norm_num at * <;> try nlinarith;
        exact ⟨ fun h => fun _ _ => h, fun h => h ( by nlinarith ) ( by nlinarith ) ⟩

/-
The f_aux inequality holds when the sum of arguments is small and the weighted sum is small.
-/
lemma f_aux_ineq_easy_case (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y ≤ 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 ≤ 1/12) :
    f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ t * f_aux x + (1 - t) * f_aux y := by
      -- Since $Z \ge W$, and $f_aux$ is increasing on $(0, 1/12]$, we have $f_aux(Z) \ge f_aux(W)$.
      have h_f_aux_Z_ge_f_aux_W : f_aux (t ^ 2 * x + (1 - t) ^ 2 * y + t * (1 - t) / 6) ≥ f_aux (t * x + (1 - t) * y) := by
        -- Since $Z \ge W$, we have $f_aux(Z) \ge f_aux(W)$.
        have h_f_aux_Z_ge_f_aux_W : t ^ 2 * x + (1 - t) ^ 2 * y + t * (1 - t) / 6 ≥ t * x + (1 - t) * y := by
          nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ];
        -- Since $f_aux$ is increasing on $(0, 1/12]$, we have $f_aux(Z) \ge f_aux(W)$.
        have h_f_aux_inc : StrictMonoOn f_aux (Set.Ioc 0 (1 / 12)) := by
          exact fun x hx y hy hxy => by rw [ f_aux, f_aux ] ; rw [ div_lt_div_iff₀ ] <;> nlinarith only [ hx.1, hx.2, hy.1, hy.2, hxy, mul_pos hx.1 ( sub_pos.2 hxy ) ] ;
        exact h_f_aux_inc.le_iff_le ⟨ by nlinarith, by nlinarith ⟩ ⟨ by nlinarith, by nlinarith ⟩ |>.2 h_f_aux_Z_ge_f_aux_W;
      refine le_trans ?_ h_f_aux_Z_ge_f_aux_W;
      have h_f_aux_W_ge_t_f_aux_x_plus_1_minus_t_f_aux_y : ConcaveOn ℝ (Set.Ioo 0 (1 / 4)) f_aux := by
        apply_rules [ concaveOn_of_deriv2_nonpos, neg_nonneg ] <;> norm_num;
        · exact convex_Ioo _ _;
        · exact ContinuousOn.div ( ContinuousOn.mul ( continuousOn_const.mul continuousOn_id ) ( continuousOn_const.sub ( continuousOn_const.mul continuousOn_id ) ) ) ( ContinuousOn.add ( continuousOn_const.mul continuousOn_id ) continuousOn_const ) fun x hx => by linarith [ hx.1, hx.2 ] ;
        · exact DifferentiableOn.div ( DifferentiableOn.mul ( differentiableOn_id.const_mul _ ) ( differentiableOn_const _ |> DifferentiableOn.sub <| differentiableOn_id.const_mul _ ) ) ( DifferentiableOn.add ( differentiableOn_id.const_mul _ ) ( differentiableOn_const _ ) ) fun x hx => by linarith [ hx.1, hx.2 ] ;
        · -- Let's calculate the first derivative of $f_aux$.
          have h_deriv : ∀ x ∈ Set.Ioo 0 (1 / 4), deriv f_aux x = (2 * (1 - 8 * x) * (12 * x + 1) - 2 * x * (1 - 4 * x) * 12) / (12 * x + 1)^2 := by
            intros x hx; rw [ show f_aux = fun x => 2 * x * ( 1 - 4 * x ) / ( 12 * x + 1 ) from funext fun x => rfl ] ; norm_num [ mul_assoc, mul_comm, mul_left_comm, ne_of_gt ( show 0 < 12 * x + 1 from by linarith [ hx.1 ] ) ] ;
            norm_num [ show x * 12 + 1 ≠ 0 by linarith [ hx.1 ] ] ; ring;
          exact DifferentiableOn.congr ( by exact DifferentiableOn.div ( by exact Differentiable.differentiableOn ( by ring_nf; norm_num ) ) ( by exact Differentiable.differentiableOn ( by ring_nf; norm_num ) ) fun x hx => by nlinarith only [ hx.1, hx.2 ] ) h_deriv;
        · -- Let's calculate the second derivative of $f_aux$.
          have h_deriv2 : ∀ x : ℝ, 0 < x → x < 1 / 4 → deriv (deriv f_aux) x = deriv (fun x => (2 * (1 - 8 * x) * (12 * x + 1) - 2 * x * (1 - 4 * x) * 12) / (12 * x + 1) ^ 2) x := by
            intros x hx hx'; refine' Filter.EventuallyEq.deriv_eq _ ; filter_upwards [ Ioo_mem_nhds hx hx' ] with x hx ; rw [ show deriv f_aux x = ( 2 * ( 1 - 8 * x ) * ( 12 * x + 1 ) - 2 * x * ( 1 - 4 * x ) * 12 ) / ( 12 * x + 1 ) ^ 2 from _ ] ;
            exact HasDerivAt.deriv ( by convert HasDerivAt.div ( HasDerivAt.mul ( HasDerivAt.const_mul 2 ( hasDerivAt_id' x ) ) ( HasDerivAt.const_sub 1 ( HasDerivAt.const_mul 4 ( hasDerivAt_id' x ) ) ) ) ( HasDerivAt.add ( HasDerivAt.const_mul 12 ( hasDerivAt_id' x ) ) ( hasDerivAt_const _ _ ) ) _ using 1 <;> norm_num ; ring ; linarith [ hx.1, hx.2 ] );
          intro x hx hx'; rw [ h_deriv2 x hx hx' ] ; norm_num [ mul_comm ];
          norm_num [ show x * 12 + 1 ≠ 0 by linarith ] ; ring_nf ; norm_num;
          nlinarith [ inv_pos.mpr ( by positivity : 0 < 1 + x * 48 + x ^ 2 * 864 + x ^ 3 * 6912 + x ^ 4 * 20736 ) ];
      exact h_f_aux_W_ge_t_f_aux_x_plus_1_minus_t_f_aux_y.2 ⟨ hx, hx1 ⟩ ⟨ hy, hy1 ⟩ ( by linarith ) ( by linarith ) ( by linarith )

/-
f_aux is concave on (0, infinity).
-/
lemma f_aux_concave : ConcaveOn ℝ (Set.Ioi 0) f_aux := by
  unfold f_aux;
  constructor <;> norm_num;
  · exact convex_Ioi 0;
  · -- By definition of concavity, we need to show that for any $x, y > 0$ and $a, b \geq 0$ with $a + b = 1$, the inequality holds.
    intro x hx y hy a b ha hb hab
    field_simp;
    obtain rfl := eq_sub_of_add_eq hab;
    nlinarith [ mul_nonneg hx.le ( sq_nonneg ( y - x ) ), mul_nonneg hy.le ( sq_nonneg ( x - y ) ), mul_nonneg hx.le ( mul_nonneg hb ( sq_nonneg ( x - y ) ) ), mul_nonneg hy.le ( mul_nonneg hb ( sq_nonneg ( y - x ) ) ), mul_nonneg hx.le ( mul_nonneg ha ( sq_nonneg ( x - y ) ) ), mul_nonneg hy.le ( mul_nonneg ha ( sq_nonneg ( y - x ) ) ) ]

/-
f_aux is increasing on (0, 1/12].
-/
lemma f_aux_increasing (x y : ℝ) (hx : 0 < x) (hy : y ≤ 1/12) (hxy : x ≤ y) : f_aux x ≤ f_aux y := by
  unfold f_aux; rw [ div_le_div_iff₀ ] <;> nlinarith [ mul_self_nonneg ( y - x ), mul_nonneg hx.le ( sub_nonneg_of_le hxy ) ] ;

/-
f_aux is decreasing on [1/12, infinity).
-/
lemma f_aux_decreasing (x y : ℝ) (hx : 1/12 ≤ x) (hy : x ≤ y) : f_aux y ≤ f_aux x := by
  unfold f_aux;
  rw [ div_le_div_iff₀ ] <;> nlinarith [ mul_le_mul_of_nonneg_left hy ( by linarith : 0 ≤ x ) ]

/-
The f_aux inequality holds when the sum of arguments is small and the weighted sum is small.
-/
lemma f_aux_ineq_easy_case_v2 (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y ≤ 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 ≤ 1/12) :
    f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ t * f_aux x + (1 - t) * f_aux y := by
      -- Apply the lemma f_aux_ineq_easy_case with the given conditions.
      apply f_aux_ineq_easy_case t x y ht ht1 hx hx1 hy hy1 hsum hZ

/-
The f_aux inequality holds when the sum of arguments is large and the weighted sum is large.
-/
lemma f_aux_ineq_case2_easy (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y > 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 ≥ 1/12) :
    f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ t * f_aux x + (1 - t) * f_aux y := by
      have := f_aux_concave;
      contrapose! this;
      unfold ConcaveOn at *;
      simp +zetaDelta at *;
      refine' fun _ => ⟨ x, hx, y, hy, t, ht.le, 1 - t, sub_nonneg.mpr ht1.le, _, _ ⟩ <;> norm_num at *;
      refine' lt_of_le_of_lt _ this;
      refine' f_aux_decreasing _ _ _ _;
      · grind;
      · nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ]

/-
The difference function diff(t, x, y) is decreasing in y when y is in the increasing region of f_aux and Z is in the decreasing region.
-/
def diff (t x y : ℝ) : ℝ :=
  let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
  f_aux Z - (t * f_aux x + (1 - t) * f_aux y)

lemma diff_decreasing_y (t x y y' : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hy : 0 < y) (hy' : y' ≤ 1/12) (hyy' : y ≤ y')
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 > 1/12) :
    diff t x y ≥ diff t x y' := by
  unfold diff
  let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
  let Z' := t^2 * x + (1 - t)^2 * y' + t * (1 - t) / 6
  have hZ_Z' : Z ≤ Z' := by
    dsimp [Z, Z']
    nlinarith [sq_nonneg (1-t)]
  have hZ_gt : Z > 1/12 := hZ
  have hZ'_gt : Z' > 1/12 := lt_of_lt_of_le hZ_gt hZ_Z'
  have h_f_aux_dec : f_aux Z' ≤ f_aux Z := by
    apply f_aux_decreasing
    · exact le_of_lt hZ_gt
    · exact hZ_Z'
  have h_f_aux_inc : f_aux y ≤ f_aux y' := by
    apply f_aux_increasing
    · exact hy
    · exact hy'
    · exact hyy'
  linarith [mul_nonneg (sub_nonneg.mpr ht1.le) (sub_nonneg.mpr h_f_aux_inc)]

/-
If x < 1/12 and y < 1/12, then Z < 1/12.
-/
lemma Z_le_1_12_of_x_y_lt_1_12 (t x y : ℝ)
    (ht : 0 ≤ t) (ht1 : t ≤ 1)
    (hx : x < 1/12) (hy : y < 1/12) :
    t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 < 1/12 := by
      by_cases ht_half : t ≤ 1 / 2;
      · by_cases ht_zero : t = 0;
        · subst ht_zero; linarith;
        · nlinarith [ mul_self_pos.mpr ht_zero, mul_le_mul_of_nonneg_left ht_half ht ];
      · nlinarith [ mul_le_mul_of_nonneg_left ht1 ht ]

/-
poly_diff is non-negative on the boundary x+y=1/6, subject to Z > 1/12.
-/
lemma poly_diff_on_boundary (t x : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/6)
    (hZ : let y := 1/6 - x; t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 > 1/12) :
    poly_diff t x (1/6 - x) ≥ 0 := by
      rw [ poly_diff_eq_two_mul_P_poly ];
      unfold P_poly;
      nlinarith [ mul_nonneg ht.le ( sq_nonneg ( t - 1 / 2 ) ), mul_nonneg ht.le ( sq_nonneg ( x - 1 / 12 ) ), mul_nonneg ht.le ( sq_nonneg ( ( 1 - t ) ^ 2 * ( 1 - x * 6 ) + t * ( 1 - t ) + t ^ 2 * x - 1 / 12 ) ) ]

/-
Restricted version of Case 3 where x >= 1/12.
-/
lemma poly_diff_nonneg_case3_restricted (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 1/12 ≤ x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y ≤ 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 > 1/12) :
    poly_diff t x y ≥ 0 := by
      by_contra h_neg;
      -- Since $x \geq 1/12$, we can use the fact that $f_aux$ is decreasing on $[1/12, \infty)$ to bound the expression.
      have h_decreasing : f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ f_aux x := by
        apply_rules [ f_aux_decreasing ];
        · linarith;
        · nlinarith [ mul_le_mul_of_nonneg_left ht.le ( sub_nonneg.mpr ht1.le ) ];
      -- Since $x \geq 1/12$, we can use the fact that $f_aux$ is decreasing on $[1/12, \infty)$ to bound the expression further.
      have h_decreasing_further : f_aux x ≥ t * f_aux x + (1 - t) * f_aux y := by
        have h_decreasing_further : f_aux x ≥ f_aux y := by
          unfold f_aux; ring_nf; norm_num;
          field_simp;
          nlinarith only [ sq_nonneg ( x - 1 / 12 ), sq_nonneg ( y - 1 / 12 ), hx, hy, hsum ];
        nlinarith;
      unfold poly_diff at h_neg;
      unfold f_aux at *;
      field_simp at *;
      rw [ le_div_iff₀ ] at h_decreasing <;> nlinarith

/-
poly_diff is non-negative when x+y <= 1/6 and Z > 1/12 (Case 3).
-/
lemma poly_diff_nonneg_case3_v2 (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y ≤ 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 > 1/12) :
    poly_diff t x y ≥ 0 := by
      have h_poly_diff_nonneg_case3 : ∀ (t x y : ℝ), 0 < t → t < 1 → 0 < x → x < 1 / 4 → 0 < y → y < 1 / 4 → x + y ≤ 1 / 6 → t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 > 1 / 12 → poly_diff t x y ≥ 0 := by
        intros t x y ht ht1 hx hx1 hy hy1 hsum hZ;
        by_cases hx12 : x ≥ 1 / 12;
        · exact?;
        · by_cases hy12 : y ≥ 1 / 12;
          · convert poly_diff_nonneg_case3_restricted ( 1 - t ) y x ( by linarith ) ( by linarith ) ( by linarith ) ( by linarith ) ( by linarith ) ( by linarith ) ( by linarith ) ( by linarith ) using 1 ; unfold poly_diff ; ring;
          · exact False.elim <| hZ.not_le <| by nlinarith [ sq_nonneg ( t - 1 / 2 ) ] ;
      exact h_poly_diff_nonneg_case3 t x y ht ht1 hx hx1 hy hy1 hsum hZ

/-
If poly_diff is non-negative, then the f_aux inequality holds.
-/
lemma f_aux_ineq_of_poly_diff_nonneg_v2 (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (h_poly : poly_diff t x y ≥ 0) :
    let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
    f_aux Z ≥ t * f_aux x + (1 - t) * f_aux y := by
      unfold poly_diff f_aux at *;
      field_simp;
      rw [ le_div_iff₀ ] <;> nlinarith [ mul_pos hx hy, mul_pos hx ( sub_pos.mpr ht1 ), mul_pos hy ( sub_pos.mpr ht1 ) ]

/-
The f_aux inequality holds for all x, y in (0, 1/4) and t in (0, 1).
-/
lemma f_aux_weighted_ineq (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4) :
    f_aux (t^2*x + (1-t)^2*y + t*(1-t)/6) ≥ t * f_aux x + (1-t) * f_aux y := by
  let Z := t^2*x + (1-t)^2*y + t*(1-t)/6
  by_cases hsum : x + y ≤ 1/6
  · by_cases hZ : Z ≤ 1/12
    · exact f_aux_ineq_easy_case_v2 t x y ht ht1 hx hx1 hy hy1 hsum hZ
    · have hZ_gt : Z > 1/12 := by linarith
      have h_poly : poly_diff t x y ≥ 0 := poly_diff_nonneg_case3_v2 t x y ht ht1 hx hx1 hy hy1 hsum hZ_gt
      exact f_aux_ineq_of_poly_diff_nonneg_v2 t x y ht ht1 hx hx1 hy hy1 h_poly
  · have hsum_gt : x + y > 1/6 := by linarith
    by_cases hZ : Z ≥ 1/12
    · exact f_aux_ineq_case2_easy t x y ht ht1 hx hx1 hy hy1 hsum_gt hZ
    · have hZ_lt : Z < 1/12 := by linarith
      have h_poly : poly_diff t x y ≥ 0 := poly_diff_nonneg_case4 t x y ht ht1 hx hx1 hy hy1 hsum_gt hZ_lt
      exact f_aux_ineq_of_poly_diff_nonneg_v2 t x y ht ht1 hx hx1 hy hy1 h_poly

/-
Definitions of boxplus, Phi, invPhi, and is_centered.
-/
open Polynomial BigOperators Finset Classical

def boxplus_coeff (n : ℕ) (p q : ℝ[X]) (k : ℕ) : ℝ :=
  ∑ i ∈ range (k + 1),
    let j := k - i
    (Nat.factorial (n - i) * Nat.factorial (n - j) : ℝ) / (Nat.factorial n * Nat.factorial (n - k) : ℝ) *
    (p.coeff (n - i)) * (q.coeff (n - j))

def boxplus (n : ℕ) (p q : ℝ[X]) : ℝ[X] :=
  Finset.sum (range (n + 1)) (fun k => C (boxplus_coeff n p q k) * X ^ (n - k))

def Phi (p : ℝ[X]) : ℝ :=
  let roots := p.roots.toFinset
  ∑ r_i ∈ roots, (∑ r_j ∈ roots.erase r_i, 1 / (r_i - r_j))^2

def invPhi (p : ℝ[X]) : ℝ :=
  if p.roots.Nodup ∧ p.roots.card > 1 then
    1 / Phi p
  else 0

def is_centered (n : ℕ) (p : ℝ[X]) : Prop :=
  p.Monic ∧ p.natDegree = n ∧ p.coeff (n - 1) = 0

/-
invPhi is invariant under shifts.
-/
lemma invPhi_shift_invariance (p : ℝ[X]) (c : ℝ) :
    invPhi (p.comp (X + C c)) = invPhi p := by
      unfold invPhi;
      unfold Phi;
      rw [ show ( p.comp ( Polynomial.X + Polynomial.C c ) |> Polynomial.roots ) = ( p.roots.map fun x => x - c ) from ?_ ];
      · by_cases h : p.roots.Nodup <;> by_cases h' : p.roots.card > 1 <;> simp +decide [ h, h', Multiset.map_eq_zero ];
        · rw [ if_pos ];
          · rw [ Multiset.toFinset_map ];
            rw [ Finset.sum_image ];
            · congr! 3;
              refine' Finset.sum_bij ( fun x hx => x + c ) _ _ _ _ <;> aesop;
            · exact fun x hx y hy hxy => by simpa using hxy;
          · exact Multiset.Nodup.map ( fun x => by aesop ) h;
        · simp_all +decide [ Multiset.nodup_iff_count_le_one ];
          intro h''; specialize h'' ( Classical.choose h - c ) ; simp_all +decide [ Multiset.count_map ] ;
          contrapose! h''; simp_all +decide [ Multiset.filter_eq ] ;
          exact Classical.choose_spec h;
      · ext x; simp [Polynomial.eval_comp, Polynomial.eval_add, Polynomial.eval_X, Polynomial.eval_C];
        rw [ Multiset.count_map ];
        -- By definition of multiplicity, the multiplicity of $x$ in $p.comp (X + C c)$ is equal to the number of times $x + c$ appears in the roots of $p$.
        have h_mult : Polynomial.rootMultiplicity x (p.comp (Polynomial.X + Polynomial.C c)) = Polynomial.rootMultiplicity (x + c) p := by
          rw [ Polynomial.rootMultiplicity_eq_natTrailingDegree, Polynomial.rootMultiplicity_eq_natTrailingDegree ];
          norm_num [ add_assoc, Polynomial.comp_assoc ];
        rw [ show ( Multiset.filter ( fun a => x = a - c ) p.roots ) = Multiset.filter ( fun a => a = x + c ) p.roots by congr; ext; constructor <;> intro h <;> linarith ] ; rw [ Multiset.filter_eq' ] ; aesop;

/-
Definitions for shifting a polynomial to be centered.
-/
def shift_to_center_amount (n : ℕ) (p : ℝ[X]) : ℝ :=
  - p.coeff (n - 1) / n

def shifted_to_center (n : ℕ) (p : ℝ[X]) : ℝ[X] :=
  p.comp (X + C (shift_to_center_amount n p))

/-
Shifting a polynomial by -p_{n-1}/n makes it centered.
-/
lemma shifted_to_center_is_centered (n : ℕ) (p : ℝ[X])
    (hn : n ≠ 0) (hp_monic : p.Monic) (hp_deg : p.natDegree = n) :
    is_centered n (shifted_to_center n p) := by
  refine' ⟨ _, _, _ ⟩
  · convert hp_monic.comp_X_add_C _ using 1
  · unfold shifted_to_center
    rw [ Polynomial.natDegree_comp, Polynomial.natDegree_X_add_C, hp_deg ] ; aesop
  · have h_shift : shifted_to_center n p = p.comp (X + C (-p.coeff (n - 1) / n)) := by
      rfl
    simp_all +decide [ Polynomial.comp, Polynomial.eval₂_eq_sum_range ]
    rcases n <;> simp_all +decide [ Polynomial.coeff_X_add_C_pow, Finset.sum_range_succ ]
    simp_all +decide [ Finset.sum_range, Nat.choose_eq_zero_of_lt ]
    rw [ div_mul_cancel₀ ] <;> first | positivity | rw [ ← hp_deg, hp_monic.coeff_natDegree ] ; ring