/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: fa70c55f-64f7-41d0-8a89-4501441edd64

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of the auxiliary function f_aux(k) = 2k(1-4k)/(12k+1).
-/
def f_aux (k : ℝ) : ℝ := (2 * k * (1 - 4 * k)) / (12 * k + 1)

/-
The second derivative of f_aux is -64/(12k+1)^3.
-/
lemma f_aux_second_deriv (k : ℝ) (hk : k > -1/12) :
    deriv (deriv f_aux) k = -64 / (12 * k + 1)^3 := by
  -- Let's simplify the expression for the first derivative.
  suffices h_deriv : deriv (deriv f_aux) k = deriv (fun k => (deriv (fun k => 2 * k * (1 - 4 * k)) k * (12 * k + 1) - 2 * k * (1 - 4 * k) * deriv (fun k => 12 * k + 1) k) / (12 * k + 1) ^ 2) k by
    norm_num [ h_deriv, mul_comm ];
    norm_num [ show k * 12 + 1 ≠ 0 by linarith ] ; ring;
    grind;
  refine' Filter.EventuallyEq.deriv_eq _;
  filter_upwards [ lt_mem_nhds hk ] with x hx using by rw [ show f_aux = fun k => ( 2 * k * ( 1 - 4 * k ) ) / ( 12 * k + 1 ) by ext; rfl ] ; norm_num [ mul_comm, show x * 12 + 1 ≠ 0 from by linarith ] ;

/-
f_aux is increasing on (0, 1/12].
-/
lemma f_aux_increasing (x y : ℝ) (hx : 0 < x) (hy : y ≤ 1/12) (hxy : x ≤ y) :
    f_aux x ≤ f_aux y := by
  unfold f_aux;
  rw [ div_le_div_iff₀ ] <;> nlinarith [ mul_le_mul_of_nonneg_left hxy hx.le ]

/-
f_aux is decreasing on [1/12, 1/4).
-/
lemma f_aux_decreasing (x y : ℝ) (hx : 1/12 ≤ x) (hy : y < 1/4) (hxy : x ≤ y) :
    f_aux y ≤ f_aux x := by
  unfold f_aux; rw [ div_le_div_iff₀ ] <;> nlinarith [ sq_nonneg ( y - x ), mul_le_mul_of_nonneg_left hxy <| show ( 0 : ℝ ) ≤ y by linarith, pow_two_nonneg ( y + x - 2 / 6 ) ] ;

/-
Definition of invPhi_sym_param(A, c) for symmetric quartics.
-/
def invPhi_sym_param (A c : ℝ) : ℝ :=
  (2 * c * (A^2 - 4 * c)) / (A * (12 * c + A^2))

/-
Relation between invPhi_sym_param and f_aux.
-/
lemma invPhi_sym_param_eq (A c : ℝ) (hA : A ≠ 0) :
    invPhi_sym_param A c = A * f_aux (c / A^2) := by
  unfold invPhi_sym_param f_aux; ring;
  grind

/-
Difference between combined argument and weighted average for invPhi_sym_param.
-/
lemma invPhi_sym_param_arg_diff (A A' c c' : ℝ) (hA : A > 0) (hA' : A' > 0) :
    let k := c / A^2
    let k' := c' / A'^2
    let K := (c + c' + A * A' / 6) / (A + A')^2
    let k_avg := (A * k + A' * k') / (A + A')
    K - k_avg = (A * A' / (A + A')^2) * (1/6 - (k + k')) := by
  -- Combine and simplify the fractions in the expression.
  field_simp
  ring

/-
f_aux is concave on (0, infinity).
-/
lemma f_aux_concave : ConcaveOn ℝ (Set.Ioi 0) f_aux := by
  apply_rules [ concaveOn_of_deriv2_nonpos, neg_nonneg ];
  · exact convex_Ioi 0;
  · exact ContinuousOn.div ( Continuous.continuousOn ( by continuity ) ) ( Continuous.continuousOn ( by continuity ) ) fun x hx => by linarith [ hx.out ] ;
  · exact DifferentiableOn.div ( DifferentiableOn.mul ( differentiableOn_id.const_mul _ ) ( differentiableOn_id.const_mul _ |> DifferentiableOn.const_sub <| _ ) ) ( DifferentiableOn.add ( differentiableOn_id.const_mul _ ) ( differentiableOn_const _ ) ) fun x hx => by linarith [ Set.mem_Ioi.mp <| interior_subset hx ] ;
  · refine' DifferentiableOn.congr _ _;
    exact fun x => ( 2 * ( 1 - 4 * x ) + 2 * x * ( -4 ) ) / ( 12 * x + 1 ) - ( 2 * x * ( 1 - 4 * x ) ) * 12 / ( 12 * x + 1 ) ^ 2;
    · exact DifferentiableOn.sub ( DifferentiableOn.div ( by exact DifferentiableOn.add ( DifferentiableOn.mul ( differentiableOn_const _ ) ( differentiableOn_const _ |> DifferentiableOn.sub <| differentiableOn_id.const_mul _ ) ) ( DifferentiableOn.mul ( DifferentiableOn.mul ( differentiableOn_const _ ) ( differentiableOn_id ) ) ( differentiableOn_const _ ) ) ) ( by exact DifferentiableOn.add ( DifferentiableOn.mul ( differentiableOn_const _ ) ( differentiableOn_id ) ) ( differentiableOn_const _ ) ) fun x hx => by linarith [ Set.mem_Ioi.mp ( interior_subset hx ) ] ) ( DifferentiableOn.div ( by exact DifferentiableOn.mul ( DifferentiableOn.mul ( DifferentiableOn.mul ( differentiableOn_const _ ) ( differentiableOn_id ) ) ( differentiableOn_const _ |> DifferentiableOn.sub <| differentiableOn_id.const_mul _ ) ) ( differentiableOn_const _ ) ) ( by exact DifferentiableOn.pow ( by exact DifferentiableOn.add ( DifferentiableOn.mul ( differentiableOn_const _ ) ( differentiableOn_id ) ) ( differentiableOn_const _ ) ) _ ) fun x hx => by exact ne_of_gt <| sq_pos_of_pos <| by linarith [ Set.mem_Ioi.mp ( interior_subset hx ) ] );
    · intro x hx; unfold f_aux; norm_num [ mul_comm, show x ≠ 0 from ne_of_gt <| interior_subset hx, show x * 12 + 1 ≠ 0 from by linarith [ Set.mem_Ioi.mp <| interior_subset hx ] ] ; ring;
      grind;
  · -- By definition of $f_aux$, we know that its second derivative is given by $-64 / (12k + 1)^3$.
    have h_second_deriv : ∀ k : ℝ, k > 0 → deriv^[2] f_aux k = -64 / (12 * k + 1)^3 := by
      exact fun k hk => f_aux_second_deriv k <| by linarith;
    exact fun x hx => h_second_deriv x ( interior_subset hx ) ▸ div_nonpos_of_nonpos_of_nonneg ( by norm_num ) ( pow_nonneg ( by linarith [ Set.mem_Ioi.mp ( interior_subset hx ) ] ) _ )

/-
Easy case 1 for f_aux inequality.
-/
lemma f_aux_ineq_easy_case (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y ≤ 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 ≤ 1/12) :
    f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ t * f_aux x + (1 - t) * f_aux y := by
  -- Since $f_aux$ is concave on $(0, \infty)$, we can apply Jensen's inequality.
  have h_jensen : ConcaveOn ℝ (Set.Ioi 0) f_aux := by
    exact?;
  -- Since $Z \leq 1/12$, we have $f_aux(Z) \geq f_aux(tx + (1-t)y)$.
  have h_f_aux_Z_ge_f_aux_txy : f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ f_aux (t * x + (1 - t) * y) := by
    apply_rules [ f_aux_increasing ];
    · nlinarith;
    · nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ];
  exact le_trans ( h_jensen.2 hx hy ( by linarith ) ( by linarith ) ( by linarith ) ) h_f_aux_Z_ge_f_aux_txy

/-
Easy case 2 for f_aux inequality.
-/
lemma f_aux_ineq_case2_easy (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y > 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 ≥ 1/12) :
    f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ t * f_aux x + (1 - t) * f_aux y := by
  -- Since $f_aux$ is decreasing on $[1/12, 1/4)$, we have $f_aux(Z) \geq f_aux(tx + (1-t)y)$.
  have h_decr : f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ f_aux (t * x + (1 - t) * y) := by
    apply_rules [ f_aux_decreasing ] ; nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ] ;
    nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ];
  refine le_trans ?_ h_decr;
  have h_concave : ConcaveOn ℝ (Set.Ioi 0) f_aux := by
    exact?;
  exact h_concave.2 hx hy ( by linarith ) ( by linarith ) ( by linarith )

/-
Definition of poly_diff and its symmetry.
-/
def poly_diff (t x y : ℝ) : ℝ :=
  let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
  (2 * Z * (1 - 4 * Z)) * (1 + 12 * x) * (1 + 12 * y) -
  (t * (2 * x * (1 - 4 * x)) * (1 + 12 * Z) * (1 + 12 * y) +
   (1 - t) * (2 * y * (1 - 4 * y)) * (1 + 12 * Z) * (1 + 12 * x))

lemma poly_diff_symmetry (t x y : ℝ) :
    poly_diff t x y = poly_diff (1 - t) y x := by
  unfold poly_diff; ring;

/-
Definition of diff and its monotonicity in y.
-/
def diff (t x y : ℝ) : ℝ :=
  let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
  f_aux Z - (t * f_aux x + (1 - t) * f_aux y)

lemma diff_decreasing_y (t x y y' : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hy : 0 < y) (hy' : y' ≤ 1/12) (hyy' : y ≤ y')
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 > 1/12) :
    diff t x y ≥ diff t x y' := by
  unfold diff;
  unfold f_aux;
  -- Since $Z$ is increasing with $y$, we have $Z(y) \leq Z(y')$.
  have hZ_le : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 ≤ t^2 * x + (1 - t)^2 * y' + t * (1 - t) / 6 := by
    gcongr;
  -- Since $f_aux$ is decreasing on $[1/12, 1/4)$, we have $f_aux(Z(y)) \geq f_aux(Z(y'))$.
  have h_f_aux_le : (2 * (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) * (1 - 4 * (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6))) / (12 * (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) + 1) ≥ (2 * (t^2 * x + (1 - t)^2 * y' + t * (1 - t) / 6) * (1 - 4 * (t^2 * x + (1 - t)^2 * y' + t * (1 - t) / 6))) / (12 * (t^2 * x + (1 - t)^2 * y' + t * (1 - t) / 6) + 1) := by
    rw [ ge_iff_le, div_le_div_iff₀ ] <;> try linarith;
    nlinarith [ mul_le_mul_of_nonneg_left hZ_le ( sub_nonneg_of_le hZ.le ), mul_le_mul_of_nonneg_left hZ_le ( sub_nonneg_of_le hZ.le ), mul_le_mul_of_nonneg_left hZ_le ( sub_nonneg_of_le hZ.le ), mul_le_mul_of_nonneg_left hZ_le ( sub_nonneg_of_le hZ.le ), mul_le_mul_of_nonneg_left hZ_le ( sub_nonneg_of_le hZ.le ), mul_le_mul_of_nonneg_left hZ_le ( sub_nonneg_of_le hZ.le ), mul_le_mul_of_nonneg_left hZ_le ( sub_nonneg_of_le hZ.le ) ];
  -- Since $f_aux$ is increasing on $(0, 1/12]$, we have $f_aux(y) \leq f_aux(y')$.
  have h_f_aux_inc : (2 * y * (1 - 4 * y)) / (12 * y + 1) ≤ (2 * y' * (1 - 4 * y')) / (12 * y' + 1) := by
    rw [ div_le_div_iff₀ ] <;> nlinarith only [ hy, hy', hyy', mul_le_mul_of_nonneg_left hyy' hy.le ];
  nlinarith [ mul_le_mul_of_nonneg_left hyy' ( sub_nonneg_of_le ht1.le ) ]

/-
poly_diff is non-negative on the boundary x+y=1/6.
-/
lemma poly_diff_on_boundary (t x : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/6)
    (hZ : let y := 1/6 - x; t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 > 1/12) :
    poly_diff t x (1/6 - x) ≥ 0 := by
  unfold poly_diff;
  by_contra h_neg;
  nlinarith only [ mul_pos ht hx, mul_pos ht ( sub_pos.mpr ht1 ), mul_pos hx ( sub_pos.mpr ht1 ), hZ, h_neg, sq_nonneg ( t - 1 / 2 ), sq_nonneg ( x - 1 / 12 ) ]

/-
Relationship between poly_diff and diff.
-/
lemma poly_diff_eq_diff_mul_denoms (t x y : ℝ)
    (hx : 12 * x + 1 ≠ 0) (hy : 12 * y + 1 ≠ 0)
    (hZ_denom : 12 * (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) + 1 ≠ 0) :
    let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
    poly_diff t x y = diff t x y * (12 * Z + 1) * (12 * x + 1) * (12 * y + 1) := by
  -- Let's expand the definition of `diff t x y`.
  simp [diff, f_aux];
  rw [ div_sub' ];
  · field_simp;
    rw [ eq_div_iff ];
    · rw [ div_add_div, mul_div, sub_div', mul_div ];
      · rw [ eq_div_iff ];
        · unfold poly_diff; ring;
        · exact mul_ne_zero ( by contrapose! hx; linarith ) ( by contrapose! hy; linarith );
      · exact mul_ne_zero ( by contrapose! hx; linarith ) ( by contrapose! hy; linarith );
      · rwa [ mul_comm ];
      · contrapose! hy; linarith;
    · cases lt_or_gt_of_ne hZ_denom <;> nlinarith;
  · contrapose! hZ_denom; linarith

/-
Restricted case 3 for poly_diff non-negativity.
-/
lemma poly_diff_nonneg_case3_restricted (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 1/12 ≤ x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y ≤ 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 > 1/12) :
    poly_diff t x y ≥ 0 := by
      -- By combining the results from the previous steps, we conclude that $poly_diff t x y \geq 0$.
      have h_poly_nonneg : poly_diff t x y ≥ (diff t x (1/6 - x)) * (12 * (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) + 1) * (12 * x + 1) * (12 * y + 1) := by
        have h_poly_nonneg : diff t x y ≥ diff t x (1/6 - x) := by
          apply diff_decreasing_y t x y (1 / 6 - x) ht ht1 hy (by linarith) (by linarith) hZ;
        rw [ poly_diff_eq_diff_mul_denoms ] <;> try linarith;
        gcongr;
      refine le_trans ?_ h_poly_nonneg;
      -- Since $poly_diff t x (1/6 - x) \geq 0$ and the denominators are positive, their product is non-negative.
      have h_poly_nonneg : poly_diff t x (1/6 - x) ≥ 0 := by
        apply poly_diff_on_boundary t x ht ht1 (by linarith) (by linarith) (by
        nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ]);
      rw [ poly_diff_eq_diff_mul_denoms ] at h_poly_nonneg <;> try linarith;
      · contrapose! h_poly_nonneg;
        refine' mul_neg_of_neg_of_pos _ _;
        · refine' mul_neg_of_neg_of_pos _ _;
          · refine' mul_neg_of_neg_of_pos _ _;
            · exact lt_of_not_ge fun h => h_poly_nonneg.not_le <| mul_nonneg ( mul_nonneg ( mul_nonneg h <| by linarith ) <| by linarith ) <| by linarith;
            · nlinarith only [ ht, ht1, hx, hx1, hy, hy1, hsum, hZ ];
          · linarith;
        · linarith;
      · nlinarith only [ sq_nonneg ( t - 1 / 2 ), ht, ht1, hx, hx1, hy, hy1, hsum ]

/-
Case 3 for poly_diff non-negativity.
-/
lemma poly_diff_nonneg_case3 (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y ≤ 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 > 1/12) :
    poly_diff t x y ≥ 0 := by
  by_cases hx12 : x ≥ 1 / 12
  · apply poly_diff_nonneg_case3_restricted t x y ht ht1 hx12 hx1 hy hy1 hsum hZ
  · by_cases hy12 : y ≥ 1 / 12
    · rw [poly_diff_symmetry]
      have hsum' : y + x ≤ 1/6 := by linarith
      have hZ' : (1 - t)^2 * y + (1 - (1 - t))^2 * x + (1 - t) * (1 - (1 - t)) / 6 > 1/12 := by
        simp; linarith
      apply poly_diff_nonneg_case3_restricted (1 - t) y x (by linarith) (by linarith) hy12 hy1 hx hx1 hsum' hZ'
    · -- This case (x < 1/12 and y < 1/12) contradicts Z > 1/12
      have hZ_le : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 < 1/12 := by
        -- We need a lemma for this: Z_le_1_12_of_x_y_lt_1_12
        -- Or just prove it inline
        nlinarith [sq_nonneg (t - 1/2)]
      linarith

/-
Z is less than 1/12 if x and y are less than 1/12.
-/
lemma Z_le_1_12_of_x_y_lt_1_12 (t x y : ℝ)
    (ht : 0 ≤ t) (ht1 : t ≤ 1)
    (hx : x < 1/12) (hy : y < 1/12) :
    t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 < 1/12 := by
  by_contra h_contra;
  by_cases ht_eq : t = 0 ∨ t = 1;
  · rcases ht_eq with ( rfl | rfl ) <;> norm_num at h_contra <;> linarith;
  · exact ht_eq <| Classical.or_iff_not_imp_left.2 fun h => mul_left_cancel₀ ( sub_ne_zero_of_ne h ) <| by nlinarith [ mul_self_pos.2 h, mul_self_pos.2 ( sub_ne_zero_of_ne <| mt Or.inr ht_eq ) ] ;

/-
poly_diff non-negative implies f_aux inequality.
-/
lemma f_aux_ineq_of_poly_diff_nonneg (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (h_poly : poly_diff t x y ≥ 0) :
    let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
    f_aux Z ≥ t * f_aux x + (1 - t) * f_aux y := by
  -- By definition of $f_aux$, we know that $f_aux(Z) - (t * f_aux(x) + (1 - t) * f_aux(y)) = \frac{poly\_diff(t, x, y)}{(12Z+1)(12x+1)(12y+1)}$.
  have h_diff : f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) - (t * f_aux x + (1 - t) * f_aux y) = poly_diff t x y / ((12 * (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) + 1) * (12 * x + 1) * (12 * y + 1)) := by
    unfold poly_diff f_aux;
    field_simp;
    rw [ div_sub' ] <;> ring ; nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ), mul_pos hx hy ];
  exact le_of_sub_nonneg ( h_diff.symm ▸ div_nonneg h_poly ( mul_nonneg ( mul_nonneg ( by nlinarith ) ( by nlinarith ) ) ( by nlinarith ) ) )

/-
Structure of Case 4 regions.
-/
lemma case4_structure (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hy : 0 < y)
    (hsum : x + y > 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 < 1/12) :
    (x > 1/12 ∧ y < 1/12 ∧ t < 1/2) ∨ (y > 1/12 ∧ x < 1/12 ∧ t > 1/2) := by
  by_cases hx12 : x > 1 / 12 <;> by_cases hy12 : y > 1 / 12 <;> simp_all +decide [ not_lt ];
  · nlinarith [ sq_nonneg ( t - 1 / 2 ), mul_pos ht ( sub_pos.mpr ht1 ) ];
  · exact Or.inl ⟨ lt_of_le_of_ne hy12 ( by rintro rfl; nlinarith ), by nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ] ⟩;
  · exact Or.inr ⟨ lt_of_le_of_ne hx12 ( by rintro rfl; nlinarith ), by nlinarith [ mul_pos ht ( sub_pos.2 ht1 ) ] ⟩;
  · grind

/-
Restricted case 3 for poly_diff non-negativity (v2).
-/
lemma poly_diff_nonneg_case3_restricted_v2 (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 1/12 ≤ x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y ≤ 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 > 1/12) :
    poly_diff t x y ≥ 0 := by
      exact?

#check poly_diff_nonneg_case3_restricted

#check poly_diff_nonneg_case3

/-
Weighted inequality for f_aux.
-/
lemma f_aux_weighted_ineq (t x y : ℝ)
    (ht0 : 0 ≤ t) (ht1 : t ≤ 1)
    (hx0 : 0 ≤ x) (hx1 : x < 1/4)
    (hy0 : 0 ≤ y) (hy1 : y < 1/4) :
    f_aux (t^2*x + (1-t)^2*y + t*(1-t)/6) ≥ t * f_aux x + (1-t) * f_aux y := by
  let Z := t^2*x + (1-t)^2*y + t*(1-t)/6
  have ht : 0 < t ∨ t = 0 := by
    rcases lt_or_eq_of_le ht0 with h | h
    · left; exact h
    · right; symm; exact h
  have ht_1 : t < 1 ∨ t = 1 := lt_or_eq_of_le ht1
  rcases ht with ht | rfl
  · rcases ht_1 with ht1 | rfl
    · -- t in (0, 1)
      have hx : 0 < x ∨ x = 0 := by
        rcases lt_or_eq_of_le hx0 with h | h
        · left; exact h
        · right; symm; exact h
      have hy : 0 < y ∨ y = 0 := by
        rcases lt_or_eq_of_le hy0 with h | h
        · left; exact h
        · right; symm; exact h
      rcases hx with hx | rfl
      · rcases hy with hy | rfl
        · -- x > 0, y > 0
          by_cases hsum : x + y ≤ 1/6
          · by_cases hZ_le : Z ≤ 1/12
            · -- Case 1
              apply f_aux_ineq_easy_case t x y ht ht1 hx hx1 hy hy1 hsum hZ_le
            · -- Case 3
              have hZ_gt : Z > 1/12 := by linarith
              apply f_aux_ineq_of_poly_diff_nonneg t x y ht ht1 hx hx1 hy hy1
              apply poly_diff_nonneg_case3 t x y ht ht1 hx hx1 hy hy1 hsum hZ_gt
          · have hsum_gt : x + y > 1/6 := by linarith
            by_cases hZ_ge : Z ≥ 1/12
            · -- Case 2
              apply f_aux_ineq_case2_easy t x y ht ht1 hx hx1 hy hy1 hsum_gt hZ_ge
            · -- Case 4
              have hZ_lt : Z < 1/12 := by linarith
              -- This is the missing case
              by_cases hx_le : x ≤ 1 / 12;
              · by_cases hy_le : y ≤ 1 / 12;
                · exact False.elim <| hZ_ge <| by nlinarith only [ sq_nonneg ( t - 1 / 2 ), sq_nonneg ( 1 - t - 1 / 2 ), hx_le, hy_le, hsum_gt, hZ_lt ] ;
                · -- Since $y > 1/12$, we have $f_aux(y) \leq f_aux(1/12)$.
                  have hy_le_1_12 : f_aux y ≤ f_aux (1 / 12) := by
                    exact f_aux_decreasing _ _ ( by linarith ) ( by linarith ) ( by linarith );
                  -- Since $Z < 1/12$, we have $f_aux(Z) \geq t * f_aux(x) + (1 - t) * f_aux(1/12)$.
                  have hZ_ge_t_f_aux_x_plus_1_minus_t_f_aux_1_12 : f_aux Z ≥ t * f_aux x + (1 - t) * f_aux (1 / 12) := by
                    have hZ_ge_t_f_aux_x_plus_1_minus_t_f_aux_1_12 : f_aux (t^2 * x + (1 - t)^2 * (1 / 12) + t * (1 - t) / 6) ≥ t * f_aux x + (1 - t) * f_aux (1 / 12) := by
                      apply_rules [ f_aux_ineq_easy_case ];
                      · norm_num;
                      · norm_num;
                      · grind;
                      · nlinarith only [ sq_nonneg ( t - 1 / 2 ), ht, ht1, hx, hx_le, hy, hy_le ];
                    refine le_trans hZ_ge_t_f_aux_x_plus_1_minus_t_f_aux_1_12 ?_;
                    apply_rules [ f_aux_increasing ];
                    · nlinarith only [ ht, ht1, hx, hy, mul_pos ht ( sub_pos.mpr ht1 ) ];
                    · linarith;
                    · norm_num +zetaDelta at *;
                      exact mul_le_mul_of_nonneg_left hy_le.le ( sq_nonneg _ );
                  exact le_trans ( add_le_add_left ( mul_le_mul_of_nonneg_left hy_le_1_12 ( by linarith ) ) _ ) hZ_ge_t_f_aux_x_plus_1_minus_t_f_aux_1_12;
              · by_cases hy_le : y ≤ 1 / 12;
                · have h_case4 : f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ f_aux ((1 - t)^2 * y + t * (1 - t) / 6 + t^2 * (1 / 12)) := by
                    apply_rules [ f_aux_increasing ];
                    · nlinarith only [ ht, ht1, hy, hy_le ];
                    · exact le_of_lt hZ_lt;
                    · nlinarith only [ hx_le, hy_le, ht, ht1 ];
                  have h_case4 : f_aux ((1 - t)^2 * y + t * (1 - t) / 6 + t^2 * (1 / 12)) ≥ t * f_aux (1 / 12) + (1 - t) * f_aux y := by
                    convert f_aux_ineq_easy_case t ( 1 / 12 ) y ht ht1 ( by norm_num ) ( by norm_num ) hy ( by linarith ) _ _ using 1 <;> norm_num;
                    · ring;
                    · grind;
                    · nlinarith only [ ht, ht1, hy_le, hZ_lt ];
                  have h_case4 : f_aux x ≤ f_aux (1 / 12) := by
                    apply_rules [ f_aux_decreasing ] ; norm_num;
                    grind;
                  nlinarith;
                · simp +zetaDelta at *;
                  nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ), mul_pos ht ( sub_pos.mpr hx_le ), mul_pos ht ( sub_pos.mpr hy_le ), mul_pos ( sub_pos.mpr ht1 ) ( sub_pos.mpr hx_le ), mul_pos ( sub_pos.mpr ht1 ) ( sub_pos.mpr hy_le ), mul_pos ( sub_pos.mpr hx_le ) ( sub_pos.mpr hy_le ) ]
        · -- y = 0
          unfold f_aux;
          norm_num +zetaDelta at *;
          rw [ mul_div, div_le_div_iff₀ ] <;> try nlinarith;
          -- Since $t \in (0, 1)$, we have $t^2 \leq t$. Therefore, $t^2 * x \leq t * x$.
          have h_t_sq_le_t : t^2 * x ≤ t * x := by
            exact mul_le_mul_of_nonneg_right ( pow_le_of_le_one ht.le ht1.le ( by norm_num ) ) hx0;
          nlinarith [ mul_le_mul_of_nonneg_left h_t_sq_le_t hx.le, mul_le_mul_of_nonneg_left h_t_sq_le_t ( sq_nonneg ( t - 1 / 2 ) ), mul_le_mul_of_nonneg_left h_t_sq_le_t ( sq_nonneg ( x - 1 / 12 ) ), mul_le_mul_of_nonneg_left h_t_sq_le_t ( sq_nonneg ( t * x - 1 / 12 ) ) ]
      · -- x = 0
        cases hy <;> simp_all +decide [ f_aux ];
        · rw [ mul_div, div_le_div_iff₀ ] <;> try nlinarith;
          -- After dividing both sides by $(1-t)$, we can simplify the inequality.
          have h_simplified : 2 * y * (1 - 4 * y) * (12 * ((1 - t) ^ 2 * y + t * (1 - t) / 6) + 1) ≤ 2 * ((1 - t) * y + t / 6) * (1 - 4 * ((1 - t) ^ 2 * y + t * (1 - t) / 6)) * (12 * y + 1) := by
            by_contra h_contra;
            have := mul_pos ht ( mul_pos ‹0 < y› ( sub_pos.mpr ht1 ) );
            nlinarith only [ this, h_contra, ht, ht1, hy0, hy1, mul_nonneg ht0 hy0, mul_nonneg ht0 ( sq_nonneg ( t - 1 / 2 ) ), mul_nonneg hy0 ( sq_nonneg ( t - 1 / 2 ) ), mul_nonneg ht0 ( sq_nonneg ( y - 1 / 12 ) ), mul_nonneg hy0 ( sq_nonneg ( y - 1 / 12 ) ) ];
          nlinarith;
        · exact div_nonneg ( mul_nonneg ( mul_nonneg zero_le_two ( by nlinarith ) ) ( by nlinarith ) ) ( by nlinarith )
    · -- t = 1
      norm_num +zetaDelta at *
  · -- t = 0
    -- Since $0^2 * x + (1 - 0)^2 * y + 0 * (1 - 0) / 6 = y$, we have $f_aux y \geq 0 * f_aux x + (1 - 0) * f_aux y$ simplifies to $f_aux y \geq f_aux y$, which is trivially true.
    simp [f_aux]

/-
Weighted inequality for f_aux (v2).
-/
lemma f_aux_weighted_ineq_v2 (t x y : ℝ)
    (ht0 : 0 ≤ t) (ht1 : t ≤ 1)
    (hx0 : 0 ≤ x) (hx1 : x < 1/4)
    (hy0 : 0 ≤ y) (hy1 : y < 1/4) :
    f_aux (t^2*x + (1-t)^2*y + t*(1-t)/6) ≥ t * f_aux x + (1-t) * f_aux y := by
  let Z := t^2*x + (1-t)^2*y + t*(1-t)/6
  have ht : 0 < t ∨ t = 0 := by
    rcases lt_or_eq_of_le ht0 with h | h
    · left; exact h
    · right; symm; exact h
  have ht_1 : t < 1 ∨ t = 1 := lt_or_eq_of_le ht1
  rcases ht with ht | rfl
  · rcases ht_1 with ht1 | rfl
    · -- t in (0, 1)
      have hx : 0 < x ∨ x = 0 := by
        rcases lt_or_eq_of_le hx0 with h | h
        · left; exact h
        · right; symm; exact h
      have hy : 0 < y ∨ y = 0 := by
        rcases lt_or_eq_of_le hy0 with h | h
        · left; exact h
        · right; symm; exact h
      rcases hx with hx | rfl
      · rcases hy with hy | rfl
        · -- x > 0, y > 0
          by_cases hsum : x + y ≤ 1/6
          · by_cases hZ_le : Z ≤ 1/12
            · -- Case 1
              apply f_aux_ineq_easy_case t x y ht ht1 hx hx1 hy hy1 hsum hZ_le
            · -- Case 3
              have hZ_gt : Z > 1/12 := by linarith
              apply f_aux_ineq_of_poly_diff_nonneg t x y ht ht1 hx hx1 hy hy1
              apply poly_diff_nonneg_case3 t x y ht ht1 hx hx1 hy hy1 hsum hZ_gt
          · have hsum_gt : x + y > 1/6 := by linarith
            by_cases hZ_ge : Z ≥ 1/12
            · -- Case 2
              apply f_aux_ineq_case2_easy t x y ht ht1 hx hx1 hy hy1 hsum_gt hZ_ge
            · -- Case 4
              have hZ_lt : Z < 1/12 := by linarith
              exact?
        · -- y = 0
          convert f_aux_weighted_ineq t x 0 _ _ _ _ _ _ using 1 <;> norm_num [ * ]
      · -- x = 0
        convert f_aux_weighted_ineq t 0 y _ _ _ _ _ _ using 1 <;> norm_num [ * ]
    · -- t = 1
      simp [Z]
  · -- t = 0
    simp [Z]

#check f_aux_weighted_ineq

#check f_aux_weighted_ineq

/-
Superadditivity of invPhi for symmetric quartics.
-/
lemma invPhi_sym_quartic_superadditive (A A' c c' : ℝ)
    (hA : A > 0) (hA' : A' > 0)
    (hc : 0 < c) (hc_bound : c < A^2 / 4)
    (hc' : 0 < c') (hc'_bound : c' < A'^2 / 4) :
    invPhi_sym_param (A + A') (c + c' + A * A' / 6) ≥ invPhi_sym_param A c + invPhi_sym_param A' c' := by
      have h_apply_f_aux_ineq : f_aux ((c + c' + A * A' / 6) / (A + A')^2) ≥ (A / (A + A')) * f_aux (c / A^2) + (A' / (A + A')) * f_aux (c' / A'^2) := by
        convert f_aux_weighted_ineq_v2 ( A / ( A + A' ) ) ( c / A ^ 2 ) ( c' / A' ^ 2 ) _ _ _ _ _ _ using 1 <;> try positivity;
        · field_simp;
          exact congr_arg _ ( by rw [ div_eq_div_iff ] <;> ring <;> positivity );
        · rw [ one_sub_div ] <;> ring ; positivity;
        · rw [ div_le_iff₀ ] <;> linarith;
        · rw [ div_lt_iff₀ ] <;> nlinarith;
        · rw [ div_lt_iff₀ ] <;> nlinarith;
      rw [ invPhi_sym_param_eq, invPhi_sym_param_eq, invPhi_sym_param_eq ] <;> try positivity;
      rw [ div_mul_eq_mul_div, div_mul_eq_mul_div, ← add_div, ge_iff_le, div_le_iff₀ ] at * <;> first | positivity | linarith;

/-
Definitions of boxplus, Phi, invPhi, and is_centered.
-/
open Polynomial BigOperators Finset Classical

def boxplus_coeff (n : ℕ) (p q : ℝ[X]) (k : ℕ) : ℝ :=
  ∑ i ∈ range (k + 1),
    let j := k - i
    (Nat.factorial (n - i) * Nat.factorial (n - j) : ℝ) / (Nat.factorial n * Nat.factorial (n - k) : ℝ) *
    (p.coeff (n - i)) * (q.coeff (n - j))

def boxplus (n : ℕ) (p q : ℝ[X]) : ℝ[X] :=
  Finset.sum (range (n + 1)) (fun k => C (boxplus_coeff n p q k) * X ^ (n - k))

def Phi (p : ℝ[X]) : ℝ :=
  let roots := p.roots.toFinset
  ∑ r_i ∈ roots, (∑ r_j ∈ roots.erase r_i, 1 / (r_i - r_j))^2

def invPhi (p : ℝ[X]) : ℝ :=
  if p.roots.Nodup ∧ p.roots.card > 1 then
    1 / Phi p
  else 0

def is_centered (n : ℕ) (p : ℝ[X]) : Prop :=
  p.Monic ∧ p.natDegree = n ∧ p.coeff (n - 1) = 0

/-
Amount to shift a polynomial to center it.
-/
def shift_to_center_amount (n : ℕ) (p : ℝ[X]) : ℝ :=
  - p.coeff (n - 1) / n

/-
Commutativity of boxplus.
-/
lemma boxplus_comm (n : ℕ) (p q : ℝ[X]) :
    boxplus n p q = boxplus n q p := by
  simp [boxplus, boxplus_coeff];
  refine' Finset.sum_congr rfl fun x hx => _;
  rw [ ← Finset.sum_flip ];
  refine' congr_arg₂ _ ( Finset.sum_congr rfl fun i hi => _ ) rfl;
  rw [ Nat.sub_sub_self ( Finset.mem_range_succ_iff.mp hi ) ] ; ring

/-
Polynomial shifted to be centered.
-/
def shifted_to_center (n : ℕ) (p : ℝ[X]) : ℝ[X] :=
  p.comp (X + C (shift_to_center_amount n p))

/-
Finite Free Stam Inequality for centered polynomials of degree 2.
-/
lemma finite_free_stam_inequality_centered_n2 (p q : ℝ[X])
    (hp : is_centered 2 p) (hq : is_centered 2 q)
    (hp_splits : p.Splits (RingHom.id ℝ)) (hp_nodup : p.roots.Nodup)
    (hq_splits : q.Splits (RingHom.id ℝ)) (hq_nodup : q.roots.Nodup)
    (hpq_splits : (boxplus 2 p q).Splits (RingHom.id ℝ)) (hpq_nodup : (boxplus 2 p q).roots.Nodup) :
    invPhi (boxplus 2 p q) ≥ invPhi p + invPhi q := by
  unfold is_centered at *;
  -- Let's denote the roots of $p$ and $q$ by $r_1, r_2$ and $s_1, s_2$ respectively.
  obtain ⟨r1, r2, hr⟩ : ∃ r1 r2 : ℝ, p = Polynomial.C 1 * (Polynomial.X - Polynomial.C r1) * (Polynomial.X - Polynomial.C r2) := by
    rw [ Polynomial.splits_iff_card_roots ] at hp_splits;
    obtain ⟨r1, r2, hr⟩ : ∃ r1 r2 : ℝ, p.roots = {r1, r2} := by
      exact Multiset.card_eq_two.mp ( by aesop );
    use r1, r2; rw [ ← Polynomial.prod_multiset_X_sub_C_of_monic_of_roots_card_eq hp.1 ] <;> aesop;
  obtain ⟨s1, s2, hs⟩ : ∃ s1 s2 : ℝ, q = Polynomial.C 1 * (Polynomial.X - Polynomial.C s1) * (Polynomial.X - Polynomial.C s2) := by
    -- Since $q$ is a monic polynomial of degree 2 with no $x$ term, it can be written as $q(x) = x^2 + c$ for some constant $c$.
    obtain ⟨c, hc⟩ : ∃ c : ℝ, q = Polynomial.X^2 + Polynomial.C c := by
      rw [ Polynomial.as_sum_range_C_mul_X_pow q ] ; norm_num [ Finset.sum_range_succ', hq ] ;
      have := hq.1.coeff_natDegree; aesop;
    by_cases h : c ≤ 0 <;> simp_all +decide [ Polynomial.splits_iff_card_roots ];
    · exact ⟨ Real.sqrt ( -c ), -Real.sqrt ( -c ), Polynomial.funext fun x => by norm_num; linarith [ Real.mul_self_sqrt ( show 0 ≤ -c by linarith ) ] ⟩;
    · exact absurd hq_splits ( by rw [ Multiset.card_eq_zero.mpr <| by exact Multiset.eq_zero_of_forall_notMem fun x hx => by norm_num at hx; nlinarith ] ; norm_num );
  unfold invPhi; simp_all +decide [ sub_eq_iff_eq_add ] ;
  unfold boxplus; norm_num [ Polynomial.coeff_one, Polynomial.coeff_X, mul_assoc, sub_mul, Polynomial.natDegree_mul' ] at *;
  norm_num [ Finset.sum_range_succ', boxplus_coeff ];
  norm_num [ Polynomial.coeff_X ] at *;
  rw [ show r1 = -r2 by linarith, show s1 = -s2 by linarith ] ; ring_nf ; norm_num;
  unfold Phi; norm_num [ Polynomial.natDegree_add_eq_left_of_natDegree_lt, Polynomial.natDegree_sub_eq_left_of_natDegree_lt ] ;
  rw [ show ( Polynomial.X ^ 2 + - ( Polynomial.C r2 * Polynomial.C r2 ) ) = ( Polynomial.X - Polynomial.C r2 ) * ( Polynomial.X + Polynomial.C r2 ) by simpa using by ring, show ( Polynomial.X ^ 2 + - ( Polynomial.C s2 * Polynomial.C s2 ) ) = ( Polynomial.X - Polynomial.C s2 ) * ( Polynomial.X + Polynomial.C s2 ) by simpa using by ring, Polynomial.roots_mul, Polynomial.roots_mul ] <;> norm_num;
  · by_cases hr : r2 = 0 <;> by_cases hs : s2 = 0 <;> simp_all +decide [ Finset.sum_pair, sub_eq_iff_eq_add ];
    · positivity;
    · norm_num [ ← sq, hs ] at *;
      norm_num [ two_smul ] at hp_nodup;
    · norm_num [ ← sq, Polynomial.roots_mul, Polynomial.X_sub_C_ne_zero, Polynomial.X_add_C_ne_zero ] at *;
      norm_num [ two_smul ] at hq_nodup;
    · rw [ show ( Polynomial.X - Polynomial.C r2 ) * ( Polynomial.X + Polynomial.C r2 ) + - ( Polynomial.C s2 * Polynomial.C s2 ) = ( Polynomial.X - Polynomial.C ( Real.sqrt ( r2^2 + s2^2 ) ) ) * ( Polynomial.X - Polynomial.C ( -Real.sqrt ( r2^2 + s2^2 ) ) ) by exact Polynomial.funext fun x => by norm_num; linarith [ Real.mul_self_sqrt ( show 0 ≤ r2^2 + s2^2 by positivity ) ] ] ; erw [ Polynomial.roots_mul <| by exact mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ] ; norm_num;
      rw [ Finset.sum_pair, Finset.sum_pair, Finset.sum_pair ] <;> norm_num [ hr, hs, hp.2.2.symm, hq.2.2.symm ];
      · rw [ Finset.sum_pair, Finset.sum_pair, Finset.sum_pair ] <;> norm_num [ hr, hs ];
        · rw [ Finset.sum_pair, Finset.sum_pair ] <;> norm_num [ hr, hs ];
          · rw [ Finset.sum_pair ] <;> norm_num <;> ring <;> norm_num [ hr, hs ];
            · rw [ Real.sq_sqrt ] <;> nlinarith;
            · linarith [ Real.sqrt_pos.mpr ( show 0 < r2 ^ 2 + s2 ^ 2 by positivity ) ];
          · linarith [ Real.sqrt_pos.mpr ( show 0 < r2 ^ 2 + s2 ^ 2 by positivity ) ];
          · linarith [ Real.sqrt_pos.mpr ( show 0 < r2 ^ 2 + s2 ^ 2 by positivity ) ];
        · cases lt_or_gt_of_ne hs <;> linarith;
        · cases lt_or_gt_of_ne hs <;> linarith;
        · cases lt_or_gt_of_ne hs <;> linarith;
      · contrapose! hr; linarith;
      · contrapose! hr; linarith;
      · contrapose! hr; linarith;
  · exact ⟨ Polynomial.X_sub_C_ne_zero _, Polynomial.X_add_C_ne_zero _ ⟩;
  · exact ⟨ Polynomial.X_sub_C_ne_zero _, Polynomial.X_add_C_ne_zero _ ⟩

/-
invPhi is translation invariant.
-/
lemma invPhi_comp_add_C (p : ℝ[X]) (c : ℝ) :
  invPhi (p.comp (X + C c)) = invPhi p := by
  unfold invPhi;
  unfold Phi;
  rw [ show ( p.comp ( Polynomial.X + Polynomial.C c ) |> Polynomial.roots ) = p.roots.map ( fun x => x - c ) from ?_ ];
  · by_cases h : p.roots.Nodup <;> by_cases h' : p.roots.card > 1 <;> simp +decide [ h, h', sub_eq_iff_eq_add ];
    · rw [ if_pos ];
      · simp +decide [ Finset.sum_map, Finset.sum_erase ];
        rw [ Multiset.toFinset_map ];
        rw [ Finset.sum_image ];
        · exact Finset.sum_congr rfl fun x hx => by rw [ Finset.sum_image ( by aesop ) ] ; exact congr_arg ( · ^ 2 ) ( Finset.sum_congr rfl fun y hy => by ring ) ;
        · exact fun x hx y hy hxy => by simpa using hxy;
      · exact Multiset.Nodup.map ( fun x => by aesop ) h;
    · rw [ Multiset.nodup_iff_count_le_one ] at *;
      simp_all +decide [ Multiset.count_map ];
      obtain ⟨ x, hx ⟩ := h; specialize hx; simp_all +decide [ eq_sub_iff_add_eq ] ;
      intro h; specialize h ( x - c ) ; simp_all +decide [ Multiset.filter_eq ] ;
      grind;
  · ext x;
    -- The multiplicity of $x$ in the roots of $p.comp (X + C c)$ is equal to the multiplicity of $x + c$ in the roots of $p$.
    have h_mult : Polynomial.rootMultiplicity x (p.comp (Polynomial.X + Polynomial.C c)) = Polynomial.rootMultiplicity (x + c) p := by
      rw [ Polynomial.rootMultiplicity_eq_natTrailingDegree, Polynomial.rootMultiplicity_eq_natTrailingDegree ];
      norm_num [ add_assoc, Polynomial.comp_assoc ];
    rw [ Multiset.count_map ];
    rw [ show ( Multiset.filter ( fun a => x = a - c ) p.roots ) = Multiset.filter ( fun a => a = x + c ) p.roots by congr; ext; constructor <;> intro <;> linarith ] ; rw [ Multiset.filter_eq' ] ; aesop

/-
Shifting to center makes a polynomial centered.
-/
lemma shifted_to_center_is_centered (n : ℕ) (p : ℝ[X])
    (hn : n ≠ 0) (hp_monic : p.Monic) (hp_deg : p.natDegree = n) :
    is_centered n (shifted_to_center n p) := by
  constructor;
  · unfold shifted_to_center;
    rw [ Polynomial.Monic, Polynomial.leadingCoeff_comp ] <;> aesop;
  · -- The coefficient of $X^{n-1}$ in $p.comp (X + C c)$ is $p.coeff (n-1) + n*c$. Setting $c = -p.coeff (n-1)/n$ makes this coefficient zero.
    have h_coeff : Polynomial.coeff (p.comp (Polynomial.X + Polynomial.C (shift_to_center_amount n p))) (n - 1) = 0 := by
      rw [ Polynomial.comp, Polynomial.eval₂_eq_sum_range ];
      norm_num [ Polynomial.coeff_X_add_C_pow, Finset.sum_range_succ, hp_deg ];
      rw [ Finset.sum_eq_single ( n - 1 ) ] <;> norm_num;
      · rcases n with ( _ | _ | n ) <;> simp_all +decide [ Nat.choose, shift_to_center_amount ];
        · have := hp_monic.coeff_natDegree; aesop;
        · field_simp;
          have := hp_monic.coeff_natDegree; aesop;
      · exact fun k hk₁ hk₂ => Or.inr <| Or.inr <| Nat.choose_eq_zero_of_lt <| lt_of_le_of_ne ( Nat.le_sub_one_of_lt hk₁ ) hk₂;
      · aesop;
    erw [ Polynomial.natDegree_comp, Polynomial.natDegree_X_add_C ] ; aesop

/-
Boxplus of monomials.
-/
lemma boxplus_monomials (n u v : ℕ) (hu : u ≤ n) (hv : v ≤ n) :
  boxplus n (X^u) (X^v) =
  if u + v < n then 0
  else C ((Nat.factorial u * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial (u + v - n))) * X^(u + v - n) := by
  split_ifs with h;
  · -- By definition of boxplus, if $u + v < n$, then for any $k$, either $u < n - k$ or $v < k$, making the coefficient zero.
    have h_coeff_zero : ∀ k ∈ Finset.range (n + 1), (boxplus_coeff n (Polynomial.X ^ u) (Polynomial.X ^ v) k) = 0 := by
      unfold boxplus_coeff;
      intro k hk; rw [ Finset.sum_eq_zero ] ; intros i hi ; by_cases hi1 : n - i = u <;> by_cases hi2 : n - ( k - i ) = v <;> simp_all +decide [ Polynomial.coeff_X_pow ] ;
      omega;
    exact Finset.sum_eq_zero fun k hk => by aesop;
  · unfold boxplus;
    rw [ Finset.sum_eq_single ( n - ( u + v - n ) ) ] <;> norm_num [ Polynomial.coeff_X_pow ];
    · unfold boxplus_coeff;
      rw [ Finset.sum_eq_single ( n - u ) ] <;> norm_num [ Polynomial.coeff_X_pow ];
      · rw [ if_pos, if_pos ];
        · rw [ Nat.sub_sub_self ( by linarith ) ] ; ring;
          rw [ show n - ( n - ( u + v - n ) ) = u + v - n by omega ] ; rw [ show n - ( n - ( u + v - n ) - ( n - u ) ) = v by omega ] ; ring;
        · rw [ Nat.sub_sub_self hu ];
        · grind;
      · intros; omega;
      · intros; omega;
    · unfold boxplus_coeff;
      intro b hb hb'; rw [ Finset.sum_eq_zero ] ; intros ; simp_all +decide [ Polynomial.coeff_X_pow ] ;
      grind;
    · exact fun h' => absurd h' ( by omega )

/-
Translation covariance of boxplus (left).
-/
lemma boxplus_comp_add_C_left (n : ℕ) (p q : ℝ[X]) (c : ℝ)
    (hp : p.natDegree = n) (hq : q.natDegree = n) :
    boxplus n (p.comp (X + C c)) q = (boxplus n p q).comp (X + C c) := by
      refine' Polynomial.funext _;
      intro r;
      -- We'll use the fact that $p(x+c)$ has coefficients given by the binomial theorem.
      have h_coeff : ∀ i ≤ n, (p.comp (.X + (.C c))).coeff (n - i) = ∑ j ∈ Finset.range (i + 1), Nat.choose (n - j) (n - i) * c ^ (i - j) * p.coeff (n - j) := by
        intro i hi
        have h_coeff : (p.comp (.X + (.C c))).coeff (n - i) = ∑ j ∈ Finset.range (n + 1), p.coeff j * Nat.choose j (n - i) * c ^ (j - (n - i)) := by
          rw [ Polynomial.comp, Polynomial.eval₂_eq_sum_range ];
          norm_num [ Polynomial.coeff_X_add_C_pow ];
          simp +decide [ mul_assoc, mul_comm, mul_left_comm, hp ];
        rw [ h_coeff, ← Finset.sum_flip ];
        rw [ ← Finset.sum_subset ( Finset.range_mono ( Nat.succ_le_succ hi ) ) ];
        · refine' Finset.sum_congr rfl fun x hx => _;
          grind;
        · simp +zetaDelta at *;
          exact fun x hx₁ hx₂ => Or.inl <| Or.inr <| Nat.choose_eq_zero_of_lt <| by omega;
      -- Substitute the expression for the coefficients of $p(x+c)$ into the definition of $boxplus$.
      have h_boxplus_subst : ∀ k ≤ n, boxplus_coeff n (p.comp (.X + (.C c))) q k = ∑ j ∈ Finset.range (k + 1), boxplus_coeff n p q j * Nat.choose (n - j) (n - k) * c^(k - j) := by
        unfold boxplus_coeff;
        intro k hk; rw [ Finset.sum_congr rfl fun i hi => by rw [ h_coeff i ( by linarith [ Finset.mem_range.mp hi ] ) ] ] ; simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Finset.sum_mul ] ;
        rw [ Finset.sum_sigma', Finset.sum_sigma' ];
        refine' Finset.sum_bij ( fun x hx => ⟨ k - x.1 + x.2, x.2 ⟩ ) _ _ _ _ <;> simp_all +decide [ Nat.choose_succ_succ, add_comm ];
        · exact fun a ha₁ ha₂ => ⟨ by omega, by omega ⟩;
        · grind;
        · exact fun b hb₁ hb₂ => ⟨ k - ( b.fst - b.snd ), b.snd, ⟨ by omega, by omega ⟩, by ext <;> norm_num ; omega ⟩;
        · intro a ha₁ ha₂; rw [ show a.fst - a.snd = k - ( a.snd + ( k - a.fst ) ) by omega ] ; ring;
          rw [ Nat.cast_choose, Nat.cast_choose ] <;> try omega;
          field_simp;
          rw [ show n - ( a.snd + ( k - a.fst ) ) - ( n - k ) = n - a.snd - ( n - a.fst ) by omega ] ; ring;
      -- By Fubini's theorem, we can interchange the order of summation.
      have h_fubini : ∑ k ∈ Finset.range (n + 1), (∑ j ∈ Finset.range (k + 1), boxplus_coeff n p q j * Nat.choose (n - j) (n - k) * c^(k - j)) * (r^(n - k)) = ∑ j ∈ Finset.range (n + 1), boxplus_coeff n p q j * (∑ k ∈ Finset.Ico j (n + 1), Nat.choose (n - j) (n - k) * c^(k - j) * r^(n - k)) := by
        simp +decide only [mul_assoc, sum_mul, Finset.mul_sum _ _ _];
        rw [ Finset.range_eq_Ico, Finset.sum_Ico_Ico_comm ];
      -- Let's simplify the inner sum $\sum_{k=j}^{n} \binom{n-j}{n-k} c^{k-j} r^{n-k}$.
      have h_inner_sum : ∀ j ≤ n, ∑ k ∈ Finset.Ico j (n + 1), Nat.choose (n - j) (n - k) * c^(k - j) * r^(n - k) = (r + c)^(n - j) := by
        intro j hj; rw [ add_pow ] ; simp +decide [ mul_assoc, mul_comm, mul_left_comm, Finset.sum_Ico_eq_sum_range ] ;
        rw [ ← Finset.sum_flip ];
        simp +decide [ Nat.sub_sub, add_comm, tsub_tsub_cancel_of_le hj ];
        rw [ Nat.sub_add_comm hj ];
        refine' Finset.sum_congr rfl fun x hx => _ ; rw [ show n - ( j + ( n - ( j + x ) ) ) = x by rw [ tsub_eq_of_eq_add ] ; linarith [ Nat.sub_add_cancel ( show j + x ≤ n from by linarith [ Finset.mem_range.mp hx, Nat.sub_add_cancel hj ] ) ] ] ; ring;
      unfold boxplus; simp_all +decide [ Polynomial.eval_finset_sum ] ;
      exact Eq.trans ( Finset.sum_congr rfl fun x hx => by rw [ h_boxplus_subst x ( Finset.mem_range_succ_iff.mp hx ) ] ) ( h_fubini.trans ( Finset.sum_congr rfl fun x hx => by rw [ h_inner_sum x ( Finset.mem_range_succ_iff.mp hx ) ] ) )

/-
Inequality for n=3 case.
-/
lemma n3_inequality (b1 b2 u1 u2 : ℝ) (hu1 : u1 > 0) (hu2 : u2 > 0) :
  (b1 + b2)^2 / (u1 + u2)^2 ≤ b1^2 / u1^2 + b2^2 / u2^2 := by
  rw [ div_add_div, div_le_div_iff₀ ] <;> try positivity;
  have h_am_gm : (b1 * u2)^2 + (b2 * u1)^2 ≥ 2 * b1 * b2 * u1 * u2 := by
    linarith [ sq_nonneg ( b1 * u2 - b2 * u1 ) ];
  nlinarith [ sq_nonneg ( u1 - u2 ), mul_pos hu1 hu2, mul_le_mul_of_nonneg_left h_am_gm ( sq_nonneg u1 ), mul_le_mul_of_nonneg_left h_am_gm ( sq_nonneg u2 ) ]

/-
Shifting to center preserves splits and nodup.
-/
lemma shifted_to_center_properties (n : ℕ) (p : ℝ[X])
    (hp_splits : p.Splits (RingHom.id ℝ)) (hp_nodup : p.roots.Nodup) :
    (shifted_to_center n p).Splits (RingHom.id ℝ) ∧ (shifted_to_center n p).roots.Nodup := by
  constructor;
  · unfold shifted_to_center;
    exact?;
  · -- The roots of $p(x + c)$ are the roots of $p(x)$ shifted by $-c$.
    have h_roots_shift : (p.comp (X + C (shift_to_center_amount n p))).roots = Multiset.map (fun r => r - shift_to_center_amount n p) p.roots := by
      ext x;
      -- The multiplicity of a root in a polynomial is preserved under translation.
      have h_mult_shift : ∀ r : ℝ, Polynomial.rootMultiplicity r (p.comp (Polynomial.X + Polynomial.C (shift_to_center_amount n p))) = Polynomial.rootMultiplicity (r + shift_to_center_amount n p) p := by
        intro r;
        rw [ Polynomial.rootMultiplicity_eq_natTrailingDegree, Polynomial.rootMultiplicity_eq_natTrailingDegree ];
        norm_num [ add_assoc, Polynomial.comp_assoc ];
      simp_all +decide [ Multiset.count_map ];
      rw [ show ( Multiset.filter ( fun a => x = a - shift_to_center_amount n p ) p.roots ) = Multiset.filter ( fun a => a = x + shift_to_center_amount n p ) p.roots by congr; ext; constructor <;> intro <;> linarith ] ; rw [ Multiset.filter_eq' ] ; aesop;
    exact h_roots_shift.symm ▸ Multiset.Nodup.map ( fun x y hxy => by simpa using hxy ) hp_nodup

#check shifted_to_center_properties

/-
Translation covariance of boxplus (full).
-/
theorem boxplus_comp_add_C (n : ℕ) (p q : ℝ[X]) (c d : ℝ)
    (hp : p.natDegree = n) (hq : q.natDegree = n) :
    boxplus n (p.comp (X + C c)) (q.comp (X + C d)) = (boxplus n p q).comp (X + C (c + d)) := by
      have h_lhs : boxplus n (p.comp (X + C c)) (q.comp (X + C d)) = (boxplus n (p.comp (X + C c)) q).comp (X + C d) := by
        rw [ boxplus_comm ];
        rw [ boxplus_comp_add_C_left ];
        · rw [ boxplus_comm ];
        · exact hq;
        · rw [ Polynomial.natDegree_comp, Polynomial.natDegree_X_add_C, hp, mul_one ];
      rw [ h_lhs ];
      rw [ boxplus_comp_add_C_left ];
      · norm_num [ Polynomial.comp_assoc ];
        ring;
      · exact hp;
      · exact hq

#check boxplus_comp_add_C_left
#check boxplus_comp_add_C

/-
Finite Free Stam Inequality for reduced cubic polynomials.
-/
lemma conjecture_n_3_reduced (a1 b1 a2 b2 : ℝ)
  (h_real1 : (X^3 + C a1 * X + C b1).Splits (RingHom.id ℝ))
  (h_nodup1 : (X^3 + C a1 * X + C b1).roots.Nodup)
  (h_real2 : (X^3 + C a2 * X + C b2).Splits (RingHom.id ℝ))
  (h_nodup2 : (X^3 + C a2 * X + C b2).roots.Nodup)
  (h_real3 : (X^3 + C (a1+a2) * X + C (b1+b2)).Splits (RingHom.id ℝ))
  (h_nodup3 : (X^3 + C (a1+a2) * X + C (b1+b2)).roots.Nodup) :
  invPhi (X^3 + C (a1+a2) * X + C (b1+b2)) ≥
  invPhi (X^3 + C a1 * X + C b1) + invPhi (X^3 + C a2 * X + C b2) := by
  unfold invPhi;
  -- By definition of $Phi$, we know that
  have h_phi : ∀ (a b : ℝ) (h_real : Polynomial.Splits (RingHom.id ℝ) (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b)) (h_nodup : (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b).roots.Nodup), Phi (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b) = (-2 / 9 * a - 3 / 2 * (b / a)^2)⁻¹ := by
    intros a b h_real h_nodup
    have h_roots : ∃ r1 r2 r3 : ℝ, r1 + r2 + r3 = 0 ∧ r1 * r2 + r2 * r3 + r3 * r1 = a ∧ r1 * r2 * r3 = -b ∧ r1 ≠ r2 ∧ r2 ≠ r3 ∧ r3 ≠ r1 := by
      -- By definition of polynomial roots, since the polynomial splits and has distinct roots, there exist three distinct real numbers $r1$, $r2$, and $r3$ such that $r1 + r2 + r3 = 0$, $r1 * r2 + r2 * r3 + r3 * r1 = a$, and $r1 * r2 * r3 = -b$.
      obtain ⟨r1, r2, r3, hr⟩ : ∃ r1 r2 r3 : ℝ, r1 + r2 + r3 = 0 ∧ r1 * r2 + r2 * r3 + r3 * r1 = a ∧ r1 * r2 * r3 = -b ∧ r1 ≠ r2 ∧ r2 ≠ r3 ∧ r3 ≠ r1 := by
        have h_roots : ∃ r : Multiset ℝ, Multiset.card r = 3 ∧ (∀ x ∈ r, x^3 + a * x + b = 0) ∧ r.Nodup := by
          rw [ Polynomial.splits_iff_card_roots ] at h_real;
          rw [ Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] at h_real <;> by_cases ha : a = 0 <;> simp_all +decide [ Polynomial.natDegree_add_eq_left_of_natDegree_lt ];
          · exact ⟨ _, h_real, fun x hx => by simpa using Polynomial.isRoot_of_mem_roots hx, h_nodup ⟩;
          · exact ⟨ _, h_real, fun x hx => by simpa using Polynomial.isRoot_of_mem_roots hx, h_nodup ⟩
        obtain ⟨ r, hr₁, hr₂, hr₃ ⟩ := h_roots; rcases Multiset.card_eq_three.mp hr₁ with ⟨ r1, r2, r3, hr₄ ⟩ ; use r1, r2, r3; simp_all +decide [ add_eq_zero_iff_eq_neg ] ;
        grind;
      use r1, r2, r3;
    obtain ⟨ r1, r2, r3, h1, h2, h3, h4, h5, h6 ⟩ := h_roots; unfold Phi; simp +decide [ *, Finset.sum_range_succ ] ;
    -- By definition of $Phi$, we know that the roots of $X^3 + aX + b$ are $r1$, $r2$, and $r3$.
    have h_roots : (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b).roots.toFinset = {r1, r2, r3} := by
      ext x; simp [h1, h2, h3];
      exact ⟨ fun hx => Classical.or_iff_not_imp_left.2 fun hx' => Classical.or_iff_not_imp_left.2 fun hx'' => mul_left_cancel₀ ( sub_ne_zero_of_ne hx' ) <| mul_left_cancel₀ ( sub_ne_zero_of_ne hx'' ) <| by cases le_or_gt 0 x <;> nlinarith [ sq_nonneg ( x - 1 ), sq_nonneg ( x + 1 ) ], fun hx => by rcases hx with ( rfl | rfl | rfl ) <;> exact ⟨ by exact ne_of_apply_ne ( fun p => p.coeff 3 ) <| by norm_num [ Polynomial.coeff_X, Polynomial.coeff_C ], by cases le_or_gt 0 x <;> nlinarith [ sq_nonneg ( x - 1 ), sq_nonneg ( x + 1 ) ] ⟩ ⟩;
    by_cases ha : a = 0 <;> simp_all +decide [ Finset.sum_pair, Finset.sum_singleton ];
    · grind;
    · rw [ Finset.sum_insert, Finset.sum_insert ] <;> norm_num [ h4, h5, h6 ];
      · rw [ Finset.sum_insert, Finset.sum_insert ] <;> norm_num [ h4, h5, h6 ];
        · rw [ Finset.sum_insert, Finset.sum_insert ] <;> norm_num [ h4, h5, h6 ];
          · rw [ ← eq_sub_iff_add_eq' ] at h1 ; subst_vars ; ring_nf at *;
            rw [ show b = r1 * r2 ^ 2 + r1 ^ 2 * r2 by linarith ] ; ring;
            field_simp;
            rw [ div_add_one, div_add_div, div_add_div, div_add_div, div_add_div, div_add_div, div_add_div ];
            any_goals nlinarith [ mul_self_pos.2 ( sub_ne_zero.2 h4 ), mul_self_pos.2 ( sub_ne_zero.2 h5 ), mul_self_pos.2 ( sub_ne_zero.2 h6 ) ];
            · rw [ div_add_div, div_eq_div_iff ];
              · field_simp;
                ring;
              · simp_all +decide [ sub_eq_iff_eq_add, add_eq_zero_iff_eq_neg ];
                grind;
              · grind;
              · simp_all +decide [ sub_eq_iff_eq_add, add_eq_zero_iff_eq_neg ];
                exact ⟨ ⟨ ⟨ by contrapose! h6; linarith, by contrapose! h5; linarith ⟩, by contrapose! h6; linarith, by contrapose! h5; linarith ⟩, by contrapose! h6; linarith ⟩;
              · exact pow_ne_zero 2 ( by contrapose! h5; linarith );
            · grind;
            · grind;
            · grind;
            · grind;
          · tauto;
        · tauto;
      · tauto;
      · tauto;
  have h_neg : a1 < 0 ∧ a2 < 0 ∧ a1 + a2 < 0 := by
    have h_neg : ∀ (a b : ℝ) (h_real : Polynomial.Splits (RingHom.id ℝ) (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b)) (h_nodup : (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b).roots.Nodup), a < 0 := by
      intros a b h_real h_nodup
      by_contra h_nonneg
      have h_roots : ∃ r1 r2 r3 : ℝ, r1 + r2 + r3 = 0 ∧ r1 * r2 + r2 * r3 + r3 * r1 = a ∧ r1 * r2 * r3 = -b := by
        rw [ Polynomial.splits_iff_card_roots ] at h_real;
        obtain ⟨r1, r2, r3, hr⟩ : ∃ r1 r2 r3 : ℝ, Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b) = {r1, r2, r3} := by
          rw [ Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] at h_real <;> by_cases ha : a = 0 <;> simp_all +decide [ Polynomial.natDegree_add_eq_left_of_natDegree_lt ];
          · exact Multiset.card_eq_three.mp h_real;
          · exact Multiset.card_eq_three.mp h_real;
        have h_roots : Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b = Polynomial.C 1 * (Polynomial.X - Polynomial.C r1) * (Polynomial.X - Polynomial.C r2) * (Polynomial.X - Polynomial.C r3) := by
          rw [ ← Polynomial.prod_multiset_X_sub_C_of_monic_of_roots_card_eq ( show Polynomial.Monic ( Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b ) from ?_ ) ];
          · simpa [ hr ] using by ring;
          · exact h_real;
          · rw [ Polynomial.Monic, Polynomial.leadingCoeff, Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases ha : a = 0 <;> simp +decide [ ha ];
        have h₁ := congr_arg ( Polynomial.eval 0 ) h_roots; have h₂ := congr_arg ( Polynomial.eval 1 ) h_roots; have h₃ := congr_arg ( Polynomial.eval ( -1 ) ) h_roots; norm_num at h₁ h₂ h₃; exact ⟨ r1, r2, r3, by linarith, by linarith, by linarith ⟩ ;
      obtain ⟨ r1, r2, r3, h1, h2, h3 ⟩ := h_roots;
      have h_roots_eq : r1 = 0 ∧ r2 = 0 ∧ r3 = 0 := by
        exact ⟨ by nlinarith [ sq_nonneg r1, sq_nonneg r2, sq_nonneg r3 ], by nlinarith [ sq_nonneg r1, sq_nonneg r2, sq_nonneg r3 ], by nlinarith [ sq_nonneg r1, sq_nonneg r2, sq_nonneg r3 ] ⟩;
      norm_num [ h_roots_eq ] at *;
      norm_num [ ← h2, ← h3 ] at *;
      norm_num [ h3 ] at h_nodup;
      norm_num [ Multiset.nsmul_singleton ] at h_nodup;
    exact ⟨ h_neg a1 b1 h_real1 h_nodup1, h_neg a2 b2 h_real2 h_nodup2, h_neg ( a1 + a2 ) ( b1 + b2 ) h_real3 h_nodup3 ⟩;
  have h_card : ∀ (a b : ℝ) (h_real : Polynomial.Splits (RingHom.id ℝ) (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b)) (h_nodup : (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b).roots.Nodup), (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b).roots.card = 3 := by
    intros a b h_real h_nodup
    have h_card : Multiset.card (Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b)) = Polynomial.natDegree (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b) := by
      exact?;
    rw [ h_card, Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases ha : a = 0 <;> simp +decide [ ha ];
  rw [ h_phi _ _ h_real3 h_nodup3, h_phi _ _ h_real1 h_nodup1, h_phi _ _ h_real2 h_nodup2 ];
  rw [ h_card _ _ h_real1 h_nodup1, h_card _ _ h_real2 h_nodup2, h_card _ _ h_real3 h_nodup3 ] ; norm_num;
  have h_ineq : (b1 + b2)^2 / (a1 + a2)^2 ≤ b1^2 / a1^2 + b2^2 / a2^2 := by
    have h_ineq : ∀ (u1 u2 : ℝ) (hu1 : u1 > 0) (hu2 : u2 > 0) (b1 b2 : ℝ), (b1 + b2)^2 / (u1 + u2)^2 ≤ b1^2 / u1^2 + b2^2 / u2^2 := by
      exact?;
    convert h_ineq ( -a1 ) ( -a2 ) ( neg_pos.mpr h_neg.1 ) ( neg_pos.mpr h_neg.2.1 ) b1 b2 using 1 <;> ring;
  split_ifs <;> norm_num at *;
  · ring_nf at *;
    norm_num [ show a1 * a2 * 2 + a1 ^ 2 + a2 ^ 2 = ( a1 + a2 ) ^ 2 by ring ] at * ; linarith;
  · contradiction