/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 167001fa-f8ec-492e-a0ef-3122220bdb1f

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def f_aux (k : ℝ) : ℝ := (2 * k * (1 - 4 * k)) / (12 * k + 1)

lemma f_aux_concave : ConcaveOn ℝ (Set.Ioi 0) f_aux := by
  refine' ⟨ convex_Ioi 0, _ ⟩;
  simp_all +decide [ f_aux ];
  intro x hx y hy a b ha hb hab;
  -- By simplifying, we can see that the inequality holds.
  have h_simp : 2 * (a * x + b * y) * (1 - 4 * (a * x + b * y)) / (12 * (a * x + b * y) + 1) ≥ a * (2 * x * (1 - 4 * x) / (12 * x + 1)) + b * (2 * y * (1 - 4 * y) / (12 * y + 1)) := by
    have h_pos : 0 < 12 * x + 1 ∧ 0 < 12 * y + 1 ∧ 0 < 12 * (a * x + b * y) + 1 := by
      exact ⟨ by positivity, by positivity, by nlinarith ⟩
    field_simp [h_pos.left.ne', h_pos.right.left.ne', h_pos.right.right.ne'] at *;
    rw [ ← eq_sub_iff_add_eq' ] at hab ; subst_vars ; ring_nf at *;
    nlinarith [ mul_nonneg ha ( sq_nonneg ( x - y ) ), mul_nonneg ha ( mul_nonneg hy.le hx.le ), mul_nonneg hb ( sq_nonneg ( x - y ) ), mul_nonneg hb ( mul_nonneg hy.le hx.le ), mul_nonneg ha ( mul_nonneg hy.le ( sq_nonneg ( x - y ) ) ), mul_nonneg hb ( mul_nonneg hy.le ( sq_nonneg ( x - y ) ) ) ];
  exact h_simp

def poly_diff (t x y : ℝ) : ℝ :=
  let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
  (2 * Z * (1 - 4 * Z)) * (1 + 12 * x) * (1 + 12 * y) -
  (t * (2 * x * (1 - 4 * x)) * (1 + 12 * Z) * (1 + 12 * y) +
   (1 - t) * (2 * y * (1 - 4 * y)) * (1 + 12 * Z) * (1 + 12 * x))

/-
In Sub-case A with t < 1/2, the deviations u and v from 1/12 satisfy specific bounds.
-/
lemma case4a_bounds (t x y : ℝ)
    (ht : 0 < t) (ht_le : t < 1/2)
    (hW : t * x + (1 - t) * y ≥ 1/12)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 < 1/12)
    (hsum : x + y > 1/6) :
    let u := x - 1/12
    let v := y - 1/12
    v < 0 ∧ u > 0 ∧ u ≥ -v * (1 - t) / t ∧ u < -v * (1 - t)^2 / t^2 := by
      refine' ⟨ _, _, _, _ ⟩ <;> try nlinarith;
      · rw [ ge_iff_le, div_le_iff₀ ] <;> nlinarith;
      · rw [ lt_div_iff₀ ] <;> nlinarith

def poly_diff_uv (t u v : ℝ) : ℝ :=
  let x := u + 1/12
  let y := v + 1/12
  let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
  (2 * Z * (1 - 4 * Z)) * (1 + 12 * x) * (1 + 12 * y) -
  (t * (2 * x * (1 - 4 * x)) * (1 + 12 * Z) * (1 + 12 * y) +
   (1 - t) * (2 * y * (1 - 4 * y)) * (1 + 12 * Z) * (1 + 12 * x))

lemma poly_diff_eq_poly_diff_uv (t x y : ℝ) :
    poly_diff t x y = poly_diff_uv t (x - 1/12) (y - 1/12) := by
  unfold poly_diff poly_diff_uv
  ring

/-
Algebraic verification of the polynomial difference non-negativity in the (u, v) coordinates for Sub-case A.
-/
lemma poly_diff_uv_nonneg (t u v : ℝ)
    (ht : 0 < t) (ht_le : t < 1/2)
    (hv_neg : v < 0) (hu_pos : u > 0)
    (h_cone1 : u ≥ -v * (1 - t) / t)
    (h_cone2 : u < -v * (1 - t)^2 / t^2)
    (hu_small : u < 1/6) (hv_small : v > -1/12) :
    poly_diff_uv t u v ≥ 0 := by
  -- We substitute the bounds into the polynomial.
  -- poly_diff_uv is a polynomial in t, u, v.
  -- We can try to show it's positive in the cone.
  -- Let u = -v * (1-t)/t + delta, with delta >= 0.
  -- Or let u = -v * (1-t)/t * (1 + k) where 0 <= k < (1-t)/t - 1 = (1-2t)/t.
  -- Let's try nlinarith with the cone constraints.
  unfold poly_diff_uv
  -- We know u, v are small.
  -- The dominant terms should determine the sign.
  rw [ ge_iff_le, div_le_iff₀, lt_div_iff₀ ] at * <;> try nlinarith;
  -- Let's simplify the expression.
  by_cases h_case : u * t^2 + v * (1 - t)^2 ≤ 0;
  · have := mul_pos ht ( sub_pos.mpr ht_le );
    have := mul_pos this ( sub_pos.mpr hv_neg );
    have := mul_pos this ( sub_pos.mpr hu_pos );
    have := mul_pos this ( sub_pos.mpr hu_small );
    nlinarith [ mul_le_mul_of_nonneg_left h_case ( sq_nonneg t ), mul_le_mul_of_nonneg_left h_case ( sq_nonneg ( 1 - t ) ), mul_le_mul_of_nonneg_left h_case ( sq_nonneg ( u * t + v * ( 1 - t ) ) ), mul_le_mul_of_nonneg_left h_case ( sq_nonneg ( u * t - v * ( 1 - t ) ) ), mul_le_mul_of_nonneg_left h_case ( sq_nonneg ( u * ( 1 - t ) + v * t ) ), mul_le_mul_of_nonneg_left h_case ( sq_nonneg ( u * ( 1 - t ) - v * t ) ) ];
  · grind

/-
In Sub-case A (W ≥ 1/12), the polynomial difference is non-negative.
-/
lemma poly_diff_nonneg_case4a (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hW : t * x + (1 - t) * y ≥ 1/12)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 < 1/12)
    (hsum : x + y > 1/6) :
    poly_diff t x y ≥ 0 := by
      by_cases ht_half : t = 1 / 2;
      · subst ht_half; nlinarith;
      · cases lt_or_gt_of_ne ht_half;
        · convert poly_diff_uv_nonneg t ( x - 1 / 12 ) ( y - 1 / 12 ) ht ‹_› _ _ _ _ _ _ using 1 <;> norm_num;
          any_goals nlinarith [ mul_div_cancel₀ ( ( 1 / 12 - y ) * ( 1 - t ) ) ( ne_of_gt ht ), mul_div_cancel₀ ( ( 1 / 12 - y ) * ( 1 - t ) ^ 2 ) ( ne_of_gt ( sq_pos_of_pos ht ) ) ];
          exact?;
        · rename_i h;
          -- By symmetry of `poly_diff`, we have `poly_diff t x y = poly_diff (1 - t) y x`.
          have h_symm : poly_diff t x y = poly_diff (1 - t) y x := by
            unfold poly_diff; ring;
          -- By applying the results from case4a_bounds and poly_diff_uv_nonneg, we can conclude that poly_diff (1 - t) y x is non-negative.
          have h_poly_diff_nonneg : poly_diff_uv (1 - t) (y - 1/12) (x - 1/12) ≥ 0 := by
            apply poly_diff_uv_nonneg;
            any_goals nlinarith;
            · rw [ ge_iff_le, div_le_iff₀ ] <;> nlinarith;
            · rw [ lt_div_iff₀ ] <;> nlinarith only [ h, hW, hZ, hsum, mul_pos ( sub_pos.mpr h ) ( sub_pos.mpr ht1 ) ];
          exact h_symm.symm ▸ poly_diff_eq_poly_diff_uv ( 1 - t ) y x ▸ h_poly_diff_nonneg

lemma poly_diff_symmetry (t x y : ℝ) :
    poly_diff t x y = poly_diff (1 - t) y x := by
  unfold poly_diff; ring

/-
In Sub-case B with t < 1/2, the deviations u and v satisfy specific bounds.
-/
lemma case4b_bounds (t x y : ℝ)
    (ht : 0 < t) (ht_le : t < 1/2)
    (hW : t * x + (1 - t) * y < 1/12)
    (hsum : x + y > 1/6) :
    let u := x - 1/12
    let v := y - 1/12
    v < 0 ∧ u > 0 ∧ u > -v ∧ u < -v * (1 - t) / t := by
      refine' ⟨ _, _, _, _ ⟩ <;> nlinarith [ mul_div_cancel₀ ( - ( y - 1 / 12 ) * ( 1 - t ) ) ht.ne' ]

def g_aux_case4 (S : ℝ) : ℝ := -S + 5 - 4/S

lemma poly_diff_eq_g_aux_iff (t x y : ℝ)
    (hx : 1 + 12 * x > 0) (hy : 1 + 12 * y > 0)
    (hZ : 1 + 12 * (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) > 0) :
    let X := 1 + 12 * x
    let Y := 1 + 12 * y
    let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
    let K := 1 + 12 * Z
    poly_diff t x y ≥ 0 ↔ g_aux_case4 K ≥ t * g_aux_case4 X + (1 - t) * g_aux_case4 Y := by
      -- Substitute the definitions of X, Y, Z, and K into the inequality.
      simp [poly_diff, g_aux_case4];
      field_simp;
      field_simp;
      rw [ sub_div', mul_comm ];
      · rw [ mul_div, le_div_iff₀ ];
        · grind;
        · linarith;
      · nlinarith

/-
The reduced polynomial difference is non-negative in Sub-case B.
-/
def poly_diff_reduced (t u v : ℝ) : ℝ :=
  let X := 1 + 12 * (u + 1/12)
  let Y := 1 + 12 * (v + 1/12)
  let Z := t^2 * (u + 1/12) + (1 - t)^2 * (v + 1/12) + t * (1 - t) / 6
  let K := 1 + 12 * Z
  3 * t * (1 - t) * (u + v) * K * X * Y - (X * Y - K * (t * Y + (1 - t) * X))

lemma poly_diff_reduced_nonneg_case4b (t u v : ℝ)
    (ht : 0 < t) (ht_le : t < 1/2)
    (hv_neg : v < 0) (hu_pos : u > 0)
    (h_cone1 : u > -v)
    (h_cone2 : u < -v * (1 - t) / t)
    (hu_small : u < 1/6) (hv_small : v > -1/12) :
    poly_diff_reduced t u v ≥ 0 := by
  unfold poly_diff_reduced
  -- We use nlinarith.
  -- The constant term is positive, so it should be robust.
  -- Let's help nlinarith by expanding terms if needed.
  -- But first try direct nlinarith.
  rw [ lt_div_iff₀' ht ] at h_cone2;
  -- Since $u > -v$ and $t < 1/2$, we have $3t(1-t)(u+v) > 0$.
  have h_pos : 3 * t * (1 - t) * (u + v) > 0 := by
    exact mul_pos ( mul_pos ( mul_pos ( by norm_num ) ht ) ( by linarith ) ) ( by linarith );
  have h_nonneg : 252 * (t * (1 - t) * (u + v))^2 + 36 * (t * (1 - t) * (u + v))^3 ≥ 0 := by
    exact add_nonneg ( mul_nonneg ( by norm_num ) ( sq_nonneg _ ) ) ( mul_nonneg ( by norm_num ) ( pow_nonneg ( by nlinarith ) _ ) );
  nlinarith [ mul_pos h_pos ( sub_pos.mpr h_cone1 ), mul_pos h_pos ( sub_pos.mpr h_cone2 ), mul_pos h_pos ( sub_pos.mpr hu_pos ), mul_pos h_pos ( sub_pos.mpr hv_neg ), mul_pos ( sub_pos.mpr h_cone1 ) ( sub_pos.mpr h_cone2 ), mul_pos ( sub_pos.mpr h_cone1 ) ( sub_pos.mpr hu_pos ), mul_pos ( sub_pos.mpr h_cone1 ) ( sub_pos.mpr hv_neg ), mul_pos ( sub_pos.mpr h_cone2 ) ( sub_pos.mpr hu_pos ), mul_pos ( sub_pos.mpr h_cone2 ) ( sub_pos.mpr hv_neg ), mul_pos ( sub_pos.mpr hu_pos ) ( sub_pos.mpr hv_neg ) ]

lemma poly_diff_eq_two_ninths_reduced (t x y : ℝ) :
    let u := x - 1/12
    let v := y - 1/12
    poly_diff t x y = (2/9) * poly_diff_reduced t u v := by
  intro u v
  unfold poly_diff poly_diff_reduced
  ring

/-
In Sub-case B (W < 1/12), the polynomial difference is non-negative.
-/
lemma poly_diff_nonneg_case4b (t x y : ℝ)
    (ht : 0 < t) (ht_le : t < 1/2)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hW : t * x + (1 - t) * y < 1/12)
    (hsum : x + y > 1/6) :
    poly_diff t x y ≥ 0 := by
      -- Apply the non-negativity of the reduced polynomial `poly_diff_reduced`.
      have h_reduced_nonneg : poly_diff_reduced t (x - 1 / 12) (y - 1 / 12) ≥ 0 := by
        apply_rules [ poly_diff_reduced_nonneg_case4b ];
        all_goals nlinarith [ mul_div_cancel₀ ( - ( y - 1 / 12 ) * ( 1 - t ) ) ht.ne' ] ;
      exact le_of_sub_nonneg ( by rw [ poly_diff_eq_two_ninths_reduced ] ; linarith )

/-
In Sub-case B (W < 1/12), the polynomial difference is non-negative.
-/
lemma poly_diff_nonneg_case4b_v2 (t x y : ℝ)
    (ht : 0 < t) (ht_le : t < 1/2)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hW : t * x + (1 - t) * y < 1/12)
    (hsum : x + y > 1/6) :
    poly_diff t x y ≥ 0 := by
      exact?

/-
The f_aux inequality holds for Case 4 (x+y > 1/6, Z < 1/12).
-/
lemma f_aux_ineq_case4 (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y > 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 < 1/12) :
    f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ t * f_aux x + (1 - t) * f_aux y := by
      by_cases ht_half : t < 1 / 2;
      · have h_poly_diff_nonneg : poly_diff t x y ≥ 0 := by
          by_cases hW : t * x + (1 - t) * y ≥ 1 / 12;
          · apply poly_diff_nonneg_case4a t x y ht ht1 hx hx1 hy hy1 hW hZ hsum;
          · apply poly_diff_nonneg_case4b_v2 t x y ht ht_half hx (by linarith) hy (by linarith) (by linarith) (by linarith);
        unfold poly_diff f_aux at *;
        field_simp at *;
        rw [ le_div_iff₀ ] <;> nlinarith;
      · have h_poly_diff_nonneg : poly_diff (1 - t) y x ≥ 0 := by
          by_cases hW : (1 - t) * y + t * x ≥ 1 / 12;
          · apply poly_diff_nonneg_case4a;
            all_goals linarith;
          · convert poly_diff_nonneg_case4b_v2 ( 1 - t ) y x _ _ _ _ _ _ _ using 1 <;> try linarith;
            · grind;
            · nlinarith;
        unfold f_aux poly_diff at *;
        field_simp at *;
        rw [ le_div_iff₀ ] <;> nlinarith

lemma f_aux_ineq_of_poly_diff_nonneg (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (h_poly : poly_diff t x y ≥ 0) :
    let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
    f_aux Z ≥ t * f_aux x + (1 - t) * f_aux y := by
  unfold f_aux
  field_simp
  rw [le_div_iff₀] <;> unfold poly_diff at h_poly <;> nlinarith [mul_pos ht (mul_pos hx hy)]

lemma f_aux_ineq_easy_case (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y ≤ 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 ≤ 1/12) :
    f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ t * f_aux x + (1 - t) * f_aux y := by
      -- Apply the lemma for Case 1 and Case 2 to conclude the proof.
      by_cases hZ_neg : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 ≤ 0;
      · exact False.elim <| hZ_neg.not_lt <| by nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ] ;
      · -- Since $Z$ is positive and less than or equal to $1/12$, we can apply the lemma for Case 2.
        have h_case2 : f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ f_aux (t * x + (1 - t) * y) := by
          field_simp;
          -- By simplifying, we can see that the inequality holds.
          have h_simp : t * x + (1 - t) * y ≤ t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 := by
            nlinarith only [ sq_nonneg ( t - 1 / 2 ), mul_pos ht ( sub_pos.mpr ht1 ), hsum, hx, hy ];
          unfold f_aux;
          rw [ div_le_div_iff₀ ] <;> try linarith;
          · nlinarith [ mul_le_mul_of_nonneg_left h_simp ( show 0 ≤ t * x + ( 1 - t ) * y by nlinarith ), mul_le_mul_of_nonneg_left h_simp ( show 0 ≤ 12 * ( t * x + ( 1 - t ) * y ) + 1 by nlinarith ) ];
          · nlinarith only [ ht, ht1, hx, hy, hsum ];
        -- Since $f_aux$ is concave on $(0, \infty)$, we have $f_aux (t * x + (1 - t) * y) \geq t * f_aux x + (1 - t) * f_aux y$.
        have h_concave : ConcaveOn ℝ (Set.Ioi 0) f_aux := by
          exact?;
        exact le_trans ( h_concave.2 hx hy ( by linarith ) ( by linarith ) ( by linarith ) ) h_case2

lemma f_aux_decreasing (x y : ℝ) (hx : 1/12 ≤ x) (hy : y < 1/4) (hxy : x ≤ y) :
    f_aux y ≤ f_aux x := by
  unfold f_aux; rw [ div_le_div_iff₀ ] <;> try nlinarith;
  nlinarith [ mul_le_mul_of_nonneg_left hxy ( sub_nonneg_of_le hx ) ]

/-
The f_aux inequality holds for Case 2.
-/
lemma f_aux_ineq_case2_easy (t x y : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/4)
    (hy : 0 < y) (hy1 : y < 1/4)
    (hsum : x + y > 1/6)
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 ≥ 1/12) :
    f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ t * f_aux x + (1 - t) * f_aux y := by
      -- By Lemma~\ref{lem:f_aux_decreasing}, we have $f_aux(Z) \geq f_aux(W)$.
      have h_decreasing : f_aux (t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6) ≥ f_aux (t * x + (1 - t) * y) := by
        apply_rules [ f_aux_decreasing ] ; nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ] ;
        nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ) ];
      refine le_trans ?_ h_decreasing;
      apply_rules [ f_aux_concave.2 ];
      · linarith;
      · linarith;
      · ring

lemma poly_diff_on_boundary (t x : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hx : 0 < x) (hx1 : x < 1/6)
    (hZ : let y := 1/6 - x; t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 > 1/12) :
    poly_diff t x (1/6 - x) ≥ 0 := by
  unfold poly_diff
  nlinarith [ mul_pos ht ( sub_pos.mpr ht1 ), mul_pos ht ( sub_pos.mpr hx1 ), mul_pos ( sub_pos.mpr ht1 ) ( sub_pos.mpr hx1 ), pow_two_nonneg ( t - 1 / 2 ), pow_two_nonneg ( x - 1 / 12 ), pow_two_nonneg ( t * x - 1 / 24 ), pow_two_nonneg ( t * ( 1 / 6 - x ) - 1 / 24 ), pow_two_nonneg ( x * ( 1 / 6 - x ) - 1 / 24 ) ]

def diff (t x y : ℝ) : ℝ :=
  let Z := t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6
  f_aux Z - (t * f_aux x + (1 - t) * f_aux y)

lemma diff_decreasing_y (t x y y' : ℝ)
    (ht : 0 < t) (ht1 : t < 1)
    (hy : 0 < y) (hy' : y' ≤ 1/12) (hyy' : y ≤ y')
    (hZ : t^2 * x + (1 - t)^2 * y + t * (1 - t) / 6 > 1/12) :
    diff t x y ≥ diff t x y' := by
  contrapose! hyy';
  unfold diff at *;
  unfold f_aux at *;
  refine' lt_of_not_ge fun h => hyy'.not_le _;
  refine' sub_le_sub _ _;
  · rw [ div_le_div_iff₀ ] <;> try nlinarith;
    have h_diff_nonneg : (t ^ 2 * x + (1 - t) ^ 2 * y' + t * (1 - t) / 6) - (t ^ 2 * x + (1 - t) ^ 2 * y + t * (1 - t) / 6) ≥ 0 := by
      nlinarith [ mul_le_mul_of_nonneg_left h ( sq_nonneg ( 1 - t ) ) ];
    nlinarith [ mul_le_mul_of_nonneg_left h_diff_nonneg ( show 0 ≤ t ^ 2 * x + ( 1 - t ) ^ 2 * y + t * ( 1 - t ) / 6 by linarith ), mul_le_mul_of_nonneg_left h_diff_nonneg ( show 0 ≤ t ^ 2 * x + ( 1 - t ) ^ 2 * y' + t * ( 1 - t ) / 6 by linarith ) ];
  · refine' add_le_add_left ( mul_le_mul_of_nonneg_left _ ( sub_nonneg.mpr ht1.le ) ) _;
    rw [ div_le_div_iff₀ ] <;> nlinarith only [ hy, hy', h, mul_le_mul_of_nonneg_left h hy.le ]