/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 3bede162-8ab4-49c9-b0b8-32d1e3b404d8

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat Classical Pointwise
open Polynomial BigOperators Finset Classical

def boxplus_coeff (n : ℕ) (p q : ℝ[X]) (k : ℕ) : ℝ :=
  ∑ i ∈ range (k + 1),
    let j := k - i
    (Nat.factorial (n - i) * Nat.factorial (n - j) : ℝ) / (Nat.factorial n * Nat.factorial (n - k) : ℝ) *
    (p.coeff (n - i)) * (q.coeff (n - j))

def boxplus (n : ℕ) (p q : ℝ[X]) : ℝ[X] :=
  Finset.sum (range (n + 1)) (fun k => C (boxplus_coeff n p q k) * X ^ (n - k))

def Phi (p : ℝ[X]) : ℝ :=
  let roots := p.roots.toFinset
  ∑ r_i ∈ roots, (∑ r_j ∈ roots.erase r_i, 1 / (r_i - r_j))^2

def invPhi (p : ℝ[X]) : ℝ :=
  if p.roots.Nodup ∧ p.roots.card > 1 then
    1 / Phi p
  else 0

def is_centered (n : ℕ) (p : ℝ[X]) : Prop :=
  p.Monic ∧ p.natDegree = n ∧ p.coeff (n - 1) = 0

lemma boxplus_comp_add_C_left (n : ℕ) (p q : ℝ[X]) (c : ℝ)
    (hp : p.natDegree = n) (hq : q.natDegree = n) :
    boxplus n (p.comp (X + C c)) q = (boxplus n p q).comp (X + C c) := by
      refine' Polynomial.funext _;
      intro r;
      -- We'll use the fact that $p(x+c)$ has coefficients given by the binomial theorem.
      have h_coeff : ∀ i ≤ n, (p.comp (.X + (.C c))).coeff (n - i) = ∑ j ∈ Finset.range (i + 1), Nat.choose (n - j) (n - i) * c ^ (i - j) * p.coeff (n - j) := by
        intro i hi
        have h_coeff : (p.comp (.X + (.C c))).coeff (n - i) = ∑ j ∈ Finset.range (n + 1), p.coeff j * Nat.choose j (n - i) * c ^ (j - (n - i)) := by
          rw [ Polynomial.comp, Polynomial.eval₂_eq_sum_range ];
          norm_num [ Polynomial.coeff_X_add_C_pow ];
          simp +decide [ mul_assoc, mul_comm, mul_left_comm, hp ];
        rw [ h_coeff, ← Finset.sum_flip ];
        rw [ ← Finset.sum_subset ( Finset.range_mono ( Nat.succ_le_succ hi ) ) ];
        · refine' Finset.sum_congr rfl fun x hx => _;
          grind;
        · simp +zetaDelta at *;
          exact fun x hx₁ hx₂ => Or.inl <| Or.inr <| Nat.choose_eq_zero_of_lt <| by omega;
      -- Substitute the expression for the coefficients of $p(x+c)$ into the definition of $boxplus$.
      have h_boxplus_subst : ∀ k ≤ n, boxplus_coeff n (p.comp (.X + (.C c))) q k = ∑ j ∈ Finset.range (k + 1), boxplus_coeff n p q j * Nat.choose (n - j) (n - k) * c^(k - j) := by
        unfold boxplus_coeff;
        intro k hk; rw [ Finset.sum_congr rfl fun i hi => by rw [ h_coeff i ( by linarith [ Finset.mem_range.mp hi ] ) ] ] ; simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Finset.sum_mul ] ;
        rw [ Finset.sum_sigma', Finset.sum_sigma' ];
        refine' Finset.sum_bij ( fun x hx => ⟨ k - x.1 + x.2, x.2 ⟩ ) _ _ _ _ <;> simp_all +decide [ Nat.choose_succ_succ, add_comm ];
        · exact fun a ha₁ ha₂ => ⟨ by omega, by omega ⟩;
        · grind;
        · exact fun b hb₁ hb₂ => ⟨ k - ( b.fst - b.snd ), b.snd, ⟨ by omega, by omega ⟩, by ext <;> norm_num ; omega ⟩;
        · intro a ha₁ ha₂; rw [ show a.fst - a.snd = k - ( a.snd + ( k - a.fst ) ) by omega ] ; ring;
          rw [ Nat.cast_choose, Nat.cast_choose ] <;> try omega;
          field_simp;
          rw [ show n - ( a.snd + ( k - a.fst ) ) - ( n - k ) = n - a.snd - ( n - a.fst ) by omega ] ; ring;
      -- By Fubini's theorem, we can interchange the order of summation.
      have h_fubini : ∑ k ∈ Finset.range (n + 1), (∑ j ∈ Finset.range (k + 1), boxplus_coeff n p q j * Nat.choose (n - j) (n - k) * c^(k - j)) * (r^(n - k)) = ∑ j ∈ Finset.range (n + 1), boxplus_coeff n p q j * (∑ k ∈ Finset.Ico j (n + 1), Nat.choose (n - j) (n - k) * c^(k - j) * r^(n - k)) := by
        simp +decide only [mul_assoc, sum_mul, Finset.mul_sum _ _ _];
        rw [ Finset.range_eq_Ico, Finset.sum_Ico_Ico_comm ];
      -- Let's simplify the inner sum $\sum_{k=j}^{n} \binom{n-j}{n-k} c^{k-j} r^{n-k}$.
      have h_inner_sum : ∀ j ≤ n, ∑ k ∈ Finset.Ico j (n + 1), Nat.choose (n - j) (n - k) * c^(k - j) * r^(n - k) = (r + c)^(n - j) := by
        intro j hj; rw [ add_pow ] ; simp +decide [ mul_assoc, mul_comm, mul_left_comm, Finset.sum_Ico_eq_sum_range ] ;
        rw [ ← Finset.sum_flip ];
        simp +decide [ Nat.sub_sub, add_comm, tsub_tsub_cancel_of_le hj ];
        rw [ Nat.sub_add_comm hj ];
        refine' Finset.sum_congr rfl fun x hx => _ ; rw [ show n - ( j + ( n - ( j + x ) ) ) = x by rw [ tsub_eq_of_eq_add ] ; linarith [ Nat.sub_add_cancel ( show j + x ≤ n from by linarith [ Finset.mem_range.mp hx, Nat.sub_add_cancel hj ] ) ] ] ; ring;
      unfold boxplus; simp_all +decide [ Polynomial.eval_finset_sum ] ;
      exact Eq.trans ( Finset.sum_congr rfl fun x hx => by rw [ h_boxplus_subst x ( Finset.mem_range_succ_iff.mp hx ) ] ) ( h_fubini.trans ( Finset.sum_congr rfl fun x hx => by rw [ h_inner_sum x ( Finset.mem_range_succ_iff.mp hx ) ] ) )

lemma boxplus_comm (n : ℕ) (p q : ℝ[X]) :
    boxplus n p q = boxplus n q p := by
      -- By definition of `boxplus`, we know that it is symmetric.
      have h_symm : ∀ k, boxplus_coeff n p q k = boxplus_coeff n q p k := by
        intro k
        unfold boxplus_coeff
        simp [mul_comm, mul_assoc, mul_left_comm];
        rw [ ← Finset.sum_flip ];
        exact Finset.sum_congr rfl fun x hx => by rw [ tsub_tsub_cancel_of_le ( Finset.mem_range_succ_iff.mp hx ) ] ; ring;
      unfold boxplus; aesop;

theorem boxplus_comp_add_C (n : ℕ) (p q : ℝ[X]) (c d : ℝ)
    (hp : p.natDegree = n) (hq : q.natDegree = n) :
    boxplus n (p.comp (X + C c)) (q.comp (X + C d)) = (boxplus n p q).comp (X + C (c + d)) := by
      -- By definition of boxplus, we can rewrite the left-hand side.
      have h_lhs : boxplus n (p.comp (X + C c)) (q.comp (X + C d)) = (boxplus n (p.comp (X + C c)) q).comp (X + C d) := by
        rw [ boxplus_comm ];
        rw [ boxplus_comp_add_C_left ];
        · rw [ boxplus_comm ];
        · exact hq;
        · rw [ Polynomial.natDegree_comp, Polynomial.natDegree_X_add_C, hp, mul_one ];
      rw [ h_lhs ];
      rw [ boxplus_comp_add_C_left ];
      · norm_num [ Polynomial.comp_assoc ];
        ring;
      · exact hp;
      · exact hq

lemma roots_card_eq_natDegree (p : ℝ[X])
    (h_splits : p.Splits (RingHom.id ℝ)) (h_monic : p.Monic) :
    p.roots.card = p.natDegree := by
  rw [Polynomial.splits_iff_card_roots] at h_splits
  exact h_splits

lemma Phi_derivative_form (p : ℝ[X])
    (h_splits : p.Splits (RingHom.id ℝ))
    (h_nodup : p.roots.Nodup) :
    Phi p = ∑ r ∈ p.roots.toFinset, (p.derivative.derivative.eval r / (2 * p.derivative.eval r))^2 := by
      refine' Finset.sum_congr rfl fun r hr => _;
      -- Let $q(x) = \frac{p(x)}{x - r}$.
      obtain ⟨q, hq⟩ : ∃ q : Polynomial ℝ, p = (Polynomial.X - Polynomial.C r) * q ∧ q.eval r ≠ 0 := by
        obtain ⟨q, hq⟩ : ∃ q : Polynomial ℝ, p = (Polynomial.X - Polynomial.C r) * q := by
          exact Polynomial.dvd_iff_isRoot.mpr ( by aesop );
        by_cases h : q.eval r = 0 <;> simp_all +decide [ Polynomial.splits_mul, Polynomial.splits_X_sub_C ];
        rw [ Polynomial.roots_mul ] at h_nodup <;> aesop;
      -- Since $q(x)$ is a polynomial with roots $r_j$ for $j \neq r$, we can write $q(x) = c \prod_{j \neq r} (x - r_j)$ for some constant $c$.
      obtain ⟨c, hc⟩ : ∃ c : ℝ, q = Polynomial.C c * ∏ r_j ∈ p.roots.toFinset.erase r, (Polynomial.X - Polynomial.C r_j) := by
        -- Since $q$ is a polynomial with roots $r_j$ for $j \neq i$, we can write $q$ as a product of linear factors corresponding to these roots.
        have hq_factor : q = Polynomial.C (q.leadingCoeff) * ∏ r_j ∈ q.roots.toFinset, (Polynomial.X - Polynomial.C r_j) := by
          convert Polynomial.eq_prod_roots_of_splits_id _;
          · rw [ ← Multiset.toFinset_eq ];
            rfl;
            rw [ hq.1, Polynomial.roots_mul ] at h_nodup <;> aesop;
          · simp_all +decide [ Polynomial.splits_mul_iff ];
        -- Since $q$ is a polynomial with roots $r_j$ for $j \neq i$, we have $q.roots.toFinset = p.roots.toFinset.erase r$.
        have hq_roots : q.roots.toFinset = p.roots.toFinset.erase r := by
          rw [ hq.1, Polynomial.roots_mul ] <;> norm_num [ hq.2 ];
          exact ⟨ Polynomial.X_sub_C_ne_zero _, by rintro rfl; simp +decide at hq ⟩;
        exact ⟨ q.leadingCoeff, hq_roots ▸ hq_factor ⟩;
      -- By definition of $q$, we know that $q'(r) = c \sum_{j \neq r} \prod_{k \neq r, j} (r - r_k)$.
      have hq'_eval : Polynomial.eval r (Polynomial.derivative q) = c * ∑ r_j ∈ p.roots.toFinset.erase r, (∏ r_k ∈ p.roots.toFinset.erase r \ {r_j}, (r - r_k)) := by
        rw [ hc, Polynomial.derivative_mul, Polynomial.derivative_C ] ; norm_num;
        erw [ Polynomial.derivative_prod ];
        erw [ Polynomial.eval_finset_sum ] ; norm_num [ Polynomial.eval_prod ];
        simp +decide [ Finset.sdiff_singleton_eq_erase, Polynomial.eval_multiset_prod ];
        exact Or.inl rfl;
      -- By definition of $q$, we know that $q(r) = c \prod_{j \neq r} (r - r_j)$.
      have hq_eval : Polynomial.eval r q = c * ∏ r_j ∈ p.roots.toFinset.erase r, (r - r_j) := by
        simp +decide [ hc, Polynomial.eval_prod ];
      -- By definition of $q$, we know that $\sum_{j \neq r} \frac{1}{r - r_j} = \frac{q'(r)}{q(r)}$.
      have h_sum_inv : ∑ r_j ∈ p.roots.toFinset.erase r, (1 / (r - r_j)) = Polynomial.eval r (Polynomial.derivative q) / Polynomial.eval r q := by
        rw [ hq'_eval, hq_eval, eq_div_iff ];
        · simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Finset.sum_mul ];
          refine' Finset.sum_congr rfl fun x hx => _;
          field_simp;
          rw [ Finset.prod_eq_prod_diff_singleton_mul hx, mul_div_assoc ] ; norm_num [ sub_ne_zero.mpr ( show r ≠ x from by rintro rfl; exact Finset.notMem_erase _ _ hx ) ];
        · exact hq_eval ▸ hq.2;
      rw [ h_sum_inv, hq.1 ] ; norm_num [ Polynomial.derivative_mul, Polynomial.derivative_prod ] ; ring;

def scaled_coeff (n : ℕ) (p : ℝ[X]) (k : ℕ) : ℝ :=
  p.coeff (n - k) / (Nat.choose n k)

lemma scaled_coeff_boxplus (n : ℕ) (p q : ℝ[X]) (k : ℕ) (hk : k ≤ n) :
  scaled_coeff n (boxplus n p q) k = ∑ i ∈ range (k + 1), (Nat.choose k i) * scaled_coeff n p i * scaled_coeff n q (k - i) := by
    -- Expand both sides using the definitions of `scaled_coeff` and `boxplus`.
    unfold scaled_coeff boxplus
    -- Simplify the expression.
    simp [scaled_coeff, boxplus] at *;
    rw [ Finset.sum_eq_single ( k : ℕ ) ];
    · unfold boxplus_coeff;
      simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Nat.cast_choose ];
      refine Finset.sum_congr rfl fun i hi => ?_;
      rw [ Nat.cast_choose, Nat.cast_choose, Nat.cast_choose, Nat.cast_choose ] <;> try linarith [ Finset.mem_range.mp hi ];
      · field_simp;
      · exact le_trans ( Nat.sub_le _ _ ) hk;
    · grind;
    · exact fun h => False.elim <| h <| Finset.mem_range.mpr <| Nat.lt_succ_of_le hk

def kappa_4 (n : ℕ) (p : ℝ[X]) : ℝ :=
  p.coeff (n - 4) - (n - 2) * (n - 3) / (2 * n * (n - 1)) * (p.coeff (n - 2))^2

lemma kappa_4_additive (n : ℕ) (p q : ℝ[X])
    (hp : is_centered n p) (hq : is_centered n q) (hn : n ≥ 4) :
    kappa_4 n (boxplus n p q) = kappa_4 n p + kappa_4 n q := by
      -- By definition of $kappa_4$, we have
      unfold kappa_4;
      -- Let's simplify the expression using the definition of `boxplus`.
      have h_boxplus : (boxplus n p q).coeff (n - 4) = p.coeff (n - 4) * q.coeff n + p.coeff (n - 2) * q.coeff (n - 2) * ((n - 2) * (n - 3) / (n * (n - 1) : ℝ)) + p.coeff n * q.coeff (n - 4) ∧
                       (boxplus n p q).coeff (n - 2) = p.coeff (n - 2) * q.coeff n + p.coeff n * q.coeff (n - 2) := by
                         constructor <;> unfold boxplus <;> norm_num [ Polynomial.coeff_X_pow ];
                         · rw [ Finset.sum_eq_add_sum_diff_singleton ( Finset.mem_range.mpr ( by linarith : 4 < n + 1 ) ) ];
                           rw [ Finset.sum_eq_add ( 2 ) ( 0 ) ] <;> norm_num;
                           · rcases n with ( _ | _ | _ | _ | n ) <;> norm_num [ boxplus_coeff ] at *;
                             simp +arith +decide [ Finset.sum_range_succ', Nat.factorial ];
                             field_simp;
                             have := hp.2.2; have := hq.2.2; simp_all +decide [ Polynomial.coeff_eq_zero_of_natDegree_lt ] ; ring;
                           · intros; omega;
                           · intros; omega;
                         · rw [ Finset.sum_eq_add ( 2 ) ( 0 ) ] <;> norm_num [ boxplus_coeff ];
                           · rcases n with ( _ | _ | _ | n ) <;> norm_num [ Finset.sum_range_succ' ] at *;
                             simp_all +decide [ Nat.factorial_ne_zero, Nat.succ_sub_succ, mul_comm, mul_assoc, mul_left_comm, div_eq_mul_inv ];
                             cases hp ; cases hq ; aesop;
                           · intros; omega;
                           · grind;
      rcases hp with ⟨ hp₁, hp₂, hp₃ ⟩ ; rcases hq with ⟨ hq₁, hq₂, hq₃ ⟩ ; simp_all +decide [ Polynomial.Monic.def, Polynomial.leadingCoeff, Polynomial.natDegree_eq_of_degree_eq_some ] ; ring;
      grind

def cumulant (c : ℕ → ℝ) : ℕ → ℝ
| 0 => 0
| k + 1 => c (k + 1) - ∑ i ∈ (range k).attach, (Nat.choose k i.1) * c (k - i.1) * cumulant c (i.1 + 1)
termination_by k => k
decreasing_by
  simp_wf
  have h : i.val < k := Finset.mem_range.mp i.property
  omega

def kappa (n : ℕ) (p : ℝ[X]) (k : ℕ) : ℝ :=
  cumulant (fun i => scaled_coeff n p i) k

def binom_conv (a b : ℕ → ℝ) (n : ℕ) : ℝ :=
  ∑ i ∈ range (n + 1), (Nat.choose n i) * a i * b (n - i)

def seq_deriv (a : ℕ → ℝ) (n : ℕ) : ℝ := a (n + 1)

lemma seq_deriv_binom_conv (a b : ℕ → ℝ) (n : ℕ) :
    seq_deriv (binom_conv a b) n = binom_conv (seq_deriv a) b n + binom_conv a (seq_deriv b) n := by
      -- Apply Pascal's identity to split the sum into two parts.
      have h_split : ∑ k ∈ Finset.range (n + 2), Nat.choose (n + 1) k * a k * b (n + 1 - k) = ∑ k ∈ Finset.range (n + 2), Nat.choose n k * a k * b (n + 1 - k) + ∑ k ∈ Finset.range (n + 1), Nat.choose n k * a (k + 1) * b (n - k) := by
        rw [ Finset.sum_range_succ', Finset.sum_range_succ ];
        rw [ Finset.sum_range_succ' ] ; simp +decide [ Finset.sum_range_succ, Nat.choose_succ_succ ] ; ring;
        simpa only [ Finset.sum_add_distrib ] using by ring;
      convert h_split using 1;
      unfold binom_conv seq_deriv; norm_num [ Finset.sum_range_succ ] ; ring;
      rw [ add_right_comm ] ; refine' congr_arg₂ _ rfl ( Finset.sum_congr rfl fun x hx => _ ) ; rw [ Nat.add_sub_assoc ( by linarith [ Finset.mem_range.mp hx ] ) ] ;

def ff_cumulant (c : ℕ → ℝ) : ℕ → ℝ
| 0 => 0
| k + 1 => c (k + 1) - ∑ i ∈ (range k).attach, (Nat.choose k i.1) * c (k - i.1) * ff_cumulant c (i.1 + 1)
termination_by k => k
decreasing_by
  simp_wf
  have h : i.val < k := Finset.mem_range.mp i.property
  omega

def ff_kappa (n : ℕ) (p : ℝ[X]) (k : ℕ) : ℝ :=
  ff_cumulant (fun i => scaled_coeff n p i) k

def ff_binom_conv (a b : ℕ → ℝ) (n : ℕ) : ℝ :=
  ∑ i ∈ range (n + 1), (Nat.choose n i) * a i * b (n - i)

def ff_seq_deriv (a : ℕ → ℝ) (n : ℕ) : ℝ := a (n + 1)

lemma ff_seq_deriv_binom_conv (a b : ℕ → ℝ) (n : ℕ) :
    ff_seq_deriv (ff_binom_conv a b) n = ff_binom_conv (ff_seq_deriv a) b n + ff_binom_conv a (ff_seq_deriv b) n := by
      apply seq_deriv_binom_conv

lemma ff_binom_conv_comm (a b : ℕ → ℝ) (n : ℕ) :
    ff_binom_conv a b n = ff_binom_conv b a n := by
      -- By commutativity of multiplication, we can swap the order of the terms in each product.
      apply Finset.sum_bij (fun i _ => n - i);
      · exact fun i hi => Finset.mem_range.mpr ( Nat.lt_succ_of_le ( Nat.sub_le _ _ ) );
      · grind;
      · exact fun x hx => ⟨ n - x, Finset.mem_range.mpr ( Nat.lt_succ_of_le ( Nat.sub_le _ _ ) ), Nat.sub_sub_self ( Finset.mem_range_succ_iff.mp hx ) ⟩;
      · exact fun i hi => by rw [ Nat.choose_symm ( Finset.mem_range_succ_iff.mp hi ), tsub_tsub_cancel_of_le ( Finset.mem_range_succ_iff.mp hi ) ] ; ring;

lemma ff_binom_conv_assoc (a b c : ℕ → ℝ) (n : ℕ) :
    ff_binom_conv (ff_binom_conv a b) c n = ff_binom_conv a (ff_binom_conv b c) n := by
      -- By Fubini's theorem, we can interchange the order of summation.
      have h_fubini : ∑ k ∈ Finset.range (n + 1), (∑ j ∈ Finset.range (k + 1), (Nat.choose n k : ℝ) * (Nat.choose k j : ℝ) * (a j) * (b (k - j))) * (c (n - k)) = ∑ i ∈ Finset.range (n + 1), ∑ j ∈ Finset.range (n - i + 1), (Nat.choose n i : ℝ) * (Nat.choose (n - i) j : ℝ) * (a i) * (b j) * (c (n - i - j)) := by
        simp +decide only [sum_mul, sum_sigma'];
        refine' Finset.sum_bij ( fun x hx => ⟨ x.snd, x.fst - x.snd ⟩ ) _ _ _ _ <;> simp_all +decide [ Nat.sub_sub ];
        · exact fun x hx₁ hx₂ => ⟨ by linarith, by omega ⟩;
        · grind;
        · exact fun b hb₁ hb₂ => ⟨ b.fst + b.snd, b.fst, ⟨ by omega, by omega ⟩, by aesop ⟩;
        · intro x hx₁ hx₂; rw [ Nat.cast_choose, Nat.cast_choose, Nat.cast_choose, Nat.cast_choose ] <;> try omega;
          field_simp;
          rw [ show n - x.snd - ( x.fst - x.snd ) = n - x.fst by omega ] ; ring;
          rw [ Nat.add_sub_of_le ( by linarith ) ] ; ring;
      convert h_fubini using 1;
      · unfold ff_binom_conv; simp +decide [ Finset.sum_mul ] ;
        simp +decide only [mul_assoc, Finset.mul_sum _ _ _, sum_mul];
      · unfold ff_binom_conv;
        simp +decide only [mul_assoc, mul_left_comm, Finset.mul_sum _ _ _]

def ff_shifted_cumulant (c : ℕ → ℝ) (n : ℕ) : ℝ := ff_cumulant c (n + 1)

lemma ff_seq_deriv_eq_binom_conv_shifted_cumulant (c : ℕ → ℝ) (n : ℕ) (hc0 : c 0 = 1) :
    ff_seq_deriv c n = ff_binom_conv c (ff_shifted_cumulant c) n := by
      have h_split : ∑ j ∈ Finset.range (n + 1), (Nat.choose n j) * c j * ff_shifted_cumulant c (n - j) = ∑ j ∈ Finset.range (n + 1), (Nat.choose n j) * c (n - j) * ff_shifted_cumulant c j := by
        rw [ ← Finset.sum_flip ];
        exact Finset.sum_congr rfl fun x hx => by rw [ Nat.choose_symm ( Finset.mem_range_succ_iff.mp hx ), tsub_tsub_cancel_of_le ( Finset.mem_range_succ_iff.mp hx ) ] ;
      unfold ff_binom_conv ff_seq_deriv;
      unfold ff_shifted_cumulant at *;
      rw [ h_split, Finset.sum_range_succ ];
      rw [ eq_comm, ff_cumulant ];
      rw [ ← Finset.sum_attach ] ; aesop

lemma ff_binom_conv_add (a b c : ℕ → ℝ) (n : ℕ) :
    ff_binom_conv a (b + c) n = ff_binom_conv a b n + ff_binom_conv a c n := by
      -- By linearity of summation, we can split the sum into two separate sums.
      simp [ff_binom_conv, add_mul];
      -- By the distributive property of multiplication over addition, we can split the sum into two separate sums.
      simp [mul_add, Finset.sum_add_distrib]

lemma ff_binom_conv_cancel_left (a b c : ℕ → ℝ) (ha0 : a 0 ≠ 0)
    (h : ff_binom_conv a b = ff_binom_conv a c) : b = c := by
      -- By induction on $n$, we can show that $b_n = c_n$ for all $n$.
      have h_ind : ∀ n, ∀ m ≤ n, b m = c m := by
        -- By induction on $n$, we can show that $b_n = c_n$ for all $n$ using the equality of binomial convolutions.
        intro n
        induction' n with n ih;
        · replace h := congr_fun h 0; simp_all +decide [ ff_binom_conv ] ;
        · intro m hm; cases hm <;> simp_all +decide [ ff_binom_conv ] ;
          replace h := congr_fun h ( n + 1 ) ; simp_all +decide [ ff_binom_conv ] ;
          simp_all +decide [ Finset.sum_range_succ', Nat.choose_succ_self ];
      exact funext fun n => h_ind n n le_rfl

lemma ff_shifted_cumulant_additive (a b : ℕ → ℝ) (ha0 : a 0 = 1) (hb0 : b 0 = 1) :
    ff_shifted_cumulant (ff_binom_conv a b) = ff_shifted_cumulant a + ff_shifted_cumulant b := by
      -- By definition of binomial convolution, we know that the shifted cumulant of the binomial convolution of a and b is the sum of the shifted cumulants of a and b.
      have h_conv : ∀ n, ff_seq_deriv (ff_binom_conv a b) n = ff_binom_conv a (ff_seq_deriv b) n + ff_binom_conv (ff_seq_deriv a) b n := by
        -- By the properties of binomial coefficients and the definition of ff_seq_deriv, we can rewrite the right-hand side of the equation.
        intros n
        simp [ff_seq_deriv, ff_binom_conv];
        rw [ Finset.sum_range_succ', Finset.sum_range_succ ];
        rw [ Finset.sum_range_succ', Finset.sum_range_succ ] ; simp +decide [ Nat.choose_succ_succ, mul_add, add_mul, mul_assoc, mul_comm, mul_left_comm, Finset.sum_add_distrib ] ;
        rw [ ← Finset.sum_range_reflect ] ; simp +decide [ add_comm, add_left_comm, add_assoc, mul_comm, mul_assoc, mul_left_comm, Finset.sum_add_distrib ] ; ring;
        exact Finset.sum_congr rfl fun x hx => by rw [ show 1 + ( n - ( 1 + x ) ) = n - x from by linarith [ Nat.sub_add_cancel ( show 1 + x ≤ n from by linarith [ Finset.mem_range.mp hx ] ), Nat.sub_add_cancel ( show x ≤ n from by linarith [ Finset.mem_range.mp hx ] ) ] ] ; ring;
      -- By definition of binomial convolution, we know that the shifted cumulant of the binomial convolution of a and b is the sum of the shifted cumulants of a and b. Use this fact.
      have h_conv : ∀ n, ff_seq_deriv (ff_binom_conv a b) n = ff_binom_conv (ff_binom_conv a b) (ff_shifted_cumulant a + ff_shifted_cumulant b) n := by
        -- By definition of shifted cumulant, we know that the shifted cumulant of the binomial convolution of a and b is the sum of the shifted cumulants of a and b.
        have h_shifted_cumulant : ∀ n, ff_seq_deriv a n = ff_binom_conv a (ff_shifted_cumulant a) n ∧ ff_seq_deriv b n = ff_binom_conv b (ff_shifted_cumulant b) n := by
          exact fun n => ⟨ ff_seq_deriv_eq_binom_conv_shifted_cumulant a n ha0, ff_seq_deriv_eq_binom_conv_shifted_cumulant b n hb0 ⟩;
        simp_all +decide [ add_comm, add_left_comm, add_assoc, Finset.sum_add_distrib, mul_add, add_mul, Finset.mul_sum _ _ _, Finset.sum_mul ];
        intro n; rw [ funext fun i => h_shifted_cumulant i |>.1, funext fun i => h_shifted_cumulant i |>.2 ] ; simp +decide [ ff_binom_conv_add, add_comm, add_left_comm, add_assoc ] ;
        -- By the associativity of the binomial convolution, we can rearrange the terms.
        have h_assoc : ∀ (a b c : ℕ → ℝ) (n : ℕ), ff_binom_conv (ff_binom_conv a b) c n = ff_binom_conv a (ff_binom_conv b c) n := by
          exact?;
        simp +decide only [h_assoc];
        rw [ show ff_binom_conv ( ff_shifted_cumulant a ) b = ff_binom_conv b ( ff_shifted_cumulant a ) from funext fun n => ff_binom_conv_comm _ _ _ ];
      apply ff_binom_conv_cancel_left;
      rotate_right;
      exact fun n => ( ff_binom_conv a b ) n;
      · unfold ff_binom_conv; aesop;
      · funext n; exact (by
        rw [ ← h_conv, ff_seq_deriv_eq_binom_conv_shifted_cumulant ];
        unfold ff_binom_conv; norm_num [ ha0, hb0 ] ;)

lemma ff_cumulant_congr (a b : ℕ → ℝ) (n : ℕ) (h : ∀ k, k ≤ n → a k = b k) :
    ff_cumulant a n = ff_cumulant b n := by
      -- We proceed by induction on $n$.
      induction' n with n ih;
      · -- By definition of ff_cumulant, we know that ff_cumulant a 0 = a 0 and ff_cumulant b 0 = b 0.
        simp [ff_cumulant];
      · unfold ff_cumulant;
        rw [ h ];
        · -- Apply the induction hypothesis to each term in the sum.
          have h_ind : ∀ i ∈ Finset.range n, ff_cumulant a (i + 1) = ff_cumulant b (i + 1) := by
            intros i hi;
            have h_ind : ∀ k ≤ i, ff_cumulant a (k + 1) = ff_cumulant b (k + 1) := by
              intro k hk;
              induction' k using Nat.strong_induction_on with k ih;
              unfold ff_cumulant;
              grind;
            exact h_ind i le_rfl;
          exact congr rfl ( Finset.sum_congr rfl fun i hi => by rw [ h_ind i ( Finset.mem_range.mpr ( Finset.mem_range.mp i.2 ) ), h ( n - i ) ( Nat.sub_le_of_le_add <| by linarith [ Finset.mem_range.mp i.2 ] ) ] );
        · norm_num

theorem ff_kappa_additive (n : ℕ) (p q : ℝ[X])
    (hp : p.Monic) (hq : q.Monic) (hp_deg : p.natDegree = n) (hq_deg : q.natDegree = n) :
    ∀ k, k ≤ n → ff_kappa n (boxplus n p q) k = ff_kappa n p k + ff_kappa n q k := by
      -- By definition of $ff_cumulant$, we know that it is linear with respect to the sequences $a$ and $b$.
      have h_cumulant_linear : ∀ (a b : ℕ → ℝ), a 0 = 1 → b 0 = 1 → ∀ n, ff_cumulant (ff_binom_conv a b) n = ff_cumulant a n + ff_cumulant b n := by
        intros a b ha hb n
        induction' n using Nat.strong_induction_on with n ih;
        -- Apply the lemma that states the shifted cumulant of the binomial convolution is the sum of the shifted cumulants.
        have h_shifted_cumulant : ff_shifted_cumulant (ff_binom_conv a b) = ff_shifted_cumulant a + ff_shifted_cumulant b := by
          exact?;
        rcases n <;> simp_all +decide [ funext_iff ];
        · unfold ff_cumulant; aesop;
        · convert h_shifted_cumulant ‹_› using 1;
      -- By definition of $scaled_coeff$, we know that $scaled_coeff n (boxplus n p q) = binom_conv (scaled_coeff n p) (scaled_coeff n q)$.
      have h_scaled_coeff_boxplus : ∀ k ≤ n, scaled_coeff n (boxplus n p q) k = ff_binom_conv (fun i => scaled_coeff n p i) (fun i => scaled_coeff n q i) k := by
        -- By definition of $scaled_coeff$, we know that $scaled_coeff n (boxplus n p q) k = \sum_{i=0}^{k} \binom{k}{i} scaled_coeff n p i * scaled_coeff n q (k-i)$.
        intros k hk
        apply scaled_coeff_boxplus n p q k hk;
      -- By definition of $scaled_coeff$, we know that $scaled_coeff n p 0 = 1$ and $scaled_coeff n q 0 = 1$.
      have h_scaled_coeff_zero : scaled_coeff n p 0 = 1 ∧ scaled_coeff n q 0 = 1 := by
        -- Since $p$ and $q$ are monic polynomials of degree $n$, their leading coefficients are $1$.
        have h_leading_coeff : p.coeff n = 1 ∧ q.coeff n = 1 := by
          exact ⟨ by rw [ ← hp_deg, hp.coeff_natDegree ], by rw [ ← hq_deg, hq.coeff_natDegree ] ⟩;
        unfold scaled_coeff; aesop;
      intros k hk
      have h_cumulant_eq : ff_cumulant (fun i => scaled_coeff n (boxplus n p q) i) k = ff_cumulant (fun i => ff_binom_conv (fun i => scaled_coeff n p i) (fun i => scaled_coeff n q i) i) k := by
        apply ff_cumulant_congr;
        exact fun i hi => h_scaled_coeff_boxplus i ( le_trans hi hk );
      exact h_cumulant_eq.trans ( h_cumulant_linear _ _ h_scaled_coeff_zero.1 h_scaled_coeff_zero.2 k )

lemma ff_cumulant_additive (a b : ℕ → ℝ) (ha0 : a 0 = 1) (hb0 : b 0 = 1) :
    ∀ k, ff_cumulant (ff_binom_conv a b) k = ff_cumulant a k + ff_cumulant b k := by
      have h_add : ff_shifted_cumulant (ff_binom_conv a b) = ff_shifted_cumulant a + ff_shifted_cumulant b := by
        exact?;
      intro k; induction' k with k ih <;> simp_all +decide [ funext_iff ] ;
      · unfold ff_cumulant; aesop;
      · convert h_add k using 1

lemma Phi_comp_add_C (p : ℝ[X]) (c : ℝ) :
  Phi (p.comp (X + C c)) = Phi p := by
    -- By definition of polynomial composition, the roots of $p(x+c)$ are $r_i - c$ where $r_i$ are the roots of $p(x)$.
    have h_roots : (p.comp (Polynomial.X + Polynomial.C c)).roots.toFinset = Finset.image (fun r => r - c) p.roots.toFinset := by
      ext; simp [Polynomial.eval_comp, Polynomial.eval_add, Polynomial.eval_X, Polynomial.eval_C];
      rw [ Polynomial.comp_eq_zero_iff ] ; aesop;
    unfold Phi;
    rw [ h_roots, Finset.sum_image ] <;> norm_num;
    refine' Finset.sum_congr rfl fun x hx => _;
    rw [ show ( Multiset.map ( fun r => r - c ) p.roots ).toFinset.erase ( x - c ) = Finset.image ( fun r => r - c ) ( p.roots.toFinset.erase x ) from ?_, Finset.sum_image ] <;> aesop

lemma invPhi_comp_add_C (p : ℝ[X]) (c : ℝ) :
  invPhi (p.comp (X + C c)) = invPhi p := by
    unfold invPhi;
    rw [ show ( Polynomial.comp p ( Polynomial.X + Polynomial.C c ) |> Polynomial.roots ) = Multiset.map ( fun x => x - c ) ( p.roots ) from ?_ ];
    · by_cases h : Multiset.Nodup p.roots ∧ 1 < Multiset.card p.roots <;> simp_all +decide [ Multiset.nodup_map_iff_of_injective, Function.Injective ];
      · exact?;
      · grind;
    · ext x;
      rw [ Multiset.count_map ];
      rw [ show ( Polynomial.comp p ( Polynomial.X + Polynomial.C c ) |> Polynomial.roots ) = Multiset.map ( fun y => y - c ) ( p.roots ) from ?_ ];
      · rw [ Multiset.count_map ];
      · ext y; simp [Polynomial.eval_comp, Polynomial.eval_add, Polynomial.eval_X, Polynomial.eval_C];
        have h_mult : Polynomial.rootMultiplicity y (p.comp (Polynomial.X + Polynomial.C c)) = Polynomial.rootMultiplicity (y + c) p := by
          rw [ Polynomial.rootMultiplicity_eq_natTrailingDegree, Polynomial.rootMultiplicity_eq_natTrailingDegree ];
          norm_num [ add_assoc, Polynomial.comp_assoc ];
        rw [ Multiset.count_map ];
        rw [ show ( Multiset.filter ( fun a => y = a - c ) p.roots ) = Multiset.filter ( fun a => a = y + c ) p.roots by congr; ext; constructor <;> intro <;> linarith ] ; rw [ Multiset.filter_eq' ] ; aesop

lemma boxplus_monomials (n u v : ℕ) (hu : u ≤ n) (hv : v ≤ n) :
  boxplus n (X^u) (X^v) =
  if u + v < n then 0
  else C ((Nat.factorial u * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial (u + v - n))) * X^(u + v - n) := by
    -- Assume $n+1 \leq u+v$. In this case $n-k \leq k \implies k \geq \frac{n-1}{2}$.
    by_cases huv : u + v < n
    -- Case 1
    -- If $u+v < n$, then for any $k$, either $u > n-i$ or $v > n-j$, making the term zero.
    have h_zero : ∀ k ∈ Finset.range (n + 1), boxplus_coeff n (.X ^ u) (.X ^ v) k = 0 := by
      intro k hk
      simp [boxplus_coeff, huv];
      simp_all +decide [ Finset.sum_ite ];
      exact Or.inl fun x hx₁ hx₂ hx₃ => by omega;
    exact if_pos huv ▸ Finset.sum_eq_zero fun k hk => by aesop;
    -- Case 2
    -- In this case, the boxplus convolution of $X^u$ and $X^v$ is a monomial $X^{u+v-n}$ scaled by a factor involving factorials.
    have h_monomial : ∀ k, k ∈ Finset.range (n + 1) → (boxplus_coeff n (Polynomial.X ^ u) (Polynomial.X ^ v) k) = if k = 2 * n - u - v then (u.factorial * v.factorial : ℝ) / (n.factorial * (u + v - n).factorial) else 0 := by
      intro k hk
      simp [boxplus_coeff];
      split_ifs <;> simp_all +decide [ Finset.sum_ite ];
      · rw [ show n - ( 2 * n - u - v ) = u + v - n by omega ];
        rw [ Finset.card_eq_one.mpr ] ; aesop;
        use n - u;
        grind;
      · contrapose! huv; omega;
    simp_all +decide [ boxplus ];
    rw [ Finset.sum_eq_single ( 2 * n - u - v ) ];
    · rw [ h_monomial ];
      · rw [ show n - ( 2 * n - u - v ) = u + v - n by omega ] ; aesop;
      · omega;
    · aesop;
    · exact fun h => False.elim <| h <| Finset.mem_range.mpr <| by omega;

lemma boxplus_comp_add_C_left_monomials (n u v : ℕ) (c : ℝ)
  (hu : u ≤ n) (hv : v ≤ n) :
  boxplus n ((X + C c)^u) (X^v) = (boxplus n (X^u) (X^v)).comp (X + C c) := by
    -- By linearity of boxplus, we can expand both sides.
    have h_expand : boxplus n ((Polynomial.X + (Polynomial.C c)) ^ u) (Polynomial.X ^ v) = Finset.sum (Finset.range (u + 1)) (fun k => Polynomial.C ((Nat.choose u k : ℝ) * c ^ (u - k)) * boxplus n (Polynomial.X ^ k) (Polynomial.X ^ v)) := by
      -- Apply the linearity of boxplus to split the polynomial into a sum of monomials.
      have h_linear : ∀ p q : Polynomial ℝ, boxplus n (p + q) (Polynomial.X ^ v) = boxplus n p (Polynomial.X ^ v) + boxplus n q (Polynomial.X ^ v) := by
        unfold boxplus;
        unfold boxplus_coeff; norm_num [ Finset.sum_add_distrib ] ;
        intro p q; rw [ ← Finset.sum_add_distrib ] ; congr; ext; simp +decide [ Finset.sum_add_distrib, mul_add ] ;
        simp +decide [ Finset.sum_ite, Finset.filter_congr, Finset.filter_eq', Finset.filter_ne', Polynomial.coeff_mul ];
        rw [ ← Finset.sum_add_distrib ] ; congr ; ext ; rw [ ← Finset.sum_add_distrib ] ; congr ; ext ; aesop;
      have h_expand : ∀ (p : Polynomial ℝ), boxplus n p (Polynomial.X ^ v) = ∑ k ∈ Finset.range (p.natDegree + 1), Polynomial.C (p.coeff k) * boxplus n (Polynomial.X ^ k) (Polynomial.X ^ v) := by
        intro p
        have h_sum : boxplus n p (Polynomial.X ^ v) = ∑ k ∈ Finset.range (p.natDegree + 1), boxplus n (Polynomial.C (p.coeff k) * Polynomial.X ^ k) (Polynomial.X ^ v) := by
          -- By definition of polynomial multiplication and the linearity of boxplus, we can expand both sides.
          have h_expand : p = ∑ k ∈ Finset.range (p.natDegree + 1), Polynomial.C (p.coeff k) * Polynomial.X ^ k := by
            conv_lhs => rw [ p.as_sum_range_C_mul_X_pow ] ;
          conv_lhs => rw [ h_expand ];
          induction' ( Finset.range ( p.natDegree + 1 ) ) using Finset.induction <;> norm_num at *;
          · specialize h_linear 0 ( Polynomial.X ^ v ) ; norm_num at h_linear ; linear_combination' h_linear;
          · grind;
        -- By definition of boxplus, we can factor out the constant coefficient.
        have h_factor : ∀ k : ℕ, boxplus n (Polynomial.C (p.coeff k) * Polynomial.X ^ k) (Polynomial.X ^ v) = Polynomial.C (p.coeff k) * boxplus n (Polynomial.X ^ k) (Polynomial.X ^ v) := by
          intro k
          simp [boxplus];
          simp +decide [ boxplus_coeff, Finset.mul_sum _ _ _ ];
          simp +decide [ Finset.mul_sum _ _ _, mul_assoc, mul_left_comm, Finset.sum_mul ];
          exact Finset.sum_congr rfl fun _ _ => Finset.sum_congr rfl fun _ _ => by split_ifs <;> simp +decide [ *, mul_assoc, mul_left_comm ] ;
        aesop;
      rw [ h_expand ];
      norm_num [ Polynomial.natDegree_add_eq_left_of_natDegree_lt, Polynomial.coeff_X_add_C_pow ];
      ac_rfl;
    -- By definition of boxplus, we know that boxplus n (Polynomial.X ^ k) (Polynomial.X ^ v) is zero unless k + v ≥ n.
    have h_boxplus_nonzero : ∀ k ∈ Finset.range (u + 1), boxplus n (Polynomial.X ^ k) (Polynomial.X ^ v) = if k + v < n then 0 else Polynomial.C ((Nat.factorial k * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial (k + v - n))) * Polynomial.X ^ (k + v - n) := by
      exact fun k hk => boxplus_monomials n k v ( by linarith [ Finset.mem_range.mp hk ] ) ( by linarith [ Finset.mem_range.mp hk ] );
    by_cases h : u + v < n <;> simp_all +decide [ Polynomial.eval_finset_sum ];
    · exact Finset.sum_eq_zero fun x hx => if_pos <| by linarith [ Finset.mem_range.mp hx ] ;
    · -- By simplifying, we can see that both sides are equal.
      have h_simp : ∀ j ∈ Finset.range (u + v - n + 1), ∑ k ∈ Finset.Icc (n - v) u, (Nat.choose u k : ℝ) * c ^ (u - k) * (Nat.factorial k * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial (k + v - n)) * (if k + v - n = j then 1 else 0) = (Nat.factorial u * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial (u + v - n)) * (Nat.choose (u + v - n) j : ℝ) * c ^ (u + v - n - j) := by
        intro j hj
        have h_simp : ∑ k ∈ Finset.Icc (n - v) u, (Nat.choose u k : ℝ) * c ^ (u - k) * (Nat.factorial k * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial (k + v - n)) * (if k + v - n = j then 1 else 0) = (Nat.choose u (n - v + j) : ℝ) * c ^ (u - (n - v + j)) * (Nat.factorial (n - v + j) * Nat.factorial v : ℝ) / (Nat.factorial n * Nat.factorial j) := by
          rw [ Finset.sum_eq_single ( n - v + j ) ] <;> norm_num;
          · grind;
          · intros; omega;
          · exact fun h₁ h₂ => Or.inl <| Or.inl <| Or.inl <| Nat.choose_eq_zero_of_lt h₁;
        rw [ h_simp, Nat.cast_choose, Nat.cast_choose ];
        · field_simp;
          rw [ show u + v - n - j = u - ( n - v + j ) by omega ] ; ring;
        · linarith [ Finset.mem_range.mp hj ];
        · linarith [ Finset.mem_range.mp hj, Nat.sub_add_cancel hv, Nat.sub_add_cancel h ];
      refine' Polynomial.funext fun x => _;
      simp_all +decide [ Polynomial.eval_finset_sum ];
      convert Finset.sum_congr rfl fun j hj => congr_arg ( fun y => y * x ^ j ) ( h_simp j <| Finset.mem_range.mp hj ) using 1;
      · simp +decide [ Finset.sum_ite, Finset.sum_mul _ _ _ ];
        rw [ ← Finset.sum_subset ( show Finset.Icc ( n - v ) u ⊆ Finset.range ( u + 1 ) from fun x hx => Finset.mem_range.mpr ( by linarith [ Finset.mem_Icc.mp hx ] ) ) ];
        · rw [ Finset.sum_sigma' ];
          refine' Finset.sum_bij ( fun x hx => ⟨ x + v - n, x ⟩ ) _ _ _ _ <;> simp +decide;
          · exact fun a ha₁ ha₂ => ⟨ by omega, ha₁, ha₂ ⟩;
          · exact fun b hb₁ hb₂ hb₃ hb₄ => ⟨ b.snd, ⟨ hb₂, hb₃ ⟩, by aesop ⟩;
          · intro a ha₁ ha₂; rw [ if_neg ( by linarith ) ] ; norm_num ; ring;
        · intro k hk₁ hk₂; split_ifs <;> simp_all +decide [ Nat.choose_eq_zero_of_lt ] ;
      · rw [ if_neg ( by linarith ) ] ; simp +decide [ Polynomial.eval_finset_sum ] ; ring;
        rw [ add_comm, add_pow ] ; ring;
        simp +decide only [mul_assoc, Finset.mul_sum _ _ _]

lemma exists_shift_centered (n : ℕ) (p : ℝ[X]) (hn : n > 0)
  (hp_monic : p.Monic) (hp_deg : p.natDegree = n) :
  ∃ c : ℝ, (p.comp (X + C c)).coeff (n - 1) = 0 := by
    -- The coefficient of $X^{n-1}$ in $p(X+c)$ is given by the Taylor expansion formula or binomial expansion.
    have h_coeff : ∀ c : ℝ, p.comp (Polynomial.X + Polynomial.C c) = Finset.sum (Finset.range (n + 1)) (fun k => Polynomial.C (p.coeff k) * (Polynomial.X + Polynomial.C c)^k) := by
      intro c; nth_rw 1 [ p.as_sum_range_C_mul_X_pow ] ; simp +decide [ ← Polynomial.C_mul_X_pow_eq_monomial, hp_deg ] ;
    -- By comparing coefficients, we can see that the coefficient of $X^{n-1}$ in $p(X+c)$ is given by $n c + a_{n-1}$.
    have h_coeff_n_minus_1 : ∀ c : ℝ, (p.comp (Polynomial.X + Polynomial.C c)).coeff (n - 1) = n * c + p.coeff (n - 1) := by
      intro c; rw [ h_coeff c ] ; simp +decide [ Polynomial.coeff_X_add_C_pow ] ;
      rw [ Finset.sum_eq_add ( n - 1 ) n ] <;> norm_num [ Nat.choose_succ_succ, hn ];
      · rcases n with ( _ | _ | n ) <;> simp_all +decide [ Nat.choose_succ_succ, add_comm ];
        · rw [ ← hp_deg, hp_monic.coeff_natDegree ] ; ring;
        · simp_all +decide [ add_comm 1, Nat.choose_succ_succ, Polynomial.Monic.def, Polynomial.leadingCoeff, Polynomial.natDegree_eq_of_degree_eq_some ] ; ring;
      · omega;
      · intro k hk₁ hk₂ hk₃; rcases n with ( _ | _ | n ) <;> simp_all +decide [ Nat.choose_eq_zero_of_lt ] ;
        · interval_cases k <;> contradiction;
        · exact Or.inr <| Or.inr <| Nat.choose_eq_zero_of_lt <| lt_of_le_of_ne ( by omega ) hk₂;
      · exact fun h => absurd h ( by omega );
    exact ⟨ -p.coeff ( n - 1 ) / n, by rw [ h_coeff_n_minus_1, mul_div_cancel₀ _ ( by positivity ) ] ; ring ⟩

lemma boxplus_comp_add_C_left_le (n : ℕ) (p q : ℝ[X]) (c : ℝ)
  (hp : p.natDegree ≤ n) (hq : q.natDegree ≤ n) :
  boxplus n (p.comp (X + C c)) q = (boxplus n p q).comp (X + C c) := by
    -- By linearity of `boxplus`, we can expand both sides as sums of `boxplus` operations on monomials.
    have h_expand : ∀ (p q : ℝ[X]) (c : ℝ), p.natDegree ≤ n → q.natDegree ≤ n → (boxplus n (p.comp (Polynomial.X + Polynomial.C c)) q) = ∑ u ∈ Finset.range (n + 1), (p.coeff u) • ∑ v ∈ Finset.range (n + 1), (q.coeff v) • (boxplus n ((Polynomial.X + Polynomial.C c)^u) (Polynomial.X^v)) := by
      intros p q c hp hq
      have h_expand : boxplus n (p.comp (Polynomial.X + Polynomial.C c)) q = ∑ u ∈ Finset.range (n + 1), (p.coeff u) • boxplus n ((Polynomial.X + Polynomial.C c)^u) q := by
        rw [ show p.comp ( Polynomial.X + Polynomial.C c ) = ∑ u ∈ Finset.range ( n + 1 ), p.coeff u • ( Polynomial.X + Polynomial.C c ) ^ u from ?_ ];
        · unfold boxplus;
          simp +decide [ boxplus_coeff, Finset.mul_sum _ _ _, Finset.sum_mul, mul_assoc, mul_left_comm, Finset.sum_add_distrib ];
          simp +decide [ Finset.smul_sum, mul_assoc, mul_left_comm, Finset.mul_sum _ _ _, Polynomial.smul_eq_C_mul ];
          rw [ Finset.sum_comm ];
          exact Finset.sum_congr rfl fun _ _ => Finset.sum_comm;
        · rw [ Polynomial.comp, Polynomial.eval₂_eq_sum_range' ];
          exacts [ Finset.sum_congr rfl fun _ _ => by rw [ Polynomial.smul_eq_C_mul ], Nat.lt_succ_of_le hp ];
      have h_expand_q : ∀ (p q : ℝ[X]) (c : ℝ), p.natDegree ≤ n → q.natDegree ≤ n → boxplus n p q = ∑ v ∈ Finset.range (n + 1), (q.coeff v) • boxplus n p (Polynomial.X^v) := by
        intros p q c hp hq
        have h_expand_q : q = ∑ v ∈ Finset.range (n + 1), (q.coeff v) • Polynomial.X^v := by
          conv_lhs => rw [ Polynomial.as_sum_range' q ( n + 1 ) ( by linarith ) ];
          norm_num [ Polynomial.smul_eq_C_mul, ← Polynomial.C_mul_X_pow_eq_monomial ];
        conv_lhs => rw [ h_expand_q ];
        unfold boxplus;
        simp +decide [ boxplus_coeff, Finset.mul_sum _ _ _, Finset.sum_mul ];
        simp +decide [ Finset.smul_sum, Finset.sum_smul, Polynomial.smul_eq_C_mul ];
        rw [ Finset.sum_comm ];
        refine' Finset.sum_congr rfl fun x hx => _;
        rw [ Finset.sum_comm, Finset.sum_congr rfl ] ; simp +contextual [ Finset.sum_ite ];
        intro y hy; rw [ Finset.sum_eq_single ( n - ( x - y ) ) ] <;> simp +contextual [ Nat.sub_sub_self ( show x - y ≤ n from Nat.sub_le_of_le_add <| by linarith [ Finset.mem_range.mp hx ] ) ] ;
        · rw [ if_pos ( Nat.lt_succ_of_le ( Nat.sub_le _ _ ) ) ] ; norm_num ; ring;
        · exact fun b hb hb' => Or.inr fun h => False.elim <| hb' <| h.symm ▸ rfl;
        · exact fun h => absurd h ( by omega );
      convert h_expand using 2;
      rw [ h_expand_q _ _ c ( by exact le_trans ( Polynomial.natDegree_pow_le ) ( by simpa using by linarith [ Finset.mem_range.mp ‹_› ] ) ) hq ];
    have h_expand_rhs : ∀ (p q : ℝ[X]) (c : ℝ), p.natDegree ≤ n → q.natDegree ≤ n → (boxplus n p q).comp (Polynomial.X + Polynomial.C c) = ∑ u ∈ Finset.range (n + 1), (p.coeff u) • ∑ v ∈ Finset.range (n + 1), (q.coeff v) • (boxplus n (Polynomial.X^u) (Polynomial.X^v)).comp (Polynomial.X + Polynomial.C c) := by
      intros p q c hp hq
      have h_expand_rhs : (boxplus n p q) = ∑ u ∈ Finset.range (n + 1), (p.coeff u) • ∑ v ∈ Finset.range (n + 1), (q.coeff v) • (boxplus n (Polynomial.X^u) (Polynomial.X^v)) := by
        convert h_expand p q 0 hp hq using 1 ; norm_num [ Polynomial.smul_eq_C_mul ];
        norm_num [ Polynomial.smul_eq_C_mul ];
      simp +decide [ h_expand_rhs, Polynomial.smul_eq_C_mul ];
    rw [ h_expand p q c hp hq, h_expand_rhs p q c hp hq ];
    refine' Finset.sum_congr rfl fun u hu => congr_arg _ ( Finset.sum_congr rfl fun v hv => congr_arg _ <| _ );
    convert boxplus_comp_add_C_left_monomials n u v c ( Finset.mem_range_succ_iff.mp hu ) ( Finset.mem_range_succ_iff.mp hv ) using 1

lemma boxplus_comp_add_C_le (n : ℕ) (p q : ℝ[X]) (c d : ℝ)
  (hp : p.natDegree ≤ n) (hq : q.natDegree ≤ n) :
  boxplus n (p.comp (X + C c)) (q.comp (X + C d)) = (boxplus n p q).comp (X + C (c + d)) := by
    -- By commutativity and left-translation covariance, we can rewrite the left-hand side.
    have h_lhs : (boxplus n (p.comp (.X + (.C c))) (q.comp (.X + (.C d)))) = (boxplus n (q.comp (.X + (.C d))) (p.comp (.X + (.C c)))) := by
      apply boxplus_comm;
    -- By left-translation covariance, we can rewrite the right-hand side.
    have h_rhs : (boxplus n (q.comp (.X + (.C d))) (p.comp (.X + (.C c)))) = ((boxplus n q (p.comp (.X + (.C c)))).comp (.X + (.C d))) := by
      apply_rules [ boxplus_comp_add_C_left_le ];
      rw [ Polynomial.natDegree_comp, Polynomial.natDegree_X_add_C ] ; linarith;
    -- By left-translation covariance, we can rewrite the right-hand side further.
    have h_rhs'' : (boxplus n (p.comp (.X + (.C c)))) q = ((boxplus n p q).comp (.X + (.C c))) := by
      apply boxplus_comp_add_C_left_le n p q c hp hq
    rw [ h_lhs, h_rhs, ← boxplus_comm ];
    rw [ h_rhs'', Polynomial.comp_assoc ];
    norm_num [ Polynomial.comp_assoc ];
    exact congr_arg _ ( by ring )

theorem ff_kappa_additive_v2 (n : ℕ) (p q : ℝ[X])
    (hp : p.Monic) (hq : q.Monic) (hp_deg : p.natDegree = n) (hq_deg : q.natDegree = n) :
    ∀ k, k ≤ n → ff_kappa n (boxplus n p q) k = ff_kappa n p k + ff_kappa n q k := by
      -- Apply the lemma that states the additivity of the cumulants under the boxplus operation.
      apply ff_kappa_additive n p q hp hq hp_deg hq_deg

lemma boxplus_deriv_at_zero (n : ℕ) (p q : ℝ[X]) (w : ℕ)
  (hp_deg : p.natDegree ≤ n) (hq_deg : q.natDegree ≤ n) :
  (Polynomial.derivative^[w] (boxplus n p q)).eval 0 =
  (1 / Nat.factorial n) * ∑ u ∈ range (n + w + 1),
    let v := n + w - u
    (Polynomial.derivative^[u] p).eval 0 * (Polynomial.derivative^[v] q).eval 0 := by
      by_cases hw : n < w;
      · rw [ Polynomial.iterate_derivative_eq_zero ];
        · rw [ Finset.sum_eq_zero ] ; aesop;
          intro x hx; by_cases hx' : x ≤ n <;> simp_all +decide [ Polynomial.iterate_derivative_eq_zero ] ;
          · exact Or.inr ( by rw [ Polynomial.iterate_derivative_eq_zero ( by omega ) ] ; norm_num );
          · exact Or.inl ( by rw [ Polynomial.iterate_derivative_eq_zero ( by linarith ) ] ; norm_num );
        · refine' lt_of_le_of_lt ( Polynomial.natDegree_sum_le _ _ ) _;
          refine' lt_of_le_of_lt ( Finset.sup_le _ ) _;
          exacts [ n, fun k hk => le_trans ( Polynomial.natDegree_C_mul_X_pow_le _ _ ) ( Nat.sub_le _ _ ), by linarith ];
      · -- By definition of boxplus, we can write its w-th derivative at 0.
        have h_deriv : (Polynomial.derivative^[w] (boxplus n p q)).eval 0 =
          (Nat.factorial w) * (boxplus_coeff n p q (n - w)) := by
            -- By definition of $boxplus$, we know that its $w$-th derivative at $0$ is given by the sum of the $w$-th derivatives of its terms.
            have h_deriv_term : ∀ k ∈ Finset.range (n + 1), Polynomial.eval 0 ((Polynomial.derivative^[w] (Polynomial.C (boxplus_coeff n p q k) * Polynomial.X ^ (n - k)))) = if k = n - w then (Nat.factorial w) * (boxplus_coeff n p q (n - w)) else 0 := by
              intro k hk; split_ifs <;> simp_all +decide [ Polynomial.coeff_iterate_derivative ] ;
              · rw [ Nat.sub_sub_self hw ] ; norm_num [ Polynomial.eval, Polynomial.coeff_iterate_derivative ] ; ring;
                rw [ Nat.descFactorial_self ];
              · by_cases h : n - k < w <;> simp_all +decide [ Polynomial.eval, Polynomial.coeff_iterate_derivative ];
                · exact Or.inr ( ne_of_gt h );
                · omega;
            rw [ show boxplus n p q = ∑ k ∈ Finset.range ( n + 1 ), Polynomial.C ( boxplus_coeff n p q k ) * Polynomial.X ^ ( n - k ) from ?_ ];
            · convert Finset.sum_congr rfl h_deriv_term using 1;
              · induction' ( Finset.range ( n + 1 ) ) using Finset.induction <;> aesop;
              · simp +zetaDelta at *;
                exact fun h => absurd h ( by omega );
            · exact?;
        -- By definition of $boxplus_coeff$, we can rewrite the sum.
        have h_sum : ∑ u ∈ Finset.range (n + w + 1), (Polynomial.eval 0 ((Polynomial.derivative^[u] p))) * (Polynomial.eval 0 ((Polynomial.derivative^[n + w - u] q))) =
          ∑ i ∈ Finset.range (n - w + 1), (Nat.factorial (n - i) * Nat.factorial (w + i) : ℝ) *
            (p.coeff (n - i)) * (q.coeff (w + i)) := by
              have h_sum : ∑ u ∈ Finset.range (n + w + 1), (Polynomial.eval 0 ((Polynomial.derivative^[u] p))) * (Polynomial.eval 0 ((Polynomial.derivative^[n + w - u] q))) =
                ∑ u ∈ Finset.range (n + 1), (Nat.factorial u * Nat.factorial (n + w - u) : ℝ) * (p.coeff u) * (q.coeff (n + w - u)) := by
                  have h_sum : ∀ u ∈ Finset.range (n + w + 1), (Polynomial.eval 0 ((Polynomial.derivative^[u] p))) * (Polynomial.eval 0 ((Polynomial.derivative^[n + w - u] q))) =
                    (if u ≤ n then (Nat.factorial u * Nat.factorial (n + w - u) : ℝ) * (p.coeff u) * (q.coeff (n + w - u)) else 0) := by
                      intro u hu; split_ifs <;> simp_all +decide [ Polynomial.eval, Polynomial.coeff_iterate_derivative ] ;
                      · simp +decide [ Nat.descFactorial_self, mul_assoc, mul_comm, mul_left_comm ];
                      · exact Or.inl <| Polynomial.coeff_eq_zero_of_natDegree_lt <| by linarith;
                  rw [ Finset.sum_congr rfl h_sum, Finset.sum_ite ];
                  norm_num [ Finset.sum_filter ];
                  rw [ ← Finset.sum_range_add_sum_Ico _ ( by linarith : n + 1 ≤ n + w + 1 ) ];
                  rw [ Finset.sum_congr rfl fun x hx => if_pos <| by linarith [ Finset.mem_range.mp hx ], Finset.sum_congr rfl fun x hx => if_neg <| by linarith [ Finset.mem_Ico.mp hx ] ] ; norm_num;
              rw [ h_sum, ← Finset.sum_flip ];
              rw [ ← Finset.sum_subset ( Finset.range_mono ( Nat.succ_le_succ ( Nat.sub_le n w ) ) ) ];
              · refine' Finset.sum_congr rfl fun x hx => _;
                rw [ show n + w - ( n - x ) = w + x by rw [ tsub_eq_of_eq_add ] ; linarith [ Nat.sub_add_cancel ( show x ≤ n from by linarith [ Finset.mem_range.mp hx, Nat.sub_le n w ] ) ] ];
              · norm_num +zetaDelta at *;
                exact fun x hx₁ hx₂ => Or.inr <| Polynomial.coeff_eq_zero_of_natDegree_lt <| by omega;
        simp_all +decide [ boxplus_coeff ];
        rw [ Finset.mul_sum _ _ _ ] ; rw [ Finset.mul_sum _ _ _ ] ; refine' Finset.sum_congr rfl fun i hi => _ ; rw [ Nat.sub_sub_self ( by linarith [ Finset.mem_range.mp hi, Nat.sub_add_cancel hw ] ) ] ; ring;
        rw [ show n - ( n - w - i ) = w + i by exact Nat.sub_eq_of_eq_add <| by linarith [ Nat.sub_add_cancel <| show w ≤ n from hw, Nat.sub_add_cancel <| show i ≤ n - w from Finset.mem_range_succ_iff.mp hi ] ] ; norm_num [ Nat.factorial_ne_zero, mul_assoc, mul_comm, mul_left_comm ]

lemma boxplus_centered_is_centered (n : ℕ) (p q : ℝ[X])
  (hp : is_centered n p) (hq : is_centered n q) :
  is_centered n (boxplus n p q) := by
  refine' ⟨ _, _, _ ⟩;
  · have h_leading_coeff : Polynomial.coeff (boxplus n p q) n = 1 := by
      unfold boxplus;
      simp +zetaDelta at *;
      rw [ Finset.sum_eq_single 0 ] <;> norm_num;
      · unfold boxplus_coeff;
        simp +decide [ ← hp.2.1, ← hq.2.1, hp.1.coeff_natDegree, hq.1.coeff_natDegree, Nat.factorial_ne_zero ];
        rw [ hp.2.1, hq.2.1.symm, hq.1.coeff_natDegree ];
      · intros; omega;
    rwa [ Polynomial.Monic, Polynomial.leadingCoeff, Polynomial.natDegree_eq_of_degree_eq_some ];
    refine' Polynomial.degree_eq_of_le_of_coeff_ne_zero _ _;
    · refine' le_trans ( Polynomial.degree_sum_le _ _ ) _;
      exact Finset.sup_le fun i hi => le_trans ( Polynomial.degree_C_mul_X_pow_le _ _ ) ( WithBot.coe_le_coe.mpr ( Nat.sub_le _ _ ) );
    · aesop;
  · have h_deg : (boxplus n p q).natDegree ≤ n := by
      exact le_trans ( Polynomial.natDegree_sum_le _ _ ) ( Finset.sup_le fun i hi => Polynomial.natDegree_C_mul_X_pow_le _ _ |> le_trans <| by aesop );
    refine' le_antisymm h_deg ( Polynomial.le_natDegree_of_ne_zero _ );
    unfold boxplus;
    simp +zetaDelta at *;
    rw [ Finset.sum_eq_single 0 ] <;> norm_num;
    · unfold boxplus_coeff; norm_num [ hp.1.leadingCoeff, hq.1.leadingCoeff ];
      exact ⟨ ⟨ Nat.factorial_ne_zero _, by rw [ ← hp.2.1, hp.1.coeff_natDegree ] ; aesop ⟩, by rw [ ← hq.2.1, hq.1.coeff_natDegree ] ; aesop ⟩;
    · intros; omega;
  · rcases n with ( _ | _ | n ) <;> simp_all +decide [ Polynomial.coeff_eq_zero_of_natDegree_lt ];
    · unfold is_centered at * ; aesop;
    · have := hp.2.2; have := hq.2.2; unfold boxplus; norm_num [ Polynomial.coeff_eq_zero_of_natDegree_lt, hp.1, hq.1, hp.2.1, hq.2.1 ] ;
      unfold boxplus_coeff; norm_num [ Finset.sum_range_succ', ‹p.coeff 0 = 0›, ‹q.coeff 0 = 0› ] ;
    · unfold is_centered at *;
      unfold boxplus; simp_all +decide [ Polynomial.coeff_eq_zero_of_natDegree_lt, Finset.sum_range_succ' ] ;
      unfold boxplus_coeff; simp_all +decide [ Finset.sum_range_succ', Nat.factorial_ne_zero ] ;
      exact Finset.sum_eq_zero fun x hx => if_neg ( by omega )

lemma boxplus_centered_coeff_add (n : ℕ) (p q : ℝ[X])
  (hp : is_centered n p) (hq : is_centered n q) :
  (boxplus n p q).coeff (n - 2) = p.coeff (n - 2) + q.coeff (n - 2) := by
  have h_coeff : (boxplus n p q).coeff (n - 2) = ∑ i ∈ Finset.range (2 + 1), (Nat.factorial (n - i) * Nat.factorial (n - (2 - i))) / (Nat.factorial n * Nat.factorial (n - 2) : ℝ) * p.coeff (n - i) * q.coeff (n - (2 - i)) := by
    rcases n with ( _ | _ | n ) <;> simp_all +decide [ Finset.sum_range_succ ];
    · unfold is_centered at * ; aesop;
    · unfold boxplus; norm_num [ Finset.sum_range_succ' ] ; ring;
      unfold boxplus_coeff; norm_num [ Finset.sum_range_succ ] ; ring;
      cases hp ; cases hq ; aesop;
    · unfold boxplus;
      simp +decide [ Finset.sum_range_succ', Polynomial.coeff_C, Polynomial.coeff_X_pow ];
      rw [ Finset.sum_eq_zero ] <;> norm_num +decide [ Nat.factorial_ne_zero ];
      · unfold boxplus_coeff; norm_num [ Nat.factorial_succ, Finset.sum_range_succ' ] ; ring;
        field_simp;
        grind;
      · intros; omega;
  rcases n with ( _ | _ | n ) <;> simp_all +decide [ Finset.sum_range_succ' ];
  · cases hp ; cases hq ; aesop;
  · cases hp ; cases hq ; aesop;
  · simp_all +decide [ Nat.factorial_ne_zero, mul_comm, mul_assoc, mul_left_comm, div_eq_mul_inv ];
    simp_all +decide [ is_centered, Nat.factorial_succ ];
    have := hp.1.coeff_natDegree; have := hq.1.coeff_natDegree; aesop;

lemma finite_free_stam_inequality_n2 (p q : ℝ[X])
    (hp : p.Splits (RingHom.id ℝ)) (hp_nodup : p.roots.Nodup)
    (hp_monic : p.Monic) (hp_deg : p.natDegree = 2)
    (hq : q.Splits (RingHom.id ℝ)) (hq_nodup : q.roots.Nodup)
    (hq_monic : q.Monic) (hq_deg : q.natDegree = 2)
    (hpq : (boxplus 2 p q).Splits (RingHom.id ℝ))
    (hpq_nodup : (boxplus 2 p q).roots.Nodup) :
    invPhi (boxplus 2 p q) ≥ invPhi p + invPhi q := by
      -- Let's assume that $p(x) = x^2 + ax + b$ and $q(x) = x^2 + cx + d$.
      obtain ⟨a, b, hp_eq⟩ : ∃ a b : ℝ, p = Polynomial.X^2 + Polynomial.C a * Polynomial.X + Polynomial.C b := by
        rw [ p.as_sum_range_C_mul_X_pow ];
        norm_num [ Finset.sum_range_succ', hp_deg ];
        have := hp_monic.coeff_natDegree; aesop;
      obtain ⟨c, d, hq_eq⟩ : ∃ c d : ℝ, q = Polynomial.X^2 + Polynomial.C c * Polynomial.X + Polynomial.C d := by
        rw [ Polynomial.as_sum_range_C_mul_X_pow q ];
        norm_num [ Finset.sum_range_succ', hq_deg ];
        have := hq_monic.coeff_natDegree; aesop;
      -- Let's compute the roots of $p$, $q$, and $p \boxplus q$.
      have hp_roots : p.roots = Multiset.ofList [(-a + Real.sqrt (a^2 - 4 * b)) / 2, (-a - Real.sqrt (a^2 - 4 * b)) / 2] := by
        rw [ hp_eq ];
        rw [ show ( Polynomial.X ^ 2 + Polynomial.C a * Polynomial.X + Polynomial.C b : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C ( ( -a + Real.sqrt ( a ^ 2 - 4 * b ) ) / 2 ) ) * ( Polynomial.X - Polynomial.C ( ( -a - Real.sqrt ( a ^ 2 - 4 * b ) ) / 2 ) ) by exact Polynomial.funext fun x => by norm_num; linarith [ Real.mul_self_sqrt ( show 0 <= a ^ 2 - 4 * b by
                                                                                                                                                                                                                                                                                                                                                        contrapose! hp;
                                                                                                                                                                                                                                                                                                                                                        rw [ Polynomial.splits_iff_card_roots ];
                                                                                                                                                                                                                                                                                                                                                        exact ne_of_lt ( lt_of_le_of_lt ( Multiset.card_le_card <| show p.roots ≤ 0 from by exact Multiset.le_zero.mpr <| by exact Multiset.eq_zero_of_forall_notMem fun x hx => by norm_num [ hp_eq ] at hx; nlinarith [ sq_nonneg ( x + a / 2 ) ] ) <| by norm_num [ hp_deg ] ) ) ] ];
        rw [ Polynomial.roots_mul <| mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ), Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] ; tauto
      have hq_roots : q.roots = Multiset.ofList [(-c + Real.sqrt (c^2 - 4 * d)) / 2, (-c - Real.sqrt (c^2 - 4 * d)) / 2] := by
        rw [ hq_eq, show ( Polynomial.X ^ 2 + Polynomial.C c * Polynomial.X + Polynomial.C d : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C ( ( -c + Real.sqrt ( c ^ 2 - 4 * d ) ) / 2 ) ) * ( Polynomial.X - Polynomial.C ( ( -c - Real.sqrt ( c ^ 2 - 4 * d ) ) / 2 ) ) by exact Polynomial.funext fun x => by norm_num; linarith [ Real.mul_self_sqrt ( show 0 <= c ^ 2 - 4 * d by { rw [ Polynomial.splits_iff_card_roots ] at hq; obtain ⟨ x, hx ⟩ := Multiset.card_pos_iff_exists_mem.mp ( by linarith [ Polynomial.natDegree_eq_of_degree_eq_some ( show Polynomial.degree q = 2 from Polynomial.degree_eq_iff_natDegree_eq_of_pos ( by linarith ) |>.2 hq_deg ) ] ) ; norm_num [ hq_eq ] at hx; nlinarith [ sq_nonneg ( c + 2 * x ) ] } ) ] ] ; rw [ Polynomial.roots_mul <| mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ] ; rw [ Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] ; tauto;
      have hpq_roots : (boxplus 2 p q).roots = Multiset.ofList [(-a - c + Real.sqrt ((a + c)^2 - 4 * (b + d + a * c / 2))) / 2, (-a - c - Real.sqrt ((a + c)^2 - 4 * (b + d + a * c / 2))) / 2] := by
        -- By definition of $boxplus$, we have:
        have h_boxplus : boxplus 2 p q = Polynomial.X^2 + Polynomial.C (a + c) * Polynomial.X + Polynomial.C (b + d + a * c / 2) := by
          unfold boxplus;
          norm_num [ Finset.sum_range_succ', boxplus_coeff, hp_eq, hq_eq ];
          exact Polynomial.funext fun x => by norm_num [ Polynomial.coeff_X ] ; ring;
        rw [ h_boxplus ];
        rw [ show ( Polynomial.X ^ 2 + Polynomial.C ( a + c ) * Polynomial.X + Polynomial.C ( b + d + a * c / 2 ) ) = ( Polynomial.X - Polynomial.C ( ( -a - c + Real.sqrt ( ( a + c ) ^ 2 - 4 * ( b + d + a * c / 2 ) ) ) / 2 ) ) * ( Polynomial.X - Polynomial.C ( ( -a - c - Real.sqrt ( ( a + c ) ^ 2 - 4 * ( b + d + a * c / 2 ) ) ) / 2 ) ) by exact Polynomial.funext fun x => by norm_num; linarith [ Real.mul_self_sqrt ( show 0 <= ( a + c ) ^ 2 - 4 * ( b + d + a * c / 2 ) by
                                                                                                                                                                                                                                                                                                                                                                                                                                    contrapose! hpq;
                                                                                                                                                                                                                                                                                                                                                                                                                                    rw [ Polynomial.splits_iff_card_roots ];
                                                                                                                                                                                                                                                                                                                                                                                                                                    rw [ h_boxplus, Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases ha : a + c = 0 <;> simp +decide [ ha ];
                                                                                                                                                                                                                                                                                                                                                                                                                                    · rw [ Multiset.card_eq_zero.mpr ] <;> norm_num;
                                                                                                                                                                                                                                                                                                                                                                                                                                      exact Multiset.eq_zero_of_forall_notMem fun x hx => by norm_num at hx; nlinarith [ sq_nonneg ( x + ( a + c ) / 2 ) ] ;
                                                                                                                                                                                                                                                                                                                                                                                                                                    · rw [ Multiset.card_eq_zero.mpr ] <;> norm_num;
                                                                                                                                                                                                                                                                                                                                                                                                                                      exact Multiset.eq_zero_of_forall_notMem fun x hx => by norm_num at hx; nlinarith [ sq_nonneg ( x + ( a + c ) / 2 ) ] ;
                                                                                                                                                                                                                                                                                                                                                                                                                                    · exact lt_of_le_of_lt ( Polynomial.natDegree_mul_le .. ) ( by by_cases ha : a = 0 <;> by_cases hc : c = 0 <;> simp +decide [ ha, hc ] ) ) ] ];
        rw [ Polynomial.roots_mul <| mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ), Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] ; tauto;
      unfold invPhi; simp_all +decide [ Finset.card_univ ] ;
      unfold Phi; simp_all +decide [ Finset.sum ] ;
      ring_nf at *; norm_num [ hp_nodup, hq_nodup, hpq_nodup ] at *;
      rw [ Real.sq_sqrt, Real.sq_sqrt, Real.sq_sqrt ] <;> (nlinarith [ sq_nonneg ( a + c ), sq_nonneg ( c + a ), sq_nonneg ( a - c ), sq_nonneg ( c - a ), Real.sqrt_nonneg ( a ^ 2 - b * 4 ), Real.sqrt_nonneg ( c ^ 2 - d * 4 ), Real.mul_self_sqrt ( show 0 <= a ^ 2 - b * 4 from le_of_not_gt fun h => hp_nodup <| by rw [ Real.sqrt_eq_zero'.mpr h.le ] ; ring ), Real.mul_self_sqrt ( show 0 <= c ^ 2 - d * 4 from le_of_not_gt fun h => hq_nodup <| by rw [ Real.sqrt_eq_zero'.mpr h.le ] ; ring ) ] ;)

lemma n3_inequality (b1 b2 u1 u2 : ℝ) (hu1 : u1 > 0) (hu2 : u2 > 0) :
  (b1 + b2)^2 / (u1 + u2)^2 ≤ b1^2 / u1^2 + b2^2 / u2^2 := by
  rw [ div_add_div, div_le_div_iff₀ ] <;> try positivity;
  have h_am_gm : (b1 * u2)^2 + (b2 * u1)^2 ≥ 2 * b1 * b2 * u1 * u2 := by
    linarith [ sq_nonneg ( b1 * u2 - b2 * u1 ) ];
  nlinarith [ sq_nonneg ( u1 - u2 ), mul_pos hu1 hu2, mul_le_mul_of_nonneg_left h_am_gm ( sq_nonneg u1 ), mul_le_mul_of_nonneg_left h_am_gm ( sq_nonneg u2 ) ]

/-
Formula for invPhi of a centered cubic polynomial.
-/
lemma invPhi_deg3_centered (a b : ℝ)
  (h_roots : (X^3 + C a * X + C b).roots.Nodup)
  (h_real : (X^3 + C a * X + C b).Splits (RingHom.id ℝ)) :
  invPhi (X^3 + C a * X + C b) = -2/9 * a - 3/2 * (b/a)^2 := by
    unfold invPhi;
    unfold Phi;
    -- By Vieta's formulas, we know that $r_1 + r_2 + r_3 = 0$ and $r_1 r_2 + r_2 r_3 + r_3 r_1 = a$.
    obtain ⟨r₁, r₂, r₃, hr⟩ : ∃ r₁ r₂ r₃ : ℝ, r₁ + r₂ + r₃ = 0 ∧ r₁ * r₂ + r₂ * r₃ + r₃ * r₁ = a ∧ r₁ * r₂ * r₃ = -b ∧ r₁ ≠ r₂ ∧ r₂ ≠ r₃ ∧ r₃ ≠ r₁ := by
      obtain ⟨r₁, r₂, r₃, hr⟩ : ∃ r₁ r₂ r₃ : ℝ, r₁ ∈ Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b) ∧ r₂ ∈ Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b) ∧ r₃ ∈ Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b) ∧ r₁ ≠ r₂ ∧ r₂ ≠ r₃ ∧ r₃ ≠ r₁ := by
        have h_card : Multiset.card (Polynomial.roots (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b)) = 3 := by
          rw [ Polynomial.splits_iff_card_roots ] at h_real;
          rw [ h_real, Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases ha : a = 0 <;> simp +decide [ ha ];
        rcases Multiset.card_eq_three.mp h_card with ⟨ r₁, r₂, r₃, hr ⟩ ; use r₁, r₂, r₃ ; aesop;
      use r₁, r₂, r₃;
      norm_num at hr;
      grind;
    -- By Vieta's formulas, we know that the roots of the polynomial are $r₁$, $r₂$, and $r₃$.
    have h_roots : (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b).roots = {r₁, r₂, r₃} := by
      rw [ show ( Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C r₁ ) * ( Polynomial.X - Polynomial.C r₂ ) * ( Polynomial.X - Polynomial.C r₃ ) by exact Polynomial.funext fun x => by norm_num; linear_combination hr.1 * x^2 - hr.2.1 * x + hr.2.2.1 ];
      rw [ Polynomial.roots_mul ( by exact mul_ne_zero ( mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ) ( Polynomial.X_sub_C_ne_zero _ ) ), Polynomial.roots_mul ( by exact mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ), Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] ; tauto;
    by_cases ha : a = 0 <;> simp_all +decide [ Finset.sum_pair, Finset.sum_singleton ];
    · grind;
    · rw [ inv_eq_of_mul_eq_one_right ];
      simp_all +decide [ ← eq_sub_iff_add_eq', sub_eq_iff_eq_add ];
      field_simp;
      rw [ div_add_div, div_add_div, div_add_div ] <;> try nlinarith [ mul_self_pos.2 ( sub_ne_zero.2 hr.2.2.2.1 ), mul_self_pos.2 ( sub_ne_zero.2 hr.2.2.2.2.1 ), mul_self_pos.2 ( sub_ne_zero.2 hr.2.2.2.2.2 ) ];
      field_simp;
      rw [ div_add_div, div_add_div ];
      · rw [ div_mul_eq_mul_div, div_eq_iff ];
        · grind +ring;
        · simp_all +decide [ sub_eq_iff_eq_add ];
          grind +ring;
      · grind;
      · grind +ring;
      · grind;
      · grind

lemma Phi_deg3_reduced_eq (a b : ℝ)
  (h_real : (X^3 + C a * X + C b).Splits (RingHom.id ℝ))
  (h_nodup : (X^3 + C a * X + C b).roots.Nodup) :
  Phi (X^3 + C a * X + C b) = 18 * a^2 / (-4 * a^3 - 27 * b^2) := by
    obtain ⟨r1, r2, r3, hr⟩ : ∃ r1 r2 r3 : ℝ, r1 + r2 + r3 = 0 ∧ r1 * r2 + r2 * r3 + r3 * r1 = a ∧ r1 * r2 * r3 = -b ∧ r1 ≠ r2 ∧ r1 ≠ r3 ∧ r2 ≠ r3 := by
      obtain ⟨r1, r2, r3, hr⟩ : ∃ r1 r2 r3 : ℝ, r1 ∈ (Polynomial.X^3 + Polynomial.C a * Polynomial.X + Polynomial.C b).roots ∧ r2 ∈ (Polynomial.X^3 + Polynomial.C a * Polynomial.X + Polynomial.C b).roots ∧ r3 ∈ (Polynomial.X^3 + Polynomial.C a * Polynomial.X + Polynomial.C b).roots ∧ r1 ≠ r2 ∧ r1 ≠ r3 ∧ r2 ≠ r3 := by
        have h_card : Multiset.card (Polynomial.roots (Polynomial.X^3 + Polynomial.C a * Polynomial.X + Polynomial.C b)) = 3 := by
          rw [ Polynomial.splits_iff_card_roots ] at h_real;
          rw [ h_real, Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases ha : a = 0 <;> simp +decide [ ha ];
        rcases x : Polynomial.roots _ with ⟨ _ | ⟨ r1, _ | ⟨ r2, _ | ⟨ r3, _ | k ⟩ ⟩ ⟩ ⟩ <;> simp_all +decide;
      use r1, r2, r3;
      norm_num at hr;
      grind;
    have h_roots : (Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b).roots = {r1, r2, r3} := by
      rw [ show ( Polynomial.X ^ 3 + Polynomial.C a * Polynomial.X + Polynomial.C b : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C r1 ) * ( Polynomial.X - Polynomial.C r2 ) * ( Polynomial.X - Polynomial.C r3 ) by exact Polynomial.funext fun x => by norm_num; linear_combination hr.1 * x^2 - hr.2.1 * x + hr.2.2.1 ];
      rw [ Polynomial.roots_mul ( by exact mul_ne_zero ( mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ) ( Polynomial.X_sub_C_ne_zero _ ) ), Polynomial.roots_mul ( by exact mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ) ), Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] ; tauto;
    unfold Phi;
    simp_all +decide [ Finset.sum ];
    rw [ show a = r1 * r2 + r2 * r3 + r3 * r1 by linarith, show b = -r1 * r2 * r3 by linarith ];
    rw [ inv_add_inv, inv_add_inv, inv_add_inv ] <;> try cases lt_or_gt_of_ne hr.2.2.2.1 <;> cases lt_or_gt_of_ne hr.2.2.2.2.1 <;> cases lt_or_gt_of_ne hr.2.2.2.2.2 <;> nlinarith;
    rw [ div_pow, div_pow, div_pow, div_add_div, div_add_div ];
    · rw [ div_eq_div_iff ];
      · grind +ring;
      · simp +decide [ sub_eq_iff_eq_add, hr ];
        tauto;
      · grind;
    · exact pow_ne_zero 2 ( mul_ne_zero ( sub_ne_zero_of_ne <| by tauto ) ( sub_ne_zero_of_ne <| by tauto ) );
    · exact mul_ne_zero ( pow_ne_zero 2 ( mul_ne_zero ( sub_ne_zero_of_ne <| by tauto ) ( sub_ne_zero_of_ne <| by tauto ) ) ) ( pow_ne_zero 2 ( mul_ne_zero ( sub_ne_zero_of_ne <| by tauto ) ( sub_ne_zero_of_ne <| by tauto ) ) );
    · exact pow_ne_zero 2 ( mul_ne_zero ( sub_ne_zero_of_ne <| by tauto ) ( sub_ne_zero_of_ne <| by tauto ) );
    · exact pow_ne_zero 2 ( mul_ne_zero ( sub_ne_zero_of_ne <| by tauto ) ( sub_ne_zero_of_ne <| by tauto ) )

lemma cubic_distinct_real_roots_implies_a_neg (a b : ℝ)
  (h_roots : (X^3 + C a * X + C b).roots.toFinset.card = 3) :
  a < 0 := by
    by_contra h_contra; push_neg at h_contra; (
    have h_increasing : StrictMono (fun x : ℝ => x^3 + a * x + b) := by
      exact fun x y hxy => by norm_num; nlinarith [ sq_nonneg ( x^2 - y^2 ), pow_pos ( sub_pos.mpr hxy ) 3, mul_le_mul_of_nonneg_left hxy.le h_contra ] ;
    exact absurd h_roots ( by exact ne_of_lt ( lt_of_le_of_lt ( Finset.card_le_one.mpr ( by intros x hx y hy; exact h_increasing.injective <| by aesop ) ) ( by norm_num ) ) ));

lemma boxplus_deg3_reduced_eq (p q : ℝ[X])
  (hp_monic : p.Monic) (hq_monic : q.Monic)
  (hp_deg : p.natDegree = 3) (hq_deg : q.natDegree = 3)
  (hp_red : p.coeff 2 = 0) (hq_red : q.coeff 2 = 0) :
  boxplus 3 p q = X^3 + C (p.coeff 1 + q.coeff 1) * X + C (p.coeff 0 + q.coeff 0) := by
    unfold boxplus;
    simp_all +decide [ Finset.sum_range_succ, boxplus_coeff ];
    simp_all +decide [ Polynomial.Monic.def, Polynomial.leadingCoeff, Polynomial.natDegree_eq_of_degree_eq_some ];
    ring