/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 50080d30-c798-4bd9-aa5e-b0ee4db8ff0f

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat Classical Pointwise
open Polynomial BigOperators Finset Classical

def boxplus_coeff (n : ℕ) (p q : ℝ[X]) (k : ℕ) : ℝ :=
  ∑ i ∈ range (k + 1),
    let j := k - i
    (Nat.factorial (n - i) * Nat.factorial (n - j) : ℝ) / (Nat.factorial n * Nat.factorial (n - k) : ℝ) *
    (p.coeff (n - i)) * (q.coeff (n - j))

def boxplus (n : ℕ) (p q : ℝ[X]) : ℝ[X] :=
  Finset.sum (range (n + 1)) (fun k => C (boxplus_coeff n p q k) * X ^ (n - k))

def Phi (p : ℝ[X]) : ℝ :=
  let roots := p.roots.toFinset
  ∑ r_i ∈ roots, (∑ r_j ∈ roots.erase r_i, 1 / (r_i - r_j))^2

def invPhi (p : ℝ[X]) : ℝ :=
  if p.roots.Nodup ∧ p.roots.card > 1 then
    1 / Phi p
  else 0

def is_centered (n : ℕ) (p : ℝ[X]) : Prop :=
  p.Monic ∧ p.natDegree = n ∧ p.coeff (n - 1) = 0

/-
Phi(p(x+c)) = Phi(p(x)).
-/
lemma Phi_shift_invariance (p : ℝ[X]) (c : ℝ) :
    Phi (p.comp (X + C c)) = Phi p := by
      unfold Phi;
      simp_all +decide [ Finset.sum_add_distrib, sub_eq_iff_eq_add' ];
      rw [ show ( p.comp ( Polynomial.X + Polynomial.C c ) |> Polynomial.roots ).toFinset = ( p.roots.toFinset.image fun x => x - c ) from ?_, Finset.sum_image <| by aesop ];
      · exact Finset.sum_congr rfl fun x hx => by rw [ Finset.sum_image ( by aesop ) ] ; simp +decide [ sub_sub_sub_cancel_right ] ;
      · ext x;
        norm_num +zetaDelta at *;
        rw [ Polynomial.comp_eq_zero_iff ] ; aesop

/-
invPhi(p(x+c)) = invPhi(p(x)).
-/
lemma invPhi_shift_invariance (p : ℝ[X]) (c : ℝ) :
    invPhi (p.comp (X + C c)) = invPhi p := by
      rw [ invPhi ];
      rw [ show ( p.comp ( Polynomial.X + Polynomial.C c ) |> Polynomial.roots ) = ( p.roots.map ( fun x => x - c ) ) from ?_ ];
      · split_ifs <;> simp_all +decide [ invPhi ];
        · -- By definition of $Phi$, we know that
          have h_phi : Phi (p.comp (.X + (.C c))) = Phi p := by
            exact?;
          rw [ if_pos ] ; aesop;
          exact Multiset.Nodup.of_map _ ( by tauto ) |> fun h => by simpa [ sub_eq_add_neg ] using h;
        · intro h1 h2; specialize ‹ ( Multiset.map ( fun x => x - c ) p.roots ).Nodup → p.roots.card ≤ 1 › ; simp_all +decide [ Multiset.nodup_map_iff_inj_on ] ;
          linarith;
      · ext x;
        rw [ Multiset.count_map ];
        simp +decide [ eq_sub_iff_add_eq ];
        rw [ show ( Multiset.filter ( fun y => x + c = y ) p.roots ) = Multiset.replicate ( Polynomial.rootMultiplicity ( x + c ) p ) ( x + c ) from ?_ ];
        · rw [ Polynomial.rootMultiplicity_eq_natTrailingDegree, Polynomial.rootMultiplicity_eq_natTrailingDegree ];
          norm_num [ add_assoc, Polynomial.comp_assoc ];
        · ext y;
          rw [ Multiset.count_replicate ] ; aesop

/-
If p and q are centered polynomials of degree n, then their boxplus convolution is also centered.
-/
lemma boxplus_is_centered (n : ℕ) (p q : ℝ[X])
    (hp : is_centered n p) (hq : is_centered n q) :
    is_centered n (boxplus n p q) := by
  rcases hp with ⟨hp_monic, hp_deg, hp_cent⟩
  rcases hq with ⟨hq_monic, hq_deg, hq_cent⟩
  constructor
  · -- Monic
    rw [Polynomial.Monic]
    rw [boxplus]
    -- The leading coefficient comes from the k=0 term.
    -- We need to show that the coefficient of X^n is 1.
    -- The term for k=0 is C (boxplus_coeff n p q 0) * X^n.
    -- The terms for k > 0 have degree n-k < n.
    -- When $k = 0$, the coefficient is $\sum_{i=0}^{0} \frac{(n-i)!(n-j)!}{n!(n-k)!} p_{n-i} q_{n-j} = \frac{n!n!}{n!n!} p_n q_n = p_n q_n = 1$.
    have h_k0 : boxplus_coeff n p q 0 = 1 := by
      unfold boxplus_coeff;
      simp_all +decide [ Nat.factorial_ne_zero, Polynomial.Monic.def ];
      simp_all +decide [ Polynomial.leadingCoeff, Polynomial.natDegree ];
    rw [ Polynomial.leadingCoeff, Polynomial.natDegree_eq_of_degree_eq_some ];
    any_goals exact n;
    · norm_num [ Finset.sum_range_succ', h_k0 ];
      exact Finset.sum_eq_zero fun x hx => if_neg ( Nat.ne_of_gt ( Nat.sub_lt ( by linarith [ Finset.mem_range.mp hx ] ) ( by linarith [ Finset.mem_range.mp hx ] ) ) );
    · rw [ Polynomial.degree_eq_of_le_of_coeff_ne_zero ] <;> norm_num [ Polynomial.coeff_X_pow, h_k0 ];
      · exact le_trans ( Polynomial.degree_sum_le _ _ ) ( Finset.sup_le fun i hi => Polynomial.degree_C_mul_X_pow_le _ _ |> le_trans <| WithBot.coe_le_coe.mpr <| Nat.sub_le _ _ );
      · norm_num [ Finset.sum_range_succ', h_k0 ];
        exact ne_of_gt ( add_pos_of_nonneg_of_pos ( Finset.sum_nonneg fun _ _ => by split_ifs <;> linarith [ Nat.sub_add_cancel ( show ‹_› + 1 ≤ n from by linarith [ Finset.mem_range.mp ‹_› ] ) ] ) zero_lt_one )
  · constructor
    · -- Degree
      -- We need to show that the degree is n.
      -- We already know it's monic of degree at most n (from the definition).
      -- Since it's monic, the degree is exactly n.
      refine' Polynomial.natDegree_eq_of_degree_eq_some _;
      refine' Polynomial.degree_eq_of_le_of_coeff_ne_zero _ _;
      · exact le_trans ( Polynomial.degree_sum_le _ _ ) ( Finset.sup_le fun i hi => Polynomial.degree_C_mul_X_pow_le _ _ |> le_trans <| WithBot.coe_le_coe.mpr <| Nat.sub_le _ _ );
      · unfold boxplus;
        norm_num [ Finset.sum_range_succ', Polynomial.coeff_C_mul_X_pow ];
        rw [ Finset.sum_eq_zero ] <;> norm_num [ boxplus_coeff ];
        · exact ⟨ ⟨ Nat.factorial_ne_zero _, by rw [ ← hp_deg, hp_monic.coeff_natDegree ] ; aesop ⟩, by rw [ ← hq_deg, hq_monic.coeff_natDegree ] ; aesop ⟩;
        · intros; omega;
    · -- Centered
      -- We need to show that the coefficient of X^(n-1) is 0.
      -- This coefficient comes from the term k=1 (if n >= 1).
      -- If n=0, then n-1 is not well-defined in Nat, but usually centered implies n >= 1 or it's trivial.
      -- The definition of is_centered says p.natDegree = n.
      -- If n=0, then p is constant 1 (monic). coeff(0-1) is coeff(0) which is 1. But hp_cent says coeff(0-1)=0.
      -- So n must be >= 1 for a centered polynomial to exist?
      -- Wait, coeff(n-1) for n=0 is coeff(0) in Lean? No, 0-1=0 in Nat.
      -- So for n=0, centered means coeff(0)=0. But monic means coeff(0)=1. Contradiction.
      -- So n must be >= 1.
      unfold boxplus;
      rcases n with ( _ | _ | n ) <;> simp_all +decide [ Finset.sum_range_succ' ];
      · unfold boxplus_coeff; norm_num [ hp_monic, hq_monic, hp_cent, hq_cent ] ;
        norm_num [ Finset.sum_range_succ, hp_monic, hq_monic, hp_cent, hq_cent ];
      · unfold boxplus_coeff;
        simp_all +decide [ Finset.sum_range_succ ];
        exact Finset.sum_eq_zero fun x hx => if_neg ( by omega )

/-
Shifting a monic polynomial p by -p_{n-1}/n makes it centered.
-/
def shift_to_center_amount (n : ℕ) (p : ℝ[X]) : ℝ :=
  - p.coeff (n - 1) / n

def shifted_to_center (n : ℕ) (p : ℝ[X]) : ℝ[X] :=
  p.comp (X + C (shift_to_center_amount n p))

lemma shifted_to_center_is_centered (n : ℕ) (p : ℝ[X])
    (hn : n ≠ 0) (hp_monic : p.Monic) (hp_deg : p.natDegree = n) :
    is_centered n (shifted_to_center n p) := by
      refine' ⟨ _, _, _ ⟩;
      · convert hp_monic.comp_X_add_C _ using 1;
      · unfold shifted_to_center;
        rw [ Polynomial.natDegree_comp, Polynomial.natDegree_X_add_C, hp_deg ] ; aesop;
      · -- By definition of shifted_to_center, we have:
        have h_shift : shifted_to_center n p = p.comp (X + C (-p.coeff (n - 1) / n)) := by
          exact?;
        simp_all +decide [ Polynomial.comp, Polynomial.eval₂_eq_sum_range ];
        rcases n <;> simp_all +decide [ Polynomial.coeff_X_add_C_pow, Finset.sum_range_succ ];
        simp_all +decide [ Finset.sum_range, Nat.choose_eq_zero_of_lt ];
        rw [ div_mul_cancel₀ ] <;> first | positivity | rw [ ← hp_deg, hp_monic.coeff_natDegree ] ; ring;

/-
Shifting to center preserves real-rootedness and simple roots.
-/
lemma shifted_to_center_properties (n : ℕ) (p : ℝ[X])
    (hp_splits : p.Splits (RingHom.id ℝ)) (hp_nodup : p.roots.Nodup) :
    (shifted_to_center n p).Splits (RingHom.id ℝ) ∧ (shifted_to_center n p).roots.Nodup := by
      unfold shifted_to_center;
      constructor;
      · exact?;
      · -- The roots of $p(x + c)$ are just the roots of $p$ shifted by $-c$.
        have h_roots_shift : (p.comp (Polynomial.X + Polynomial.C (shift_to_center_amount n p))).roots = Multiset.map (fun r => r - shift_to_center_amount n p) p.roots := by
          ext x;
          rw [ Multiset.count_map, eq_comm ];
          rw [ show ( Multiset.filter ( fun a => x = a - shift_to_center_amount n p ) p.roots ) = Multiset.filter ( fun a => a = x + shift_to_center_amount n p ) p.roots from ?_, Multiset.filter_eq' ] ; norm_num [ eq_comm ];
          · rw [ Polynomial.rootMultiplicity_eq_natTrailingDegree, Polynomial.rootMultiplicity_eq_natTrailingDegree ];
            norm_num [ Polynomial.comp_assoc ];
            rw [ add_assoc ];
          · exact Multiset.filter_congr fun y hy => by constructor <;> intro h <;> linarith;
        exact h_roots_shift.symm ▸ Multiset.Nodup.map ( fun x => by aesop ) hp_nodup

/-
boxplus(p(x+c), q(x+d)) = (boxplus(p, q))(x + c + d).
-/
lemma boxplus_comp_add_C_left (n : ℕ) (p q : ℝ[X]) (c : ℝ)
    (hp : p.natDegree = n) (hq : q.natDegree = n) :
    boxplus n (p.comp (X + C c)) q = (boxplus n p q).comp (X + C c) := by
      refine' Polynomial.funext _;
      intro r;
      -- We'll use the fact that $p(x+c)$ has coefficients given by the binomial theorem.
      have h_coeff : ∀ i ≤ n, (p.comp (.X + (.C c))).coeff (n - i) = ∑ j ∈ Finset.range (i + 1), Nat.choose (n - j) (n - i) * c ^ (i - j) * p.coeff (n - j) := by
        intro i hi
        have h_coeff : (p.comp (.X + (.C c))).coeff (n - i) = ∑ j ∈ Finset.range (n + 1), p.coeff j * Nat.choose j (n - i) * c ^ (j - (n - i)) := by
          rw [ Polynomial.comp, Polynomial.eval₂_eq_sum_range ];
          norm_num [ Polynomial.coeff_X_add_C_pow ];
          simp +decide [ mul_assoc, mul_comm, mul_left_comm, hp ];
        rw [ h_coeff, ← Finset.sum_flip ];
        rw [ ← Finset.sum_subset ( Finset.range_mono ( Nat.succ_le_succ hi ) ) ];
        · refine' Finset.sum_congr rfl fun x hx => _;
          grind;
        · simp +zetaDelta at *;
          exact fun x hx₁ hx₂ => Or.inl <| Or.inr <| Nat.choose_eq_zero_of_lt <| by omega;
      -- Substitute the expression for the coefficients of $p(x+c)$ into the definition of $boxplus$.
      have h_boxplus_subst : ∀ k ≤ n, boxplus_coeff n (p.comp (.X + (.C c))) q k = ∑ j ∈ Finset.range (k + 1), boxplus_coeff n p q j * Nat.choose (n - j) (n - k) * c^(k - j) := by
        unfold boxplus_coeff;
        intro k hk; rw [ Finset.sum_congr rfl fun i hi => by rw [ h_coeff i ( by linarith [ Finset.mem_range.mp hi ] ) ] ] ; simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Finset.sum_mul ] ;
        rw [ Finset.sum_sigma', Finset.sum_sigma' ];
        refine' Finset.sum_bij ( fun x hx => ⟨ k - x.1 + x.2, x.2 ⟩ ) _ _ _ _ <;> simp_all +decide [ Nat.choose_succ_succ, add_comm ];
        · exact fun a ha₁ ha₂ => ⟨ by omega, by omega ⟩;
        · grind;
        · exact fun b hb₁ hb₂ => ⟨ k - ( b.fst - b.snd ), b.snd, ⟨ by omega, by omega ⟩, by ext <;> norm_num ; omega ⟩;
        · intro a ha₁ ha₂; rw [ show a.fst - a.snd = k - ( a.snd + ( k - a.fst ) ) by omega ] ; ring;
          rw [ Nat.cast_choose, Nat.cast_choose ] <;> try omega;
          field_simp;
          rw [ show n - ( a.snd + ( k - a.fst ) ) - ( n - k ) = n - a.snd - ( n - a.fst ) by omega ] ; ring;
      -- By Fubini's theorem, we can interchange the order of summation.
      have h_fubini : ∑ k ∈ Finset.range (n + 1), (∑ j ∈ Finset.range (k + 1), boxplus_coeff n p q j * Nat.choose (n - j) (n - k) * c^(k - j)) * (r^(n - k)) = ∑ j ∈ Finset.range (n + 1), boxplus_coeff n p q j * (∑ k ∈ Finset.Ico j (n + 1), Nat.choose (n - j) (n - k) * c^(k - j) * r^(n - k)) := by
        simp +decide only [mul_assoc, sum_mul, Finset.mul_sum _ _ _];
        rw [ Finset.range_eq_Ico, Finset.sum_Ico_Ico_comm ];
      -- Let's simplify the inner sum $\sum_{k=j}^{n} \binom{n-j}{n-k} c^{k-j} r^{n-k}$.
      have h_inner_sum : ∀ j ≤ n, ∑ k ∈ Finset.Ico j (n + 1), Nat.choose (n - j) (n - k) * c^(k - j) * r^(n - k) = (r + c)^(n - j) := by
        intro j hj; rw [ add_pow ] ; simp +decide [ mul_assoc, mul_comm, mul_left_comm, Finset.sum_Ico_eq_sum_range ] ;
        rw [ ← Finset.sum_flip ];
        simp +decide [ Nat.sub_sub, add_comm, tsub_tsub_cancel_of_le hj ];
        rw [ Nat.sub_add_comm hj ];
        refine' Finset.sum_congr rfl fun x hx => _ ; rw [ show n - ( j + ( n - ( j + x ) ) ) = x by rw [ tsub_eq_of_eq_add ] ; linarith [ Nat.sub_add_cancel ( show j + x ≤ n from by linarith [ Finset.mem_range.mp hx, Nat.sub_add_cancel hj ] ) ] ] ; ring;
      unfold boxplus; simp_all +decide [ Polynomial.eval_finset_sum ] ;
      exact Eq.trans ( Finset.sum_congr rfl fun x hx => by rw [ h_boxplus_subst x ( Finset.mem_range_succ_iff.mp hx ) ] ) ( h_fubini.trans ( Finset.sum_congr rfl fun x hx => by rw [ h_inner_sum x ( Finset.mem_range_succ_iff.mp hx ) ] ) )

lemma boxplus_comm (n : ℕ) (p q : ℝ[X]) :
    boxplus n p q = boxplus n q p := by
      -- By definition of `boxplus`, we know that it is symmetric.
      have h_symm : ∀ k, boxplus_coeff n p q k = boxplus_coeff n q p k := by
        intro k
        unfold boxplus_coeff
        simp [mul_comm, mul_assoc, mul_left_comm];
        rw [ ← Finset.sum_flip ];
        exact Finset.sum_congr rfl fun x hx => by rw [ tsub_tsub_cancel_of_le ( Finset.mem_range_succ_iff.mp hx ) ] ; ring;
      unfold boxplus; aesop;

theorem boxplus_comp_add_C (n : ℕ) (p q : ℝ[X]) (c d : ℝ)
    (hp : p.natDegree = n) (hq : q.natDegree = n) :
    boxplus n (p.comp (X + C c)) (q.comp (X + C d)) = (boxplus n p q).comp (X + C (c + d)) := by
      -- By definition of boxplus, we can rewrite the left-hand side.
      have h_lhs : boxplus n (p.comp (X + C c)) (q.comp (X + C d)) = (boxplus n (p.comp (X + C c)) q).comp (X + C d) := by
        rw [ boxplus_comm ];
        rw [ boxplus_comp_add_C_left ];
        · rw [ boxplus_comm ];
        · exact hq;
        · rw [ Polynomial.natDegree_comp, Polynomial.natDegree_X_add_C, hp, mul_one ];
      rw [ h_lhs ];
      rw [ boxplus_comp_add_C_left ];
      · norm_num [ Polynomial.comp_assoc ];
        ring;
      · exact hp;
      · exact hq

/-
It suffices to prove the Finite Free Stam Inequality for centered polynomials.
-/
lemma finite_free_stam_inequality_centered_sufficient (n : ℕ)
    (hn : n ≥ 2) :
    (∀ (p q : ℝ[X]),
      is_centered n p → is_centered n q →
      p.Splits (RingHom.id ℝ) → p.roots.Nodup →
      q.Splits (RingHom.id ℝ) → q.roots.Nodup →
      (boxplus n p q).Splits (RingHom.id ℝ) → (boxplus n p q).roots.Nodup →
      invPhi (boxplus n p q) ≥ invPhi p + invPhi q) →
    (∀ (p q : ℝ[X]),
      p.Monic → p.natDegree = n → p.Splits (RingHom.id ℝ) → p.roots.Nodup →
      q.Monic → q.natDegree = n → q.Splits (RingHom.id ℝ) → q.roots.Nodup →
      (boxplus n p q).Splits (RingHom.id ℝ) → (boxplus n p q).roots.Nodup →
      invPhi (boxplus n p q) ≥ invPhi p + invPhi q) := by
        intro h p q hp hp' hp'' hp''' hq hq' hq'' hq''' hq'''' hq''''';
        -- Let p_cent(x) = p(x + c_p) and q_cent(x) = q(x + c_q).
        set p_cent := shifted_to_center n p
        set q_cent := shifted_to_center n q;
        -- By the properties of the shifted polynomials, we have:
        have hp_cent : invPhi p_cent = invPhi p := by
          convert invPhi_shift_invariance p ( shift_to_center_amount n p ) using 1
        have hq_cent : invPhi q_cent = invPhi q := by
          apply invPhi_shift_invariance
        have hpq_cent : invPhi (boxplus n p_cent q_cent) = invPhi (boxplus n p q) := by
          have hpq_cent : boxplus n p_cent q_cent = (boxplus n p q).comp (X + C (shift_to_center_amount n p + shift_to_center_amount n q)) := by
            convert boxplus_comp_add_C n p q ( shift_to_center_amount n p ) ( shift_to_center_amount n q ) hp' hq' using 1;
          rw [ hpq_cent, invPhi_shift_invariance ];
        have hp_cent_centered : is_centered n p_cent := by
          apply shifted_to_center_is_centered n p (by linarith) hp hp'
        have hq_cent_centered : is_centered n q_cent := by
          apply shifted_to_center_is_centered n q (by linarith) hq hq'
        have hp_cent_splits : (p_cent).Splits (RingHom.id ℝ) := by
          have := shifted_to_center_properties n p hp'' hp''';
          exact this.1
        have hp_cent_nodup : (p_cent).roots.Nodup := by
          have := shifted_to_center_properties n p hp'' hp''' ; aesop;
        have hq_cent_splits : (q_cent).Splits (RingHom.id ℝ) := by
          exact shifted_to_center_properties n q hq'' hq''' |>.1
        have hq_cent_nodup : (q_cent).roots.Nodup := by
          convert shifted_to_center_properties n q hq'' hq''' |>.2 using 1
        have hpq_cent_splits : (boxplus n p_cent q_cent).Splits (RingHom.id ℝ) := by
          rw [ show boxplus n p_cent q_cent = ( boxplus n p q |> Polynomial.comp <| X + C ( shift_to_center_amount n p + shift_to_center_amount n q ) ) from ?_ ];
          · exact?;
          · convert boxplus_comp_add_C n p q ( shift_to_center_amount n p ) ( shift_to_center_amount n q ) hp' hq' using 1
        have hpq_cent_nodup : (boxplus n p_cent q_cent).roots.Nodup := by
          contrapose! hq''''';
          -- By the properties of the boxplus operation, we have:
          have hpq_cent_eq : boxplus n p_cent q_cent = (boxplus n p q).comp (X + C (shift_to_center_amount n p + shift_to_center_amount n q)) := by
            convert boxplus_comp_add_C n p q ( shift_to_center_amount n p ) ( shift_to_center_amount n q ) hp' hq' using 1;
          rw [ Multiset.nodup_iff_count_le_one ] at *;
          simp_all +decide [ Polynomial.eval_comp, Polynomial.eval_add, Polynomial.eval_X, Polynomial.eval_C ];
          obtain ⟨ x, hx ⟩ := hq''''';
          use x + (shift_to_center_amount n p + shift_to_center_amount n q);
          rw [ Polynomial.rootMultiplicity_eq_natTrailingDegree ] at *;
          convert hx using 2 ; norm_num [ Polynomial.comp_assoc ] ; ring;
        linarith [ h p_cent q_cent hp_cent_centered hq_cent_centered hp_cent_splits hp_cent_nodup hq_cent_splits hq_cent_nodup hpq_cent_splits hpq_cent_nodup ]

/-
For centered polynomials, (p ⊞ q)_{n-2} = p_{n-2} + q_{n-2}.
-/
lemma boxplus_centered_coeff_n_sub_2 (n : ℕ) (p q : ℝ[X])
    (hp : is_centered n p) (hq : is_centered n q) (hn : n ≥ 2) :
    (boxplus n p q).coeff (n - 2) = p.coeff (n - 2) + q.coeff (n - 2) := by
      rcases n with _ | _ | n <;> simp_all +decide [ Nat.succ_eq_add_one ];
      unfold is_centered at *;
      unfold boxplus; simp +decide [ Finset.sum_range_succ', hp.2.2, hq.2.2 ] ;
      rw [ Finset.sum_eq_zero ] <;> norm_num [ boxplus_coeff ] at *;
      · simp +arith +decide [ Finset.sum_range_succ', hp.2.1, hq.2.1 ];
        simp_all +decide [ Nat.factorial_ne_zero, mul_comm, mul_assoc, mul_left_comm ];
        have := hp.1.coeff_natDegree; have := hq.1.coeff_natDegree; aesop;
      · intros; omega;

/-
Phi(X^2 + c) = -1/(2c) for c < 0.
-/
lemma Phi_quadratic_centered (c : ℝ) (hc : c < 0) :
    let p := X^2 + C c
    Phi p = -1 / (2 * c) := by
      field_simp;
      rw [ show ( Polynomial.X ^ 2 + Polynomial.C c : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C ( -Real.sqrt ( -c ) ) ) * ( Polynomial.X - Polynomial.C ( Real.sqrt ( -c ) ) ) by exact Polynomial.funext fun x => by norm_num; nlinarith [ Real.mul_self_sqrt ( show 0 ≤ -c by linarith ) ] ];
      unfold Phi;
      erw [ Polynomial.roots_mul <| mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ), Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] ; norm_num;
      rw [ Finset.sum_pair ] <;> norm_num [ hc.ne ];
      · rw [ Finset.sum_eq_single ( Real.sqrt ( -c ) ), Finset.sum_pair ] <;> norm_num;
        · ring_nf; norm_num [ hc.le ];
        · linarith [ Real.sqrt_pos.2 ( neg_pos.2 hc ) ];
        · aesop;
        · exact fun h => by linarith [ Real.sqrt_pos.2 ( neg_pos.2 hc ) ] ;
      · linarith [ Real.sqrt_pos.2 ( neg_pos.2 hc ) ]

/-
Phi(p) = sum_{r} (p''(r) / (2p'(r)))^2.
-/
lemma Phi_derivative_form (p : ℝ[X])
    (h_splits : p.Splits (RingHom.id ℝ))
    (h_nodup : p.roots.Nodup) :
    Phi p = ∑ r ∈ p.roots.toFinset, (p.derivative.derivative.eval r / (2 * p.derivative.eval r))^2 := by
      refine' Finset.sum_congr rfl fun r hr => _;
      -- Let $q(x) = \frac{p(x)}{x - r}$.
      obtain ⟨q, hq⟩ : ∃ q : Polynomial ℝ, p = (Polynomial.X - Polynomial.C r) * q ∧ q.eval r ≠ 0 := by
        obtain ⟨q, hq⟩ : ∃ q : Polynomial ℝ, p = (Polynomial.X - Polynomial.C r) * q := by
          exact Polynomial.dvd_iff_isRoot.mpr ( by aesop );
        by_cases h : q.eval r = 0 <;> simp_all +decide [ Polynomial.splits_mul, Polynomial.splits_X_sub_C ];
        rw [ Polynomial.roots_mul ] at h_nodup <;> aesop;
      -- Since $q(x)$ is a polynomial with roots $r_j$ for $j \neq r$, we can write $q(x) = c \prod_{j \neq r} (x - r_j)$ for some constant $c$.
      obtain ⟨c, hc⟩ : ∃ c : ℝ, q = Polynomial.C c * ∏ r_j ∈ p.roots.toFinset.erase r, (Polynomial.X - Polynomial.C r_j) := by
        -- Since $q$ is a polynomial with roots $r_j$ for $j \neq i$, we can write $q$ as a product of linear factors corresponding to these roots.
        have hq_factor : q = Polynomial.C (q.leadingCoeff) * ∏ r_j ∈ q.roots.toFinset, (Polynomial.X - Polynomial.C r_j) := by
          convert Polynomial.eq_prod_roots_of_splits_id _;
          · rw [ ← Multiset.toFinset_eq ];
            rfl;
            rw [ hq.1, Polynomial.roots_mul ] at h_nodup <;> aesop;
          · simp_all +decide [ Polynomial.splits_mul_iff ];
        -- Since $q$ is a polynomial with roots $r_j$ for $j \neq i$, we have $q.roots.toFinset = p.roots.toFinset.erase r$.
        have hq_roots : q.roots.toFinset = p.roots.toFinset.erase r := by
          rw [ hq.1, Polynomial.roots_mul ] <;> norm_num [ hq.2 ];
          exact ⟨ Polynomial.X_sub_C_ne_zero _, by rintro rfl; simp +decide at hq ⟩;
        exact ⟨ q.leadingCoeff, hq_roots ▸ hq_factor ⟩;
      -- By definition of $q$, we know that $q'(r) = c \sum_{j \neq r} \prod_{k \neq r, j} (r - r_k)$.
      have hq'_eval : Polynomial.eval r (Polynomial.derivative q) = c * ∑ r_j ∈ p.roots.toFinset.erase r, (∏ r_k ∈ p.roots.toFinset.erase r \ {r_j}, (r - r_k)) := by
        rw [ hc, Polynomial.derivative_mul, Polynomial.derivative_C ] ; norm_num;
        erw [ Polynomial.derivative_prod ];
        erw [ Polynomial.eval_finset_sum ] ; norm_num [ Polynomial.eval_prod ];
        simp +decide [ Finset.sdiff_singleton_eq_erase, Polynomial.eval_multiset_prod ];
        exact Or.inl rfl;
      -- By definition of $q$, we know that $q(r) = c \prod_{j \neq r} (r - r_j)$.
      have hq_eval : Polynomial.eval r q = c * ∏ r_j ∈ p.roots.toFinset.erase r, (r - r_j) := by
        simp +decide [ hc, Polynomial.eval_prod ];
      -- By definition of $q$, we know that $\sum_{j \neq r} \frac{1}{r - r_j} = \frac{q'(r)}{q(r)}$.
      have h_sum_inv : ∑ r_j ∈ p.roots.toFinset.erase r, (1 / (r - r_j)) = Polynomial.eval r (Polynomial.derivative q) / Polynomial.eval r q := by
        rw [ hq'_eval, hq_eval, eq_div_iff ];
        · simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Finset.sum_mul ];
          refine' Finset.sum_congr rfl fun x hx => _;
          field_simp;
          rw [ Finset.prod_eq_prod_diff_singleton_mul hx, mul_div_assoc ] ; norm_num [ sub_ne_zero.mpr ( show r ≠ x from by rintro rfl; exact Finset.notMem_erase _ _ hx ) ];
        · exact hq_eval ▸ hq.2;
      rw [ h_sum_inv, hq.1 ] ; norm_num [ Polynomial.derivative_mul, Polynomial.derivative_prod ] ; ring;

/-
If deg(P) + 2 <= deg(Q), then sum_{r in roots(Q)} P(r)/Q'(r) = 0.
-/
lemma sum_residues_eq_zero_of_deg_le (P Q : Polynomial ℝ)
    (h_deg : P.natDegree + 2 ≤ Q.natDegree)
    (h_splits : Q.Splits (RingHom.id ℝ))
    (h_nodup : Q.roots.Nodup) :
    (Q.roots.map (fun r => P.eval r / Q.derivative.eval r)).sum = 0 := by
  -- By the properties of the derivative and roots, we can express $P(x)$ as a sum of its partial fractions at the roots of $Q(x)$.
  have h_partial_fractions : ∀ x, x ∉ Q.roots → P.eval x / Q.eval x = ∑ r ∈ Q.roots.toFinset, (P.eval r) / (Q.derivative.eval r) * (1 / (x - r)) := by
    -- Since $Q$ splits into linear factors over the reals and has distinct roots, we can write it as $Q(x) = c \prod_{r \in Q.roots} (x - r)$ for some constant $c$.
    obtain ⟨c, hc⟩ : ∃ c : ℝ, Q = Polynomial.C c * Finset.prod Q.roots.toFinset (fun r => Polynomial.X - Polynomial.C r) := by
      use Q.leadingCoeff;
      convert Polynomial.eq_prod_roots_of_splits_id h_splits using 1;
      rw [ ← Multiset.toFinset_eq ] ; aesop;
    -- By the properties of the derivative and roots, we can express $P(x)$ as a sum of its partial fractions at the roots of $Q(x)$ using the fact that $Q(x)$ splits into linear factors over the reals.
    have h_partial_fractions : ∀ x, x ∉ Q.roots → P.eval x / Q.eval x = ∑ r ∈ Q.roots.toFinset, (P.eval r) / (Q.derivative.eval r) * (1 / (x - r)) := by
      intro x hx
      have h_eval : P.eval x = ∑ r ∈ Q.roots.toFinset, (P.eval r) * (∏ s ∈ Q.roots.toFinset \ {r}, (x - s)) / (∏ s ∈ Q.roots.toFinset \ {r}, (r - s)) := by
        have h_eval : P = Finset.sum Q.roots.toFinset (fun r => Polynomial.C (P.eval r / (∏ s ∈ Q.roots.toFinset \ {r}, (r - s))) * (∏ s ∈ Q.roots.toFinset \ {r}, (Polynomial.X - Polynomial.C s))) := by
          refine' Polynomial.eq_of_degree_sub_lt_of_eval_finset_eq _ _ _;
          exact Q.roots.toFinset;
          · refine' lt_of_le_of_lt ( Polynomial.degree_sub_le _ _ ) ( max_lt _ _ );
            · refine' lt_of_le_of_lt ( Polynomial.degree_le_natDegree ) _;
              rw [ hc, Polynomial.natDegree_C_mul ] at h_deg <;> norm_num at *;
              · linarith;
              · rintro rfl; norm_num at *;
            · refine' lt_of_le_of_lt ( Polynomial.degree_sum_le _ _ ) ( Finset.sup_lt_iff _ |>.2 _ );
              · exact WithBot.bot_lt_coe _;
              · intro r hr; rw [ Polynomial.degree_mul, Polynomial.degree_prod, Finset.sum_congr rfl fun s hs => Polynomial.degree_X_sub_C _ ] ; norm_num [ Finset.card_sdiff, hr ] ;
                exact lt_of_le_of_lt ( add_le_add ( Polynomial.degree_C_le ) le_rfl ) ( by norm_cast; linarith [ Finset.card_pos.mpr ⟨ r, hr ⟩, Nat.sub_add_cancel ( Finset.card_pos.mpr ⟨ r, hr ⟩ ) ] );
          · intro r hr; rw [ Polynomial.eval_finset_sum, Finset.sum_eq_single r ] <;> norm_num [ hr ];
            · simp +decide [ Polynomial.eval_prod, Finset.prod_eq_zero_iff, sub_eq_zero ];
            · intro b hb hb' hb''; rw [ Polynomial.eval_prod ] ; simp +decide [ Finset.prod_eq_zero_iff, sub_eq_zero, hb'' ] ;
              exact Or.inr ⟨ ⟨ hb, by simpa using Polynomial.isRoot_of_mem_roots ( Multiset.mem_toFinset.mp hr ) ⟩, Ne.symm hb'' ⟩;
        conv_lhs => rw [ h_eval ];
        simp +decide [ Polynomial.eval_finset_sum, Polynomial.eval_mul, Polynomial.eval_prod, Polynomial.eval_sub, Polynomial.eval_X, Polynomial.eval_C, div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.prod_mul_distrib ]
      -- By the properties of the derivative and roots, we can express $Q'(x)$ as a sum of its partial fractions at the roots of $Q(x)$.
      have h_deriv : ∀ r ∈ Q.roots.toFinset, Q.derivative.eval r = c * (∏ s ∈ Q.roots.toFinset \ {r}, (r - s)) := by
        intro r hr
        have h_deriv : Q.derivative.eval r = Polynomial.eval r (Polynomial.derivative (Polynomial.C c * Finset.prod Q.roots.toFinset (fun s => Polynomial.X - Polynomial.C s))) := by
          rw [ ← hc ];
        rw [ h_deriv, Finset.prod_eq_prod_diff_singleton_mul hr ] ; norm_num [ Polynomial.derivative_prod ] ; ring;
        norm_num [ Polynomial.eval_prod ];
      -- By the properties of the derivative and roots, we can express $Q(x)$ as a product of its roots.
      have h_prod : Q.eval x = c * (∏ r ∈ Q.roots.toFinset, (x - r)) := by
        simpa [ Polynomial.eval_prod ] using congr_arg ( Polynomial.eval x ) hc;
      rw [ h_eval, h_prod, Finset.sum_div _ _ _ ];
      refine Finset.sum_congr rfl fun r hr => ?_;
      rw [ h_deriv r hr, Finset.prod_eq_prod_diff_singleton_mul hr ] ; ring;
      field_simp;
      convert mul_div_mul_right _ _ ( show ( ∏ s ∈ Q.roots.toFinset \ { r }, ( x - s ) ) ≠ 0 from Finset.prod_ne_zero_iff.mpr fun s hs => sub_ne_zero_of_ne <| by rintro rfl; exact hx <| by simpa using Finset.mem_sdiff.mp hs |>.1 ) using 1 ; ring;
    assumption;
  -- Consider the limit of the partial fraction decomposition as $x$ goes to infinity.
  have h_limit : Filter.Tendsto (fun x : ℝ => (∑ r ∈ Q.roots.toFinset, (P.eval r) / (Q.derivative.eval r) * (1 / (x - r))) * x) Filter.atTop (nhds (∑ r ∈ Q.roots.toFinset, (P.eval r) / (Q.derivative.eval r))) := by
    -- Each term in the sum $\sum_{r \in Q.roots.toFinset} \frac{P(r)}{Q'(r)} \cdot \frac{x}{x - r}$ tends to $\frac{P(r)}{Q'(r)}$ as $x$ goes to infinity.
    have h_term_limit : ∀ r ∈ Q.roots.toFinset, Filter.Tendsto (fun x : ℝ => (P.eval r) / (Q.derivative.eval r) * (x / (x - r))) Filter.atTop (nhds ((P.eval r) / (Q.derivative.eval r))) := by
      intro r hr
      have : Filter.Tendsto (fun x : ℝ => x / (x - r)) Filter.atTop (nhds 1) := by
        erw [ Metric.tendsto_nhds ];
        exact fun ε ε_pos => Filter.eventually_atTop.mpr ⟨ ⌈ε⁻¹ * ( |r| + 1 ) ⌉₊ + |r| + 1, fun x hx => abs_lt.mpr ⟨ by cases abs_cases r <;> nlinarith [ Nat.le_ceil ( ε⁻¹ * ( |r| + 1 ) ), mul_inv_cancel₀ ( ne_of_gt ε_pos ), div_mul_cancel₀ x ( by linarith : ( x - r ) ≠ 0 ) ], by cases abs_cases r <;> nlinarith [ Nat.le_ceil ( ε⁻¹ * ( |r| + 1 ) ), mul_inv_cancel₀ ( ne_of_gt ε_pos ), div_mul_cancel₀ x ( by linarith : ( x - r ) ≠ 0 ) ] ⟩ ⟩;
      simpa using this.const_mul _;
    simpa [ mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _ ] using tendsto_finset_sum _ h_term_limit |> Filter.Tendsto.congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with x hx; simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, hx.ne' ] );
  -- Since $P(x)/Q(x)$ tends to zero as $x$ goes to infinity, the limit of the partial fraction decomposition must also be zero.
  have h_zero_limit : Filter.Tendsto (fun x : ℝ => P.eval x / Q.eval x * x) Filter.atTop (nhds 0) := by
    field_simp;
    have := Polynomial.div_tendsto_zero_of_degree_lt ( P * Polynomial.X ) Q;
    by_cases hP : P = 0 <;> by_cases hQ : Q = 0 <;> simp_all +decide [ Polynomial.degree_eq_natDegree ];
    exact this ( mod_cast by linarith );
  convert tendsto_nhds_unique h_limit ( h_zero_limit.congr' _ ) using 1;
  · rw [ ← Multiset.toFinset_eq ] ; aesop;
  · filter_upwards [ Filter.eventually_gt_atTop ( ∑ r ∈ Q.roots.toFinset, |r| ) ] with x hx;
    rw [ h_partial_fractions x ];
    intro hx';
    exact hx.not_le ( Finset.single_le_sum ( fun r _ => abs_nonneg r ) ( by aesop ) |> le_trans ( le_abs_self _ ) )

/-
Phi(p) = -1/4 * sum_{mu in roots(p')} p''(mu)/p(mu).
-/
lemma Phi_eq_sum_roots_deriv (p : ℝ[X])
    (h_splits : p.Splits (RingHom.id ℝ))
    (h_nodup : p.roots.Nodup)
    (h_deg : p.natDegree ≥ 2)
    (h_deriv_nodup : p.derivative.roots.Nodup) :
    Phi p = -1/4 * (p.derivative.roots.map (fun μ => p.derivative.derivative.eval μ / p.eval μ)).sum := by
      -- Consider the rational function $R(z) = \frac{(p''(z))^2}{p(z)p'(z)}$.
      set R : Polynomial ℝ := (Polynomial.derivative (Polynomial.derivative p))^2
      set Q : Polynomial ℝ := p * Polynomial.derivative p
      have h_deg_R_Q : R.natDegree + 2 ≤ Q.natDegree := by
        have h_deg_R : R.natDegree = 2 * (p.natDegree - 2) := by
          have h_deg_p'' : Polynomial.natDegree (Polynomial.derivative (Polynomial.derivative p)) = p.natDegree - 2 := by
            have h_deg_p'' : Polynomial.natDegree (Polynomial.derivative p) = p.natDegree - 1 := by
              rcases k : Polynomial.natDegree p with ( _ | _ | k ) <;> simp_all +decide [ Polynomial.natDegree_eq_of_degree_eq_some ];
              rw [ Polynomial.natDegree_eq_of_degree_eq_some ] ; aesop;
            generalize_proofs at *; (
            rcases k : Polynomial.natDegree p with ( _ | _ | k ) <;> simp_all +decide [ Polynomial.natDegree ];
            · aesop_cat;
            · rfl)
          generalize_proofs at *; (
          aesop)
        have h_deg_Q : Q.natDegree = p.natDegree + (p.natDegree - 1) := by
          rw [ Polynomial.natDegree_mul', Polynomial.natDegree ];
          · rcases k : Polynomial.natDegree p with ( _ | _ | k ) <;> simp_all +decide [ Polynomial.natDegree_eq_of_degree_eq_some ];
            simp_all +decide [ Polynomial.natDegree ];
            rfl;
          · simp +zetaDelta at *;
            exact ⟨ by aesop_cat, by exact fun h => by rw [ Polynomial.eq_C_of_derivative_eq_zero h ] at h_deg h_splits h_nodup; aesop_cat ⟩
        rw [h_deg_R, h_deg_Q]
        skip;
        omega
      have h_splits_RQ : Q.Splits (RingHom.id ℝ) := by
        have h_splits_deriv : Polynomial.Splits (RingHom.id ℝ) (Polynomial.derivative p) := by
          have h_splits_deriv_roots : (Polynomial.derivative p).roots.Nodup := h_deriv_nodup
          have h_splits_deriv_card : (Polynomial.derivative p).roots.card = (Polynomial.derivative p).natDegree := by
            have h_splits_deriv_card : (Polynomial.derivative p).roots.card ≥ (Polynomial.derivative p).natDegree := by
              have h_splits_deriv_roots : (Polynomial.derivative p).roots.card ≥ (Polynomial.natDegree p) - 1 := by
                have h_splits_deriv_roots : (Polynomial.derivative p).roots.card ≥ Multiset.card (Polynomial.roots p) - 1 := by
                  norm_num +zetaDelta at *;
                  exact?
                generalize_proofs at *; (
                rw [ Polynomial.splits_iff_card_roots ] at h_splits ; aesop)
              generalize_proofs at *; (
              rcases k : Polynomial.natDegree p with ( _ | _ | k ) <;> simp_all +decide [ Polynomial.natDegree ];
              · aesop_cat;
              · exact?)
            generalize_proofs at *; (
            exact le_antisymm ( Polynomial.card_roots' _ ) h_splits_deriv_card)
          exact?
        generalize_proofs at *; (
        exact?)
      have h_nodup_RQ : Q.roots.Nodup := by
        have h_roots_Q : Q.roots = p.roots + (Polynomial.derivative p).roots := by
          rw [ Polynomial.roots_mul ] ; aesop;
        -- Since $p$ and $p'$ have distinct roots, their union also has distinct roots.
        have h_union_distinct : Disjoint (p.roots.toFinset) ((Polynomial.derivative p).roots.toFinset) := by
          have h_distinct_roots : ∀ r ∈ p.roots.toFinset, p.derivative.eval r ≠ 0 := by
            intro r hr; intro H; have := Polynomial.dvd_iff_isRoot.mpr ( show Polynomial.eval r p = 0 from by aesop ) ; obtain ⟨ q, hq ⟩ := this; simp_all +decide [ Polynomial.derivative_mul ] ;
            rw [ Polynomial.roots_mul ] at h_nodup <;> aesop
          generalize_proofs at *; (
          exact Finset.disjoint_left.mpr fun x hx₁ hx₂ => h_distinct_roots x hx₁ <| by aesop;)
        generalize_proofs at *; (
        rw [ h_roots_Q, Multiset.nodup_add ] ; aesop;)
      have h_sum_residues : ∑ r ∈ Q.roots.toFinset, R.eval r / Q.derivative.eval r = 0 := by
        have := sum_residues_eq_zero_of_deg_le R Q h_deg_R_Q h_splits_RQ h_nodup_RQ;
        rw [ ← this, ← Multiset.toFinset_eq ] ; aesop;
      have h_sum_residues_eq : ∑ r ∈ p.roots.toFinset, (Polynomial.derivative (Polynomial.derivative p)).eval r ^ 2 / (p.derivative.eval r ^ 2) + ∑ μ ∈ (Polynomial.derivative p).roots.toFinset, (Polynomial.derivative (Polynomial.derivative p)).eval μ / p.eval μ = 0 := by
        have h_sum_residues_eq : ∑ r ∈ Q.roots.toFinset, R.eval r / Q.derivative.eval r = ∑ r ∈ p.roots.toFinset, R.eval r / Q.derivative.eval r + ∑ μ ∈ (Polynomial.derivative p).roots.toFinset, R.eval μ / Q.derivative.eval μ := by
          rw [ ← Finset.sum_union ] ; congr ; ext ; aesop;
          refine' Finset.disjoint_left.mpr _;
          intro x hx₁ hx₂; have := Polynomial.card_roots' p; simp_all +decide [ Polynomial.natDegree ] ;
          have := Polynomial.dvd_iff_isRoot.mpr hx₁.2; obtain ⟨ q, hq ⟩ := this; simp_all +decide [ Polynomial.derivative_mul ] ;
          rw [ Polynomial.roots_mul ] at h_nodup <;> aesop;
        simp +zetaDelta at *;
        convert h_sum_residues_eq.symm.trans h_sum_residues using 1;
        refine' congrArg₂ ( · + · ) _ _ <;> refine' Finset.sum_congr rfl fun x hx => _ <;> by_cases hx' : Polynomial.eval x p = 0 <;> by_cases hx'' : Polynomial.eval x ( Polynomial.derivative p ) = 0 <;> simp +decide [ hx', hx'', sq, mul_assoc, div_eq_mul_inv ] ; ring;
        · aesop;
        · aesop;
        · aesop;
        · by_cases h : Polynomial.eval x ( Polynomial.derivative ( Polynomial.derivative p ) ) = 0 <;> aesop;
        · simp_all +decide [ Polynomial.rootMultiplicity_eq_zero ]
      have h_phi_eq : Phi p = 1 / 4 * ∑ r ∈ p.roots.toFinset, (Polynomial.derivative (Polynomial.derivative p)).eval r ^ 2 / (p.derivative.eval r ^ 2) := by
        rw [ Phi_derivative_form p h_splits h_nodup ] ; norm_num [ div_pow, mul_pow ] ; ring;
        rw [ Finset.sum_mul _ _ _ ]
      rw [h_phi_eq] at *; (
      rw [ show ( Polynomial.derivative p |> Polynomial.roots |> Multiset.map ( fun μ => Polynomial.eval μ ( Polynomial.derivative ( Polynomial.derivative p ) ) / Polynomial.eval μ p ) |> Multiset.sum ) = ∑ μ ∈ ( Polynomial.derivative p |> Polynomial.roots |> Multiset.toFinset ), Polynomial.eval μ ( Polynomial.derivative ( Polynomial.derivative p ) ) / Polynomial.eval μ p from ?_ ] ; linarith;
      rw [ ← Multiset.toFinset_eq ] ; aesop;);

/-
Phi(x^3 + ax + b) = -18a^2 / (27b^2 + 4a^3).
-/
def Phi_cubic_centered_formula (a b : ℝ) : ℝ :=
  -18 * a^2 / (27 * b^2 + 4 * a^3)

/-
For centered cubic polynomials, the constant term of p ⊞ q is the sum of the constant terms of p and q.
-/
lemma boxplus_centered_cubic_coeff_0 (p q : ℝ[X])
    (hp : is_centered 3 p) (hq : is_centered 3 q) :
    (boxplus 3 p q).coeff 0 = p.coeff 0 + q.coeff 0 := by
      unfold is_centered at *;
      unfold boxplus; norm_num [ Finset.sum_range_succ', hp, hq, Polynomial.coeff_zero_eq_eval_zero ] ; ring; (
      unfold boxplus_coeff; norm_num [ Polynomial.eval_eq_sum_range, Finset.sum_range_succ', hp, hq ] ; ring;
      have := hp.1.coeff_natDegree; have := hq.1.coeff_natDegree; aesop;)

/-
invPhi(x^3 + ax + b) = -3/2 (b/a)^2 - 2/9 a.
-/
def invPhi_cubic_centered_formula (a b : ℝ) : ℝ :=
  -3/2 * (b/a)^2 - 2/9 * a

lemma invPhi_eq_invPhi_cubic_centered_formula (a b : ℝ)
    (h_discr : 4 * a^3 + 27 * b^2 < 0) :
    let p := X^3 + C a * X + C b
    p.roots.Nodup → p.Splits (RingHom.id ℝ) →
    invPhi p = invPhi_cubic_centered_formula a b := by
      intro p h_nodup_splits h_roots_splits
      have h_phi : Phi p = -18 * a ^ 2 / (27 * b ^ 2 + 4 * a ^ 3) := by
        convert Phi_eq_sum_roots_deriv p h_roots_splits h_nodup_splits _ _ using 1;
        · -- The roots of $p'(x) = 3x^2 + a$ are $\mu = \pm \sqrt{-a/3}$.
          have h_roots_deriv : Polynomial.roots (Polynomial.derivative p) = {Real.sqrt (-a / 3), -Real.sqrt (-a / 3)} := by
            norm_num +zetaDelta at *;
            rw [ show ( Polynomial.C 3 * Polynomial.X ^ 2 + Polynomial.C a : Polynomial ℝ ) = ( Polynomial.C 3 ) * ( Polynomial.X ^ 2 - Polynomial.C ( -a / 3 ) ) by exact Polynomial.funext fun x => by norm_num; ring, Polynomial.roots_C_mul ] <;> norm_num;
            rw [ show ( Polynomial.X ^ 2 - Polynomial.C ( -a / 3 ) : Polynomial ℝ ) = ( Polynomial.X - Polynomial.C ( Real.sqrt ( -a ) / Real.sqrt 3 ) ) * ( Polynomial.X - Polynomial.C ( - ( Real.sqrt ( -a ) / Real.sqrt 3 ) ) ) by exact Polynomial.funext fun x => by norm_num; ring_nf; norm_num ; rw [ Real.sq_sqrt <| by nlinarith [ sq_nonneg a ] ] ; ring, Polynomial.roots_mul <| by exact mul_ne_zero ( Polynomial.X_sub_C_ne_zero _ ) ( Polynomial.X_sub_C_ne_zero _ ), Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] ; norm_num;
          rw [ h_roots_deriv ] ; norm_num ; ring;
          norm_num [ p ] ; ring;
          field_simp;
          rw [ show ( Real.sqrt ( -a ) ) ^ 3 = Real.sqrt ( -a ) * Real.sqrt ( -a ) ^ 2 by ring, Real.sq_sqrt <| neg_nonneg.mpr <| by nlinarith [ sq_nonneg a ] ] ; norm_num [ pow_three ] ; ring;
          rw [ show ( a ^ 3 * 4 + b ^ 2 * 27 ) = ( a * Real.sqrt ( -a ) * 2 + b * Real.sqrt 3 * 3 ) * ( - ( a * Real.sqrt ( -a ) * 2 ) + b * Real.sqrt 3 * 3 ) by ring_nf; norm_num [ Real.sq_sqrt ( show 0 ≤ -a by nlinarith [ sq_nonneg a ] ) ] ; ring ] ; norm_num ; ring;
          field_simp;
          rw [ div_sub_div ] <;> ring <;> norm_num;
          · rw [ Real.sq_sqrt ] <;> nlinarith [ sq_nonneg a ];
          · by_contra h_contra;
            have h_eq : b = (a * Real.sqrt (-a) * 2) / (Real.sqrt 3 * 3) := by
              exact eq_div_of_mul_eq ( by positivity ) ( by linarith );
            subst h_eq; ring_nf at *; norm_num at *;
            rw [ Real.sq_sqrt ] at h_discr <;> nlinarith [ sq_nonneg a ];
          · by_contra h_contra;
            have h_eq : b = - (a * Real.sqrt (-a) * 2) / (3 * Real.sqrt 3) := by
              exact eq_div_of_mul_eq ( by positivity ) ( by linarith );
            subst h_eq; ring_nf at *; norm_num at *;
            rw [ Real.sq_sqrt ] at h_discr <;> nlinarith [ sq_nonneg a ];
        · rw [ Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases ha : a = 0 <;> simp +decide [ ha ];
        · convert Polynomial.nodup_roots _ using 1;
          refine' IsCoprime.symm _;
          norm_num [ p ];
          refine' IsCoprime.mul_left _ _;
          · exact ⟨ Polynomial.C ( 1 / 3 ), 0, Polynomial.funext fun x => by norm_num ⟩;
          · refine' IsCoprime.mul_left _ _;
            · exact ⟨ Polynomial.C ( 1 / 2 ), 0, Polynomial.funext fun x => by norm_num ⟩;
            · refine' IsCoprime.symm _;
              refine' IsCoprime.symm ( Polynomial.irreducible_X.coprime_iff_not_dvd.mpr _ );
              rw [ Polynomial.X_dvd_iff ] ; norm_num;
              rintro rfl; nlinarith;
      unfold invPhi invPhi_cubic_centered_formula;
      by_cases ha : a = 0 <;> simp_all +decide [ Polynomial.splits_iff_card_roots ];
      rw [ if_pos ];
      · grind;
      · erw [ Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> aesop

/-
Algebraic inequality for n=3 Stam.
-/
lemma algebraic_stam_inequality_n3 (A C B D : ℝ) (hA : A < 0) (hC : C < 0) :
    -3/2 * ((B + D) / (A + C))^2 - 2/9 * (A + C) ≥ (-3/2 * (B / A)^2 - 2/9 * A) + (-3/2 * (D / C)^2 - 2/9 * C) := by
      -- Let t = C/(A+C). Then (1-t) = A/(A+C).
      set t : ℝ := C / (A + C)
      have ht : 0 < t ∧ t < 1 := by
        exact ⟨ div_pos_of_neg_of_neg hC ( by linarith ), by rw [ div_lt_iff_of_neg ] <;> linarith ⟩;
      -- Then $(B + D) / (A + C) = (1 - t) * (B / A) + t * (D / C)$.
      have h_rewrite : (B + D) / (A + C) = (1 - t) * (B / A) + t * (D / C) := by
        grind;
      rw [ h_rewrite ] ; nlinarith [ mul_le_mul_of_nonneg_left ht.2.le ( sub_nonneg_of_le ht.1.le ), sq_nonneg ( B / A - D / C ) ] ;

/-
If X^3 + aX + b has distinct real roots, then 4a^3 + 27b^2 < 0.
-/
lemma cubic_discriminant_neg_of_nodup_splits (a b : ℝ)
    (h_nodup : (X^3 + C a * X + C b).roots.Nodup)
    (h_splits : (X^3 + C a * X + C b).Splits (RingHom.id ℝ)) :
    4 * a^3 + 27 * b^2 < 0 := by
      obtain ⟨x₁, x₂, x₃, hx⟩ : ∃ x₁ x₂ x₃ : ℝ, x₁ ≠ x₂ ∧ x₁ ≠ x₃ ∧ x₂ ≠ x₃ ∧ x₁^3 + a * x₁ + b = 0 ∧ x₂^3 + a * x₂ + b = 0 ∧ x₃^3 + a * x₃ + b = 0 := by
        -- Since the polynomial has distinct roots, we can extract three distinct elements from its roots.
        obtain ⟨x₁, x₂, x₃, hx⟩ : ∃ x₁ x₂ x₃ : ℝ, x₁ ∈ Polynomial.roots (Polynomial.X^3 + Polynomial.C a * Polynomial.X + Polynomial.C b) ∧ x₂ ∈ Polynomial.roots (Polynomial.X^3 + Polynomial.C a * Polynomial.X + Polynomial.C b) ∧ x₃ ∈ Polynomial.roots (Polynomial.X^3 + Polynomial.C a * Polynomial.X + Polynomial.C b) ∧ x₁ ≠ x₂ ∧ x₁ ≠ x₃ ∧ x₂ ≠ x₃ := by
          have h_card : Multiset.card (Polynomial.roots (Polynomial.X^3 + Polynomial.C a * Polynomial.X + Polynomial.C b)) = 3 := by
            rw [ Polynomial.splits_iff_card_roots ] at h_splits;
            rw [ h_splits, Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases ha : a = 0 <;> simp +decide [ ha ];
          rcases Multiset.card_eq_three.mp h_card with ⟨ x₁, x₂, x₃, h ⟩ ; use x₁, x₂, x₃ ; aesop;
        exact ⟨ x₁, x₂, x₃, hx.2.2.2.1, hx.2.2.2.2.1, hx.2.2.2.2.2, by aesop ⟩;
      -- By Vieta's formulas, we know that $x_1 + x_2 + x_3 = 0$ and $x_1 x_2 + x_2 x_3 + x_3 x_1 = a$.
      have h_vieta_sum : x₁ + x₂ + x₃ = 0 := by
        exact mul_left_cancel₀ ( sub_ne_zero_of_ne hx.1 ) <| mul_left_cancel₀ ( sub_ne_zero_of_ne hx.2.1 ) <| mul_left_cancel₀ ( sub_ne_zero_of_ne hx.2.2.1 ) <| by linear_combination hx.2.2.2.1 * ( x₂ - x₃ ) - hx.2.2.2.2.1 * ( x₁ - x₃ ) + hx.2.2.2.2.2 * ( x₁ - x₂ ) ;
      have h_vieta_prod_sum : x₁ * x₂ + x₂ * x₃ + x₃ * x₁ = a := by
        exact mul_left_cancel₀ ( sub_ne_zero_of_ne hx.1 ) ( by ring_nf; nlinarith );
      -- By Vieta's formulas, we know that $x_1 x_2 x_3 = -b$.
      have h_vieta_prod : x₁ * x₂ * x₃ = -b := by
        grind +ring;
      -- Substitute $a = x₁ * x₂ + x₂ * x₃ + x₃ * x₁$ and $b = -x₁ * x₂ * x₃$ into the inequality.
      have h_sub : 4 * (x₁ * x₂ + x₂ * x₃ + x₃ * x₁) ^ 3 + 27 * (-x₁ * x₂ * x₃) ^ 2 < 0 := by
        have h_sub : (x₁ - x₂)^2 * (x₁ - x₃)^2 * (x₂ - x₃)^2 > 0 := by
          exact mul_pos ( mul_pos ( sq_pos_of_ne_zero ( sub_ne_zero.mpr hx.1 ) ) ( sq_pos_of_ne_zero ( sub_ne_zero.mpr hx.2.1 ) ) ) ( sq_pos_of_ne_zero ( sub_ne_zero.mpr hx.2.2.1 ) );
        rw [ ← eq_sub_iff_add_eq' ] at h_vieta_sum ; subst_vars ; nlinarith;
      aesop

/-
Finite Free Stam Inequality for n=3 centered polynomials.
-/
theorem finite_free_stam_inequality_centered_n3 (p q : ℝ[X])
    (hp : is_centered 3 p) (hq : is_centered 3 q)
    (hp_real : p.Splits (RingHom.id ℝ)) (hp_nodup : p.roots.Nodup)
    (hq_real : q.Splits (RingHom.id ℝ)) (hq_nodup : q.roots.Nodup)
    (hpq_real : (boxplus 3 p q).Splits (RingHom.id ℝ)) (hpq_nodup : (boxplus 3 p q).roots.Nodup) :
    invPhi (boxplus 3 p q) ≥ invPhi p + invPhi q := by
      obtain ⟨a, b, hp_eq⟩ : ∃ a b : ℝ, p = Polynomial.X^3 + Polynomial.C a * Polynomial.X + Polynomial.C b := by
        rcases hp with ⟨ hp₁, hp₂, hp₃ ⟩;
        rw [ p.as_sum_range_C_mul_X_pow ] ; use p.coeff 1, p.coeff 0; norm_num [ Finset.sum_range_succ', hp₂, hp₃ ] ;
        rw [ ← hp₂, hp₁.coeff_natDegree, Polynomial.C_1 ]
      obtain ⟨c, d, hq_eq⟩ : ∃ c d : ℝ, q = Polynomial.X^3 + Polynomial.C c * Polynomial.X + Polynomial.C d := by
        rcases hq with ⟨ hq₁, hq₂, hq₃ ⟩;
        rw [ Polynomial.as_sum_range_C_mul_X_pow q ] ; use q.coeff 1, q.coeff 0; norm_num [ Finset.sum_range_succ', hq₂, hq₃ ] ; ring;
        rw [ ← hq₂, hq₁.coeff_natDegree ] ; norm_num
      obtain ⟨e, f, hpq_eq⟩ : ∃ e f : ℝ, boxplus 3 p q = Polynomial.X^3 + Polynomial.C e * Polynomial.X + Polynomial.C f := by
        -- Since $p$ and $q$ are centered, their boxplus convolution is also centered, hence has the form $X^3 + eX + f$.
        have h_centered : is_centered 3 (boxplus 3 p q) := by
          exact?;
        rcases h_centered with ⟨ hp₁, hp₂, hp₃ ⟩ ; rw [ Polynomial.as_sum_range_C_mul_X_pow ( boxplus 3 p q ) ] ; norm_num [ Finset.sum_range_succ', Polynomial.natDegree_eq_of_degree_eq_some, hp₁, hp₂, hp₃ ] ;
        rw [ Polynomial.Monic, Polynomial.leadingCoeff, Polynomial.natDegree_eq_of_degree_eq_some ( Polynomial.degree_eq_natDegree <| by aesop_cat ) ] at hp₁ ; aesop;
      -- By definition of $invPhi$, we know that
      have h_invPhi_p : invPhi p = -3 / 2 * (b / a) ^ 2 - 2 / 9 * a := by
        convert invPhi_eq_invPhi_cubic_centered_formula a b _ _ using 1;
        · aesop;
        · convert cubic_discriminant_neg_of_nodup_splits a b _ _ using 1 <;> aesop;
        · aesop
      have h_invPhi_q : invPhi q = -3 / 2 * (d / c) ^ 2 - 2 / 9 * c := by
        convert invPhi_eq_invPhi_cubic_centered_formula c d _ _ using 1;
        · aesop;
        · convert cubic_discriminant_neg_of_nodup_splits c d _ _ using 1 <;> aesop;
        · aesop
      have h_invPhi_pq : invPhi (boxplus 3 p q) = -3 / 2 * (f / e) ^ 2 - 2 / 9 * e := by
        convert invPhi_eq_invPhi_cubic_centered_formula e f _ using 1;
        · aesop;
        · convert cubic_discriminant_neg_of_nodup_splits e f _ _ using 1 <;> aesop;
      -- By definition of $boxplus$, we know that $e = a + c$ and $f = b + d$.
      have h_e : e = a + c := by
        have h_e : (boxplus 3 p q).coeff 1 = a + c := by
          convert boxplus_centered_coeff_n_sub_2 3 p q hp hq ( by norm_num ) using 1 ; norm_num [ hp_eq, hq_eq ];
        aesop
      have h_f : f = b + d := by
        have := boxplus_centered_cubic_coeff_0 p q hp hq; aesop;
      -- By definition of $a$, $b$, $c$, and $d$, we know that $4a^3 + 27b^2 < 0$ and $4c^3 + 27d^2 < 0$.
      have h_discr_p : 4 * a^3 + 27 * b^2 < 0 := by
        apply cubic_discriminant_neg_of_nodup_splits a b; aesop;
        aesop
      have h_discr_q : 4 * c^3 + 27 * d^2 < 0 := by
        convert cubic_discriminant_neg_of_nodup_splits c d _ _ using 1 <;> aesop;
      -- By definition of $a$, $b$, $c$, and $d$, we know that $a < 0$ and $c < 0$.
      have h_a_neg : a < 0 := by
        nlinarith [ sq_nonneg a ]
      have h_c_neg : c < 0 := by
        nlinarith [ sq_nonneg c ];
      have := algebraic_stam_inequality_n3 a c b d h_a_neg h_c_neg; aesop;

/-
If X^2 + c has distinct real roots, then c < 0.
-/
lemma quadratic_centered_coeff_neg (c : ℝ)
    (h_nodup : (X^2 + C c).roots.Nodup)
    (h_splits : (X^2 + C c).Splits (RingHom.id ℝ)) :
    c < 0 := by
      rw [ Polynomial.splits_iff_card_roots ] at h_splits;
      by_contra h_nonneg;
      rcases lt_or_eq_of_le ( le_of_not_gt h_nonneg ) with h | rfl <;> norm_num at *;
      · obtain ⟨ x, hx ⟩ := Multiset.card_pos_iff_exists_mem.mp ( by linarith ) ; norm_num at hx ; nlinarith;
      · norm_num [ two_smul ] at h_nodup

/-
Finite Free Stam Inequality for n=2 centered polynomials.
-/
theorem finite_free_stam_inequality_centered_n2 (p q : ℝ[X])
    (hp : is_centered 2 p) (hq : is_centered 2 q)
    (hp_real : p.Splits (RingHom.id ℝ)) (hp_nodup : p.roots.Nodup)
    (hq_real : q.Splits (RingHom.id ℝ)) (hq_nodup : q.roots.Nodup)
    (hpq_real : (boxplus 2 p q).Splits (RingHom.id ℝ)) (hpq_nodup : (boxplus 2 p q).roots.Nodup) :
    invPhi (boxplus 2 p q) ≥ invPhi p + invPhi q := by
      -- By definition of $p$ and $q$, we know that $p = X^2 + c_p$ and $q = X^2 + c_q$ for some $c_p, c_q \in ℝ$.
      obtain ⟨cp, hp_eq⟩ : ∃ cp : ℝ, p = Polynomial.X ^ 2 + Polynomial.C cp := by
        rcases hp with ⟨ hp_monic, hp_deg, hp_coeff ⟩ ; rw [ Polynomial.as_sum_range_C_mul_X_pow p ] ; use p.coeff 0 ; norm_num [ Finset.sum_range_succ', hp_monic, hp_deg, hp_coeff ] ;
        rw [ ← hp_deg, hp_monic.coeff_natDegree, Polynomial.C_1 ]
      obtain ⟨cq, hq_eq⟩ : ∃ cq : ℝ, q = Polynomial.X ^ 2 + Polynomial.C cq := by
        rcases hq with ⟨ hq₁, hq₂, hq₃ ⟩;
        rw [ Polynomial.as_sum_range_C_mul_X_pow q ] ; norm_num [ Finset.sum_range_succ', hq₂, hq₃ ];
        have := hq₁.coeff_natDegree; aesop;
      -- By definition of $p$ and $q$, we know that $p ⊞ q = X^2 + (c_p + c_q)$.
      have h_boxplus_eq : boxplus 2 p q = Polynomial.X ^ 2 + Polynomial.C (cp + cq) := by
        unfold boxplus;
        unfold boxplus_coeff; norm_num [ Finset.sum_range_succ', hp_eq, hq_eq ] ; ring;
      have h_invPhis : ∀ c : ℝ, (Polynomial.X ^ 2 + Polynomial.C c).roots.Nodup → (Polynomial.X ^ 2 + Polynomial.C c).Splits (RingHom.id ℝ) → invPhi (Polynomial.X ^ 2 + Polynomial.C c) = -2 * c := by
        intros c hc_nodup hc_splits
        have h_discriminant : c < 0 := by
          exact?;
        -- By definition of $invPhi$, we know that $invPhi(X^2 + c) = -2c$.
        have h_invPhi_def : invPhi (Polynomial.X ^ 2 + Polynomial.C c) = 1 / (Phi (Polynomial.X ^ 2 + Polynomial.C c)) := by
          unfold invPhi;
          rw [ Polynomial.splits_iff_card_roots ] at hc_splits ; aesop;
        rw [ h_invPhi_def, Phi_quadratic_centered c h_discriminant ] ; ring;
        norm_num;
      grind

/-
If p splits, card(roots(p)) = deg(p).
-/
lemma roots_card_eq_natDegree (p : ℝ[X])
    (h_splits : p.Splits (RingHom.id ℝ)) (h_monic : p.Monic) :
    p.roots.card = p.natDegree := by
  rw [Polynomial.splits_iff_card_roots] at h_splits
  exact h_splits

/-
invPhi(x^4 + ax^2 + c) = -2c(a^2 - 4c) / (a(12c + a^2)).
-/
def invPhi_symmetric_quartic_formula (a c : ℝ) : ℝ :=
  -2 * c * (a^2 - 4 * c) / (a * (12 * c + a^2))

lemma invPhi_eq_invPhi_symmetric_quartic_formula (a c : ℝ)
    (h_discr : a^2 - 4 * c > 0) (h_c : c > 0) (h_a : a < 0) :
    let p := X^4 + C a * X^2 + C c
    p.roots.Nodup → p.Splits (RingHom.id ℝ) →
    invPhi p = invPhi_symmetric_quartic_formula a c := by
      intros p hp_nodup hp_splits;
      -- By definition of invPhi, we have invPhi p = 1 / Phi p.
      rw [invPhi];
      unfold invPhi_symmetric_quartic_formula;
      rw [ if_pos ⟨ hp_nodup, by
        have h_card : Multiset.card (Polynomial.roots p) = 4 := by
          convert Polynomial.natDegree_eq_card_roots hp_splits using 1;
          · exact?;
          · convert Polynomial.natDegree_eq_card_roots hp_splits using 1;
            rw [ Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases ha : a = 0 <;> simp +decide [ ha ];
        linarith ⟩, Phi_eq_sum_roots_deriv ];
      · -- The roots of the derivative $p'(x) = 4x^3 + 2ax$ are $0$ and $\pm \sqrt{-a/2}$.
        have h_roots_deriv : (Polynomial.derivative p).roots = {0, Real.sqrt (-a / 2), -Real.sqrt (-a / 2)} := by
          norm_num +zetaDelta at *;
          rw [ show ( Polynomial.C 4 * Polynomial.X ^ 3 + Polynomial.C a * ( Polynomial.C 2 * Polynomial.X ) : Polynomial ℝ ) = ( Polynomial.C 4 ) * ( Polynomial.X - Polynomial.C ( Real.sqrt ( -a ) / Real.sqrt 2 ) ) * ( Polynomial.X - Polynomial.C ( -Real.sqrt ( -a ) / Real.sqrt 2 ) ) * ( Polynomial.X - Polynomial.C 0 ) by exact Polynomial.funext fun x => by norm_num; ring_nf; norm_num [ Real.sq_sqrt <| show 0 ≤ -a by linarith ] ; ring ];
          rw [ Polynomial.roots_mul, Polynomial.roots_mul ];
          · erw [ Polynomial.roots_C_mul, Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C, Polynomial.roots_X_sub_C ] <;> norm_num ; ring;
            norm_num [ Multiset.cons_eq_cons ];
            exact Or.inr ⟨ ne_of_gt <| Real.sqrt_pos.mpr <| neg_pos.mpr h_a, Or.inr <| ne_of_gt <| Real.sqrt_pos.mpr <| neg_pos.mpr h_a ⟩;
          · exact mul_ne_zero ( mul_ne_zero ( Polynomial.C_ne_zero.mpr ( by norm_num ) ) ( Polynomial.X_sub_C_ne_zero _ ) ) ( Polynomial.X_sub_C_ne_zero _ );
          · exact mul_ne_zero ( mul_ne_zero ( mul_ne_zero ( Polynomial.C_ne_zero.mpr ( by norm_num ) ) ( Polynomial.X_sub_C_ne_zero _ ) ) ( Polynomial.X_sub_C_ne_zero _ ) ) ( Polynomial.X_sub_C_ne_zero _ );
        norm_num [ h_roots_deriv ] ; ring;
        norm_num [ p ] ; ring;
        rw [ show ( Real.sqrt ( -a ) ) ^ 4 = ( Real.sqrt ( -a ) ^ 2 ) ^ 2 by ring, show ( Real.sqrt 2 ) ⁻¹ ^ 4 = ( ( Real.sqrt 2 ) ⁻¹ ^ 2 ) ^ 2 by ring, Real.sq_sqrt <| by linarith, inv_pow ] ; norm_num ; ring;
        field_simp;
        rw [ neg_div', div_eq_div_iff ] <;> nlinarith [ mul_div_cancel₀ ( c * 4 * 8 ) ( by nlinarith : ( -a ^ 2 + c * 4 ) ≠ 0 ) ];
      · assumption;
      · assumption;
      · rw [ Polynomial.natDegree_add_C, Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> by_cases ha : a = 0 <;> simp +decide [ ha ];
      · refine' Multiset.nodup_iff_count_le_one.mpr _;
        intro x; by_cases hx : x = 0 <;> simp_all +decide [ Polynomial.derivative_add, Polynomial.derivative_mul, Polynomial.derivative_pow ] ;
        · simp +zetaDelta at *;
          rw [ Polynomial.rootMultiplicity_le_iff ] <;> norm_num;
          · rintro ⟨ q, hq ⟩ ; have := congr_arg ( Polynomial.derivative · |> Polynomial.eval 0 ) hq ; norm_num [ Polynomial.derivative_pow ] at this;
            linarith;
          · exact ne_of_apply_ne ( fun p => p.coeff 3 ) ( by norm_num [ Polynomial.coeff_one, Polynomial.coeff_X, mul_assoc, add_mul ] );
        · refine' Nat.le_of_not_lt fun h => _;
          have h_root : Polynomial.eval x (Polynomial.derivative p) = 0 ∧ Polynomial.eval x (Polynomial.derivative (Polynomial.derivative p)) = 0 := by
            exact ⟨ by exact Polynomial.rootMultiplicity_pos ( by aesop ) |>.1 ( by linarith ), by exact Polynomial.isRoot_iterate_derivative_of_lt_rootMultiplicity h ⟩;
          norm_num +zetaDelta at *;
          grind

/-
kappa_4(p ⊞ q) = kappa_4(p) + kappa_4(q) for n >= 4.
-/
def kappa_4 (n : ℕ) (p : ℝ[X]) : ℝ :=
  p.coeff (n - 4) - (n - 2) * (n - 3) / (2 * n * (n - 1)) * (p.coeff (n - 2))^2

lemma kappa_4_additive (n : ℕ) (p q : ℝ[X])
    (hp : is_centered n p) (hq : is_centered n q) (hn : n ≥ 4) :
    kappa_4 n (boxplus n p q) = kappa_4 n p + kappa_4 n q := by
      -- By definition of $kappa_4$, we have
      unfold kappa_4;
      -- Let's simplify the expression using the definition of `boxplus`.
      have h_boxplus : (boxplus n p q).coeff (n - 4) = p.coeff (n - 4) * q.coeff n + p.coeff (n - 2) * q.coeff (n - 2) * ((n - 2) * (n - 3) / (n * (n - 1) : ℝ)) + p.coeff n * q.coeff (n - 4) ∧
                       (boxplus n p q).coeff (n - 2) = p.coeff (n - 2) * q.coeff n + p.coeff n * q.coeff (n - 2) := by
                         constructor <;> unfold boxplus <;> norm_num [ Polynomial.coeff_X_pow ];
                         · rw [ Finset.sum_eq_add_sum_diff_singleton ( Finset.mem_range.mpr ( by linarith : 4 < n + 1 ) ) ];
                           rw [ Finset.sum_eq_add ( 2 ) ( 0 ) ] <;> norm_num;
                           · rcases n with ( _ | _ | _ | _ | n ) <;> norm_num [ boxplus_coeff ] at *;
                             simp +arith +decide [ Finset.sum_range_succ', Nat.factorial ];
                             field_simp;
                             have := hp.2.2; have := hq.2.2; simp_all +decide [ Polynomial.coeff_eq_zero_of_natDegree_lt ] ; ring;
                           · intros; omega;
                           · intros; omega;
                         · rw [ Finset.sum_eq_add ( 2 ) ( 0 ) ] <;> norm_num [ boxplus_coeff ];
                           · rcases n with ( _ | _ | _ | n ) <;> norm_num [ Finset.sum_range_succ' ] at *;
                             simp_all +decide [ Nat.factorial_ne_zero, Nat.succ_sub_succ, mul_comm, mul_assoc, mul_left_comm, div_eq_mul_inv ];
                             cases hp ; cases hq ; aesop;
                           · intros; omega;
                           · grind;
      rcases hp with ⟨ hp₁, hp₂, hp₃ ⟩ ; rcases hq with ⟨ hq₁, hq₂, hq₃ ⟩ ; simp_all +decide [ Polynomial.Monic.def, Polynomial.leadingCoeff, Polynomial.natDegree_eq_of_degree_eq_some ] ; ring;
      grind

/-
Coefficients of boxplus for symmetric quartics.
-/
lemma boxplus_symmetric_quartic_coeffs (p q : ℝ[X])
    (hp : is_centered 4 p) (hq : is_centered 4 q)
    (hp_sym : p.coeff 1 = 0) (hq_sym : q.coeff 1 = 0) :
    (boxplus 4 p q).coeff 2 = p.coeff 2 + q.coeff 2 ∧
    (boxplus 4 p q).coeff 0 = p.coeff 0 + q.coeff 0 + p.coeff 2 * q.coeff 2 / 6 := by
      constructor;
      · convert boxplus_centered_coeff_n_sub_2 4 p q hp hq _ using 1 ; norm_num;
      · unfold boxplus; norm_num [ Finset.sum_range_succ' ] ; ring;
        unfold boxplus_coeff; norm_num [ Finset.sum_range_succ' ] ; ring;
        have := hp.1; have := hq.1; ( have := hp.2.1; have := hq.2.1; ( erw [ Polynomial.Monic, Polynomial.leadingCoeff, Polynomial.natDegree_eq_of_degree_eq_some ( Polynomial.degree_eq_natDegree <| by aesop ) ] at *; aesop; ) )

/-
Boxplus of symmetric centered quartics is symmetric.
-/
lemma boxplus_symmetric_quartic_is_symmetric (p q : ℝ[X])
    (hp : is_centered 4 p) (hq : is_centered 4 q)
    (hp_sym : p.coeff 1 = 0) (hq_sym : q.coeff 1 = 0) :
    (boxplus 4 p q).coeff 1 = 0 := by
      rw [ show ( boxplus 4 p q : Polynomial ℝ ) = ∑ i ∈ Finset.range ( 4 + 1 ), Polynomial.C ( ( boxplus_coeff 4 p q i ) ) * Polynomial.X ^ ( 4 - i ) by rfl ] ; simp_all +decide [ Finset.sum ] ;
      unfold boxplus_coeff; norm_num [ Finset.sum_range_succ, hp_sym, hq_sym ] ;
      cases hp ; cases hq ; aesop

/-
g(u) = (8u^2 - 2u) / (12u + 1) is convex on [0, infinity).
-/
def g_aux (u : ℝ) : ℝ := (8 * u^2 - 2 * u) / (12 * u + 1)

lemma g_aux_second_deriv (u : ℝ) (hu : u > -1/12) :
    deriv^[2] g_aux u = 64 / (12 * u + 1)^3 := by
      -- Let's simplify the expression for the second derivative.
      have h_simplify : deriv^[2] (fun u : ℝ => (8 * u^2 - 2 * u) / (12 * u + 1)) u = deriv (fun u : ℝ => (16 * u - 2) * (12 * u + 1) / (12 * u + 1)^2 - (8 * u^2 - 2 * u) * 12 / (12 * u + 1)^2) u := by
        refine' Filter.EventuallyEq.deriv_eq _;
        filter_upwards [ lt_mem_nhds hu ] with u hu using by norm_num [ mul_comm, show u * 12 + 1 ≠ 0 from by linarith ] ; ring;
      convert h_simplify using 1 ; norm_num [ mul_comm ] ; ring;
      norm_num [ show 1 + u * 24 + u ^ 2 * 144 ≠ 0 by nlinarith ] ; ring;
      grind

lemma g_aux_convex_on : ConvexOn ℝ (Set.Ici 0) g_aux := by
  refine' ⟨ convex_Ici _, _ ⟩;
  unfold g_aux;
  norm_num +zetaDelta at *;
  intro x hx y hy a b ha hb hab; rw [ mul_div, mul_div, div_add_div, div_le_div_iff₀ ] <;> try positivity;
  obtain rfl := eq_sub_of_add_eq hab;
  nlinarith [ mul_nonneg hb ( sq_nonneg ( x - y ) ), mul_nonneg hb ( mul_nonneg hx hy ), mul_nonneg hb ( mul_nonneg hx ha ), mul_nonneg hb ( mul_nonneg hy ha ), mul_nonneg hx hy, mul_nonneg hx ha, mul_nonneg hy ha ]

/-
F_aux(a, c) = a * g_aux(c/a^2).
-/
def F_aux (a c : ℝ) : ℝ :=
  -2 * c * (a^2 - 4 * c) / (a * (12 * c + a^2))

lemma F_aux_eq_a_mul_g_aux (a c : ℝ) (ha : a ≠ 0) :
    F_aux a c = a * g_aux (c / a^2) := by
  unfold F_aux g_aux
  field_simp
  ring

/-
F_aux(a, c) = -a * h_aux(4c/a^2).
-/
def h_aux (k : ℝ) : ℝ := k * (1 - k) / (2 * (3 * k + 1))

lemma F_aux_eq_neg_a_mul_h_aux (a c : ℝ) (ha : a ≠ 0) (h_denom : 12 * c + a^2 ≠ 0) :
    F_aux a c = -a * h_aux (4 * c / a^2) := by
  unfold F_aux h_aux
  field_simp
  ring